// Prose readings, keyed by Commons file title. Each says where the icon was made, what it
// shows, and what in it answers to Luke's verses — nothing the picture does not show, and
// nothing borrowed from another Gospel without saying whose it is.
module.exports={

// ---- chapter 2 ----

"File:031 Nativity of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":
 "A Greek panel from the church of St Paraskevi at Langadas, north of Thessaloniki, inscribed in the dark of the cave beside the Child: Η ΓΕΝΝΗΣΙΣ ΤΟΥ ΧΡΙΣΤΟΥ, the Nativity of Christ. The board has been badly hurt — a wide scar of lost paint falls from the top edge straight through the manger — and what is left is very nearly Luke's sentence and nothing else. The Child lies swaddled in gold-flecked bands in a manger built as a low stone chest, stepped at the foot the way an altar is stepped, and Luke gives the birth itself in one clause: and wrapped him in swaddling clothes, and laid him in a manger. The Theotokos kneels at the left and Joseph opposite her at the right, both with their hands crossed on the breast and both bowing to the manger rather than to each other; neither is doing anything, which is the painter's way of saying that nothing here was done by them. Behind Joseph an old man wrapped to the throat in a shaggy fleece stands with his head thrown back. Above the cave the panel carries the paragraph Luke writes next: on the hillside at the left an angel in orange leans down over two shepherds, one of them with a pipe held to his lips in both hands. The three riders coming over the hill at the right, and the eight-pointed star above the manger, are Matthew's — Luke has neither a star nor wise men. What he has instead is a decree from Caesar Augustus, a journey to the city of David, and no room for them in the inn.",

"File:12 Nativity of Jesus Icon in Assumption of Mary Church in Agios Vasileios.jpg":
 "A small panel from a village church of the Dormition at Agios Vasileios, and the most worn icon in this reader: the surface has been rubbed back so far that the haloes — thick rings of gold, dotted round the rim like jewellery — are often the only part of a figure still certain. Read what is legible and it is Luke's. A white stone trough stands on the ground at the centre and the Child lies in it swaddled in rose-coloured bands: laid him in a manger. Two figures kneel to the trough with their hands crossed on the breast. The one on the right, in a rose maphorion under a jewelled halo, is the Theotokos; the old grey-bearded man in blue on the left is Joseph. Behind and between them stand others whose faces have gone altogether. A broad orange shaft comes down the middle of the board from the top edge to the manger. The upper register holds a small scene in each corner: at the right a figure in white raises his hand over a man who leans on a staff on the hillside, which is what Luke writes next — there were in the same country shepherds abiding in the field, keeping watch over their flock by night — and at the left a knot of small figures too far gone to name, of which nothing honest can be said but that they are there.",

"File:Nativity Icon Panagia Evraidos Church 19 Century.jpg":
 "A nineteenth-century Greek panel from the church of Panagia Evraidou, painted on a landscape ground of green hills and blue sky instead of gold, in the late Greek manner. It gives the shepherds as much of the board as the Holy Family, and it leaves out the one concrete thing Luke reports: there is no cave, no ox and ass, and no manger. The Child lies swaddled in white bands directly on the grass with thin gold rays spreading from him across it, and Joseph at the left and the Theotokos at the right each reach a hand toward him without touching him. Across the whole width of the panel runs a band of red letters; what is still legible in it is ΠΟΙΜΕΝ — the shepherds. Above the band, on the hillside, a haloed beardless youth in blue and red kneels and puts his hand out toward a shepherd who sits below him with his own hand raised and a long pipe across his lap: the painter has given the messenger a halo and no wings. Four angels lean over a bank of cloud along the top edge, two at either side of a triple shaft of red light, which is the multitude of the heavenly host praising God. Two white sheep lie on the grass at the bottom of the panel, below the Child's feet.",

// ---- chapter 3 ----

"File:St John the Baptist Late XVII - Early XVIII Cenury St Mary Blonichka Church, Ohris Icon Gallery.jpg":
 "A panel of about 1700 from the church of St Mary Blonichka at Ohrid. It is not a scene: it is the Forerunner as the Church paints him, standing full length with two great feathered wings folded up behind his shoulders. The wings are not a claim that he was an angel. The Greek word for a messenger is angelos, and Luke does put that word in the Lord's mouth about him — This is he, of whom it is written, Behold, I send my messenger before thy face, which shall prepare thy way before thee — but he says it four chapters after these verses, and the painter has taken it literally. He wears the shaggy hide of camel's hair over a blue-green himation, and a plain pale staff stands upright against his left side. The open scroll in his hand gives a sermon Luke never reports: ΜΕΤΑΝΟΕΙΤΕ ΗΓΓΙΚΕΝ ΓΑΡ Η ΒΑΣΙΛΕΙΑ ΤΩΝ ΟΥΡΑΝΩΝ — Repent ye: for the kingdom of heaven is at hand — which is Matthew's wording of the preaching. Luke's own summary is a single clause, preaching the baptism of repentance for the remission of sins, and then he stands aside and lets Isaiah speak for three verses. In the charger at the Forerunner's waist lies his own severed head with its eyes closed, painted while the living man stands above it, and that is why the panel belongs to the man and not to any one passage about him. Luke has the better claim to it even so: he alone tells the Forerunner's conception and his birth and his father's name, and he alone says where the years between went — the child grew, and waxed strong in spirit, and was in the deserts till the day of his shewing unto Israel.",

"File:Prodromos Didaskon Ioudaious Dionysiou.jpg":
 "A fresco of 1547 from the Forerunner cycle in the katholikon of Dionysiou on Mount Athos. The inscription runs across the top on either side of the halo: Ο ΠΡΟΔΡΟΜΟΣ ΔΙΔΑΣΚΩΝ ΤΟΥΣ ΙΟΥΔΑΙΟΥΣ, the Forerunner teaching the Jews. He stands barefoot in a wilderness of grey rock, the garment of hair under a green-gold himation, his right hand up in the gesture of speech and a tall staff ending in a small cross held against his left shoulder. What makes the fresco Luke's is that it paints his hearers in two kinds, and puts them on opposite sides of him. At his right a close press of five or six bearded men in soft caps and long robes, unarmed, leaning in over each other's shoulders: the multitude that came forth to be baptized of him, and the publicans who came with them. At his left, in scale corselets and lamellar skirts and helmets and greaves, with red cloaks over their shoulders, stand soldiers — five of them, the foremost cradling something round in both hands against his chest. Luke 3:14 is the only place in the four Gospels where soldiers come to the Forerunner and ask what they are to do, and the answer he gives is about their own trade and nobody else's: Do violence to no man, neither accuse any falsely; and be content with your wages. Between the two groups, at his feet, stands one small bare-trunked tree. Luke's hardest sentence in these verses is about such a tree — And now also the axe is laid unto the root of the trees — and no axe is painted at this one.",

};
