// Prose readings, keyed by Commons file title. Each says where the icon was made, what it
// shows, and what in it answers to Luke's verses — nothing the picture does not show, and
// nothing borrowed from another Gospel without saying whose it is.
module.exports={

// ---- chapter 2 ----

"File:031 Nativity of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":
 "A Greek panel from the church of St Paraskevi at Langadas, north of Thessaloniki, inscribed in the dark of the cave beside the Child: Η ΓΕΝΝΗΣΙΣ ΤΟΥ ΧΡΙΣΤΟΥ, the Nativity of Christ. The board has been badly hurt — a wide scar of lost paint falls from the top edge straight through the manger — and what is left is very nearly Luke's sentence and nothing else. The Child lies swaddled in gold-flecked bands in a manger built as a low stone chest, stepped at the foot the way an altar is stepped, and Luke gives the birth itself in one clause: and wrapped him in swaddling clothes, and laid him in a manger. The Theotokos kneels at the left and Joseph opposite her at the right, both with their hands crossed on the breast and both bowing to the manger rather than to each other; neither is doing anything, which is the painter's way of saying that nothing here was done by them. Behind Joseph an old man wrapped to the throat in a shaggy fleece stands with his head thrown back. Above the cave the panel carries the paragraph Luke writes next: on the hillside at the left an angel in orange leans down over two shepherds, one of them with a pipe held to his lips in both hands. The three riders coming over the hill at the right, and the eight-pointed star above the manger, are Matthew's — Luke has neither a star nor wise men. What he has instead is a decree from Caesar Augustus, a journey to the city of David, and no room for them in the inn.",

"File:12 Nativity of Jesus Icon in Assumption of Mary Church in Agios Vasileios.jpg":
 "A small panel from a village church of the Dormition at Agios Vasileios, and the most worn icon in this reader: the surface has been rubbed back so far that the haloes — thick rings of gold, dotted round the rim like jewellery — are often the only part of a figure still certain. Read what is legible and it is Luke's. At the centre stands a block of white masonry with a straight top and a moulded lip, and the Child lies along the top of it swaddled in rose-coloured bands. Whether the painter drew a trough with a far rim or a bare slab cannot be told — the surface is too far gone — but something is built there for him to be laid on, and and Luke's own clause for it is and wrapped him in swaddling clothes, and laid him in a manger. Two figures kneel to the trough with their hands crossed on the breast. The one on the right, in a rose maphorion under a jewelled halo, is the Theotokos; the old grey-bearded man in blue on the left is Joseph. Behind and between them stand others whose faces have gone altogether. A broad orange shaft comes down the middle of the board from the top edge to the manger. The upper register holds a small scene in each corner: at the right a figure in white raises his hand over a man who leans on a staff on the hillside, which is what Luke writes next — there were in the same country shepherds abiding in the field, keeping watch over their flock by night — and at the left a knot of small figures too far gone to name, of which nothing honest can be said but that they are there.",

"File:Nativity Icon Panagia Evraidos Church 19 Century.jpg":
 "A nineteenth-century Greek panel from the church of Panagia Evraidou, painted on a landscape ground of green hills and blue sky instead of gold, in the late Greek manner. It gives the shepherds as much of the board as the Holy Family, and it leaves out the one concrete thing Luke reports: there is no cave, no ox and ass, and no manger. The Child lies swaddled in white bands directly on the grass with thin gold rays spreading from him across it, and Joseph at the left and the Theotokos at the right each reach a hand toward him without touching him. Across the whole width of the panel runs a band of red letters; what is still legible in it is ΠΟΙΜΕΝ — the shepherds. Above the band, on the hillside, a haloed beardless youth in blue and red kneels and puts his hand out toward a shepherd who sits below him with his own hand raised and a long pipe across his lap: the painter has given the messenger a halo and no wings. Four angels lean over a bank of cloud along the top edge, two at either side of a triple shaft of red light, which is the multitude of the heavenly host praising God. Two pale beasts lie on the grass at the bottom of the panel below the Child's feet, the nearer one with a long muzzle and a drooping ear.",

// ---- chapter 3 ----

"File:St John the Baptist Late XVII - Early XVIII Cenury St Mary Blonichka Church, Ohris Icon Gallery.jpg":
 "A panel of about 1700 from the church of St Mary Blonichka at Ohrid. It is not a scene: it is the Forerunner as the Church paints him, standing full length with two great feathered wings folded up behind his shoulders. The wings are not a claim that he was an angel. The Greek word for a messenger is angelos, and Luke does put that word in the Lord's mouth about him — This is he, of whom it is written, Behold, I send my messenger before thy face, which shall prepare thy way before thee — but he says it four chapters after these verses, and the painter has taken it literally. He wears the shaggy hide of camel's hair over a blue-green himation, and a plain pale staff stands upright against his left side. The open scroll in his hand gives a sermon Luke never reports: ΜΕΤΑΝΟΕΙΤΕ ΗΓΓΙΚΕΝ ΓΑΡ Η ΒΑΣΙΛΕΙΑ ΤΩΝ ΟΥΡΑΝΩΝ — Repent ye: for the kingdom of heaven is at hand — which is Matthew's wording of the preaching. Luke's own summary is a single clause, preaching the baptism of repentance for the remission of sins, and then he stands aside and lets Isaiah speak for three verses. In the charger at the Forerunner's waist lies his own severed head with its eyes closed, painted while the living man stands above it, and that is why the panel belongs to the man and not to any one passage about him. Luke has the better claim to it even so: he alone tells the Forerunner's conception and his birth and his father's name, and he alone says where the years between went — the child grew, and waxed strong in spirit, and was in the deserts till the day of his shewing unto Israel.",

"File:Prodromos Didaskon Ioudaious Dionysiou.jpg":
 "A fresco of 1547 from the Forerunner cycle in the katholikon of Dionysiou on Mount Athos. The inscription runs across the top on either side of the halo: Ο ΠΡΟΔΡΟΜΟΣ ΔΙΔΑΣΚΩΝ ΤΟΥΣ ΙΟΥΔΑΙΟΥΣ, the Forerunner teaching the Jews. He stands barefoot in a wilderness of grey rock, the garment of hair under a green-gold himation, his right hand up in the gesture of speech and a tall staff ending in a small cross held against his left shoulder. What makes the fresco Luke's is that it paints his hearers in two kinds, and puts them on opposite sides of him. At his right a close press of five or six bearded men in soft caps and long robes, unarmed, leaning in over each other's shoulders: the multitude that came forth to be baptized of him, and the publicans who came with them. At his left, in scale corselets and lamellar skirts and helmets and greaves, with red cloaks over their shoulders, stand soldiers — five of them, the foremost cradling something round in both hands against his chest. Luke 3:14 is the only place in the four Gospels where soldiers come to the Forerunner and ask what they are to do, and the answer he gives is about their own trade and nobody else's: Do violence to no man, neither accuse any falsely; and be content with your wages. Between the two groups, at his feet, stands one small bare-trunked tree. Luke's hardest sentence in these verses is about such a tree — And now also the axe is laid unto the root of the trees — and no axe is painted at this one.",

"File:Baptism of Christ, Early XIV Century, St Mary Perivleptos Church, Ohrid Icon Gallery.jpg":
 "A panel of the early fourteenth century from St Mary Perivleptos at Ohrid, and the oldest of Luke's four Baptism icons, its gold ground split by a long crack but every figure on it whole. Christ stands waist-deep in dark water at the centre, and Luke puts him there almost incidentally, among a crowd that has already gone under: Now when all the people were baptized, it came to pass, that Jesus also being baptized, and praying, the heaven was opened. The clause makes him the last into the river, not the first, and the painter keeps him the same scale and the same bareness as any other man there — nothing marks him out but the halo. John leans in from the rocks at the left, his hand raised over Christ's head without touching it. Above, at the top edge, a scalloped grey arc is torn open in the gold, and a narrow beam falls from it toward Christ; the paint at its foot, where the dove itself belongs, has worn away to a small pale blur. Four haloed figures wait on the far bank at the right, heads bowed, their hands kept under their draped sleeves rather than bare. At the lower left, among bare wintry trees, a grey axe leans against a trunk — the Forerunner's own warning, given twelve verses earlier in this same chapter: and now also the axe is laid unto the root of the trees. Near it a small draped figure lies at the water's edge, turned back over its own shoulder as though in flight: the river given a body, an image from the Church's own hymn for this feast rather than from Luke's own sentence, which says only that the heaven was opened.",

"File:019 Baptism of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":
 "A Greek panel from the church of St Paraskevi at Langadas, worn hard enough that the two riverbanks have gone to flat green and the faces are mostly gone. What survives is the shape Luke's own sentence gives the scene: the heaven opened, painted as a torn grey-green cleft with small dark trees planted along both its slopes, and down the centre of it a broad orange-red shaft falls toward Christ's head, narrowing at its foot to a small worn mark too flattened by rubbing to call a bird with any confidence. John leans in at the left with his hand raised over him, not on him. At the right, two winged angels in gold and red stand one behind the other, their heads bowed and their own hands, covered by the fall of a white cloth held between them, not shown bare — the reverence the Gospel's own words do not describe, since Luke gives none of the actors here any gesture at all beyond a voice and a heaven that opens. Christ stands in dark water between the banks, and the single sentence Luke sets over the whole scene runs the length of two verses: Jesus also being baptized, and praying, the heaven was opened, and the Holy Ghost descended in a bodily shape like a dove upon him.",

"File:03 Baptism of Christ Icon from Saint Paraskevi Church in Adam.jpg":
 "A panel from the church of St Paraskevi at Adam, better preserved than its neighbour from Langadas and carrying, across the top in worn red letters, the remains of a title — legible now only as fragments of the Baptism … of Christ. Above Christ's head a white dove, wings spread and rayed with light, descends on a straight shaft out of a bank of grey cloud: the one icon of Luke's four where the bird itself, and not only the light around it, is still there to be seen — the Holy Ghost descended in a bodily shape like a dove upon him. John the Forerunner stands at the left, one hand laid on Christ's head, the other holding the end of his own cloak; three haloed angels wait at the right, the foremost holding a white cloth in both hands for the moment Christ will need it. Below the surface of the water, roots of the riverbank trees run down on both sides toward Christ's feet, tangled and bare, but no axe is cut into either trunk here — that detail belongs to the Ohrid panel, not this one. The water itself is dark and unpeopled beneath him; nothing in this telling personifies the river Luke never mentions by name at all in these two verses, only the heaven that opens above it.",

"File:0663Ha. Hermitage Museum (Hall 143). Icon of the Epiphany.jpg":
 "A Russian icon of the seventeenth century, in the Hermitage's collection, and the darkest of Luke's four: the whole centre of the panel is a single wedge of near-black water and sky fused into one shape, split at the top into two jagged banks of cloud with a white radiant star bursting between them. A thin silver ray runs straight down the middle of the black from that star to a second, smaller point of light just above Christ's head — the one clear passage, in any of these four icons, from the heaven that Luke says opened to the mark that stands for the dove that descended out of it, small and still uncertain in shape at this resolution, with two or three tiny red letters beside it too worn to read. John the Forerunner stands at the left in green, his hand on Christ's head; three winged angels lean in from the right in a diagonal file, the foremost in red holding a folded white cloth in both covered hands. Christ himself is thin, pale and marked with the dark lines of a body under strain, standing upright in the black water with his hands open at his sides — not lifted in prayer as some icons show him, though Luke's own clause insists that he was: Jesus also being baptized, and praying, the heaven was opened.",

"File:Christ's temptation (Monreale).jpg":
 "The same Monreale mosaic Matthew's and Mark's readers show, chosen here because it paints the one temptation all three Synoptics tell in the same order: the first. Luke's own opening sentence ties it directly to what has just happened at the Jordan in a way Matthew's does not — And Jesus being full of the Holy Ghost returned from Jordan, and was led by the Spirit into the wilderness — the same Spirit that had only just descended in a bodily shape now driving him out to fast and be tried before he does anything else. The mosaic gives the exchange in Latin around Christ and the winged, dark tempter reaching for the five stones between them: SI FILI DI ES DIC VT LAPIDES ISTI PANE FIANT — command these stones to become bread, if you are the Son of God. It is Matthew's own plural; Luke's devil asks for only one: If thou be the Son of God, command this stone that it be made bread. Luke's own wording of Christ's answer is shorter than Matthew's too: It is written, That man shall not live by bread alone, but by every word of God, stopping short of Matthew's addition that proceedeth out of the mouth of God. It is the first fall in a contest Luke alone tells in a different order from Matthew's — the mountain of the kingdoms comes second in this Gospel, the pinnacle of the temple third, where Matthew has them reversed. St Augustine, weighing the two orders against each other, judged it uncertain which Evangelist had kept the true sequence and which had arranged his own for effect; the Church has never had to choose between them.",

"File:Cathedral (Monreale) - Right wing transept - 2nd Temptation of Christ.jpg":
 "The panel that follows the first temptation along the same wall at Monreale, and in Luke's own order this is the last of the three, not the middle one Matthew makes it. The devil has set Christ on the roof of a small arcaded building — the pinnacle of the temple. Luke alone names the city beneath it: he brought him to Jerusalem. The Latin gives the last exchange of the contest: SI FILIUS DEI ES MITTE TE DEORSUM — if thou be the Son of God, cast thyself down from hence. Christ's reply stands on the other side: SCRIPTUM EST NON TEMPTABIS DOMINUM DEUM TUUM, the inscription's own it is written — though Luke's own third citation changes the verb the first two use: It is said, Thou shalt not tempt the Lord thy God. The winged tempter hangs beside Christ in the air, reaching toward him without touching, exactly as he offered the stones in the first scene. Between the two temptation scenes on this wall lies the one this reader has no icon for: taking him up into an high mountain, shewed unto him all the kingdoms of the world in a moment of time. What ends here is the whole contest, and Luke closes it with a warning the picture cannot show: when the devil had ended all the temptation, he departed from him for a season — not for good, and with none of Matthew's angels sent at once to minister to him. Luke gives him no such comfort here; the season would run until the Passion.",

"File:Monreale - Jesus heals Simon's mother in law.jpg":
 "The same Monreale mosaic Matthew's and Mark's readers show, and the Latin across the top already concedes Luke's own word before any Gospel text is quoted: IHS LIBERAT SOCRUM SIMONIS A MAGNIS FEBRIBUS, Jesus frees Simon's mother-in-law from a great fever. Magnis is Luke's own adjective; neither Matthew nor Mark qualifies the fever at all, and Simon's wife's mother was taken with a great fever is the physician's distinction Luke alone draws, a lesser fever set against a dangerous one. The gesture the mosaicist paints — Christ crossing the room with his arm already out toward her while she raises herself from the bed and reaches back, the two hands close but not joined across the gold — suits Luke's telling better than it suits the other two: Luke is the one Evangelist who has Christ neither touch her hand, as Matthew says, nor take her by the hand and lift her up, as Mark does. What Luke gives instead is a word alone: he stood over her, and rebuked the fever; and it left her — the same verb his Gospel uses elsewhere for silencing unclean spirits, and the fever obeys it as they do. The four men behind Christ are those who had just come with him out of the synagogue, and a fifth head looks in from the doorway at the upper right. Luke ends the verse where Matthew and Mark both end theirs, with what the healing was for: and immediately she arose and ministered unto them.",

// ---- chapter 5 ----

"File:Miraculous catch of fish - Sant'Apollinare Nuovo - Ravenna 2016.jpg":
 "A panel from the miracle cycle of Sant'Apollinare Nuovo at Ravenna, from the first years of the sixth century, catalogued on Commons as the Miraculous Draught of Fish and identified by a specialist in Christian iconography as the Calling of Peter and Andrew, the calling Matthew and Mark both open with one shared clause: casting a net into the sea: for they were fishers. Grey-haired and short-bearded, Peter leans out over the near gunwale with both hands already in the net; beside him, dark-haired and wilder, Andrew works the oar. A second man stands behind Christ on the bank, in a plain mantle, without a halo; who he is meant to be, neither the fresco nor this reading can say. St Augustine, in the Catena, sets the tellings side by side rather than choosing between them: Matthew and Mark here briefly state the matter, and how it was done. Luke explains it more at large. He also allows that the calling Matthew and Mark report may have come later, a second call after the one Luke tells here: so that afterwards that might happen which Matthew and Mark speak of. Luke's own telling gives a night's empty labour turned by Christ's word into a catch that fills two boats until they begin to sink, and Peter falling at Jesus' knees before the word that ends the story: Fear not; from henceforth thou shalt catch men. Christ stands on the bank here rather than seated with Peter in the boat, as Luke's own text has him through most of the story: he entered into one of the ships, which was Simon’s. The mosaic gives Andrew a face; Luke's own account of this calling never names him, a silence St Augustine notices in the same Catena block: he does not mention Andrew by name, who however is thought to have been in that ship, according to the accounts of Matthew and Mark.",

"File:Christ cleans leper man.jpg":
 "The same Monreale mosaic Matthew's and Mark's readers show, and the same Latin plea painted above the gold: POTES ME MVNDARE. Thou canst make me clean. Luke's own description of the man is the fullest of the three Synoptics: not a leper, as Matthew and Mark both have it, but a man full of leprosy, and the mosaicist has covered him with the disease from throat to ankle — dark spots scattered over his bare chest, his forearm, his shin — where Matthew's and Mark's own readings of this picture point only to the hand Christ reaches toward. He stands at the threshold of the building at the right, leaning on a staff, one hand lifted toward Christ and the other still open as though the plea were not yet finished; Christ comes from the left with his own hand out across the gold, the disciples pressed close behind him. Luke closes the story where Matthew and Mark do not: he withdrew himself into the wilderness, and prayed — the same habit of prayer this reader has already met at Christ's own baptism three chapters back, and one no icon of this scene paints.",

"File:Monreale - healing of paralytic.jpg":
 "The same Monreale mosaic Matthew's and Mark's readers show, and Luke's own word for what is happening along the top of the wall is neither of theirs: not Mark's roof dug open nor Matthew's men with a rope, but the tiling — they went upon the housetop, and let him down through the tiling with his couch into the midst before Jesus. Looked at closely, the two men lean in over a lattice of thin overlapping strips and work it apart with their bare hands; no rope is painted at this or any resolution, only fingers gripping the strips themselves. Christ sits enthroned at the left, his hand out; the paralytic has already come up off the bed onto his knees and reaches both arms back toward him, his feet still caught against the frame. Luke alone of the three gives Christ's opening word to him as a single term of address rather than a title of sonship: Man, thy sins are forgiven thee. Matthew and Mark both have Son instead. Luke alone also closes the miracle on the man's own voice: he departed to his own house, glorifying God; and they were all amazed, and they glorified God, and were filled with fear, saying, We have seen strange things to day. The scribes and Pharisees, in a tight knot of heads at the right, are Luke's own witnesses too: they had come out of every town of Galilee, and Judaea, and Jerusalem, drawn there before the miracle rather than only reacting to it.",

"File:Healing of the Paralytic 04-17.jpg":
 "The same Dionisy fresco Matthew's reader shows, from the Nativity cathedral at Ferapontov, and read here for the two clauses that belong to Luke alone. In the middle of the wall the man walks upright with his bed shouldered, and Luke's own sentence for the moment does not stop at the doorway the way Matthew's does: and immediately he rose up before them, and took up that whereon he lay, and departed to his own house, glorifying God. No other Evangelist gives him that last verb. At the right, where the fresco gathers a knot of witnesses with their heads drawn close together, is the moment Luke alone reports in full: they were all amazed, and they glorified God, and were filled with fear, saying, We have seen strange things to day. That is Luke's own word for it, a plain transliteration into English of the Greek paradoxa, things outside all expectation. Christ sits at the left with the apostles behind him, and below him the sick man still lies on his bed among the crowd that brought him — the getting up and the going out are Dionisy's whole subject on this wall, painted three times over so the eye cannot miss what Luke calls the strangest thing anyone there had seen.",

// ---- chapter 5, tier B: Levi ----

"File:090 Mathew the Apostle Icon from Saint Paraskevi Church in Langadas.jpg":
 "A village panel of the nineteenth century from St Paraskevi at Langadas, the same portrait Matthew's and Mark's readers show: an old man with a long white beard, a codex on his knee and a reed pen in his hand. Luke names him only once, at the moment of the calling — he went forth, and saw a publican, named Levi, sitting at the receipt of custom — and never again in this Gospel by that name; the Church has always read Levi and Matthew as the same man, and this is his icon at the far end of the life that calling began, not a picture of the custom-house itself. Luke's own verse for what happened at the table is the one no other Evangelist writes in quite these words: he left all, rose up, and followed him — the same phrase, forsook all, Luke had already used of the fishermen four verses into this chapter, so that the tax-gatherer's rising and theirs are made to answer one another.",

"File:Matthew the Evangelist - icon.jpeg":
 "The same Palekh panel Matthew's and Mark's readers show, Levi painted as the Evangelist he became rather than as the publican Luke's own verse finds him: sitting at his desk with the quill lifted and the winged man — his symbol among the four living creatures — dictating at his shoulder. Luke's account of the call is the shortest clause of any Synoptic's, he left all, rose up, and followed him, and gives no word at all to what the icon spends its whole surface on, the writing of the book afterward. What Luke does give, and Matthew's own Gospel of this same day does not, is the feast that followed the rising: and Levi made him a great feast in his own house: and there was a great company of publicans and of others that sat down with them — his own house still open to the trade he had just left, on the same day he left it.",

// ---- chapter 6 ----

"File:Iomenos xeran echon cheira Dionysiou.jpg":
 "The same Dionysiou fresco Matthew's and Mark's readers show, read here for the one clause that belongs to Luke alone. Before Christ says a word to anyone, Luke tells what is happening that the fresco cannot paint: but he knew their thoughts, and said to the man which had the withered hand, Rise up, and stand forth in the midst — a sentence neither Matthew nor Mark gives at this point in the story, where both let the question about the sabbath come first and the knowledge of the watchers' minds go unmentioned. The man stands alone in the centre of the floor in his short red tunic, his arm already lifting; Christ sits at the left with the apostles behind him; three elders wait along the right wall, one with his hand raised in objection. Luke keeps Mark's next gesture — and looking round about upon them all — but not what Mark hangs on it, no anger and no grief at the hardness of their hearts, only the look itself and then the command: Stretch forth thy hand. And where Mark's men go out to the Herodians, Luke names no council and no ally at all: they were filled with madness; and communed one with another what they might do to Jesus — fury without a plan, in the verse where Mark already has one forming.",

"File:Synaxis of the Twelve Apostles by Constantinople master (early 14th c., Pushkin museum).jpg":
 "A panel painted in Constantinople in the early fourteenth century, now in Moscow, its title lettered in Greek across the top — Η ΣΥΝΑΞΙΣ ΤΩΝ ΔΩΔΕΚΑ ΑΠΟΣΤΟΛΩΝ, the Synaxis of the Twelve Apostles — the apostles' own names running on after it in the same band. They stand in two ranks, four in front with their haloes overlapping and eight behind, holding scrolls and Gospel books. It is a feast icon, kept on the thirtieth of June, set here over the choosing itself rather than any picture of what led to it. Mark's own account puts Christ on a mountain for this choosing too, but only Luke gives what he did there the whole night before it: he went out into a mountain to pray, and continued all night in prayer to God. And when it was day, he called unto him his disciples: and of them he chose twelve, whom also he named apostles. His own list keeps eleven of Matthew's and Mark's names and changes one: where they give Thaddaeus, Luke names Judas the brother of James, the same man tradition calls Jude. Luke also renders one apostle's surname differently from the other two: Simon called Zelotes, where Matthew and Mark both call him the Canaanite — the same word in its own Aramaic dress.",

"File:Synaxis of the Twelve Apostles Dimitar Molerov Rila Monastery 1835.jpg":
 "An icon of 1835 by Dimitar Molerov at the monastery of Rila in Bulgaria — the same close photograph Matthew's and Mark's readers show, five of the twelve filling the frame in a single rank, their gold haloes overlapping into an unbroken line, holding a white scroll, a Gospel bound in gold and stones, and, at the right, the small silver cross of a martyr. The Synaxis is the Church's feast for all twelve together, the thirtieth of June, and stands over the choosing rather than any picture of the mountain. What Luke's own account gives, and Matthew's and Mark's readings of this same icon do not, is the night before the choosing: he went out into a mountain to pray, and continued all night in prayer to God. Luke's own list changes one name from Matthew's: Judas the brother of James, not Thaddaeus.",

"File:The Twelve Apostles, with later gilding, Greek, Late Byzantine, early 1300s, tempera and gold leaf on wood panel - Princeton University Art Museum - DSC06701.jpg":
 "A late Byzantine panel of the early fourteenth century, tempera and gold leaf on wood, now in the Princeton University Art Museum, its gilding a later addition — the same photograph Matthew's and Mark's readers show, the twelve packed into three close ranks against gold until their haloes overlap, a company rather than twelve portraits. That crowding suits the verse just after Luke's own choosing better than the choosing itself: he came down with them, and stood in the plain, and the company of his disciples, and a great multitude of people out of all Judaea and Jerusalem, and from the sea coast of Tyre and Sidon, which came to hear him, and to be healed of their diseases. Luke's own list of the twelve, given three verses earlier, keeps eleven names Matthew and Mark also give and changes one: Judas the brother of James in place of their Thaddaeus.",

// ---- chapter 7 ----

"File:Iomenos Gon Ekatonarchou Dionysiou.jpg":
 "The same Dionysiou fresco Matthew's reader shows, from the katholikon on Mount Athos, 1547. Its own titulus names him son, where Matthew's own underlying word for him, παῖς, can mean either boy or servant — Matthew's own reading of this fresco already notes the painter has made that choice. Luke gives the same man one thing neither Matthew's Gospel nor this titulus does: a certain centurion’s servant, who was dear unto him, was sick, and ready to die. The fresco paints the centurion himself standing at a low wall directly opposite Christ, helmeted and in armour, one hand raised in speech — the meeting Matthew's own Gospel tells: there came unto him a centurion, beseeching him. Luke's account never once puts him in the room. He sent unto him the elders of the Jews, beseeching him that he would come and heal his servant. Only when Jesus was already near the house did he send friends a second time, and it is through them, not to Christ's own face, that Luke gives the centurion's best-known words: Lord, trouble not thyself: for I am not worthy that thou shouldest enter under my roof. Neither the elders nor the friends are painted; only the soldier himself, standing exactly where this Gospel never puts him. St Augustine, weighing Luke's account against Matthew's in the Catena, poses the difficulty as one question — how then will that be true which Matthew relates, A certain centurion came to him, seeing that he himself did not come? — and answers that Matthew made use of a general mode of expression: the more he believed the nearer he came. The elders' own plea is Luke's alone among the Synoptics, and gives the reason no other Gospel does: he loveth our nation, and he hath built us a synagogue. The servant himself sits up fair-haired on a red coverlet at the edge of the frame, face turned up, touched by no one in the picture — the one distance every Gospel that tells this story keeps, whoever carries the words there: say in a word, and my servant shall be healed.",

};
