// Prose readings, keyed by Commons file title. Each says where the icon was made, what it
// shows, and what in it answers to Luke's verses — nothing the picture does not show, and
// nothing borrowed from another Gospel without saying whose it is.
module.exports={

// ---- chapter 2 ----

"File:031 Nativity of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":
 "A Greek panel from the church of St Paraskevi at Langadas, north of Thessaloniki, inscribed in the dark of the cave beside the Child: Η ΓΕΝΝΗΣΙΣ ΤΟΥ ΧΡΙΣΤΟΥ, the Nativity of Christ. The board has been badly hurt — a wide scar of lost paint falls from the top edge straight through the manger — and what is left is very nearly Luke's sentence and nothing else. The Child lies swaddled in gold-flecked bands in a manger built as a low stone chest, stepped at the foot the way an altar is stepped, and Luke gives the birth itself in one clause: and wrapped him in swaddling clothes, and laid him in a manger. The Theotokos kneels at the left and Joseph opposite her at the right, both with their hands crossed on the breast and both bowing to the manger rather than to each other; neither is doing anything, which is the painter's way of saying that nothing here was done by them. Behind Joseph an old man wrapped to the throat in a shaggy fleece stands with his head thrown back. Above the cave the panel carries the paragraph Luke writes next: on the hillside at the left an angel in orange leans down over two shepherds, one of them with a pipe held to his lips in both hands. The three riders coming over the hill at the right, and the eight-pointed star above the manger, are Matthew's — Luke has neither a star nor wise men. What he has instead is a decree from Caesar Augustus, a journey to the city of David, and no room for them in the inn.",

"File:12 Nativity of Jesus Icon in Assumption of Mary Church in Agios Vasileios.jpg":
 "A small panel from a village church of the Dormition at Agios Vasileios, and the most worn icon in this reader: the surface has been rubbed back so far that the haloes — thick rings of gold, dotted round the rim like jewellery — are often the only part of a figure still certain. Read what is legible and it is Luke's. At the centre stands a block of white masonry with a straight top and a moulded lip, and the Child lies along the top of it swaddled in rose-coloured bands. Whether the painter drew a trough with a far rim or a bare slab cannot be told — the surface is too far gone — but something is built there for him to be laid on, and and Luke's own clause for it is and wrapped him in swaddling clothes, and laid him in a manger. Two figures kneel to the trough with their hands crossed on the breast. The one on the right, in a rose maphorion under a jewelled halo, is the Theotokos; the old grey-bearded man in blue on the left is Joseph. Behind and between them stand others whose faces have gone altogether. A broad orange shaft comes down the middle of the board from the top edge to the manger. The upper register holds a small scene in each corner: at the right a figure in white raises his hand over a man who leans on a staff on the hillside, which is what Luke writes next — there were in the same country shepherds abiding in the field, keeping watch over their flock by night — and at the left a knot of small figures too far gone to name, of which nothing honest can be said but that they are there.",

"File:Nativity Icon Panagia Evraidos Church 19 Century.jpg":
 "A nineteenth-century Greek panel from the church of Panagia Evraidou, painted on a landscape ground of green hills and blue sky instead of gold, in the late Greek manner. It gives the shepherds as much of the board as the Holy Family, and it leaves out the one concrete thing Luke reports: there is no cave, no ox and ass, and no manger. The Child lies swaddled in white bands directly on the grass with thin gold rays spreading from him across it, and Joseph at the left and the Theotokos at the right each reach a hand toward him without touching him. Across the whole width of the panel runs a band of red letters; what is still legible in it is ΠΟΙΜΕΝ — the shepherds. Above the band, on the hillside, a haloed beardless youth in blue and red kneels and puts his hand out toward a shepherd who sits below him with his own hand raised and a long pipe across his lap: the painter has given the messenger a halo and no wings. Four angels lean over a bank of cloud along the top edge, two at either side of a triple shaft of red light, which is the multitude of the heavenly host praising God. Two pale beasts lie on the grass at the bottom of the panel below the Child's feet, the nearer one with a long muzzle and a drooping ear.",

// ---- chapter 3 ----

"File:St John the Baptist Late XVII - Early XVIII Cenury St Mary Blonichka Church, Ohris Icon Gallery.jpg":
 "A panel of about 1700 from the church of St Mary Blonichka at Ohrid. It is not a scene: it is the Forerunner as the Church paints him, standing full length with two great feathered wings folded up behind his shoulders. The wings are not a claim that he was an angel. The Greek word for a messenger is angelos, and Luke does put that word in the Lord's mouth about him — This is he, of whom it is written, Behold, I send my messenger before thy face, which shall prepare thy way before thee — but he says it four chapters after these verses, and the painter has taken it literally. He wears the shaggy hide of camel's hair over a blue-green himation, and a plain pale staff stands upright against his left side. The open scroll in his hand gives a sermon Luke never reports: ΜΕΤΑΝΟΕΙΤΕ ΗΓΓΙΚΕΝ ΓΑΡ Η ΒΑΣΙΛΕΙΑ ΤΩΝ ΟΥΡΑΝΩΝ — Repent ye: for the kingdom of heaven is at hand — which is Matthew's wording of the preaching. Luke's own summary is a single clause, preaching the baptism of repentance for the remission of sins, and then he stands aside and lets Isaiah speak for three verses. In the charger at the Forerunner's waist lies his own severed head with its eyes closed, painted while the living man stands above it, and that is why the panel belongs to the man and not to any one passage about him. Luke has the better claim to it even so: he alone tells the Forerunner's conception and his birth and his father's name, and he alone says where the years between went — the child grew, and waxed strong in spirit, and was in the deserts till the day of his shewing unto Israel.",

"File:Prodromos Didaskon Ioudaious Dionysiou.jpg":
 "A fresco of 1547 from the Forerunner cycle in the katholikon of Dionysiou on Mount Athos. The inscription runs across the top on either side of the halo: Ο ΠΡΟΔΡΟΜΟΣ ΔΙΔΑΣΚΩΝ ΤΟΥΣ ΙΟΥΔΑΙΟΥΣ, the Forerunner teaching the Jews. He stands barefoot in a wilderness of grey rock, the garment of hair under a green-gold himation, his right hand up in the gesture of speech and a tall staff ending in a small cross held against his left shoulder. What makes the fresco Luke's is that it paints his hearers in two kinds, and puts them on opposite sides of him. At his right a close press of five or six bearded men in soft caps and long robes, unarmed, leaning in over each other's shoulders: the multitude that came forth to be baptized of him, and the publicans who came with them. At his left, in scale corselets and lamellar skirts and helmets and greaves, with red cloaks over their shoulders, stand soldiers — five of them, the foremost cradling something round in both hands against his chest. Luke 3:14 is the only place in the four Gospels where soldiers come to the Forerunner and ask what they are to do, and the answer he gives is about their own trade and nobody else's: Do violence to no man, neither accuse any falsely; and be content with your wages. Between the two groups, at his feet, stands one small bare-trunked tree. Luke's hardest sentence in these verses is about such a tree — And now also the axe is laid unto the root of the trees — and no axe is painted at this one.",

"File:Baptism of Christ, Early XIV Century, St Mary Perivleptos Church, Ohrid Icon Gallery.jpg":
 "A panel of the early fourteenth century from St Mary Perivleptos at Ohrid, and the oldest of Luke's four Baptism icons, its gold ground split by a long crack but every figure on it whole. Christ stands waist-deep in dark water at the centre, and Luke puts him there almost incidentally, among a crowd that has already gone under: Now when all the people were baptized, it came to pass, that Jesus also being baptized, and praying, the heaven was opened. The clause makes him the last into the river, not the first, and the painter keeps him the same scale and the same bareness as any other man there — nothing marks him out but the halo. John leans in from the rocks at the left, his hand raised over Christ's head without touching it. Above, at the top edge, a scalloped grey arc is torn open in the gold, and a narrow beam falls from it toward Christ; the paint at its foot, where the dove itself belongs, has worn away to a small pale blur. Four haloed figures wait on the far bank at the right, heads bowed, their hands kept under their draped sleeves rather than bare. At the lower left, among bare wintry trees, a grey axe leans against a trunk — the Forerunner's own warning, given twelve verses earlier in this same chapter: and now also the axe is laid unto the root of the trees. Near it a small draped figure lies at the water's edge, turned back over its own shoulder as though in flight: the river given a body, an image from the Church's own hymn for this feast rather than from Luke's own sentence, which says only that the heaven was opened.",

"File:019 Baptism of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":
 "A Greek panel from the church of St Paraskevi at Langadas, worn hard enough that the two riverbanks have gone to flat green and the faces are mostly gone. What survives is the shape Luke's own sentence gives the scene: the heaven opened, painted as a torn grey-green cleft with small dark trees planted along both its slopes, and down the centre of it a broad orange-red shaft falls toward Christ's head, narrowing at its foot to a small worn mark too flattened by rubbing to call a bird with any confidence. John leans in at the left with his hand raised over him, not on him. At the right, two winged angels in gold and red stand one behind the other, their heads bowed and their own hands, covered by the fall of a white cloth held between them, not shown bare — the reverence the Gospel's own words do not describe, since Luke gives none of the actors here any gesture at all beyond a voice and a heaven that opens. Christ stands in dark water between the banks, and the single sentence Luke sets over the whole scene runs the length of two verses: Jesus also being baptized, and praying, the heaven was opened, and the Holy Ghost descended in a bodily shape like a dove upon him.",

"File:03 Baptism of Christ Icon from Saint Paraskevi Church in Adam.jpg":
 "A panel from the church of St Paraskevi at Adam, better preserved than its neighbour from Langadas and carrying, across the top in worn red letters, the remains of a title — legible now only as fragments of the Baptism … of Christ. Above Christ's head a white dove, wings spread and rayed with light, descends on a straight shaft out of a bank of grey cloud: the one icon of Luke's four where the bird itself, and not only the light around it, is still there to be seen — the Holy Ghost descended in a bodily shape like a dove upon him. John the Forerunner stands at the left, one hand laid on Christ's head, the other holding the end of his own cloak; three haloed angels wait at the right, the foremost holding a white cloth in both hands for the moment Christ will need it. Below the surface of the water, roots of the riverbank trees run down on both sides toward Christ's feet, tangled and bare, but no axe is cut into either trunk here — that detail belongs to the Ohrid panel, not this one. The water itself is dark and unpeopled beneath him; nothing in this telling personifies the river Luke never mentions by name at all in these two verses, only the heaven that opens above it.",

"File:0663Ha. Hermitage Museum (Hall 143). Icon of the Epiphany.jpg":
 "A Russian icon of the seventeenth century, in the Hermitage's collection, and the darkest of Luke's four: the whole centre of the panel is a single wedge of near-black water and sky fused into one shape, split at the top into two jagged banks of cloud with a white radiant star bursting between them. A thin silver ray runs straight down the middle of the black from that star to a second, smaller point of light just above Christ's head — the one clear passage, in any of these four icons, from the heaven that Luke says opened to the mark that stands for the dove that descended out of it, small and still uncertain in shape at this resolution, with two or three tiny red letters beside it too worn to read. John the Forerunner stands at the left in green, his hand on Christ's head; three winged angels lean in from the right in a diagonal file, the foremost in red holding a folded white cloth in both covered hands. Christ himself is thin, pale and marked with the dark lines of a body under strain, standing upright in the black water with his hands open at his sides — not lifted in prayer as some icons show him, though Luke's own clause insists that he was: Jesus also being baptized, and praying, the heaven was opened.",

"File:Christ's temptation (Monreale).jpg":
 "The same Monreale mosaic Matthew's and Mark's readers show, chosen here because it paints the one temptation all three Synoptics tell in the same order: the first. Luke's own opening sentence ties it directly to what has just happened at the Jordan in a way Matthew's does not — And Jesus being full of the Holy Ghost returned from Jordan, and was led by the Spirit into the wilderness — the same Spirit that had only just descended in a bodily shape now driving him out to fast and be tried before he does anything else. The mosaic gives the exchange in Latin around Christ and the winged, dark tempter reaching for the five stones between them: SI FILI DI ES DIC VT LAPIDES ISTI PANE FIANT — command these stones to become bread, if you are the Son of God. It is Matthew's own plural; Luke's devil asks for only one: If thou be the Son of God, command this stone that it be made bread. Luke's own wording of Christ's answer is shorter than Matthew's too: It is written, That man shall not live by bread alone, but by every word of God, stopping short of Matthew's addition that proceedeth out of the mouth of God. It is the first fall in a contest Luke alone tells in a different order from Matthew's — the mountain of the kingdoms comes second in this Gospel, the pinnacle of the temple third, where Matthew has them reversed. St Augustine, weighing the two orders against each other, judged it uncertain which Evangelist had kept the true sequence and which had arranged his own for effect; the Church has never had to choose between them.",

"File:Cathedral (Monreale) - Right wing transept - 2nd Temptation of Christ.jpg":
 "The panel that follows the first temptation along the same wall at Monreale, and in Luke's own order this is the last of the three, not the middle one Matthew makes it. The devil has set Christ on the roof of a small arcaded building — the pinnacle of the temple. Luke alone names the city beneath it: he brought him to Jerusalem. The Latin gives the last exchange of the contest: SI FILIUS DEI ES MITTE TE DEORSUM — if thou be the Son of God, cast thyself down from hence. Christ's reply stands on the other side: SCRIPTUM EST NON TEMPTABIS DOMINUM DEUM TUUM, the inscription's own it is written — though Luke's own third citation changes the verb the first two use: It is said, Thou shalt not tempt the Lord thy God. The winged tempter hangs beside Christ in the air, reaching toward him without touching, exactly as he offered the stones in the first scene. Between the two temptation scenes on this wall lies the one this reader has no icon for: taking him up into an high mountain, shewed unto him all the kingdoms of the world in a moment of time. What ends here is the whole contest, and Luke closes it with a warning the picture cannot show: when the devil had ended all the temptation, he departed from him for a season — not for good, and with none of Matthew's angels sent at once to minister to him. Luke gives him no such comfort here; the season would run until the Passion.",

"File:Monreale - Jesus heals Simon's mother in law.jpg":
 "The same Monreale mosaic Matthew's and Mark's readers show, and the Latin across the top already concedes Luke's own word before any Gospel text is quoted: IHS LIBERAT SOCRUM SIMONIS A MAGNIS FEBRIBUS, Jesus frees Simon's mother-in-law from a great fever. Magnis is Luke's own adjective; neither Matthew nor Mark qualifies the fever at all, and Simon's wife's mother was taken with a great fever is the physician's distinction Luke alone draws, a lesser fever set against a dangerous one. The gesture the mosaicist paints — Christ crossing the room with his arm already out toward her while she raises herself from the bed and reaches back, the two hands close but not joined across the gold — suits Luke's telling better than it suits the other two: Luke is the one Evangelist who has Christ neither touch her hand, as Matthew says, nor take her by the hand and lift her up, as Mark does. What Luke gives instead is a word alone: he stood over her, and rebuked the fever; and it left her — the same verb his Gospel uses elsewhere for silencing unclean spirits, and the fever obeys it as they do. The four men behind Christ are those who had just come with him out of the synagogue, and a fifth head looks in from the doorway at the upper right. Luke ends the verse where Matthew and Mark both end theirs, with what the healing was for: and immediately she arose and ministered unto them.",

// ---- chapter 5 ----

"File:Miraculous catch of fish - Sant'Apollinare Nuovo - Ravenna 2016.jpg":
 "A panel from the miracle cycle of Sant'Apollinare Nuovo at Ravenna, from the first years of the sixth century, catalogued on Commons as the Miraculous Draught of Fish and identified by a specialist in Christian iconography as the Calling of Peter and Andrew, the calling Matthew and Mark both open with one shared clause: casting a net into the sea: for they were fishers. Grey-haired and short-bearded, Peter leans out over the near gunwale with both hands already in the net; beside him, dark-haired and wilder, Andrew works the oar. A second man stands behind Christ on the bank, in a plain mantle, without a halo; who he is meant to be, neither the fresco nor this reading can say. St Augustine, in the Catena, sets the tellings side by side rather than choosing between them: Matthew and Mark here briefly state the matter, and how it was done. Luke explains it more at large. He also allows that the calling Matthew and Mark report may have come later, a second call after the one Luke tells here: so that afterwards that might happen which Matthew and Mark speak of. Luke's own telling gives a night's empty labour turned by Christ's word into a catch that fills two boats until they begin to sink, and Peter falling at Jesus' knees before the word that ends the story: Fear not; from henceforth thou shalt catch men. Christ stands on the bank here rather than seated with Peter in the boat, as Luke's own text has him through most of the story: he entered into one of the ships, which was Simon’s. The mosaic gives Andrew a face; Luke's own account of this calling never names him, a silence St Augustine notices in the same Catena block: he does not mention Andrew by name, who however is thought to have been in that ship, according to the accounts of Matthew and Mark.",

"File:Christ cleans leper man.jpg":
 "The same Monreale mosaic Matthew's and Mark's readers show, and the same Latin plea painted above the gold: POTES ME MVNDARE. Thou canst make me clean. Luke's own description of the man is the fullest of the three Synoptics: not a leper, as Matthew and Mark both have it, but a man full of leprosy, and the mosaicist has covered him with the disease from throat to ankle — dark spots scattered over his bare chest, his forearm, his shin — where Matthew's and Mark's own readings of this picture point only to the hand Christ reaches toward. He stands at the threshold of the building at the right, leaning on a staff, one hand lifted toward Christ and the other still open as though the plea were not yet finished; Christ comes from the left with his own hand out across the gold, the disciples pressed close behind him. Luke closes the story where Matthew and Mark do not: he withdrew himself into the wilderness, and prayed — the same habit of prayer this reader has already met at Christ's own baptism three chapters back, and one no icon of this scene paints.",

"File:Monreale - healing of paralytic.jpg":
 "The same Monreale mosaic Matthew's and Mark's readers show, and Luke's own word for what is happening along the top of the wall is neither of theirs: not Mark's roof dug open nor Matthew's men with a rope, but the tiling — they went upon the housetop, and let him down through the tiling with his couch into the midst before Jesus. Looked at closely, the two men lean in over a lattice of thin overlapping strips and work it apart with their bare hands; no rope is painted at this or any resolution, only fingers gripping the strips themselves. Christ sits enthroned at the left, his hand out; the paralytic has already come up off the bed onto his knees and reaches both arms back toward him, his feet still caught against the frame. Luke alone of the three gives Christ's opening word to him as a single term of address rather than a title of sonship: Man, thy sins are forgiven thee. Matthew and Mark both have Son instead. Luke alone also closes the miracle on the man's own voice: he departed to his own house, glorifying God; and they were all amazed, and they glorified God, and were filled with fear, saying, We have seen strange things to day. The scribes and Pharisees, in a tight knot of heads at the right, are Luke's own witnesses too: they had come out of every town of Galilee, and Judaea, and Jerusalem, drawn there before the miracle rather than only reacting to it.",

"File:Healing of the Paralytic 04-17.jpg":
 "The same Dionisy fresco Matthew's reader shows, from the Nativity cathedral at Ferapontov, and read here for the two clauses that belong to Luke alone. In the middle of the wall the man walks upright with his bed shouldered, and Luke's own sentence for the moment does not stop at the doorway the way Matthew's does: and immediately he rose up before them, and took up that whereon he lay, and departed to his own house, glorifying God. No other Evangelist gives him that last verb. At the right, where the fresco gathers a knot of witnesses with their heads drawn close together, is the moment Luke alone reports in full: they were all amazed, and they glorified God, and were filled with fear, saying, We have seen strange things to day. That is Luke's own word for it, a plain transliteration into English of the Greek paradoxa, things outside all expectation. Christ sits at the left with the apostles behind him, and below him the sick man still lies on his bed among the crowd that brought him — the getting up and the going out are Dionisy's whole subject on this wall, painted three times over so the eye cannot miss what Luke calls the strangest thing anyone there had seen.",

// ---- chapter 5, tier B: Levi ----

"File:090 Mathew the Apostle Icon from Saint Paraskevi Church in Langadas.jpg":
 "A village panel of the nineteenth century from St Paraskevi at Langadas, the same portrait Matthew's and Mark's readers show: an old man with a long white beard, a codex on his knee and a reed pen in his hand. Luke names him only once, at the moment of the calling — he went forth, and saw a publican, named Levi, sitting at the receipt of custom — and never again in this Gospel by that name; the Church has always read Levi and Matthew as the same man, and this is his icon at the far end of the life that calling began, not a picture of the custom-house itself. Luke's own verse for what happened at the table is the one no other Evangelist writes in quite these words: he left all, rose up, and followed him — the same phrase, forsook all, Luke had already used of the fishermen four verses into this chapter, so that the tax-gatherer's rising and theirs are made to answer one another.",

"File:Matthew the Evangelist - icon.jpeg":
 "The same Palekh panel Matthew's and Mark's readers show, Levi painted as the Evangelist he became rather than as the publican Luke's own verse finds him: sitting at his desk with the quill lifted and the winged man — his symbol among the four living creatures — dictating at his shoulder. Luke's account of the call is the shortest clause of any Synoptic's, he left all, rose up, and followed him, and gives no word at all to what the icon spends its whole surface on, the writing of the book afterward. What Luke does give, and Matthew's own Gospel of this same day does not, is the feast that followed the rising: and Levi made him a great feast in his own house: and there was a great company of publicans and of others that sat down with them — his own house still open to the trade he had just left, on the same day he left it.",

// ---- chapter 6 ----

"File:Iomenos xeran echon cheira Dionysiou.jpg":
 "The same Dionysiou fresco Matthew's and Mark's readers show, read here for the one clause that belongs to Luke alone. Before Christ says a word to anyone, Luke tells what is happening that the fresco cannot paint: but he knew their thoughts, and said to the man which had the withered hand, Rise up, and stand forth in the midst — a sentence neither Matthew nor Mark gives at this point in the story, where both let the question about the sabbath come first and the knowledge of the watchers' minds go unmentioned. The man stands alone in the centre of the floor in his short red tunic, his arm already lifting; Christ sits at the left with the apostles behind him; three elders wait along the right wall, one with his hand raised in objection. Luke keeps Mark's next gesture — and looking round about upon them all — but not what Mark hangs on it, no anger and no grief at the hardness of their hearts, only the look itself and then the command: Stretch forth thy hand. And where Mark's men go out to the Herodians, Luke names no council and no ally at all: they were filled with madness; and communed one with another what they might do to Jesus — fury without a plan, in the verse where Mark already has one forming.",

"File:Synaxis of the Twelve Apostles by Constantinople master (early 14th c., Pushkin museum).jpg":
 "A panel painted in Constantinople in the early fourteenth century, now in Moscow, its title lettered in Greek across the top — Η ΣΥΝΑΞΙΣ ΤΩΝ ΔΩΔΕΚΑ ΑΠΟΣΤΟΛΩΝ, the Synaxis of the Twelve Apostles — the apostles' own names running on after it in the same band. They stand in two ranks, four in front with their haloes overlapping and eight behind, holding scrolls and Gospel books. It is a feast icon, kept on the thirtieth of June, set here over the choosing itself rather than any picture of what led to it. Mark's own account puts Christ on a mountain for this choosing too, but only Luke gives what he did there the whole night before it: he went out into a mountain to pray, and continued all night in prayer to God. And when it was day, he called unto him his disciples: and of them he chose twelve, whom also he named apostles. His own list keeps eleven of Matthew's and Mark's names and changes one: where they give Thaddaeus, Luke names Judas the brother of James, the same man tradition calls Jude. Luke also renders one apostle's surname differently from the other two: Simon called Zelotes, where Matthew and Mark both call him the Canaanite — the same word in its own Aramaic dress.",

"File:Synaxis of the Twelve Apostles Dimitar Molerov Rila Monastery 1835.jpg":
 "An icon of 1835 by Dimitar Molerov at the monastery of Rila in Bulgaria — the same close photograph Matthew's and Mark's readers show, five of the twelve filling the frame in a single rank, their gold haloes overlapping into an unbroken line, holding a white scroll, a Gospel bound in gold and stones, and, at the right, the small silver cross of a martyr. The Synaxis is the Church's feast for all twelve together, the thirtieth of June, and stands over the choosing rather than any picture of the mountain. What Luke's own account gives, and Matthew's and Mark's readings of this same icon do not, is the night before the choosing: he went out into a mountain to pray, and continued all night in prayer to God. Luke's own list changes one name from Matthew's: Judas the brother of James, not Thaddaeus.",

"File:The Twelve Apostles, with later gilding, Greek, Late Byzantine, early 1300s, tempera and gold leaf on wood panel - Princeton University Art Museum - DSC06701.jpg":
 "A late Byzantine panel of the early fourteenth century, tempera and gold leaf on wood, now in the Princeton University Art Museum, its gilding a later addition — the same photograph Matthew's and Mark's readers show, the twelve packed into three close ranks against gold until their haloes overlap, a company rather than twelve portraits. That crowding suits the verse just after Luke's own choosing better than the choosing itself: he came down with them, and stood in the plain, and the company of his disciples, and a great multitude of people out of all Judaea and Jerusalem, and from the sea coast of Tyre and Sidon, which came to hear him, and to be healed of their diseases. Luke's own list of the twelve, given three verses earlier, keeps eleven names Matthew and Mark also give and changes one: Judas the brother of James in place of their Thaddaeus.",

// ---- chapter 7 ----

"File:Iomenos Gon Ekatonarchou Dionysiou.jpg":
 "The same Dionysiou fresco Matthew's reader shows, from the katholikon on Mount Athos, 1547. Its own titulus names him son, where Matthew's own underlying word for him, παῖς, can mean either boy or servant — Matthew's own reading of this fresco already notes the painter has made that choice. Luke gives the same man one thing neither Matthew's Gospel nor this titulus does: a certain centurion’s servant, who was dear unto him, was sick, and ready to die. The fresco paints the centurion himself standing at a low wall directly opposite Christ, helmeted and in armour, one hand raised in speech — the meeting Matthew's own Gospel tells: there came unto him a centurion, beseeching him. Luke's account never once puts him in the room. He sent unto him the elders of the Jews, beseeching him that he would come and heal his servant. Only when Jesus was already near the house did he send friends a second time, and it is through them, not to Christ's own face, that Luke gives the centurion's best-known words: Lord, trouble not thyself: for I am not worthy that thou shouldest enter under my roof. Neither the elders nor the friends are painted; only the soldier himself, standing exactly where this Gospel never puts him. St Augustine, weighing Luke's account against Matthew's in the Catena, poses the difficulty as one question — how then will that be true which Matthew relates, A certain centurion came to him, seeing that he himself did not come? — and answers that Matthew made use of a general mode of expression: the more he believed the nearer he came. The elders' own plea is Luke's alone among the Synoptics, and gives the reason no other Gospel does: he loveth our nation, and he hath built us a synagogue. The servant himself sits up fair-haired on a red coverlet at the edge of the frame, face turned up, touched by no one in the picture — the one distance every Gospel that tells this story keeps, whoever carries the words there: say in a word, and my servant shall be healed.",

// ---- chapter 8 ----

"File:Representation of the Sower's parable.JPEG":
 "The same Romanian panel Mark's reader shows, its title lettered across the top, PILDA SEMĂNĂTORULUI — the parable of the sower — with the number 21 beside it, one panel in a series. The panel paints the sower with Christ's face under his own halo, walking forward with seed caught in the fold of his cloak, his arm swung out ahead of him and the throwing hand already open and empty. Luke's own words leave the figure unnamed — A sower went out to sow his seed — but the identification is not the painter's invention: the Catena's own comment on this opening clause already reads Christ's advent into it. St John Chrysostom writes of it, But Christ fitly denominates His advent, His going forth. At the left, on a bare trodden path, birds are down among the fallen seed, four on a close count, for Luke's own clause: some fell by the way side; and it was trodden down, and the fowls of the air devoured it — trodden down is Luke's own addition; the birds devouring the seed is in Matthew's and Mark's telling too. Bare grey rock fills the upper right; where Matthew and Mark both blame no depth of earth, Luke's own verse names a cause neither uses, moisture: it withered away, because it lacked moisture. A thicket with small red flowers grows along the right edge, for the thorns sprang up with it, and choked it; Luke's own explanation of that ground later names a third thing that chokes, missing from Matthew's two things and different from Mark's own third, the lusts of other things: pleasures of this life. Whether the dark, cone-shaped growth behind Christ's shoulder is meant for trees or stands for a ground of its own is not clear from the panel, and neither is a cluster of round pale shapes at the lower right, flecked like the fallen seed — stones, perhaps, or a harvest already reaped; this reading does not choose between them. What is plain is Luke's own name for the last ground: an honest and good heart, having heard the word, keep it, and bring forth fruit with patience — the heart, the keeping and the patience are his own words, though hearing the word and bringing forth fruit both echo Mark's own telling of this ground. Luke also holds back the count the other two give for it, keeping only the top of the yield: an hundredfold, with no thirty or sixty beside it.",

"File:Hrist utišava buru na moru, manastir Gračanica.jpg":
 "The same Gračanica fresco, about 1320, that Matthew's and Mark's readers show, from the monastery King Milutin built in Kosovo. Christ appears twice in the same boat, exactly as those readers already describe: standing at the left, one arm stretched out above the waves, and, apart at the right, resting his head on his hand as a man asleep. Luke's own account gives that sleep one plain verse and moves straight on to the storm: he fell asleep: and there came down a storm of wind on the lake; and they were filled with water, and were in jeopardy — the peril there, grammatically, is the men's own, where Mark's fuller telling gives it instead to the ship, now full. Between the two Christs a grey-bearded man stands at the mast, his face turned up toward the standing Christ; beside him another, in a red tunic, reaches up with both hands into the rigging. Luke's word for the water throughout these four verses is lake, never sea, painted here as ridge after ridge of curling grey brushwork under a sky gone almost black. Luke gives the disciples' own cry a shape neither Matthew nor Mark repeats, doubling the address itself: Master, master, we perish. Where Matthew and Mark both name the sea, Luke's own object is the wind and the raging of the water: and they ceased, and there was a calm. His question to them afterward is Luke's own wording too, Where is your faith?, and it is the disciples themselves who close the passage in wonder: they being afraid wondered, saying one to another, What manner of man is this! for he commandeth even the winds and water, and they obey him.",

"File:Mosaic of the exorcism of the Gerasene demoniac from the Basilica of Sant'Apollinare Nuovo.jpg":
 "The same Ravenna mosaic Mark's reader shows, from Sant'Apollinare Nuovo, about 520 — Christ painted young and beardless, a cross already in his halo, with one unhaloed companion at his shoulder. A single man kneels before him in a plain tan tunic, sleeved to the wrist, both arms reaching out: one man, not two, which is why the mosaic answers to Luke's own telling as it does to Mark's rather than to Matthew's pair. Luke's own account gives him, before Christ ever speaks, a description of his own: a certain man, which had devils long time, and ware no clothes, neither abode in any house, but in the tombs. The mosaic's man is clothed rather than naked; the dark hollow in the rock behind him could be read as the mouth of a tomb, or simply as shadow between the stones, and this reading does not decide it. The three swine at the right, already running down the bank into a strip of bright water, share the same single frame as the kneeling man, though in Luke's own order they run only after the asking and the sending: they besought him that he would not command them to go out into the deep, and, once let go, the herd ran violently down a steep place into the lake, and were choked. The mosaicist has painted one held moment for a scene Luke's own text spreads across several — the meeting, the naming, the plea, the drowning — and the man's calm, clothed kneeling reads more naturally as Luke's own ending, sitting at the feet of Jesus, clothed, and in his right mind, than as his condition when Christ arrived, even though the swine beside him have not yet finished their fall. Luke's own closing sentence gives the one healing two names: Christ's own charge names God, shew how great things God hath done unto thee, and the man's own preaching names Jesus, how great things Jesus had done unto him.",

"File:Daughter of the head of synagogue is resurrected by Christ.jpg":
 "The same Monreale mosaic Mark's reader shows, from Monreale Cathedral, the 1180s. The Latin inscription across the top runs IHS FILIAM IAYRI PRINCIPIS SYNAG..., cut off at the edge of this photograph, and continues onto a second line below it: Jesus raises the daughter of Jairus, ruler of the synagogue, in the house. The painter's own spelling, IAYRI, is not the classical Iairi; the name is Luke's own too, but from the passage before this one, which the picture does not illustrate. Christ approaches from the left with three unhaloed companions behind him, an elder grey-bearded, a dark-bearded man, and a fair youth — exactly the number, though not the names, of he suffered no man to go in, save Peter, and James, and John, and the father and the mother of the maiden. The room the mosaicist has built for them holds far more than that admitted five: a crowd of mourning women and bearded men, one gripping a book, presses in behind the bed on every side, which sits uneasily beside Luke's own he put them all out. The girl herself sits upright already, dressed in a jewelled gown, her hand clasped in Christ's at the bed's edge: took her by the hand, and called, saying, Maid, arise. A bearded man stands at the bed's head with one hand pressed to his breast, closer to a father's own grief than to a ruler's petition, and behind him a woman's hand is at her own cheek — a grief the mosaic has not yet let go of, though Luke's own next clause has already moved past it: her spirit came again, and she arose straightway.",

"File:Raising of Jairus' daughter 03-19.jpg":
 "The same Ferapontov fresco Matthew's and Mark's readers show, Dionisy's work of 1502 on a curved wall, painted twice over with the one scene as those two readers already describe: Christ arriving at the right, and Christ at the bedside at the left. At the right, hand raised in speech, with a cluster of golden-haloed apostles behind him; small at his feet, one or two more kneeling figures — Matthew's reader counts two — belong to the moment Luke sets in the passage before this one: he fell down at Jesus’ feet, and besought him that he would come into his house, a verse this reader does not illustrate on its own, since 8:40–48 has no icon here. At the left the girl sits up already in a white hood and gown, her own hand raised to meet Christ's, the two overlapping at the wrist: took her by the hand, and called, saying, Maid, arise. Mark's reader says the face inside the haloed figure at the bed has flaked away entirely, leaving a bare ring of ochre; at this resolution it has not vanished so much as dimmed to a faint brown ghost, its features still just traceable, nearer Matthew's own barely legible than to a bare ring. A veiled woman and a bearded man stand together at the bed's head, looking down at the girl — Matthew's reader calls them the parents, and Luke names both as the two Christ did admit: and the father and the mother of the maiden.",

"File:Tokalı Kilise Raising of daughter of Jairus - 2004 6964.jpg":
 "The same fresco Matthew's and Mark's readers show, painted on the rock face of a cave church at Göreme in the tenth century — the oldest of the three Jairus images, and on this wall the most worn. Its coverlet dominates the lower half of the composition, patterned in dark red scrollwork edged with a band of black zigzags, drawn with more care than anything else on the wall. The child herself cannot be seen to have a hand at all: she lies swathed to the crown in a striped wrapping of blue and white, and both Matthew's reading and this one agree on what that means for the scene — there is nothing of hers left for Christ's own hand to close over. He leans toward her from the left, a cross still traceable in his halo, one companion's plain halo crowding close behind his own. Further left again, past the edge of a painted doorway, an unhaloed man raises one hand; a run of Greek letters beside him has worn past this reading's ability to make out a name, so none is given here. Beyond the crowd gathered at the bed, a second cross-marked halo appears — Christ, on this reading, a second time on this same stretch of wall, though whether this is the same moment or the next scene along it, none of the three readings of this fresco settles. Luke's own sentence for what happens at the bed carries no word in a second language, unlike Mark's Aramaic: he put them all out, and took her by the hand, and called, saying, Maid, arise.",

// ---- chapter 9 ----

"File:Evlogesis Pente Arton Dionysiou.jpg":
 "The same Dionysiou fresco of 1547 that Matthew's, Mark's and John's readers show, inscribed along the top Η ΕΥΛΟΓΗΣΙΣ ΤΩΝ ΠΕΝΤΕ ΑΡΤΩΝ — the blessing of the five loaves. Luke alone names whose ground this desert place is: he took them, and went aside privately into a desert place belonging to the city called Bethsaida, a detail neither Matthew nor Mark gives here. Christ stands at the left, ΙΣ ΧΣ lettered by his halo, his eyes already lifted past the man before him into the night above them both — looking up to heaven, he blessed them, and brake — his own bare hand cupping the five stacked loaves, the two fishes resting on top of the pile; the grey-bearded apostle before him leans in toward the pile, though his hands are lost in the fold of his own sleeve, and whether he has yet closed on it the picture does not quite show. Behind Christ a jagged white mountain climbs into the dark; one Gospel does put a mountain at this same miracle, Jesus went up into a mountain, and there he sat with his disciples, but it is John's, and Luke never mentions one. Across the middle ground an apostle in green carries bread out to a crowd seated in ordered rows on the slope; among them sits a fair-haired, bare-headed figure, woman or youth, and a boy stands apart with one hand raised — neither counted in Luke's own bare tally of the day, for they were about five thousand men. The ranks themselves keep Luke's own instruction: he said to his disciples, Make them sit down by fifties in a company — his own number is fifties alone, not Mark's hundreds and fifties, and the painter has set the crowd out in blocks to answer it. At the lower left a stack of round loaves in wicker baskets comes to five, by a close count, short of Luke's own twelve baskets gathered afterward of fragments that remained — Mark's reader counts four in the same stack, Matthew's about half a dozen; the painting has not made the number easy to settle twice the same way.",

"File:Feeding the multitude, Sant'Apollinare Nuovo, Ravenna.jpg":
 "The same mosaic Matthew's and Mark's readers show, sixth-century work from Sant'Apollinare Nuovo at Ravenna, kept down to five figures on gold. Both arms are already held out from the body at the centre, one to either side; the face between them is young and beardless, a small cross fixed inside the halo behind it. On the left, a pair of hands lift a stack of bread, a cross scored into each round loaf; on the right, two dark fish are held out together, gripped rather than caught mid-exchange. A narrow strip of green runs along the foot of the whole scene, a plant set at either end of it — the one piece of ground the mosaicist allows the miracle, and no crowd anywhere on it. Luke's own verb for the moment carries a word neither Matthew nor Mark gives it: he blessed them, and brake, and gave to the disciples to set before the multitude — both of theirs leave the object of the blessing unsaid, bare blessed, and brake, and only Luke says what was blessed. That plain pronoun sits close to what the gold panel itself shows: hands already closing over the bread and the fish, with no multitude anywhere in the frame still waiting to be fed.",

"File:Transfiguration of Christ Icon Sinai 12th century.jpg":
 "Luke dates this ascent differently from Matthew and Mark, about an eight days after these sayings rather than their six, and gives it a purpose neither states, to pray, with the company in an order that puts John ahead of James: he took Peter and John and James, and went up into a mountain to pray. This detail, cut from a wide Sinai festal beam whose gold ground is worn through in patches across the whole board, keeps the composition every other icon here shares: Christ on the peak between the two, one hand raised, a scroll in the other. Elias, at the left, is wrapped in a dark mantle, one hand showing half-open at his waist; Moses, at the right, is younger, holds a pale tablet against himself, and reaches his free hand toward Christ. Below, where the wear is worst, three men are scattered across the damaged gold: one seated with a hand lifted as if answering something, one bowed flat at the centre, one kneeling with a hand near his own chest. The seated figure's raised hand is as near as the panel comes to Peter's offer, and Luke's own qualifier for it comes in the same breath, not after it: Master, it is good for us to be here: and let us make three tabernacles; one for thee, and one for Moses, and one for Elias: not knowing what he said.",

"File:Icon of the Transfiguration from Saint Catherine's, Sinai.jpg":
 "Behind Christ's head on this second Sinai panel there is no disc of gold at all, only a few pale red lines fading out into the same bare ground the rest of the board is painted on — of the four Transfigurations in this gallery, the one that risks the least on light drawn in around him. What carries the glory instead is the clothing, and the Evangelist whose own word for it this icon paints most exactly is Luke: his raiment was white and glistering, glistering being his alone, where Matthew has white as the light and Mark exceeding white as snow, so as no fuller on earth can white them. At the left a grey head is wrapped away almost entirely in a dark mantle; at the right stands a much younger figure, dark hair loose, one hand out toward Christ, no tablet in it this time, unlike the same two painted on the panel beside this one — his other hand is lost in the fall of his own robe. Three men are strung along a narrow seam of light below: nearest the mountain's edge, still on his knees, one hand caught mid-gesture, is Peter; further down, gone entirely into the folds of his own robe, is John, no face left to see; apart from the other two, seated rather than kneeling, one hand loose on a raised knee, watching sideways, is James. This gallery's habit of putting all three men down at the sight — kneeling, folded over, seated, none of them standing — reads nearer to Matthew's own report, they fell on their face, than to anything Luke says happened to them there — Luke gives no fall at all. What he gives instead comes earlier, before the glory is even seen: Peter and they that were with him were heavy with sleep: and when they were awake, they saw his glory, and the two men that stood with him. Sleep first, then waking, then glory — and this panel's own middle figure, given no gesture and no face, is as near as paint comes to showing which of the three that sleep sat heaviest on.",

"File:Icon of transfiguration (Spaso-Preobrazhensky Monastery, Yaroslavl).jpg":
 "The most crowded of the four Transfigurations in this gallery, and the only one that paints anything Luke reports beyond the mountaintop itself. The light around Christ at the centre is spiked into eight points, dark blue-green with long gold rays breaking through them; at the left Elias leans out from the rock, hand lifted mid-gesture; at the right Moses leans from another ledge, both arms wrapped around an object bound in cloth rather than opened. Both Matthew and Mark also report the two men talking with Christ; only Luke gives the subject of it, and this panel's own choice to keep Moses's object closed sits well beside what he alone reports next: who appeared in glory, and spake of his decease which he should accomplish at Jerusalem. At the foot of the mountain, one apostle kneels with both arms thrown up toward the light, his face still lifted to it; of the other two, one is pitched head-first down the slope, a hand at his own face, and the other is down on hands and knees, face turned away and hidden. Two small scenes flank the mountain that none of the other three icons here paint at all: at one side, Christ leading the three up the slope on the way there; at the other, Christ bringing them down again — the next passage, and Luke alone gives it its own day: on the next day, when they were come down from the hill, much people met him.",

"File:042 Transfiguration of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":
 "Signed along the bottom edge — 1885 · χείρ Σταύρου Μαργαρίτη εκ Κολακιάς — this one panel reverses the composition every other Transfiguration in this gallery repeats. It is Moses who kneels on the left this time, an open pale tablet on his knee and his own eyes on it rather than on Christ; the old man with the full white beard, one hand curled at his own breast, kneels opposite him on the right — Elias. They are the same two Luke names taking part in the vision, there talked with him two men, which were Moses and Elias; what the two spoke of is given on the Yaroslavl icon in this same gallery and is not repeated here. Light gathers around Christ near the top of the panel, egg-shaped and pale rather than a full disc, his right hand lifted to bless and a scroll closed in the other. Three men below have each been thrown a different way: one has flung both arms straight up while still on his knees; a second lies full length, face to the sky, in the middle of the slope; a third has recoiled hardest of all, at the far edge, and beside his own halo the letters ΙΑΚ still hold — James, named by the painter where the other two are not.",

// ---- chapter 11 ----

"File:Christos Iomenos Daimonon Takophon Dionysiou.jpg":
 "The same Dionysiou fresco of 1547 that Matthew's reader shows at 9:32-34, its own dumb demoniac — Ο Χ(ΡΙΣΤΟ)Σ ΙΩΜΕΝΟΣ ΤΟΝ ΔΑΙΜΟΝΩΝ ΤΑΚΩΦΟΝ lettered across the top in three lines, the word for his affliction broken by the line itself. That earlier passage of Matthew's is not what the Catena itself sets beside this healing. Bede reads it as the same miracle Matthew tells at 12:22, the only demoniac of Matthew's whom he calls both blind and dumb together: that demoniac is related by Matthew to have been not only dumb, but blind. Three miracles then were performed at the same time on one man — and the same dispute about Beelzebub follows there too. This fresco, borrowed from Matthew's shorter, earlier notice of a dumb demoniac alone, keeps a dumb man and no blindness, which is all Luke himself says of him: a devil, and it was dumb. Theophylact's own comment on the word explains the ear the painter has chosen for Christ's hand to rest on, not the head or the mouth: He who was brought before the Lord was both dumb in speech, and deaf in hearing. He was casting out a devil, and it was dumb. And it came to pass, when the devil was gone out, the dumb spake; and the people wondered — and this fresco gives that wonder to a second man, standing apart in an archway of his own, both hands lifted, palms open, no halo on him. A crowd of apostles presses close at Christ's shoulder; the healed man himself is caught bending forward, a green tunic under a red mantle, a hand pressed to his chest, set against a plain wall — nothing about him showing what he was a moment before, since Luke's own account describes him not at all, only the one word, dumb. What follows in Luke's own text, some of them said, He casteth out devils through Beelzebub the chief of the devils, and everything Christ answers it with — a kingdom divided against itself, a house divided against a house, the finger of God, the strong man armed — belongs to the rest of the passage, and none of it is painted here.",

// ---- chapter 15 ----

"File:The Good Shepherd from the Imperial Palace of Constantinople 5th-6th century AD.jpg":
 "No halo, no cross, nothing to mark this figure for Christ at all — a country vignette worked into a palace floor's plain white tesserae, fifth or sixth century, the same one Matthew's reader shows. A beast is draped across his own shoulders, its legs gripped fore and aft by his two hands, and a woven basket of two pale rounded shapes rests at his side. The pose itself is centuries older than the parable it has come to stand for, the ancient ram-bearer, a shepherd with a ram across his shoulders, and the Church took the whole shape over rather than invent one of its own. What that borrowed pose happens to show, though, answers to Luke's own wording of this parable more exactly than to Matthew's: only Luke gives the shepherd this clause, he layeth it on his shoulders, rejoicing, where Matthew's own telling of the same parable never mentions a shoulder at all. The two Gospels also place the flock and the search differently: Luke leaves the ninety and nine standing in the wilderness while the shepherd goes after the one that is lost; Matthew instead sends the shepherd himself into the mountains to seek it. Wilderness or mountains, any rejoicing — none of it is in this worn floor; it stands for the word shepherd rather than picturing the parable. What drew the parable out of Christ, in Luke's own Gospel only, was a complaint about the company he kept: then drew near unto him all the publicans and sinners for to hear him. And the Pharisees and scribes murmured, saying, This man receiveth sinners, and eateth with them.",

"File:Ravenna — The Good Shepherd mosaic.jpg":
 "A gold-framed lunette from the tomb built for Galla Placidia at Ravenna, about 425, the same one Matthew's reader shows, set under a night-blue vault scattered with gold rosettes like stars. The one seated inside the frame is young and beardless, dressed in gold and violet with a full disc of light behind his head; what stands upright in his left hand is not a shepherd's crook but a cross, and his right hand touches the nose of the nearest animal. Five more stand or lie on the green ground around his rock, six in all, three either side, and not one has its head down to graze — every face is turned to his. No shoulder carries anything here; that gesture belongs to the plainer floor in this same gallery. Neither does this gold court picture the parable's own ending any more than the floor pictures its opening — no home, no gathered friends and neighbours, no one saying Rejoice with me; for I have found my sheep which was lost — but the six watching faces sit well enough over the joy Luke names last of all: I say unto you, that likewise joy shall be in heaven over one sinner that repenteth, more than over ninety and nine just persons, which need no repentance.",

// ---- chapter 19 ----

"File:Baiophoros Dionysiou.jpg":
 "White letters against the dark sky above this 1547 Dionysiou fresco give its own title, Η ΒΑΙΟΦΟΡΟΣ — the name the Church gives the feast, not a word out of any Gospel's own text. One animal only carries Christ here, who blesses with his right hand while the company behind him presses close under a run of gold haloes; above them, a full green palm holds two boys at once, working branches loose and passing them down, and across the scene Jerusalem's own towers wait with its people already spilling out through the gate. Not one clause of that tree is Luke's: his own account of this ride never names a branch, a palm, or a leaf, only cloth in the road, and as he went, they spread their clothes in the way — they, in Luke's own sentence, being the disciples who had just set him on the colt, not a crowd. That branch-cutting is a detail this fresco shares with the Langadas and Athonite panels in the gallery; the Adam panel's own palm has nobody in it. All three borrow the scene from Mark's and Matthew's telling, or from John's own naming of the palm outright. What belongs to Luke alone in this stretch of road is its direction: he went before, ascending up to Jerusalem — Christ, not the company behind him, setting the pace.",

"File:005 Entry into Jerusalem Icon from Saint Paraskevi Church in Langadas.jpg":
 "Red letters at the upper left carry the same feast-name lettered on the fresco beside this one in the gallery, Η ΒΑΙΟΦΟΡΟΣ. Here the white mount is turned so that Christ's own head faces backward toward the company following him rather than ahead toward the walls waiting for him — the reverse of the phrase Luke's own text uses for this stretch of road, he went before, ascending up to Jerusalem, Christ leading out ahead of the very men this panel has him watching instead. The errand behind the scene is already finished in Luke's own telling: two men were sent for this same colt, and they that were sent went their way, and found even as he had said unto them — it is the procession itself this panel paints, not the sending or the finding. One dark palm stands in the middle of the board, a small figure worked into its branches, the detail the reading beside this one in the gallery already marks as absent from Luke's own words entirely. Cloth already lies flat on the ground under the advancing hooves, which is the one clause of this whole scene Luke's own text does give: they spread their clothes in the way.",

"File:18 Triumphal entry into Jerusalem Icon from Saint Paraskevi Church in Adam..jpg":
 "A low mountain range sits behind the walls in this 1846 panel from the village of Adam, and a single small palm stands at the left — but nobody is in it. That empty palm sets this panel apart from the three other Entry icons in this gallery, each of which puts someone in its tree. Jerusalem itself takes up the whole top half of the board, towers and a gold dome already close enough to touch, and it is toward that city, not back at the three haloed men following him, that Christ's own face is turned — unlike the Langadas panel beside it in the gallery, where the same gesture runs the other way. Luke alone marks exactly where this moment falls on the road: when he was come nigh, even now at the descent of the mount of Olives — the walls already this large because so little of the road is left to cover. A child is down on his knees at the animal's own hooves, a dark cloth already spread there and another garment laid beside it; at the far right a lone figure in pink leans out high above the crowd at the gate, one arm stretched out to the left.",

"File:Entry into Jerusalem (Afon icon).jpg":
 "Sixteenth-century work from Athos, and the fullest of the four Entry panels in this gallery: a packed file of haloed men at the left, a boy working a branch loose from the dark tree at the centre — again, no such branch is anywhere in Luke's own account of this ride — and the entire right side of the board given over to Jerusalem, row on row of onlooking faces crowded at its gate. That gate crowd paints a city coming out to meet him, which is nearer to John's own account of this day than to Luke's; Luke's own acclamation comes from neither city nor tree but from the packed file at the left itself: not any multitude at large, but the whole multitude of the disciples, who took up praising God with a loud voice for all the mighty works that they had seen, calling out Blessed be the King that cometh in the name of the Lord: peace in heaven, and glory in the highest. That cometh in the name of the Lord is a line all four Gospels share; what the crowd itself cries in Luke alone, among the three Synoptics, is the King in place of Matthew's son of David and Mark's kingdom of our father David, no Hosanna at all, and the pairing peace in heaven, and glory in the highest, which answers back across his own Gospel to its opening pages, where angels sang the same two words in the other order to shepherds in a field: glory to God in the highest, and on earth peace. None of what comes right after this in Luke's own text — Pharisees demanding Christ silence his disciples, and his answer, that if these should hold their peace, the stones would immediately cry out — is painted anywhere in this gallery.",

"File:Christ banish tradesmen from Temple (Monreale).jpg":
 "The same Monreale mosaic Matthew's and Mark's readers show. Next to an older, grey-haired figure at the left stands another man, unhaloed, one arm raised with a short rod closed in his fist; off to the right a wooden dove-cage hangs from the end of a long pole that runs down to one of the sellers, and hoofed animals crowd the lower right corner. None of that belongs to Luke's own account of the act, which stops two clauses short of any of it: he went into the temple, and began to cast out them that sold therein, and them that bought. Mark opens his own telling with the identical verb — began to cast out them that sold and bought — so the difference is not in how forcefully Luke's Christ acts, only in how soon his sentence ends: no table overturned, no money-changer named, no dove-seller, no ox. What follows in Luke, and in nothing this scene paints, is a habit rather than an act — he taught daily in the temple — met at once by a plot no single gesture could freeze: the chief priests and the scribes and the chief of the people sought to destroy him. Luke does not stand alone in explaining why it failed; Mark gives the same shape a few verses after his own telling of this same cleansing, the crowd's own astonishment stopping the same men. But Luke's own wording of it is his: and could not find what they might do: for all the people were very attentive to hear him. Cyril of Alexandria, on this clause, sets the crowd's devotion squarely against the leaders' unbelief: the people held Christ in far higher estimation than the Scribes and Pharisees, and chiefs of the Jews, who not receiving the faith of Christ themselves, rebuked others.",

"File:Rossano Gospels - Cleansing of the Temple.jpg":
 "The same leaf from the Rossano Gospels that Matthew's and Mark's readers already show — silver script on purple parchment, one of the earliest illustrated Gospel books to survive — read here as a page of witness rather than one plain scene. The upper band paints the act itself, headed ΠΕΡΙ ΤΩΝ ΕΚΒΛΗΘΕΝΤΩΝ ΕΚ ΤΟΥ ΙΕΡΟΥ, concerning those cast out of the temple, with a money-changer, a dove-cage and driven oxen all given a place in the picture though none of them has one in Luke's own two verses: them that sold therein, and them that bought is the whole of his description. Below, four busts stand witness in a row, each with his own column of text. The crowned bust at the left is David, and the same crown and the same overlined caption recur at the third bust — David quoted twice, with Hosea between his two appearances and Isaiah after them. Isaiah is the one whose prophecy the scene above is built on, Isaiah 56:7 behind My house is the house of prayer — but where Matthew and Mark both keep the prophecy's own future tense, shall be called, Luke alone flattens it to a plain is. Jeremiah, the source of the sentence's second half, den of thieves, has no column among the manuscript's four witnesses. Bede, writing on this same block of the Catena, offers three reasons the leaders wanted him dead without choosing between them — his daily teaching, the traders he had just cast out, or the praise that had already met him at the gate — and Luke's own next clause only says that they sought to destroy him and could not find what they might do, for all the people were very attentive to hear him, a shape Mark gives too, in his own words, a few verses after his own account of this same act.",

// ---- chapter 21 ----

"File:Second Coming by G.Klontzas (16th c.).jpg":
 "Georgios Klontzas painted this Cretan icon of the Deutera Parousia in the late sixteenth century; Matthew's and Mark's readers already show the same board for their own versions of Christ's own Olivet sermon. Christ sits in a mandorla near the top, and that detail alone gives this reading solid ground: Luke's own noun for the moment is singular where the other two Synoptics are not — and then shall they see the Son of man coming in a cloud with power and great glory — one cloud, against Matthew's clouds of heaven and Mark's own plural. Everything below the throne — ranked saints, a wide flame, ground opening on its dead at the bottom edge — belongs to the Church's own picture of the Last Judgment more than to any one Evangelist's nine verses; nothing here is drawn specifically from what Luke goes on to say. Two things that are Luke's own among the Synoptics have no clear counterpart here. His own list of signs adds a sea roaring that neither Matthew's nor Mark's parallel names — the sea and the waves roaring — a detail the dead-rising register at the foot of the panel, bare ground rather than any sea, does not touch either way. And where Matthew and Mark both keep the parable's tree singular, Ambrose notices that Luke widens it: Matthew speaks of the fig-tree only, Luke of all the trees — a distinction this Last Judgment does not set out to illustrate at all. What the icon spends most of its space on, no part of it attempts the way Luke's own text in these verses actually closes: heaven and earth shall pass away: but my words shall not pass away.",

// ---- chapter 22 ----

"File:Deipnos Mystikos Dionysiou.jpg":
 "Mark's reader already shows this 1547 Dionysiou fresco, Ο ΔΕΙΠΝΟΣ Ο ΜΥΣΤΙΚΟΣ lettered above the table. Among the jugs, knives and more than one goblet already set on the cloth, a footed bowl at the centre holds a single fish — the painter's own addition — Luke's own words for how the meal began go no further than they made ready the passover, and give no dish a name. What the crowded cloth does not sort out is the shape Luke's own telling gives this table across his seven verses: two cups, not one. The first comes before the bread is even touched — he took the cup, and gave thanks, and said, Take this, and divide it among yourselves — sealed at once with a vow, I will not drink of the fruit of the vine, until the kingdom of God shall come. Only then does Luke report the bread — and he took bread, and gave thanks, and brake it, and gave unto them, saying, This is my body which is given for you — followed by a second cup, likewise also the cup after supper, saying, This cup is the new testament in my blood. Gave thanks is Luke's own verb for both bread and cup alike; Matthew and Mark bless the bread and keep gave thanks for the cup only. And where a man in this fresco leans in with his arm toward the bowl, Luke's own sign for that same moment names no dish at all — the hand of him that betrayeth me is with me on the table — the dipping into a dish belonging to Matthew's and Mark's own telling of the warning, not to his.",

"File:05 Last Supper Icon from Saint Paraskevi Church in Adam.jpg":
 "Asterios Anagnostos signed and dated this panel 1898, from the church of Ayia Paraskevi in the village of Adam — the same one Matthew's and Mark's readers already show — inscribed ὁ δεῖπνος ὁ μυστικός, the Mystical Supper. Christ's hand is lifted, palm out; at his side the disciple John's own Gospel calls beloved leans in, his head low — a figure and a posture that belong to John's telling, not Luke's, whose own account of this meal names no one at the table until the warning to Simon a few verses further on. Two small cups sit apart on the cloth, one to either flank of the great bowl at the centre, a dark flask standing beside the cup at the left — a pair that happens to match an arithmetic that is Luke's alone among the Synoptics: two cups, not one, the first before the bread is broken, he took the cup, and gave thanks, and said, Take this, and divide it among yourselves, the second after it, likewise also the cup after supper, saying, This cup is the new testament in my blood. A sleeve reaches toward the great bowl at the centre from the right, though Luke's own words for this same warning name no bowl and no dish at all: behold, the hand of him that betrayeth me is with me on the table. The dish belongs to Matthew's and Mark's own telling of this warning, not to Luke's sentence for it.",

"File:Kirillo-Belozersky iconostasis 12 - Last Supper.jpg":
 "The same 1497 panel from the festival tier at Kirillo-Belozersky that Matthew's and Mark's readers already show. Christ sits apart, at the table's own upper corner rather than its centre, the board tipped forward so nothing on the cloth is hidden from a viewer looking up at it. Bread lies in small triangular pieces across the pale cloth; one is already held between an apostle's fingers at the far side, the closest this icon comes to painting Luke's own he took bread, and gave thanks, and brake it, and gave unto them. Three vessels sit along the table's edge: a footed cup toward one end, a lidded jar between it and the far end, and there, a cup whose outline was only ever drawn, never filled in with paint. Whatever is missing there, whether by the plan of 1497 or five centuries of wear since, the two cups that remain — one finished, one only sketched — sit closer to an arithmetic that is Luke's alone among the four Gospels than a single cup would: two cups over this meal, the first before the bread, he took the cup, and gave thanks, and said, Take this, and divide it among yourselves, the second after it, likewise also the cup after supper, saying, This cup is the new testament in my blood. One apostle leans across and lowers his hand toward the footed cup, near where Luke's own warning sits, though Luke's own sentence for it puts the hand on the table, not in any vessel: the hand of him that betrayeth me is with me on the table. Two apostles at the front face one another with empty, open hands, a gesture this icon cannot date within Luke's own seven verses for the meal, since his account still has Simon warned by name and two swords produced before the company ever leaves this table.",

};
