// Passage types, key verses and type-icon declarations for the Gospel of Luke. `keyVerse` pulls
// the KJV text automatically. Tier is declared, not counted: `tierB` marks the passages whose
// icon is the one the Church attaches to them without depicting their verses.
//
// Only the passages that have an icon are listed. A tier-c passage of Luke has no card and no
// opener, so `app.js` never reaches `p.type` or `p.keyText` for it — checked against the four
// call sites (app.js:176, :209, :297, :312), all of which sit inside `card()` or
// `renderDrawer()`. Entries for the other 104 passages would be dead weight in a hand-edited
// literal that `make check` already guards for duplicate keys because a duplicate once cost a
// session's corrections.
//
// Key verses lean on what only Luke says, where he says something only he says: the soldiers at
// the Jordan, the tiling of the roof, the angel in the garden, the Lord turning to look upon
// Peter, the thief promised paradise, and "Why seek ye the living among the dead?"
//
// `story` retells the passage's own verses — it adds nothing the text does not say, keeps KJV
// spelling (`shewed`, not `shown`) and curly apostrophes, and folds KJV clauses in without
// quotation marks, the same convention Matthew's and John's own `story` fields use. Check every
// batch with `BOOK=luke node src/tools/story_check.js` before commit, then read every "so",
// "that" or "because" the story adds and every quoted speech whose pronouns changed by eye
// against the printed verses — the script catches invented vocabulary, not an invented relation
// between two words that are both already in the text.
module.exports={

 // ---- the six type icons ----
 // The Angel of the Desert is the Church's icon of the Forerunner himself — winged, with his
 // own severed head already in the charger — not a scene from these verses. Mark declares the
 // same file tierB at 1:2-8.
 forerunnerpreach:{tierB:true,type:'Prophet',keyVerse:4,
  story:"In the fifteenth year of the reign of Tiberius Caesar, Pontius Pilate being governor of Judaea and Herod being tetrarch of Galilee, the word of God came unto John the son of Zacharias in the wilderness. He came into all the country about Jordan, preaching the baptism of repentance for the remission of sins, as it is written in the book of the words of Esaias the prophet: The voice of one crying in the wilderness, Prepare ye the way of the Lord, make his paths straight. Every valley shall be filled, and every mountain and hill shall be brought low, and the crooked shall be made straight, and the rough ways shall be made smooth; and all flesh shall see the salvation of God."},
 // The Church identifies Levi at the receipt of custom with the Apostle Matthew, and these are
 // his own icons, not a picture of the receipt of custom.
 levi:{tierB:true,type:'Event',keyVerse:32,
  story:"After these things Jesus went forth, and saw a publican, named Levi, sitting at the receipt of custom, and said unto him, Follow me. Levi left all, rose up, and followed him, and made him a great feast in his own house, and there was a great company of publicans and of others that sat down with them. Their scribes and Pharisees murmured against his disciples, saying, Why do ye eat and drink with publicans and sinners? Jesus answering said unto them, They that are whole need not a physician, but they that are sick: I came not to call the righteous, but sinners to repentance."},
 // The Synaxis of the Twelve is the feast of the apostles, not the night of prayer on the
 // mountain and the choosing at daybreak that Luke reports.
 twelve:{tierB:true,type:'Event',keyVerse:13,
  story:"In those days he went out into a mountain to pray, and continued all night in prayer to God. When it was day he called unto him his disciples, and of them he chose twelve, whom also he named apostles — Simon, whom he also named Peter, and Andrew his brother, James and John, Philip and Bartholomew, Matthew and Thomas, James the son of Alphaeus, and Simon called Zelotes, and Judas the brother of James, and Judas Iscariot, which also was the traitor. He came down with them, and stood in the plain, with the company of his disciples and a great multitude of people out of all Judaea and Jerusalem and from the sea coast of Tyre and Sidon, which came to hear him and to be healed of their diseases; they that were vexed with unclean spirits were healed, and the whole multitude sought to touch him, for there went virtue out of him, and healed them all."},
 // The Good Shepherd carrying the sheep is the image the Church reads over this parable; neither
 // mosaic paints the ninety and nine left in the wilderness.
 lostsheep:{tierB:true,type:'Parable',keyVerse:5,
  story:"Then drew near unto him all the publicans and sinners for to hear him; and the Pharisees and scribes murmured, saying, This man receiveth sinners, and eateth with them. And he spake this parable unto them, saying, What man of you, having an hundred sheep, if he lose one of them, doth not leave the ninety and nine in the wilderness, and go after that which is lost, until he find it? And when he hath found it, he layeth it on his shoulders, rejoicing; and when he cometh home, he calleth together his friends and neighbours, saying unto them, Rejoice with me, for I have found my sheep which was lost. I say unto you, that likewise joy shall be in heaven over one sinner that repenteth, more than over ninety and nine just persons, which need no repentance."},
 // Looked at 2026-09-20d to settle the question HANDOFF left open. The fresco is a frontal
 // Christ on a footstool between two ranked groups of apostles carrying books, with a generic
 // post-resurrection inscription; no wounds are shown, and none of these verses is in it — no
 // table, no broiled fish, no fear. So it is the Church's image of the risen Lord among his own,
 // tierB here as in Matthew and Mark, and `assign.js` was moved to tier b to agree.
 peace:{tierB:true,type:'Event',keyVerse:39,
  story:"As they thus spake, Jesus himself stood in the midst of them, and saith unto them, Peace be unto you. But they were terrified and affrighted, and supposed that they had seen a spirit; and he said unto them, Why are ye troubled? and why do thoughts arise in your hearts? Behold my hands and my feet, that it is I myself: handle me, and see; for a spirit hath not flesh and bones, as ye see me have. And when he had thus spoken, he shewed them his hands and his feet; and while they yet believed not for joy, and wondered, he said unto them, Have ye here any meat? And they gave him a piece of a broiled fish, and of an honeycomb, and he took it, and did eat before them."},
 // St Luke's own icon, shown with his symbol the ox — not a picture of the prologue's four
 // verses. Harvested 2026-09-25c, the bonus find alongside the Feast-cycle harvest.
 prologue:{tierB:true,type:'Event',keyVerse:3,
  story:"Luke opens by naming his purpose. Many had already taken in hand to set forth in order a declaration of the things most surely believed among us, as the eyewitnesses and ministers of the word had delivered them; having himself had perfect understanding of all things from the very first, he too determined to write in order for the most excellent Theophilus, that Theophilus might know the certainty of the things wherein he had already been instructed."},

 // ---- chapter 1 ----
 zacharias:{type:'Event',keyVerse:13,
  story:"Zacharias, a priest of the course of Abia, and his wife Elisabeth, both righteous before God, were old and had no child. As he burned incense in the temple an angel of the Lord appeared beside the altar and told him, Fear not: thy prayer is heard, and thy wife Elisabeth shall bear thee a son, and thou shalt call his name John — a son who shall be great in the sight of the Lord, filled with the Holy Ghost even from his mother’s womb, and who shall go before him in the spirit and power of Elias, to turn the hearts of the fathers to the children. Zacharias asked a sign, Whereby shall I know this? for I am an old man; the angel answered, I am Gabriel, that stand in the presence of God, and told him he should be dumb, and not able to speak, until the day that these things should be performed, because he believed not. He came out of the temple unable to speak, and when the days of his ministration were ended he departed to his own house; after those days Elisabeth conceived, and hid herself five months, saying, Thus hath the Lord dealt with me, to take away my reproach among men."},
 annunciation:{type:'Feast',keyVerse:38,
  story:"In the sixth month the angel Gabriel was sent from God to Nazareth, to a virgin espoused to Joseph of the house of David, named Mary. Hail, thou that art highly favoured, the Lord is with thee, he said, and she was troubled at the saying. Fear not, Mary, he told her: thou shalt conceive in thy womb and bring forth a son, and shalt call his name JESUS; he shall be great, and shall be called the Son of the Highest, and of his kingdom there shall be no end. How shall this be, seeing I know not a man? she asked, and he answered, The Holy Ghost shall come upon thee, and the power of the Highest shall overshadow thee; therefore that holy thing which shall be born of thee shall be called the Son of God — and he told her that her cousin Elisabeth, called barren, had herself conceived in her old age, for with God nothing shall be impossible. Mary answered, Behold the handmaid of the Lord; be it unto me according to thy word, and the angel departed from her."},
 visitation:{type:'Event',keyVerse:42,
  story:"Mary arose and went with haste into the hill country of Juda, to the house of Zacharias, and saluted Elisabeth. At the sound of her voice the babe leaped in Elisabeth’s womb, and Elisabeth, filled with the Holy Ghost, cried out with a loud voice, Blessed art thou among women, and blessed is the fruit of thy womb — and whence is this to me, that the mother of my Lord should come to me? As soon as the voice of thy salutation sounded in mine ears, she said, the babe leaped in my womb for joy; and blessed is she that believed, for there shall be a performance of those things which were told her from the Lord."},
 // Luke's own detail, and the one the icon paints beside the birth itself. `type:'Feast'` prints
 // the "Great Feast" ribbon (app.js), and this is not one of the Twelve — but neither are
 // `supper`, `thomas` (John) or `myrrhbearers` (Mark), already typed 'Feast' by earlier sessions,
 // where `beheading` (Matthew, Mark) is typed 'Event' despite having its own fixed feast day. The
 // convention is not perfectly consistent; flagged for the owner rather than changed here.
 forerunnerbirth:{type:'Feast',keyVerse:63,
  story:"When Elisabeth’s full time came she brought forth a son, and her neighbours and cousins rejoiced with her at the great mercy the Lord had shewed her. On the eighth day they came to circumcise the child and would have called him Zacharias after his father, but his mother said, Not so; he shall be called John — though none of her kindred bore that name. They made signs to his father, who asked for a writing table and wrote, His name is John, and they marvelled all; immediately his mouth was opened and his tongue loosed, and he spake, and praised God. Fear came on all that dwelt round about, and the sayings were noised abroad through all the hill country, every hearer laying them up in his heart and asking, What manner of child shall this be!"},

 // ---- chapter 2 ----
 nativity:{type:'Feast',keyVerse:7,
  story:"A decree from Caesar Augustus went out that all the world should be taxed, and Joseph went up from Nazareth in Galilee to Bethlehem, the city of David, because he was of the house and lineage of David, to be taxed with Mary his espoused wife, being great with child. While they were there the days were accomplished that she should be delivered, and she brought forth her firstborn son, wrapped him in swaddling clothes, and laid him in a manger — because there was no room for them in the inn."},
 circumcision:{type:'Feast',keyVerse:21, // same ribbon caveat as forerunnerbirth above
  story:"When eight days were accomplished for the circumcising of the child, his name was called JESUS, the name the angel had given him before he was conceived in the womb."},
 // The Hypapante, one of the Twelve Great Feasts — Symeon's Nunc Dimittis.
 meeting:{type:'Feast',keyVerse:29,
  story:"When the days of Mary’s purification were accomplished according to the law of Moses, they brought the child to Jerusalem, to present him to the Lord, and to offer a sacrifice according to that which is said in the law of the Lord, a pair of turtledoves or two young pigeons. There was a man in Jerusalem, Simeon, just and devout, waiting for the consolation of Israel, to whom it had been revealed by the Holy Ghost that he should not see death before he had seen the Lord’s Christ. Coming by the Spirit into the temple, he took the child up in his arms and blessed God: Lord, now lettest thou thy servant depart in peace, according to thy word: for mine eyes have seen thy salvation, which thou hast prepared before the face of all people; a light to lighten the Gentiles, and the glory of thy people Israel. He blessed Joseph and Mary, and told Mary that this child is set for the fall and rising again of many in Israel, and for a sign which shall be spoken against (yea, a sword shall pierce through thy own soul also), that the thoughts of many hearts may be revealed. Anna, a widowed prophetess of great age who never departed from the temple but served God with fastings and prayers night and day, came in at that instant and gave thanks likewise, speaking of the child to all them that looked for redemption in Jerusalem."},

 // ---- chapter 3 ----
 // The fresco's right-hand group is soldiers in mail, and 3:14 is the only place in the four
 // Gospels where soldiers come to John and ask what they shall do.
 fruits:{type:'Teaching',keyVerse:14,
  story:"To the multitude that came forth to be baptized John said, O generation of vipers, who hath warned you to flee from the wrath to come? Bring forth therefore fruits worthy of repentance, and begin not to say within yourselves, We have Abraham to our father, for God is able of these stones to raise up children unto Abraham; now also the axe is laid unto the root of the trees, and every tree that bringeth not forth good fruit is hewn down and cast into the fire. Asked what they should do, he told the people, He that hath two coats, let him impart to him that hath none, and he that hath meat, let him do likewise; he told the publicans, Exact no more than that which is appointed you; and he told the soldiers, Do violence to no man, neither accuse any falsely, and be content with your wages."},
 baptism:{type:'Feast',keyVerse:22,
  story:"When all the people were baptized, Jesus also being baptized, and praying, the heaven was opened, and the Holy Ghost descended in a bodily shape like a dove upon him, and a voice came from heaven: Thou art my beloved Son; in thee I am well pleased."},

 // ---- chapter 4 ----
 // Luke's own close to the forty days, and his own order: the stones, the kingdoms, the pinnacle.
 temptation:{type:'Event',keyVerse:13,
  story:"Jesus, full of the Holy Ghost, returned from Jordan and was led by the Spirit into the wilderness, forty days tempted of the devil; he did eat nothing in those days, and when they were ended he afterward hungered. If thou be the Son of God, said the devil, command this stone that it be made bread — but Jesus answered, It is written, That man shall not live by bread alone, but by every word of God. Taking him up into an high mountain, the devil shewed him all the kingdoms of the world in a moment of time, and offered him all this power and the glory of them if he would worship him; Jesus answered, Get thee behind me, Satan: for it is written, Thou shalt worship the Lord thy God, and him only shalt thou serve. Then the devil set him on a pinnacle of the temple and said, If thou be the Son of God, cast thyself down from hence, for it is written, He shall give his angels charge over thee, to keep thee; and Jesus answered, It is said, Thou shalt not tempt the Lord thy God. When the devil had ended all the temptation, he departed from him for a season."},
 petersmother:{type:'Miracle',keyVerse:39,
  story:"Jesus arose out of the synagogue and entered into Simon’s house, where Simon’s wife’s mother was taken with a great fever, and they besought him for her. He stood over her, and rebuked the fever, and it left her; immediately she arose and ministered unto them. When the sun was setting, all they that had any sick with divers diseases brought them unto him, and he laid his hands on every one of them and healed them; devils also came out of many, crying out, Thou art Christ the Son of God, but he rebuked them and suffered them not to speak, for they knew that he was Christ."},

 // ---- chapter 5 ----
 draught:{type:'Miracle',keyVerse:11,
  story:"As the people pressed upon him to hear the word of God, Jesus stood by the lake of Gennesaret and saw two ships standing by the lake, the fishermen gone out of them and washing their nets. He entered into Simon’s ship, and prayed him to thrust out a little from the land, and sat down and taught the people out of the ship; when he had left speaking he told Simon, Launch out into the deep, and let down your nets for a draught. Simon answered, Master, we have toiled all the night and taken nothing, nevertheless at thy word I will let down the net — and they inclosed a great multitude of fishes, and their net brake; and they beckoned unto their partners in the other ship, that they should come and help them, and they came, and filled both the ships, so that they began to sink. Simon Peter, astonished, fell down at Jesus’ knees, saying, Depart from me, for I am a sinful man, O Lord; and Jesus told him, Fear not, from henceforth thou shalt catch men. And when they had brought their ships to land, they forsook all, and followed him."},
 leper:{type:'Miracle',keyVerse:13,
  story:"In a certain city was a man full of leprosy who, seeing Jesus, fell on his face and besought him, saying, Lord, if thou wilt, thou canst make me clean. Jesus put forth his hand and touched him, saying, I will: be thou clean — and immediately the leprosy departed from him. He charged him to tell no man, but to go and shew himself to the priest and offer for his cleansing according as Moses commanded, for a testimony unto them; yet so much the more went there a fame abroad of him, and great multitudes came together to hear him and to be healed of their infirmities, and he withdrew himself into the wilderness, and prayed."},
 // The tiling, which is what the Monreale mosaic paints.
 paralytic:{type:'Miracle',keyVerse:19,
  story:"As Jesus taught, with Pharisees and doctors of the law sitting by who had come out of every town of Galilee and Judaea and Jerusalem, and the power of the Lord was present to heal them, men brought in a bed a man taken with a palsy, and sought means to bring him in and lay him before Jesus. Finding no way in because of the multitude, they went upon the housetop and let him down through the tiling with his couch into the midst before Jesus; and when Jesus saw their faith he said, Man, thy sins are forgiven thee. The scribes and Pharisees began to reason, Who is this which speaketh blasphemies? who can forgive sins but God alone? — but Jesus, perceiving their thoughts, asked them, Whether is easier, to say, Thy sins be forgiven thee, or to say, Rise up and walk? and, that they might know that the Son of man hath power upon earth to forgive sins, he said to the man sick of the palsy, Arise, and take up thy couch, and go into thine house. Immediately he rose up before them, took up that whereon he lay, and departed to his own house, glorifying God; and they were all amazed, and glorified God, and were filled with fear, saying, We have seen strange things to day."},

 // ---- chapter 6 ----
 witheredhand:{type:'Miracle',keyVerse:10,
  story:"On another sabbath Jesus entered into the synagogue and taught, and there was a man whose right hand was withered; the scribes and Pharisees watched him, whether he would heal on the sabbath day, that they might find an accusation against him. Knowing their thoughts, he said to the man with the withered hand, Rise up, and stand forth in the midst, and he arose and stood forth. Then Jesus said unto them, I will ask you one thing: is it lawful on the sabbath days to do good, or to do evil? to save life, or to destroy it? and looking round about upon them all, he said to the man, Stretch forth thy hand; and he did so, and his hand was restored whole as the other. But they were filled with madness, and communed one with another what they might do to Jesus."},

 // ---- chapter 7 ----
 centurion:{type:'Miracle',keyVerse:9,
  story:"When Jesus had ended all his sayings in the audience of the people, he entered into Capernaum. A certain centurion’s servant, who was dear unto him, was sick and ready to die, and when the centurion heard of Jesus he sent unto him the elders of the Jews, beseeching him that he would come and heal his servant. They came to Jesus and besought him instantly, saying that he was worthy for whom he should do this, for he loveth our nation, and he hath built us a synagogue. Jesus went with them; and when he was now not far from the house, the centurion sent friends to him, saying, Lord, trouble not thyself, for I am not worthy that thou shouldest enter under my roof — wherefore neither thought I myself worthy to come unto thee: but say in a word, and my servant shall be healed. For I also am a man set under authority, having under me soldiers, and I say unto one, Go, and he goeth, and to another, Come, and he cometh, and to my servant, Do this, and he doeth it. When Jesus heard these things he marvelled at him, and turned him about, and said unto the people that followed him, I say unto you, I have not found so great faith, no, not in Israel. They that were sent, returning to the house, found the servant whole that had been sick."},

 // ---- chapter 8 ----
 sower:{type:'Parable',keyVerse:11,
  story:"When much people were gathered together, come to him out of every city, he spake by a parable: A sower went out to sow his seed, and as he sowed some fell by the way side, and it was trodden down, and the fowls of the air devoured it; and some fell upon a rock, and as soon as it was sprung up, it withered away, because it lacked moisture; and some fell among thorns, and the thorns sprang up with it, and choked it; and other fell on good ground, and sprang up, and bare fruit an hundredfold. When he had said these things he cried, He that hath ears to hear, let him hear. His disciples asked him what this parable might be, and he said, Unto you it is given to know the mysteries of the kingdom of God, but to others in parables, that seeing they might not see, and hearing they might not understand. Now the parable is this: the seed is the word of God. Those by the way side are they that hear, then cometh the devil, and taketh away the word out of their hearts, lest they should believe and be saved. They on the rock are they which, when they hear, receive the word with joy, and these have no root, which for a while believe, and in time of temptation fall away. That which fell among thorns are they which, when they have heard, go forth, and are choked with cares and riches and pleasures of this life, and bring no fruit to perfection. But that on the good ground are they which in an honest and good heart, having heard the word, keep it, and bring forth fruit with patience."},
 storm:{type:'Miracle',keyVerse:24,
  story:"On a certain day he went into a ship with his disciples, and said unto them, Let us go over unto the other side of the lake; and they launched forth. As they sailed he fell asleep, and there came down a storm of wind on the lake, and they were filled with water, and were in jeopardy. They came to him, and awoke him, saying, Master, master, we perish; then he arose, and rebuked the wind and the raging of the water, and they ceased, and there was a calm. He said unto them, Where is your faith? and they, being afraid, wondered, saying one to another, What manner of man is this! for he commandeth even the winds and water, and they obey him."},
 gadarene:{type:'Miracle',keyVerse:35,
  story:"They arrived at the country of the Gadarenes, which is over against Galilee. When Jesus went forth to land, there met him out of the city a certain man which had devils long time, and ware no clothes, neither abode in any house, but in the tombs. When he saw Jesus, he cried out, and fell down before him, and with a loud voice said, What have I to do with thee, Jesus, thou Son of God most high? I beseech thee, torment me not — for Jesus had commanded the unclean spirit to come out of the man, for oftentimes it had caught him, and he was kept bound with chains and in fetters, and he brake the bands, and was driven of the devil into the wilderness. Jesus asked him, What is thy name? and he said, Legion, because many devils were entered into him. They besought him that he would not command them to go out into the deep; and there was there an herd of many swine feeding on the mountain, and they besought him that he would suffer them to enter into them, and he suffered them. Then the devils went out of the man, and entered into the swine, and the herd ran violently down a steep place into the lake, and were choked. When they that fed them saw what was done, they fled, and told it in the city and in the country. They went out to see what was done, and came to Jesus, and found the man, out of whom the devils were departed, sitting at the feet of Jesus, clothed, and in his right mind, and they were afraid; and they that saw it told them by what means he that was possessed of the devils was healed. Then the whole multitude of the country of the Gadarenes round about besought him to depart from them, for they were taken with great fear, and he went up into the ship, and returned back again. The man out of whom the devils were departed besought him that he might be with him, but Jesus sent him away, saying, Return to thine own house, and shew how great things God hath done unto thee. And he went his way, and published throughout the whole city how great things Jesus had done unto him."},
 issueofblood:{type:'Miracle',keyVerse:44,
  story:"When Jesus was returned, the people gladly received him, for they were all waiting for him. There came a man named Jairus, a ruler of the synagogue, and he fell down at Jesus’ feet, and besought him that he would come into his house, for he had one only daughter, about twelve years of age, and she lay a dying. But as he went the people thronged him; and a woman having an issue of blood twelve years, which had spent all her living upon physicians, neither could be healed of any, came behind him, and touched the border of his garment, and immediately her issue of blood stanched. Jesus said, Who touched me? and when all denied, Peter and they that were with him said, Master, the multitude throng thee and press thee, and sayest thou, Who touched me? And Jesus said, Somebody hath touched me, for I perceive that virtue is gone out of me. When the woman saw that she was not hid, she came trembling, and falling down before him, she declared unto him before all the people for what cause she had touched him, and how she was healed immediately. He said unto her, Daughter, be of good comfort: thy faith hath made thee whole; go in peace."},
 jairus:{type:'Miracle',keyVerse:54,
  story:"While he yet spake, there came one from the ruler of the synagogue’s house, saying to him, Thy daughter is dead; trouble not the Master. But when Jesus heard it he answered him, Fear not: believe only, and she shall be made whole. When he came into the house he suffered no man to go in, save Peter, and James, and John, and the father and the mother of the maiden. All wept, and bewailed her, but he said, Weep not; she is not dead, but sleepeth. And they laughed him to scorn, knowing that she was dead. He put them all out, and took her by the hand, and called, saying, Maid, arise. Her spirit came again, and she arose straightway, and he commanded to give her meat. Her parents were astonished, but he charged them that they should tell no man what was done."},

 // ---- chapter 9 ----
 fivethousand:{type:'Miracle',keyVerse:16,
  story:"The apostles, when they were returned, told him all that they had done; and he took them, and went aside privately into a desert place belonging to the city called Bethsaida. And the people, when they knew it, followed him, and he received them, and spake unto them of the kingdom of God, and healed them that had need of healing. When the day began to wear away, the twelve came, and said unto him, Send the multitude away, that they may go into the towns and country round about, and lodge, and get victuals, for we are here in a desert place. But he said unto them, Give ye them to eat. And they said, We have no more but five loaves and two fishes, except we should go and buy meat for all this people — for they were about five thousand men. He said to his disciples, Make them sit down by fifties in a company, and they did so, and made them all sit down. Then he took the five loaves and the two fishes, and looking up to heaven, he blessed them, and brake, and gave to the disciples to set before the multitude. They did eat, and were all filled, and there was taken up of fragments that remained to them twelve baskets."},
 // Luke alone ties the Transfiguration to prayer: "And as he prayed, the fashion of his
 // countenance was altered."
 transfiguration:{type:'Feast',keyVerse:29,
  story:"About an eight days after these sayings, Jesus took Peter and John and James, and went up into a mountain to pray. As he prayed, the fashion of his countenance was altered, and his raiment was white and glistering, and, behold, there talked with him two men, which were Moses and Elias, who appeared in glory, and spake of his decease which he should accomplish at Jerusalem. Peter and they that were with him were heavy with sleep, and when they were awake, they saw his glory, and the two men that stood with him. As they departed from him, Peter said unto Jesus, Master, it is good for us to be here, and let us make three tabernacles, one for thee, and one for Moses, and one for Elias — not knowing what he said. While he thus spake, there came a cloud, and overshadowed them, and they feared as they entered into the cloud; and there came a voice out of the cloud, saying, This is my beloved Son: hear him. When the voice was past, Jesus was found alone; and they kept it close, and told no man in those days any of those things which they had seen."},

 // ---- chapter 10 ----
 samaritan:{type:'Parable',keyVerse:34,
  story:"A certain lawyer stood up, and tempted him, saying, Master, what shall I do to inherit eternal life? He said unto him, What is written in the law? how readest thou? And he answering said, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy strength, and with all thy mind; and thy neighbour as thyself. And he said unto him, Thou hast answered right: this do, and thou shalt live. But he, willing to justify himself, said unto Jesus, And who is my neighbour? And Jesus answering said, A certain man went down from Jerusalem to Jericho, and fell among thieves, which stripped him of his raiment, and wounded him, and departed, leaving him half dead. And by chance there came down a certain priest that way, and when he saw him, he passed by on the other side; and likewise a Levite, when he was at the place, came and looked on him, and passed by on the other side. But a certain Samaritan, as he journeyed, came where he was, and when he saw him, he had compassion on him, and went to him, and bound up his wounds, pouring in oil and wine, and set him on his own beast, and brought him to an inn, and took care of him. On the morrow when he departed, he took out two pence, and gave them to the host, and said unto him, Take care of him; and whatsoever thou spendest more, when I come again, I will repay thee. Which now of these three, thinkest thou, was neighbour unto him that fell among the thieves? And he said, He that shewed mercy on him. Then said Jesus unto him, Go, and do thou likewise."},

 // ---- chapter 11 ----
 // The devil that was dumb — exactly what the Dionysiou fresco is inscribed for.
 beelzebub:{type:'Miracle',keyVerse:14,
  story:"He was casting out a devil, and it was dumb; and when the devil was gone out, the dumb spake, and the people wondered. But some of them said, He casteth out devils through Beelzebub the chief of the devils; and others, tempting him, sought of him a sign from heaven. But he, knowing their thoughts, said unto them, Every kingdom divided against itself is brought to desolation, and a house divided against a house falleth; if Satan also be divided against himself, how shall his kingdom stand? because ye say that I cast out devils through Beelzebub. And if I by Beelzebub cast out devils, by whom do your sons cast them out? therefore shall they be your judges. But if I with the finger of God cast out devils, no doubt the kingdom of God is come upon you. When a strong man armed keepeth his palace, his goods are in peace; but when a stronger than he shall come upon him, and overcome him, he taketh from him all his armour wherein he trusted, and divideth his spoils. He that is not with me is against me, and he that gathereth not with me scattereth. When the unclean spirit is gone out of a man, he walketh through dry places, seeking rest; and finding none, he saith, I will return unto my house whence I came out. And when he cometh, he findeth it swept and garnished. Then goeth he, and taketh to him seven other spirits more wicked than himself, and they enter in, and dwell there; and the last state of that man is worse than the first."},

 // ---- chapter 17 ----
 tenlepers:{type:'Miracle',keyVerse:14,
  story:"As he went to Jerusalem, he passed through the midst of Samaria and Galilee; and as he entered into a certain village, there met him ten men that were lepers, which stood afar off, and lifted up their voices, and said, Jesus, Master, have mercy on us. When he saw them, he said unto them, Go shew yourselves unto the priests; and as they went, they were cleansed. One of them, when he saw that he was healed, turned back, and with a loud voice glorified God, and fell down on his face at his feet, giving him thanks — and he was a Samaritan. And Jesus answering said, Were there not ten cleansed? but where are the nine? There are not found that returned to give glory to God, save this stranger. And he said unto him, Arise, go thy way: thy faith hath made thee whole."},

 // ---- chapter 18 ----
 publican:{type:'Parable',keyVerse:13,
  story:"He spake this parable unto certain which trusted in themselves that they were righteous, and despised others: Two men went up into the temple to pray; the one a Pharisee, and the other a publican. The Pharisee stood and prayed thus with himself, God, I thank thee, that I am not as other men are, extortioners, unjust, adulterers, or even as this publican: I fast twice in the week, I give tithes of all that I possess. And the publican, standing afar off, would not lift up so much as his eyes unto heaven, but smote upon his breast, saying, God be merciful to me a sinner. I tell you, this man went down to his house justified rather than the other: for every one that exalteth himself shall be abased, and he that humbleth himself shall be exalted."},

 // ---- chapter 19 ----
 entry:{type:'Feast',keyVerse:36,
  story:"When he had thus spoken, he went before, ascending up to Jerusalem; and when he was come nigh to Bethphage and Bethany, at the mount called the mount of Olives, he sent two of his disciples, saying, Go ye into the village over against you; in the which at your entering ye shall find a colt tied, whereon yet never man sat: loose him, and bring him hither. And if any man ask you, Why do ye loose him? thus shall ye say unto him, Because the Lord hath need of him. And they that were sent went their way, and found even as he had said unto them; and as they were loosing the colt, the owners thereof said unto them, Why loose ye the colt? And they said, The Lord hath need of him. And they brought him to Jesus, and cast their garments upon the colt, and set Jesus thereon; and as he went, they spread their clothes in the way."},
 temple:{type:'Event',keyVerse:46,
  story:"He went into the temple, and began to cast out them that sold therein, and them that bought; saying unto them, It is written, My house is the house of prayer: but ye have made it a den of thieves. And he taught daily in the temple. But the chief priests and the scribes and the chief of the people sought to destroy him, and could not find what they might do: for all the people were very attentive to hear him."},

 // ---- chapter 21 ----
 coming:{type:'Teaching',keyVerse:27,
  story:"There shall be signs in the sun, and in the moon, and in the stars, and upon the earth distress of nations, with perplexity, the sea and the waves roaring; men’s hearts failing them for fear, and for looking after those things which are coming on the earth, for the powers of heaven shall be shaken. And then shall they see the Son of man coming in a cloud with power and great glory. And when these things begin to come to pass, then look up, and lift up your heads; for your redemption draweth nigh. And he spake to them a parable: Behold the fig tree, and all the trees; when they now shoot forth, ye see and know of your own selves that summer is now nigh at hand. So likewise ye, when ye see these things come to pass, know ye that the kingdom of God is nigh at hand. Verily I say unto you, This generation shall not pass away, till all be fulfilled. Heaven and earth shall pass away: but my words shall not pass away."},

 // ---- chapter 22 ----
 supper:{type:'Feast',keyVerse:19,
  story:"When the hour was come, he sat down, and the twelve apostles with him. And he said unto them, With desire I have desired to eat this passover with you before I suffer: for I say unto you, I will not any more eat thereof, until it be fulfilled in the kingdom of God. And he took the cup, and gave thanks, and said, Take this, and divide it among yourselves: for I say unto you, I will not drink of the fruit of the vine, until the kingdom of God shall come. And he took bread, and gave thanks, and brake it, and gave unto them, saying, This is my body which is given for you: this do in remembrance of me. Likewise also the cup after supper, saying, This cup is the new testament in my blood, which is shed for you."},
 // The angel from heaven strengthening him: Luke alone.
 gethsemane:{type:'Event',keyVerse:43,
  story:"He came out, and went, as he was wont, to the mount of Olives; and his disciples also followed him. And when he was at the place, he said unto them, Pray that ye enter not into temptation. And he was withdrawn from them about a stone’s cast, and kneeled down, and prayed, saying, Father, if thou be willing, remove this cup from me: nevertheless not my will, but thine, be done. And there appeared an angel unto him from heaven, strengthening him; and being in an agony he prayed more earnestly, and his sweat was as it were great drops of blood falling down to the ground. And when he rose up from prayer, and was come to his disciples, he found them sleeping for sorrow, and said unto them, Why sleep ye? rise and pray, lest ye enter into temptation."},
 // Luke alone gives the Lord's words to Judas at the kiss.
 arrest:{type:'Event',keyVerse:48,
  story:"While he yet spake, behold a multitude, and he that was called Judas, one of the twelve, went before them, and drew near unto Jesus to kiss him. But Jesus said unto him, Judas, betrayest thou the Son of man with a kiss? When they which were about him saw what would follow, they said unto him, Lord, shall we smite with the sword? And one of them smote the servant of the high priest, and cut off his right ear. And Jesus answered and said, Suffer ye thus far; and he touched his ear, and healed him. Then Jesus said unto the chief priests, and captains of the temple, and the elders, which were come to him, Be ye come out, as against a thief, with swords and staves? When I was daily with you in the temple, ye stretched forth no hands against me: but this is your hour, and the power of darkness."},
 // Luke alone has the Lord turn and look upon Peter.
 denial:{type:'Event',keyVerse:61,
  story:"Then took they him, and led him, and brought him into the high priest’s house. And Peter followed afar off. And when they had kindled a fire in the midst of the hall, and were set down together, Peter sat down among them. But a certain maid beheld him as he sat by the fire, and earnestly looked upon him, and said, This man was also with him. And he denied him, saying, Woman, I know him not. And after a little while another saw him, and said, Thou art also of them; and Peter said, Man, I am not. And about the space of one hour after another confidently affirmed, saying, Of a truth this fellow also was with him: for he is a Galilaean. And Peter said, Man, I know not what thou sayest. And immediately, while he yet spake, the cock crew. And the Lord turned, and looked upon Peter. And Peter remembered the word of the Lord, how he had said unto him, Before the cock crow, thou shalt deny me thrice. And Peter went out, and wept bitterly."},
 // Luke alone gives Christ this clause of his answer to the council's first question;
 // neither icon paints it, but it is part of the largest block of his own words in either scene.
 council:{type:'Event',keyVerse:68,
  story:"The men that held Jesus mocked him, and smote him; and when they had blindfolded him, they struck him on the face, and asked him, saying, Prophesy, who is it that smote thee? And many other things blasphemously spake they against him. And as soon as it was day, the elders of the people and the chief priests and the scribes came together, and led him into their council, saying, Art thou the Christ? tell us. And he said unto them, If I tell you, ye will not believe: and if I also ask you, ye will not answer me, nor let me go. Hereafter shall the Son of man sit on the right hand of the power of God. Then said they all, Art thou then the Son of God? And he said unto them, Ye say that I am. And they said, What need we any further witness? for we ourselves have heard of his own mouth."},

 // ---- chapter 23 ----
 // Augustine's own comment on this block says Matthew and Mark affirm the accusing but
 // never give its words, where Luke has laid open the very charges themselves — a clause
 // in this passage that passes the header's own "only Luke says" test.
 pilate:{type:'Event',keyVerse:2,
  story:"The whole multitude of them arose, and led him unto Pilate; and they began to accuse him, saying, We found this fellow perverting the nation, and forbidding to give tribute to Caesar, saying that he himself is Christ a King. And Pilate asked him, saying, Art thou the King of the Jews? And he answered him and said, Thou sayest it. Then said Pilate to the chief priests and to the people, I find no fault in this man. And they were the more fierce, saying, He stirreth up the people, teaching throughout all Jewry, beginning from Galilee to this place."},
 // Luke alone gives the thief on the right hand his words and the promise of paradise.
 crucifixion:{type:'Event',keyVerse:43,
  story:"And when they were come to the place, which is called Calvary, there they crucified him, and the malefactors, one on the right hand, and the other on the left. Then said Jesus, Father, forgive them; for they know not what they do. And they parted his raiment, and cast lots. And the people stood beholding. And the rulers also with them derided him, saying, He saved others; let him save himself, if he be Christ, the chosen of God. And the soldiers also mocked him, coming to him, and offering him vinegar, and saying, If thou be the king of the Jews, save thyself. And a superscription also was written over him in letters of Greek, and Latin, and Hebrew, THIS IS THE KING OF THE JEWS. And one of the malefactors which were hanged railed on him, saying, If thou be Christ, save thyself and us. But the other answering rebuked him, saying, Dost not thou fear God, seeing thou art in the same condemnation? And we indeed justly; for we receive the due reward of our deeds: but this man hath done nothing amiss. And he said unto Jesus, Lord, remember me when thou comest into thy kingdom. And Jesus said unto him, Verily I say unto thee, To day shalt thou be with me in paradise."},
 // None of Matthew, Mark or John says Joseph dissented from the council that condemned Christ;
 // only Luke's own parenthesis at 23:51 does.
 burial:{type:'Event',keyVerse:51,
  story:"There was a man named Joseph, a counsellor; and he was a good man, and a just: (the same had not consented to the counsel and deed of them;) he was of Arimathaea, a city of the Jews: who also himself waited for the kingdom of God. This man went unto Pilate, and begged the body of Jesus. And he took it down, and wrapped it in linen, and laid it in a sepulchre that was hewn in stone, wherein never man before was laid. And that day was the preparation, and the sabbath drew on. And the women also, which came with him from Galilee, followed after, and beheld the sepulchre, and how his body was laid; and they returned, and prepared spices and ointments, and rested the sabbath day according to the commandment."},

 // ---- chapter 24 ----
 // The two angels of 24:4 speak it, and the Dionysiou fresco paints two where Matthew and Mark
 // give one.
 myrrhbearers:{type:'Event',keyVerse:5,
  story:"Upon the first day of the week, very early in the morning, the women came unto the sepulchre, bringing the spices which they had prepared, and certain others with them; and they found the stone rolled away from the sepulchre, and they entered in, and found not the body of the Lord Jesus. As they were much perplexed thereabout, behold, two men stood by them in shining garments; and as they were afraid, and bowed down their faces to the earth, they said unto them, Why seek ye the living among the dead? He is not here, but is risen: remember how he spake unto you when he was yet in Galilee, saying, The Son of man must be delivered into the hands of sinful men, and be crucified, and the third day rise again. And they remembered his words, and returned from the sepulchre, and told all these things unto the eleven, and to all the rest. It was Mary Magdalene, and Joanna, and Mary the mother of James, and other women that were with them, which told these things unto the apostles; and their words seemed to them as idle tales, and they believed them not. Then arose Peter, and ran unto the sepulchre; and stooping down, he beheld the linen clothes laid by themselves, and departed, wondering in himself at that which was come to pass."},
 emmausroad:{type:'Event',keyVerse:17,
  story:"Two of them went that same day to a village called Emmaus, which was from Jerusalem about threescore furlongs, and they talked together of all these things which had happened. And it came to pass, that, while they communed together and reasoned, Jesus himself drew near, and went with them; but their eyes were holden that they should not know him. And he said unto them, What manner of communications are these that ye have one to another, as ye walk, and are sad? And the one of them, whose name was Cleopas, answering said unto him, Art thou only a stranger in Jerusalem, and hast not known the things which are come to pass there in these days? And he said unto them, What things? And they said unto him, Concerning Jesus of Nazareth, which was a prophet mighty in deed and word before God and all the people, and how the chief priests and our rulers delivered him to be condemned to death, and have crucified him. But we trusted that it had been he which should have redeemed Israel: and beside all this, to day is the third day since these things were done. Yea, and certain women also of our company made us astonished, which were early at the sepulchre; and when they found not his body, they came, saying, that they had also seen a vision of angels, which said that he was alive. And certain of them which were with us went to the sepulchre, and found it even so as the women had said: but him they saw not."},
 breaking:{type:'Event',keyVerse:35,
  story:"Then he said unto them, O fools, and slow of heart to believe all that the prophets have spoken: ought not Christ to have suffered these things, and to enter into his glory? And beginning at Moses and all the prophets, he expounded unto them in all the scriptures the things concerning himself. And they drew nigh unto the village, whither they went; and he made as though he would have gone further. But they constrained him, saying, Abide with us: for it is toward evening, and the day is far spent. And he went in to tarry with them. And it came to pass, as he sat at meat with them, he took bread, and blessed it, and brake, and gave to them; and their eyes were opened, and they knew him; and he vanished out of their sight. And they said one to another, Did not our heart burn within us, while he talked with us by the way, and while he opened to us the scriptures? And they rose up the same hour, and returned to Jerusalem, and found the eleven gathered together, and them that were with them, saying, The Lord is risen indeed, and hath appeared to Simon. And they told what things were done in the way, and how he was known of them in breaking of bread."},
 ascension:{type:'Feast',keyVerse:51,
  story:"He led them out as far as to Bethany, and lifted up his hands, and blessed them; and it came to pass, while he blessed them, he was parted from them, and carried up into heaven. And they worshipped him, and returned to Jerusalem with great joy: and were continually in the temple, praising and blessing God."},
};
