// Keyed by Commons file title. `read` = a prose reading of the icon.
// `hot` = [label, explanation, top%, left%] — coordinates measured against the image.
const D=n=>'File:'+n+' Dionysiou.jpg';
module.exports={

'USER:icon-nativity':{
 read:"The icon the reader supplied, and a full Orthodox Nativity with every part of the composition in it. At the top the star sends a single ray straight down. The cave beneath is painted black — the darkness of a world without God — and in the black stands the manger, shaped like a stone chest, with the Child bound in swaddling bands like a corpse and the ox and the ass leaning their heads over him: the icon of the Nativity already contains the icon of the burial. The Theotokos reclines across the middle of the field in her red maphorion, turned away from the Child. Above and to the left the Magi come on foot and again on horseback; at the right an angel in red bends down to a shepherd leaning on his staff. At the bottom left Joseph sits apart with his chin on his hand while a bent old man in a shaggy coat leans over him and talks to him; at the bottom right two women wash the Child in a basin — the oldest detail in the scene, and one no Gospel reports. Around the cave the whole creation brings its gift, as the hymn of the feast says: the angels their singing, the heavens a star, the magi their gifts, the shepherds their wonder, the earth a cave, and mankind a Virgin Mother.",
 hot:[
  ["The single ray from the star","One ray descends from a single point of light and divides in three over the cave: the one God, the Holy Trinity, and the star that the Magi followed. The light comes from outside the created order — it is not painted as a source within the picture.","5%","50%"],
  ["The Theotokos at the centre","She is the largest figure and lies at rest, not in the exhaustion of ordinary birth. In many Greek icons she turns away from the Child toward Joseph — toward the doubting world she is about to answer.","46%","33%"],
  ["The manger like a tomb","The Child is wrapped in swaddling bands that are painted as grave-clothes and laid in a stone manger shaped as a sarcophagus. The ox and the ass stand over him, fulfilling Isaiah: the ox knoweth his owner, and the ass his master’s crib.","50%","61%"],
  ["Joseph and the old man","Joseph sits apart, troubled, while a bent old shepherd speaks to him — the tempter, who whispers that a virgin birth is impossible. This is Matthew’s Joseph, the just man who doubted before the angel came to him in the dream.","78%","16%"],
  ["The washing of the Child","The midwives bathe the newborn: the icon insists on a real human infancy against every teaching that Christ only appeared to take flesh.","83%","62%"]]},

'File:Transfiguration of Christ Icon Sinai 12th century.jpg':{
 read:"Christ stands in a mandorla of uncreated light on Mount Tabor. Moses and Elias — the Law and the Prophets — stand on either side, the dead and the living, both alive to him. Below, the three disciples are on the ground, though this panel does not throw them headlong as many do: Peter turns back up toward Christ with his hand raised, John kneels with his face buried in his sleeve, and James sits and looks aside. St Gregory Palamas taught from this scene that the light of the Transfiguration is the uncreated energy of God himself, and that this same light is the inheritance of the saints.",
 hot:[
  ["The mandorla of uncreated light","Here the almond is pale — the lightest thing on the board, grey-white, with faint lines radiating across it from behind him — where many icons paint it darkening toward the centre. Divine light is not brightness added to Christ; it is the eternal glory that was always his, briefly shown to eyes that could not otherwise bear it.","20%","50%"],
  ["Moses and Elias","At the left the old man with the white beard, in a dark mantle, is Elias, who was taken up alive; at the right the beardless young man in white, holding a squared bound book against his side, is Moses, who died and was buried. Both turn to Christ with open hands. The Law and the Prophets stand with him, and death and life are equally under his feet.","20%","28%"],
  ["The disciples cast down","They are not flung down here. Peter at the left sits on the rock and turns back up toward Christ with his hand raised — he is the one who speaks, Lord, it is good for us to be here. John in the middle kneels with his face buried in his sleeve, and James at the right sits on the ground and looks aside. Only John is doing what Matthew says of all three when the voice came: they fell on their face, and were sore afraid. Above them the upper register is perfectly still — the two orders of the icon are earth and heaven.","74%","48%"]]},

[D('Stavrosis')]:{
 read:"A fresco of 1547 from Dionysiou on Mount Athos, spread across the heads of two arches and inscribed Η ΣΤΑΥΡΩΣΙΣ. It repays going through slowly, because a good deal of what is in it is not in Matthew and the most startling thing in it is Matthew's alone. Christ hangs at the centre with ΙΣ ΧΣ lettered beside the arms of the cross, the head inclined and the body upright and composed: Orthodox painting refuses to dwell on the agony. On his right stand the Theotokos and three other women; on his left St John, lettered Ο ΘΕΟΛΟΓΟΣ, with his hand to his cheek. That group is St John's Gospel and not this one — Matthew keeps the women at a distance, and many women were there beholding afar off. What is Matthew's stands just behind them: a soldier holding up the reed with the sponge, and the centurion in gilt armour with a great round shield, who speaks the sentence the whole chapter has been working toward, Truly this was the Son of God. At the two outer edges the thieves hang on their crosses, and under each of them a soldier in a short tunic swings a wooden club at the bound legs — the breaking of the legs, which is in St John only. Then the foot of the cross, which is the part to look at. The rock is split with black fissures; in a cave under it lies a skull; and out of the broken ground figures are climbing, one naked with his arm raised, others still bound in their grave-bands. No other Evangelist reports that: and the earth did quake, and the rocks rent; And the graves were opened; and many bodies of the saints which slept arose.",
 hot:[
  ["Christ reigning from the Cross","The head bows but the body is upright and composed. Orthodox iconography refuses to dwell on physical agony: what is shown is the voluntary self-offering of the Lord of glory.","16%","45%"],
  ["The Theotokos and the women","She stands at his right hand with three other women, and St John, lettered Ο ΘΕΟΛΟΓΟΣ, faces them from the other side of the cross with his hand at his cheek. The word spoken over them, Woman, behold thy son, is in St John’s Gospel and not in this one: Matthew keeps the women back, and many women were there beholding afar off.","32%","24%"],
  ["The soldiers with clubs","At each outer edge a soldier in a short tunic and laced boots swings a wooden club at the bound legs of a thief. That is the breaking of the legs, which St John reports and no other Evangelist does — the fresco paints the whole Passion as the Church reads it, not only this chapter.","48%","8%"],
  ["The centurion and the sponge","Behind St John stand a soldier holding up the reed with the sponge on it and the centurion, haloed, in gilt armour with a great round shield. Matthew gives him the last word of the crucifixion: Truly this was the Son of God.","32%","74%"],
  ["The rent rock and the risen dead","Under the cross the rock is split with black fissures and a skull lies in a cave beneath it; out of the broken ground figures are climbing, one naked with his arm up, others still in their grave-bands. This is Matthew and nobody else — and the earth did quake, and the rocks rent; And the graves were opened; and many bodies of the saints which slept arose.","86%","52%"],
  ["The two thieves","On either side hang the two crucified with him. Matthew records that both reviled him; the Church remembers that one repented, and made of the cross itself a door into paradise.","14%","88%"]]},

[D('Deipnos Mystikos')]:{
 read:"The Mystical Supper is painted around a curved table so that no one has his back to the viewer — the Church is meant to see herself seated there. Christ presides; the beloved disciple leans toward his breast; and one hand reaches to the dish, the sign Christ gave of the betrayer. Matthew’s account is the one the Church reads on Holy Thursday: Take, eat; this is my body.",
 hot:[
  ["Christ presiding","He sits at the middle of the far side of the table, haloed, with ΙΣ ΧΣ either side of his head and Ο ΔΕΙΠΝΟΣ Ο ΜΥΣΤΙΚΟΣ, the Mystical Supper, lettered above. His right hand is raised in blessing before his own breast. The Supper is painted not as a farewell meal but as the first Liturgy.","20%","46%"],
  ["The beloved disciple","John leans toward the Lord’s breast — the posture the Fathers read as the model of prayer: the disciple who listens at the heart of Christ.","33%","54%"],
  ["The common dish","He that dippeth his hand with me in the dish, the same shall betray me. A footed bowl stands in the middle of the table with a fish lying in it. On the far side, below the beloved disciple, a man in green with a red cloak lies forward over the cloth and stretches his arm along it toward the bowl, his hand open and short of it. That reach is how the icon marks Judas, not any mark of monstrosity, and the fresco letters no name.","57%","45%"]]},

'File:Ide Topos pou Ekato Dionysiou.jpg':{
 read:"A fresco of 1547 from Dionysiou on Mount Athos. The inscription across the top is the angel's own sentence — ΙΔΕ Ο ΤΟΠΟΣ ΟΠΟΥ ΕΚΕΙΤΟ, behold the place where he lay — and a smaller one beside the sepulchre reads Ο ΑΓΙΟΣ ΤΑΦΟΣ, the holy tomb. There are two angels in it, not one: a great winged figure seated on the fallen stone in the middle, in blue with red wings, his hand out toward the women, and a second standing beyond the tomb at the right in rose and white. The stone itself is a red slab tilted out of its bed. The sepulchre stands open at the right with the grave-clothes still lying in it in white bands. Two myrrhbearing women come in from the left, one in dark red and one in green carrying her vessel. Along the bottom right lies the watch — half a dozen soldiers in mail, sprawling and reeling, one flat on his back with his arm flung out, others crouched under their raised shields. They are not asleep. Matthew is the only Evangelist who puts a guard at this tomb at all, and he says in five words what became of them: the keepers did shake, and became as dead men. Orthodox iconography never paints the Resurrection itself, because nobody saw it; it paints the evidence, and here the evidence includes the men posted to prevent it.",
 hot:[
  ["The myrrhbearing women","Mary Magdalene and the other Mary come with their spices. Matthew makes them the first witnesses and the first preachers of the Resurrection — sent by the angel to tell the apostles.","40%","10%"],
  ["The two angels","There are two of them. The great one sits on the fallen stone in the middle with his hand out to the women — his countenance was like lightning, and his raiment white as snow, and the seal of death is now a seat — and a second stands beyond the tomb at the right in rose and white. Matthew names one; the painter has given the scene the pair that St Luke and St John report.","26%","40%"],
  ["The empty grave-clothes","The tomb is shown open and orderly, the linen still lying in place. The body was not taken; it passed through.","50%","72%"],
  ["The guard struck down","Half a dozen soldiers in mail sprawl and reel along the foot of the fresco, one flat on his back with his arm flung out, others crouched under their raised shields. They are not asleep, and Matthew is the only Evangelist who has them there at all: the keepers did shake, and became as dead men. The precaution taken against the Resurrection became its unwilling witness.","82%","52%"]]},

[D('Baiophoros')]:{
 read:"A fresco of 1547 from Dionysiou on Mount Athos, and the first thing to see is that it is painted around a door. A real arched doorway of the church opens in the middle of the wall, and the painter has set Christ on one side of it and the city on the other, so that whoever walks through passes between them. The inscription above reads Η ΒΑΪΟΦΟΡΟΣ, the Palm-bearing, which is the Greek name of the feast. Christ rides side-saddle on a white colt at the left, blessing, with the apostles crowded behind him and the bare rock of the mount above; Jerusalem stands at the right, white walls and domes, with its people coming out of the gate to meet him. Between the two, growing out of the rock beside the doorway, is the palm — and there are three children up in it: one in yellow astride a branch with a knife in his hand, one in red stretched out along a frond, one in pink shinning up the trunk, and a fourth standing at its foot. Below, under the colt's hooves, two more children are spreading a dark patterned garment on the ground, and a red-striped cloth is down already. Both halves of Matthew's verse are here and they are given to children: a very great multitude spread their garments in the way; others cut down branches from the trees, and strawed them in the way. He rides not a war-horse but a borrowed foal, which is the prophecy he is quoted as fulfilling: Behold, thy King cometh unto thee, meek, and sitting upon an ass.",
 hot:[
  ["Christ on the colt","He sits sideways, turned back toward the disciples rather than toward the acclaim ahead — the icon shows a King indifferent to his own triumph.","42%","15%"],
  ["The children in the palm tree","Three of them are up in it: one in yellow astride a branch with a knife, one in red stretched along a frond, one in pink climbing the trunk, with a fourth at its foot. They are cutting the branches — others cut down branches from the trees, and strawed them in the way — and in a few days the crowd below will be shouting something else.","13%","40%"],
  ["The people of the city","Jerusalem pours out through its gate. Matthew says all the city was moved, saying, Who is this?","32%","84%"],
  ["The garments spread in the way","Two children are laying a dark patterned cloth on the ground under the colt's hooves, and a red-striped one is down already: a very great multitude spread their garments in the way. The painter gives the work to children — the ones whose praise Christ defends in the temple the next day.","87%","33%"],
  ["The doorway the fresco is painted around","The black arch in the middle of the wall is a real door of the church. The painter has set Christ on one side of it and Jerusalem on the other, so that whoever walks through passes between them and into the city.","55%","54%"]]},

'File:Baptism of Christ, Early XIV Century, St Mary Perivleptos Church, Ohrid Icon Gallery.jpg':{
 read:"The Theophany — the manifestation of the Holy Trinity at the Jordan. Christ stands naked in the water as one condemned, the Forerunner laying his hand on his head, angels waiting on the far bank with cloths in veiled hands. The Father’s voice comes from above and the Spirit descends: this is my beloved Son, in whom I am well pleased.",
 hot:[
  ["Christ in the Jordan","He stands in the water as in a grave; the river is painted rising round him like a dark tomb. He is baptised not to be cleansed but to cleanse the waters, and through them the world.","55%","44%"],
  ["St John the Forerunner","He stretches out his hand with fear, having said, I have need to be baptized of thee. The axe is in this panel: it lies at the root of the small dark tree just below him, blade and handle together — now also the axe is laid unto the root of the trees, which is his own preaching of repentance.","40%","23%"],
  ["The angels with veiled hands","Four of them stand on the bank, two behind two, bowing toward the river with white cloths carried over their hands — hands covered, as servants approach a king. Even the bodiless powers do not touch the mystery bare-handed.","40%","70%"],
  ["The ray from heaven","A dark scalloped segment of heaven opens at the top of the panel and a single narrow ray comes down from it toward Christ’s head, ending in a small pale dove. The Father speaks and the Spirit comes: the Trinity is manifest, which is why the feast is called Theophany and not merely the Baptism.","16%","44%"]]},

[D('Epitaphios Threnos')]:{
 read:"The Lamentation at the Tomb — the Epitaphios Threnos of Holy Friday. Matthew tells it briefly: Joseph of Arimathaea begged the body, wrapped it in clean linen, and laid it in his own new tomb. The icon fills the silence with the mourning of the Church: the Theotokos holds her Son’s head against her face, the myrrhbearers raise their hands, and the empty cross stands behind against a night sky.",
 hot:[
  ["The empty Cross","The instrument stands bare in the middle distance, its title-board still at the head, against a sky full of stars and the white walls of the city. Nothing leans against it now: the ladder has been taken down, and a man at the right carries it on his shoulder. The work is finished; what remains is burial.","20%","48%"],
  ["The Theotokos","She holds his head in her arms and presses her cheek to his, with ΜΡ ΘΥ lettered beside her halo — the same embrace many icons give the Mother and Child, now at the other end of the life. What began in the manger ends on the stone.","64%","27%"],
  ["The stone of unction","The body is not yet wrapped. It lies bare but for a white loincloth, on a white linen sheet spread over a red slab, with the wounds marked in the feet: the painter shows the clean linen cloth of Matthew’s verse before it is wound. The same stone is venerated in Jerusalem, and every Orthodox altar keeps its memory in the antimension.","72%","58%"],
  ["Joseph and Nicodemus","Two men at the right. The old one, haloed and grey-bearded, bends over the feet with the edge of the linen in his hands; behind him a dark-bearded man without a halo stands with the ladder over his shoulder and his cheek in his hand. The tradition names them Joseph of Arimathaea and Nicodemus, and the fresco letters neither. Nicodemus is St John’s: Matthew names only Joseph, a rich man of Arimathaea, who also himself was Jesus’ disciple, and says that he went to Pilate, and begged the body of Jesus.","50%","88%"]]},

'File:Separation of Sheep and Goats MET cdi24-144-4s1.jpg':{
 read:"This is a copy, made in the early twentieth century and now in the Metropolitan Museum of Art, of one of the oldest images of the Last Judgment in Christian art — the early sixth-century mosaic at Sant’Apollinare Nuovo in Ravenna. Christ, beardless in the early manner, sits between two angels and divides them: two white sheep on his right hand, one grey goat on his left. Matthew 25 is the only place in the Gospels where the criterion of judgment is stated outright, and it is not doctrine but mercy: I was an hungred, and ye gave me meat.",
 hot:[
  ["Christ the Judge","He is seated, not standing, and makes no gesture of wrath — only of division. In Orthodox theology the judgment is the same love met differently by those who have and have not learned to receive it.","30%","50%"],
  ["The angel in red","A winged angel in red stands behind the sheep at Christ’s right hand, his own right hand raised palm outward before his breast.","24%","30%"],
  ["The angel in blue","A second winged angel, in blue, stands behind the goat at Christ’s left and makes the same gesture. The two are painted alike in everything but their colour, and they frame the whole scene as the two possibilities of one human life.","24%","70%"],
  ["The sheep on the right","Two white sheep stand at his right hand, facing him, and his open hand is held out over the head of the upper one. Come, ye blessed of my Father, inherit the kingdom prepared for you from the foundation of the world.","62%","14%"],
  ["The goats on the left","At his left stands one goat, grey and dark along the back, where the sheep are white. They too ask, Lord, when saw we thee an hungred? Neither side recognised him — the difference was in what they did, not in what they knew.","65%","85%"]]},

'File:RossGospWiseFoolVirginsF4.jpg':{
 read:"A leaf from the Rossano Gospels, a sixth-century Greek codex written in silver and gold on purple-dyed parchment — one of the oldest illustrated Gospel books in the world. It has darkened so far that the purple is nearly black across the top, so read only what survives. On the right, five women in white with veiled heads stand beside Christ, and each holds an upright torch ending in a red flame; a dark band of foliage runs over their heads, studded with round white points. On the left stand five more in coloured robes — blue, red, ochre, and one wholly in black with her hands raised — and they are carrying torches too, but the painter has put no flame on any of them. That contrast is the whole of what this leaf shows, and it is worth being exact: nothing here paints lamps going out, or the oil, or the sellers, or the cry at midnight. Between the two groups stands a tall panelled door, shut, and the shut door is what Matthew's ending needs: Afterward came also the other virgins, saying, Lord, Lord, open to us. But he answered and said, Verily I say unto you, I know you not.",
 hot:[
  ["The wise with burning lamps","Five women in white with veiled heads, each holding an upright torch that ends in a red flame. They took oil in their vessels with their lamps. The Fathers read the oil as mercy and the lamps as the virginity or the faith that mercy alone keeps burning.","40%","80%"],
  ["Christ at the door","The Bridegroom receives them. In the Orthodox Holy Week this parable is sung at the Bridegroom services: Behold, the Bridegroom cometh at midnight.","38%","57%"],
  ["The shut door","And the door was shut. The refusal is not arbitrary: the foolish went away to buy at the very moment when only what they already had could serve.","50%","47%"],
  ["The foolish in the dark","Five more on the far side of the door in coloured robes — blue, red, ochre, and one wholly in black with her hands raised. They carry torches too, and the painter has put a flame on none of them. Watch therefore, for ye know neither the day nor the hour.","45%","14%"]]},

'File:Victor (iconographer) Tree of Jesse.png':{
 read:"The Tree of Jesse — the icon the Church paints for Christ’s genealogy. Jesse, the father of David, lies at the root; from his side a vine rises bearing the kings and prophets of Israel on its branches, each with a scroll of his own prophecy; and at the heart of it, at the centre of the icon, sits the Theotokos with the Child. Matthew’s forty-two generations are here made visible as one living plant, and Isaiah’s word is fulfilled: there shall come forth a rod out of the stem of Jesse.",
 hot:[
  ["The Theotokos and the Child","The whole tree grows toward this. She is the flower of the root of Jesse, and the Child in her lap is the fruit for which every branch below was grown.","45%","44%"],
  ["Jesse at the root","He lies along the foot of the icon with his head propped on his hand, the pose in which Jesse is painted sleeping, unaware of what will grow out of him — as the generations of the genealogy were unaware. His face is too small in this photograph to show whether the eyes are shut. The painter has signed the dark ground beside him: ΧΕΙΡ ΒΙΚΤΩΡΟΣ · ΑΧΟΔ ·, the hand of Victor, and ΑΧΟΔ in Greek numerals is 1674.","93%","40%"],
  ["The kings crowned above","David and the kings of Judah are painted crowned in the upper branches. Matthew’s first fourteen generations run from Abraham to David, the second from David to the Exile.","8%","46%"],
  ["The prophets with scrolls","Each figure holds an open scroll with a single word lettered on it, and the word is a name out of Matthew's list — ΑΒΡΑΑΜ at the root, ΡΟΒΟΑΜ and ΑΒΙΑ among the branches. They are not prophecies: the painter has given every man in the genealogy his own name to hold, so that the list Matthew writes out is painted as a company of people, each holding his place in it.","62%","80%"]]},

'File:IkonaZapovediBlazhenGIM.jpg':{
 read:"A Russian icon of the Commandments of the Beatitudes: each of the nine blessings of Matthew 5 is given its own scene, so that the reader sees what poverty of spirit, mourning, meekness, hunger for righteousness, mercy, purity of heart, peacemaking and persecution actually look like when lived. The Beatitudes are not painted as sentences but as ways of life, which is exactly how the Fathers read them."},

"File:Representation of the Sower's parable.JPEG":{
 read:"A modern Orthodox mosaic of the Sower — Pilda Semănătorului. The four grounds of Matthew 13 are laid out around the sowing Christ: the beaten path where the birds come, the stony place, the thorns, and the good earth. Christ is himself the Sower, and the seed is the word of the kingdom.",
 hot:[
  ["The Sower","He that soweth the good seed is the Son of man. He is painted haloed, as Christ himself, sowing broadcast without measuring the ground — the word is given to every soil alike. The title lettered above him is Romanian, 21. PILDA SEMĂNĂTORULUI, the parable of the sower, the twenty-first of a numbered set.","35%","55%"],
  ["The birds on the wayside","Then cometh the wicked one, and catcheth away that which was sown in his heart. The path is beaten hard by traffic: a heart worn smooth by everything that passes over it.","52%","20%"],
  ["The stony ground","He heareth the word, and anon with joy receiveth it; yet hath he not root in himself, but dureth for a while. The stones are not under anything: flat pale slabs lie bare on the ground at the lower right with the seed scattered over them, nothing for it to root in.","85%","72%"],
  ["The thorns and the good ground","The care of this world, and the deceitfulness of riches, choke the word: the painter gives them as a thicket of thistles with red heads, growing where the seed falls. The panel stops at its border behind them — the hundredfold is in the parable and is not painted here.","58%","78%"]]},

[D('Christos Didaskon')]:{
 read:"Christ the Teacher, enthroned and expounding — the image the Church sets over the discourses. Orthodox iconography does not usually illustrate the parables as scenes; it paints instead the One who speaks them, seated in the teacher’s place with the elders listening. What matters in a parable is not the anecdote but the mouth it comes from.",
 hot:[
  ["Christ enthroned as Teacher","He sits, as a teacher sat in the synagogue, and his right hand is raised in the gesture of speech that is also the gesture of blessing: in him the two are the same act.","28%","30%"],
  ["The listeners","The elders and scribes are painted attentive and seated at a lower level. They hear the same words as the disciples; hearing is not yet understanding.","46%","62%"],
  ["The inscription","The Greek titulus above names the scene — Christ teaching. Every Orthodox icon carries its name written on it: the image is never left to the viewer’s guess.","5%","36%"]]},

[D('Christos Apostolois')]:{
 read:"Christ standing among the apostles, both hands outstretched toward the two ranks of them. It is the image the Church uses for the moments when the Lord turns aside from the crowds to instruct, warn or send out the Twelve — including his last word on the mountain in Galilee: Go ye therefore, and teach all nations.",
 hot:[
  ["Christ sending","He stands frontally on a red cushion over a stepped footstool with both arms open, ΙΣ ΧΣ lettered either side of his halo. Across the top of the fresco runs a line of Greek in which ΕΜΦΑΝΙCΑС — having appeared — and ΤΟΙС ΥΠ ΑΥΤ(ΟΥ) ΓΕΝΟΜΕΝΟΙС — to those who were made by him — can be read: it is a title about an appearing, not the words of Matthew 28. The whole composition moves outward from him toward the edges of the panel — the icon of a mission, not of a conversation.","30%","50%"],
  ["The apostles on his right","Four of them stand close at his right with the haloes overlapping, and they are not painted alike: a grey-bearded man holds a red book, an older one behind him holds a white scroll, and every face is drawn differently. They stand as a body, all of them turned in toward him.","28%","15%"],
  ["The apostles on his left","Lo, I am with you alway, even unto the end of the world. Five or six of them press in at his left — one with his hand raised and a red book under it, a white-bearded one in red, a beardless youth at the edge — and not one of them is turned away: the whole company faces the figure in the middle.","30%","82%"]]},

'File:Synaxis of the Twelve Apostles by Constantinople master (early 14th c., Pushkin museum).jpg':{
 read:"The Synaxis of the Twelve Apostles — a Constantinopolitan panel of the early fourteenth century. The Twelve stand together as one assembly, and the Church keeps their common feast on the 30th of June, the day after Peter and Paul. Matthew 10 is where they are first named and first sent.",
 hot:[
  ["The inscription","The Greek across the top reads Η СΥΝΑΞΙС ΤΩΝ ΔΩΔΕΚΑ ΑΠΟСΤΟΛΩΝ, the Synaxis of the Twelve Apostles, and the names follow in Matthew's own order — ΠΕΤΡΟС, ΑΝΔΡΕΟС, ΙΑΚΩΒΟС, ΙΩ, ΦΙΛΙΠΠΟС, ΒΑΡΘΟ, ΘΩΜΑС, ΜΑΤΘ, ΙΑΚΩΒΟС, ΘΑΔΔΑΙΟС, ΙΜΩΝ — as far as the rubbed gold lets them be read.","13%","40%"],
  ["The four set forward","Four of them stand a step in front of the rest and are painted larger: a beardless young one at the left, one holding a scroll, and two with red books. No ΠΑΥΛΟΣ can be read in what survives of the name-band — St Paul is often given a place in a Synaxis although he was not of the Twelve, and this icon appears to keep to Matthew's list.","50%","25%"],
  ["The rank behind","Eight more stand shoulder to shoulder behind them, and the front rank hides everything below their chins: not one of their hands, and nothing they may be carrying, is visible in the panel. Four in front and eight behind is the Twelve. Freely ye have received, freely give.","28%","52%"]]},
};
