// Prose readings for the remaining icons.
module.exports={
'File:Second Coming by G.Klontzas (16th c.).jpg':
 "A Cretan icon of the Second Coming \u2014 the Deutera Parousia \u2014 painted by Georgios Klontzas at the end of the sixteenth century. Christ sits in judgment in the mandorla at the top, the Theotokos and the Forerunner turned toward him in entreaty. Below them stands the Hetoimasia, the throne prepared and empty, bearing the cross; the twelve apostles are enthroned to either side. From beneath the throne the river of fire runs the whole height of the icon and widens at the foot of it into a broad orange lake — not a hell-mouth. In it naked figures stand to the waist in iron collars and chains while black winged devils drive them with hooks and spears, and green scaly beasts, horned and crocodile-snouted, swim among them; at the right the lake is closed off by the huge ribbed flank of a beast. On the left the ranks of the saved stand in order \u2014 patriarchs, bishops, monks, martyrs; along the bottom the earth and the sea give up their dead. This is the icon the Church sets against the whole of the discourse on the Mount of Olives: the sign of the Son of Man appearing in heaven, and all the tribes of the earth seeing him come with power and great glory.",
'File:Christ banish tradesmen from Temple (Monreale).jpg':
 "A twelfth-century mosaic from Monreale in Sicily, worked by Byzantine craftsmen. Christ, the scourge of cords raised in his right hand, overturns the money-changers' table \u2014 the coins are still scattered across it \u2014 while the sellers draw back with their oxen and sheep and a cage of doves hanging above them. The Latin inscription names exactly what he cast out: those selling doves and oxen, and the tables. What Matthew records next is the point of the cleansing: with the traders gone, the blind and the lame came to him in the temple and he healed them, and the children cried Hosanna to the Son of David.",
'File:Cathedral (Monreale) - North arch of transept - Adoration by the Magi.jpg':
 "A twelfth-century mosaic from Monreale in Sicily, worked by Byzantine craftsmen for a Norman king — Eastern iconography in a Western church. The Magi approach the Theotokos enthroned with the Child, offering gold, frankincense and myrrh. The Fathers read the three gifts as a confession: gold to a king, incense to God, myrrh to one who will die and be buried.",
'File:Menologion of Basil II - Flight into Egypt.jpg':
 "A miniature from the Menologion of Basil II, made in Constantinople about the year 1000 — one of the great illuminated books of Byzantium. Joseph goes ahead and the Theotokos carries the Child on the ass out of the land of Israel. Matthew says they went by night; the miniature is painted on gold, as Byzantine books paint everything. The icon is quiet and small: the Lord of all is a refugee on a borrowed animal.",
'File:Massacre of the Innocents (Ionian, 17th c., Byzantine museum).jpg':
 "A seventeenth-century icon of the Ionian school. The Church commemorates the fourteen thousand Holy Innocents on the 29th of December, four days after the Nativity, and counts them the first martyrs — children who bore witness by dying for Christ before they could speak. Rachel weeping for her children stands in the icon for every mother of them.",
'File:Christos Prodomo Dionysiou.jpg':
 "Christ enthroned with St John the Forerunner standing beside him — half of the Deesis, the Forerunner's side of it, without the Theotokos who would face him on the other. He is painted gaunt and wild-haired, holding a scroll with his own preaching. He is the last of the prophets and the first to point: Behold the Lamb of God.",
"File:Christ's temptation (Monreale).jpg":
 "The Temptation in the wilderness, from Monreale. The Latin inscription carries the devil’s words: If thou be the Son of God, command that these stones be made bread. The tempter is painted as a dark winged figure — a fallen angel, not a beast: the temptations of Christ are addressed to the mind, and are answered each time out of Deuteronomy.",
'File:Iomenos Asthenoun tas apo Poikilon noson.jpg':
 "Christ healing those sick of divers diseases — an Athonite fresco from the katholikon of Dionysiou on Mount Athos, painted in 1547 by a master of the Cretan school. Christ stands at the left with his disciples behind him and the sick are brought to him along the wall, some standing, some sitting on the ground. Matthew closes chapter 4 with exactly this summary of the whole Galilean ministry.",
'File:105 Christ Enthroned Icon from Saint Paraskevi Church in Langadas.jpg':
 "Christ enthroned, from the icon collection of St Paraskevi in Langadas, northern Greece. He holds the open book — the Gospel is not an object he carries but the word he is — and blesses with the other hand. Where the Church has no narrative icon of a teaching, this is the icon she sets over it.",
'File:Christ cleans leper man.jpg':
 "The cleansing of the leper, from the Monreale mosaics. The Latin above carries the leper’s own words: Thou canst make me clean. Matthew says Jesus put forth his hand, and touched him — contact with a leper made a man unclean, and here the current runs the other way. The mosaicist has stopped just short of it: Christ's open hand and the leper's spotted one reach toward one another across a hand's breadth of bare gold, and the touch is the next instant.",
'File:Iomenos Gon Ekatonarchou Dionysiou.jpg':
 "Christ and the centurion, from Dionysiou on Mount Athos. The soldier kneels or stands at a distance, and the servant lies on a bed behind him. His words are said at every Orthodox Liturgy before communion, in the priest’s prayer: I am not worthy that thou shouldest enter under my roof.",
"File:Monreale - Jesus heals Simon's mother in law.jpg":
 "Peter’s mother-in-law, healed of a fever, from Monreale. Christ takes her hand and raises her; the Latin names the fever. The detail the icon preserves is what she did next: she arose, and ministered unto them. Healing in the Gospels is never an end in itself.",
'File:Hrist utišava buru na moru, manastir Gračanica.jpg':
 "Christ stilling the storm, a fresco from the monastery of Gračanica in Kosovo, built by King Milutin in 1321. Christ is painted twice in the one boat — asleep in the stern at the right, and standing at the left rebuking the sea — with the disciples between the two of him and the waves drawn as hard scrolling ridges. Byzantine painting shows water as pattern rather than motion — what is dangerous is not the wave but the fear.",
'File:Christos Iomenos Daimonon Takophon Dionysiou.jpg':
 "The healing of the dumb man possessed with a devil — Athos, Dionysiou, 1547. The Greek titulus painted across the top names the scene exactly: τὸν δαιμονῶντα κωφόν, the dumb demoniac. He was brought to Christ by others, because he could not ask anything for himself; and when the devil was cast out, the dumb spake. It is the last of the ten miracles Matthew gathers into chapters 8 and 9, and the one after which the Pharisees said that he cast out devils by the prince of the devils.",
'File:Christos Iomenos Paralyton Dionysiou.jpg':
 "The healing of the paralytic, from Dionysiou. The man is shown twice in the same frame — lying before Christ and walking away with his bed on his shoulder. Byzantine icons often paint two moments together, because the icon is not a photograph of an instant but the whole event held still.",
'File:090 Mathew the Apostle Icon from Saint Paraskevi Church in Langadas.jpg':
 "St Matthew the Apostle and Evangelist — the publican whose calling this passage records, and the writer of this Gospel. He is painted with the book he wrote. The Church keeps his feast on the 16th of November, and reads at it the very verses in which Christ said to him, Follow me.",
'File:Daughter of the head of synagogue is resurrected by Christ.jpg':
 "The raising of Jairus’s daughter, from Monreale. Christ takes the girl by the hand on her bed while the mourners stand by — the minstrels and the noisy crowd Matthew mentions, put outside before the miracle. The maid is not awakened but raised: the Greek word is the one used of the Resurrection.",
'File:Christos Iomenos Typhlon.jpg':
 "Christ healing a blind man — Athos, Dionysiou, 1547. The Greek titulus is singular, τὸν τυφλόν, and the man is painted twice: once before Christ, and once bending over a cross-shaped basin of water at the right. That basin is the pool of Siloam, so the fresco is the healing of the man born blind of John 9, which the Orthodox lectionary reads on the Sunday of the Blind Man — not the two blind men of Matthew 9:27–31, whose cry, Thou Son of David, have mercy on us, this passage records. It is set here because the Athonite cycle paints the blind man of the lectionary and not Matthew's pair.",
'File:Iomenos Daimonizomenon Dionysiou.jpg':
 "A fresco of 1547 from the katholikon of Dionysiou on Mount Athos, lettered in white across the black sky: Ο Χ(ΡΙΣΤΟ)Σ ΙΩΜΕΝΟΣ ΤΑΝ ΔΑΙΜΟΝΙΖΟΜΕΝΟΝ — Christ healing the demoniac. The possessed man stands at the left on the rocks, stripped to a blue cloth at the hips, his arms flung up and his mouth open. Above his head is the devil, and it is not left vague: a small black imp with spread wings and thin crooked limbs, with a black streak running down out of it into the man’s open mouth. Christ stands opposite with two apostles behind him, one in blue and one in ochre, and never comes near the man — he points at the imp at arm’s length, and that is the whole of the miracle as this painter tells it. Orthodox iconography gives evil no grandeur: it is small, black and outmatched. Matthew says the man was blind, and dumb, and that afterwards both spake and saw; the fresco paints the mouth and leaves the eyes alone. What the rest of these verses are about is not the healing but the quarrel over it — This fellow doth not cast out devils, but by Beelzebub the prince of the devils — and the answer to it, But if I cast out devils by the Spirit of God, then the kingdom of God is come unto you.",
'File:Elkomenos Prodromos Phylaken Dionysiou.jpg':
 "A fresco of 1547 from the Forerunner cycle at Dionysiou on Mount Athos. The inscription names it exactly: ΕΛΚΟΜΕΝΟΣ Ο ΠΡΟΔΡΟΜΟΣ ΕΙΣ ΤΗΝ ΦΥΛΑΚΗΝ — the Forerunner dragged into the prison. A soldier in a plumed helmet and scale corselet has him by both wrists and strides off to the right; the Forerunner leans back against the pull, barefoot, his feet skidding on the pavement. At the far right stands the prison, a white stone tower, and in its barred window is the Forerunner again — the same gaunt face under the same gold halo, looking out through the grille. The painter has put the seizing and the shutting up in one frame. At the left, cut off by the edge of the fresco, a crowned king sits on a carved throne with a spearman standing at his door. Matthew tells none of this here. He gives the whole of it in a subordinate clause — Now when Jesus had heard that John was cast into prison, he departed into Galilee — and keeps the reason back until the fourteenth chapter. This is the icon of the event that clause points at, which is why the card says it is not a depiction of these verses; what Matthew makes of the moment is the sentence immediately after it, From that time Jesus began to preach, and to say, Repent: for the kingdom of heaven is at hand.",
'File:Christos Pantokrator Dionysiou.jpg':
 "Christ Pantocrator in the dome of the katholikon at Dionysiou. He blesses with the right hand and holds the Gospel in the left, looking down on the whole church from the height. This is the face the Church raises over the words Come unto me, all ye that labour and are heavy laden, and I will give you rest.",
'File:Iomenos xeran echon cheira Dionysiou.jpg':
 "The healing of the man with the withered hand, in the synagogue on the sabbath — Dionysiou, Athos. The Pharisees sit on either side watching. Christ heals in front of them and asks the question the icon leaves hanging: is it lawful to do well on the sabbath days?",
'File:Iomenos Daimonizomenous Dionysiou.jpg':
 "The two demoniacs of the Gadarenes — Athos, Dionysiou, 1547. The Greek titulus is plural, τοὺς δαιμονιζομένους, and the fresco paints both the men Matthew describes: coming out of the tombs, exceeding fierce, so that no man might pass by that way. Mark and Luke tell the same miracle of one man only; St Augustine supposes that the one they name was the better known of the two, and that the whole country grieved for him.",
'File:Prophetes Ionas Ketos Dionysiou.jpg':
 "The prophet Jonah and the great fish, Dionysiou, Athos. Christ himself gave this as the only sign that would be given: as Jonas was three days and three nights in the whale’s belly, so shall the Son of man be three days and three nights in the heart of the earth. The Church reads the book of Jonah entire at the Paschal Vigil.",
'File:Theotokos Panachranta Dionysiou.jpg':
 "The Theotokos Panachranta — the All-Immaculate — from Dionysiou on Mount Athos. She is enthroned with the Child. The Church sets her image over the words Whosoever shall do the will of my Father which is in heaven, the same is my brother, and sister, and mother: she is the first and the pattern of that obedience.",
'File:Apotome Agiou Ioannou Prodromou Dionysiou.jpg':
 "A fresco of 1547 from Dionysiou on Mount Athos, inscribed Η ΑΠΟΤΜΗΣΙΣ ΤΟΥ ΠΡΟΔΡΟΜΟΥ. It holds two moments at once, and it is worth being exact about which. The executioner still has his sword up over his head at the upper left — and the Forerunner is already beheaded: his body kneels forward in the middle of the fresco, headless, with its bound hands stretched down to the pavement and the blood running from the neck. The head itself lies on the stone step above the body, inside a great disc of gold. That disc is his halo, not a dish, and it is what makes this fresco easy to misread. The charger is elsewhere and it is empty — a shallow red-brown platter held out in both hands by the crowned girl who kneels at the right in a red gown sewn with gold, waiting for what has not yet been put into it. Behind them is the prison, a white building with a barred window and a door. Matthew’s account is almost as cold: he sent, and beheaded John in the prison, and his head was brought in a charger, and given to the damsel: and she brought it to her mother. The Church keeps the feast on the 29th of August as a strict fast, one of the few days of mourning in the calendar that is not for Christ himself.",
'File:Evlogesis Pente Arton Dionysiou.jpg':
 "A fresco of 1547 from the katholikon of Dionysiou on Athos, inscribed along the top Η ΕΥΛΟΓΗΣΙΣ ΤΩΝ ΠΕΝΤΕ ΑΡΤΩΝ — the blessing of the five loaves. Christ stands alone at the left with ΙΣ ΧΣ lettered beside his halo, and he is not making the blessing gesture the title leads you to expect. He holds the loaves gathered up in both hands with the two fishes laid across the top of them, and his face is turned up into the dark sky. That is the rarer half of Matthew’s sentence and this painter has chosen it: took the five loaves, and the two fishes, and looking up to heaven, he blessed, and brake, and gave the loaves to his disciples. Across the middle of the fresco the disciples do the giving — one bent under a load, one handing bread down to a seated rank, a third in green at the far edge — and the multitude sits in two crowded groups on the grass, with a small child among them reaching up. At the bottom left stand the baskets of fragments, woven cylinders heaped with broken bread. The painter has stacked them into a clump rather than laid out twelve; about half a dozen mouths can be counted.",
'File:Monreale - Peter Saved from the Waves.jpg':
 "Christ catching Peter as he begins to sink, from Monreale. The mosaic keeps the exact moment Matthew records — Jesus stretched forth his hand, and caught him. Peter is painted already half in the water: the icon is honest about how far he had got before the hand came.",
'File:Christos Iomenos Thygatera Xananaias Dionysiou.jpg':
 "A fresco of 1547 from Dionysiou on Athos, inscribed across the top Ο Χ(ΡΙΣΤΟ)Σ ΙΩΜΕΝΟΣ ΤΗΝ ΘΥΓΑΤΕΡΑ ΤΗΣ ΧΑΝΑΝΑΙΑΣ — Christ healing the daughter of the Canaanite woman. The woman does not kneel, and the posture is the point of the picture: she stands squarely in the middle of the fresco in a pale robe and head-cloth with both hands open and lifted toward Christ. She is arguing, not prostrate. Matthew gives her three refusals to get past — his silence, the disciples’ Send her away, and I am not sent but unto the lost sheep of the house of Israel — and then the sentence that is hers alone, Truth, Lord: yet the dogs eat of the crumbs which fall from their masters’ table, which drew from Christ a word he said to no one else: O woman, great is thy faith. He stands at the left with three apostles crowded at his shoulder and reaches his hand out to her. At the right, on a great red couch under a tiled roof, the daughter is painted too — half-raised on the bedding, a band round her head, a blue cloth over her lap. The Evangelist has the healing happen out of sight and at a distance; the painter has brought the house into the same frame so that the answer and its effect stand side by side, and her daughter was made whole from that very hour.",
'File:Monreale - Multiplication of the Loaves and Fishes.jpg':
 "A mosaic of the 1180s from the nave of Monreale in Sicily, worked by Greek craftsmen for a Norman king — and the one icon in this reader whose own inscription counts a different miracle from the one it stands under. The Latin is lettered in red across the gold: IHS DE QVINQVE PANIBVS ET DVOBVS PISCIBVS QVINQVE MILIA HOMINVM SATIAVIT ET DE FRAGMENTIS DVODECIM COPHINI IMPLETI SVNT — Jesus fed five thousand men from five loaves and two fishes, and of the fragments twelve baskets were filled. Every number there belongs to the first feeding, in the chapter before this one. These verses give seven loaves, a few little fishes, four thousand men, and seven baskets. What the mosaic actually shows is common to both accounts and is worth looking at for itself: at the lower left Christ stands among his disciples and does not bless the bread — he puts it into a white cloth that a disciple holds stretched between both hands — and along the middle of the field the disciples carry it out, while the multitude sits in ranks on a green hillside at the right, faces banked one above another to the top of the panel. A row of woven baskets runs along the bottom edge with a man bending over them to fill them.",
'File:The Good Shepherd from the Imperial Palace of Constantinople 5th-6th century AD.jpg':
 "A panel from the pavement of the imperial palace at Constantinople, fifth or sixth century. It is a floor, not an icon, and that governs everything about it: the ground is plain white tesserae and the figure sits in it as a vignette, at the scale and in the manner of the country subjects such pavements were filled with. A man in a short belted tunic and boots stands with a beast carried across his shoulders and a woven basket at his side holding two round pale things. That is the kriophoros, the ram-bearer — a figure Greek and Roman art had been making for centuries before there were Christians to borrow it, and the shape the early Church took over when it wanted the shepherd of the parable. He is not Christ and nothing in the pavement says he is: no halo, no cross, no inscription. The tesserae are coarse and worn enough that the animal on his shoulders is a shape rather than a legible sheep. Nor is Matthew's parable here — no lost sheep, no mountains, no ninety and nine, and no rejoicing. What the panel gives is the oldest visual language the Church had for these verses, which is why it stands as a type and not as a depiction, and why the card says so. Doth he not leave the ninety and nine, and goeth into the mountains, and seeketh that which is gone astray?",
'File:Workers in the vineyard, Minuscule 269 (11th century).jpg':
 "A miniature from an eleventh-century Byzantine Gospel manuscript. The householder hires labourers at the gate in the upper register; in the lower they work the vines. The parable is the Church’s image for the vineyard passages of Matthew: the eleventh-hour labourer receives the same penny, and the last shall be first.",
'File:Christ heals two Jericho blind men.jpg':
 "A mosaic of the 1180s from Monreale in Sicily. What is still legible of the Latin along the top reads CLAMANTES DOMINE MISERERE NOSTRI — crying, Lord, have mercy on us, which is the cry Matthew says they raised twice over the crowd's rebuke: Have mercy on us, O Lord, thou Son of David. The mosaic stops one moment short of the miracle, and the gap is the whole picture. Christ stands at the left with the apostles banked behind him and puts his hand out to the right — and it does not arrive. Between his fingers and the nearer man's face there is a span of gold ground and then the brown flank of the hill; nothing is touched. Matthew's next sentence is the one the mosaic is waiting on: So Jesus had compassion on them, and touched their eyes: and immediately their eyes received sight. The two sit on the ground at the foot of the rock with their sticks across them, faces turned up, hands open and raised, and the mosaicist has set their eyes as blank white ovals, so the blindness can be seen before the inscription is read. A dark tree grows out of the rock above them. Their words are the ones the Orthodox Church has said more often than any others — Lord, have mercy — and the Jesus Prayer is built out of the same two halves, the naming of the Son of David and the asking for mercy.",
'File:074 Cursing the fig tree Icon from Saint Paraskevi Church in Langadas.jpg':
 "A nineteenth-century Greek panel from St Paraskevi at Langadas, its gold ground rubbed through to the board in places. Christ stands right of centre in a rose himation over blue, his right arm up and stretched toward the tree, an open scroll in his left hand whose writing is no longer legible. Behind him the apostles are packed into a wedge of overlapping gold haloes, and behind them at the upper left stand the walls and towers and cypresses of the city he had walked out of that morning. The tree fills the right quarter of the panel and it is in full green leaf — thick, dark and healthy — and that is the thing to see: this painter has not painted the withering. Matthew gives it in one clause, and presently the fig tree withered away, and the icon stops before it, at the raised hand and the leaves. What the tree lacks is in the sentence before: he came to it, and found nothing thereon, but leaves only. The Fathers read the whole thing as a parable acted instead of spoken — a show of religion with nothing under it — and by leaving the show intact the panel keeps the word, and not the ruin, at the centre.",
'File:Parable of the Wedding Feast 04-14.jpg':
 "A fresco of 1502 by Dionisy in the Nativity cathedral at Ferapontov in the Russian North, faded now to pale ochre, white and blue-green. The king stands at the left under an arched doorway — a flat gold crown, a green cloak over a dark tunic with a broad jewelled band down the front, an attendant in a white cap at his shoulder — and he is pointing into the hall. He is not enthroned and he is not at table; the king of this parable is a man giving orders, and Dionisy paints him giving them. Across the middle, servants in red and ochre bring dishes to two tables spread with white cloths, with tall vessels standing on them, and the guests are crowded along the far side in green and red and brown. Then the right-hand edge, which is what the last four verses are about. A man in a pale tunic is bent almost double, head down and arms hanging, while a figure behind him puts a hand on him and pushes: he is being thrown out, and that is as far as the fresco goes — nobody in it is bound. Matthew's king asks him one question, Friend, how camest thou in hither not having a wedding garment? — and he was speechless. What the king says next is not painted: Bind him hand and foot, and take him away, and cast him into outer darkness. The parable ends a line later, For many are called, but few are chosen.",
'File:Christ, last judgment, narthex, GRACANICA 7 D39A0936.jpg':
 "Christ in glory, from the Last Judgment in the narthex of Gračanica. The narthex — the porch a worshipper passes through on the way in — is where the Orthodox Church habitually paints the Judgment, so that no one enters the nave without walking under it. Matthew 24 is its text: they shall see the Son of man coming in the clouds of heaven.",
'File:Monreale - Anointing at Bethany.jpg':
 "The anointing at Bethany, from Monreale. Christ reclines at table on the left; the woman lies prostrate at his feet with the alabaster box emptied on the floor beside her, while the disciples crowd the far side of the table to object to the waste. Matthew says she poured the ointment on his head — the Sicilian mosaicists have painted the feet, the way Luke and John tell it. She hath wrought a good work upon me: in that she hath poured this ointment on my body, she did it for my burial. The Orthodox Church sings of her through Holy Wednesday.",
'File:Judas receiving money, icon of Yaroslavl (19 c, priv.coll).jpg':
 "Judas receiving the thirty pieces of silver — a nineteenth-century icon of the Yaroslavl school. The high priest counts the money out on the table and Judas stands at the left corner with his hand open over it, dressed as an apostle and barefoot as the apostles are painted, and alone in the icon in having no halo. Thirty pieces was the price of a slave in the law of Moses, and Zechariah had already named the sum: a goodly price that I was prised at of them.",
'File:Alektor Petrou Dionysiou.jpg':
 "Peter and the cock, Dionysiou, Athos. The scene is set in the high priest’s courtyard where Peter sat with the servants at the fire, and the painter has put two moments on one wall: Peter denying, with the maid pointing at him from a doorway, and Peter a second time at the right, bent double with his face hidden. The cock stands on a little pillared roof above them both, no bigger than a hand. Before the cock crow, thou shalt deny me thrice. The icon of the denial is also the icon of the tears that followed it.",
"File:The Lord's prayer in Gethsemane - Stavronikita monastery, Mt Athos - Theophanes of Crete, 16th c..jpg":
 "The prayer in Gethsemane, painted by Theophanes the Cretan at Stavronikita on Mount Athos in the sixteenth century — Theophanes is the master of the Cretan school and one of the great Orthodox iconographers. He has painted the whole night in one frame: Christ appears four times up the face of the rock — kneeling three times in prayer, and once upright and turned back toward the sleepers — while below him the disciples lie asleep in a heap the width of the wall. O my Father, if it be possible, let this cup pass from me: nevertheless not as I will, but as thou wilt.",
'File:Prodosia Dionysiou.jpg':
 "The Betrayal — Prodosia — from Dionysiou on Athos. Judas takes Christ by the shoulders to kiss him while the crowd closes in with swords and staves and torches; at the edge Peter strikes at Malchus. Friend, wherefore art thou come? The icon leaves Christ perfectly still at the centre of a scene made entirely of motion.",
'File:Krinomenos Christou Dionysiou.jpg':
 "Christ being judged, Dionysiou, Athos. The titulus names both hearings at once — Ο ΧΣ ΚΡΙΝΟΜΕΝΟС ΥΠΟ ΑΝΝΑ ΚΑΙ ΚΑΙΑΦΑ, Christ judged by Annas and Caiaphas — and two priests sit enthroned under the canopy while Christ stands before them barefoot, his hands free and one of them held out in the painters' gesture for speech. An open scroll and an inkhorn lie on the desk between them: the charge is being written down. The composition is deliberately reversed from the icons of Christ enthroned: the Judge of all stands, and men sit above him.",
'File:Ypestrepseta Triakonta Argyria Ioudas.jpg':
 "Judas returning the thirty pieces of silver — Dionysiou, Athos. At the right he is bent over the table casting the money down, and the priests put up a hand to refuse it; at the far left of the same wall the painter has already hanged him from a tree. The fresco holds the remorse and the end of him in one frame. I have sinned in that I have betrayed the innocent blood. The Fathers distinguish his remorse sharply from Peter’s repentance: both wept, but only one went back to the Lord.",
'File:Aponepsis Pilatou Dionysiou.jpg':
 "Pilate washing his hands — Dionysiou, Athos. The governor is enthroned and a servant pours water over his fingers while Christ stands to one side. I am innocent of the blood of this just person: see ye to it. The icon fixes the moment a man performs a ritual of innocence in the act of committing the crime.",
'File:Mnemeion Christou Dionysiou.jpg':
 "NOT IN USE — and it must not be put back under Matthew 27:62–66. Its painted inscription reads Ο ΔΕ ΠΕΤΡΟС ΚΑΙ Ι(ΩΑΝΝΗ)С ΕΔΡΑΜΟΝ ΕΠΙ ΤΟ ΜΝΗΜΕΙΟΝ — but Peter and John ran to the sepulchre — and it paints the empty tomb with the grave-clothes and the folded napkin, labelled Ο ΑΓΙΟС ΤΑΦΟС. That is John 20 and Luke 24 on the morning of the Resurrection, not the sealing and the watch. Matthew nowhere reports Peter running to the tomb, so no passage in this reader owns it.",

// Readings for the further icons of a scene. Each one says where and when it was made and
// what it does differently from the icon it stands beside — that difference is the reason it
// is here at all.
"File:Icon with the Virgin of the Tree of Jesse. 1666 (8384481474).jpg":
 "A Cretan icon of 1666 by Theodore Poulakis, recovered after a theft and now kept in the Byzantine and Christian Museum in Athens. Where the Athonite tree ranges the kings along its branches, Poulakis sets the Theotokos enthroned with the Child at the centre of the tree and turns the whole genealogy toward her: Matthew's list of forty-two generations ends in a person, not a name.",
"File:Tree of Jesse icon (17 c.).jpg":
 "A seventeenth-century Russian panel of the same subject, and the plainest way the genealogy has ever been painted. Seven registers of seated forefathers fill a warm ochre ground, five or six to a row, each inside a thin roundel of vine with a small red rosette where the tendrils meet, and each turned toward his neighbour. There is no trunk and no sleeping Jesse: the vine here is reduced to the scaffolding that makes the compartments. The list ends at the head of the central column, where the Theotokos stands on a pedestal holding the Child. Along the base, outside the vine, runs a row of standing prophets holding open scrolls, with a blackened inscription plate at the middle of it and a small figure bowing beneath. It reads exactly as Matthew's first chapter reads aloud — a list, and at the end of the list, Christ.",
"File:031 Nativity of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":
 "A Greek icon from the collection of St Paraskevi at Langadas, inscribed in the dark of the cave Η ΓΕΝΝΗCΙC ΤΟΥ ΧΡΙΣΤΟΥ. The board is badly hurt — a wide scar of lost paint falls from the top edge straight through the manger — but its centre is intact. The cave behind the Child is painted almost black, and the manger is a low chest of stone stepped at the foot the way an altar is stepped: Orthodox painters give the Nativity a dark cave and a crib shaped like a tomb, because the birth is already read in the light of the burial. The Theotokos kneels at the left of it and Joseph kneels opposite her at the right, both with their hands crossed on the breast and both bowed to the manger rather than to each other; neither is doing anything, which is the painter's way of saying that nothing here was done by them. Joseph is where Matthew's whole account leaves him — the just man who was minded to put her away privily, who then did as the angel of the Lord had bidden him, and who never speaks a word in the Gospel. Behind him an old man wrapped to the throat in a shaggy fleece stands with his head thrown back. Above the cave are things Matthew never reports: an angel leaning down to two shepherds on the hillside, one of them piping, which is Luke's account and not his.",
"File:12 Nativity of Jesus Icon in Assumption of Mary Church in Agios Vasileios.jpg":
 "The same feast from a village church of the Dormition at Agios Vasileios, on a panel a foot and a half high, and the most worn icon in this reader: the surface has been rubbed back so far that the gold haloes, dotted round the rim like jewellery, are often the only part of a figure still certain. What is legible is this. A block of white masonry with a straight top and a moulded lip stands at the centre, and the Child lies along the top of it swaddled in rose-coloured bands — whether the painter drew a trough with a far rim or a bare slab can no longer be told. Two figures kneel to it with their hands crossed on the breast: the Theotokos on the right in a rose maphorion under a jewelled halo, and on the left the old grey-bearded man in blue who is Joseph, whose dream and whose obedience are the whole of Matthew's account of the birth. Behind and between them stand others whose faces have gone altogether. A broad orange shaft comes down the middle of the board from the top edge to the manger. The upper register holds one small scene in each corner, and only the right-hand one can still be read.",
"File:Nativity Icon Panagia Evraidos Church 19 Century.jpg":
 "A nineteenth-century Greek icon from the church of Panagia Evraidou. Its ground is landscape — green hills and a blue sky rather than gold — which is the late Greek manner, and it is the plainest Nativity in this reader as well as the one that leaves most out: there is no cave, no ox and ass, and no manger. The Child lies swaddled in white bands directly on the grass, with thin gold rays spreading from him across it, and Joseph at the left and the Theotokos at the right each reach a hand toward him without touching him. The light does not come down as one ray either: three broad red shafts fall between the four angels along the top edge. Under them a band of red letters crosses the whole panel, of which the word still legible is ΠΟΙΜΕΝ, the shepherds — and the shepherds on the hillside above are Luke's, not Matthew's. What is Matthew's is the pair kneeling at the Child and nothing else: he gives the birth itself in half a verse, and gives it as the end of Joseph's story — knew her not till she had brought forth her firstborn son: and he called his name JESUS.",
"File:Cathedral (Monreale) - North arch of transept - Journey of the Magi.jpg":
 "The panel that comes immediately before the Adoration in the Monreale cycle, and the only image in this reader of the first half of these verses: the three kings still on the road, each of them turning and pointing up at the star. The mosaicist has lettered the Latin in abbreviation, with strokes over the shortened words — ...TES · STELLĀ · IN · ORIĒTE · VENT — which is MAGI VIDENTES STELLAM IN ORIENTE VENIUNT IN HIERUSALEM, the Magi, seeing the star in the east, come to Jerusalem. The star itself is set in a dark blue disc at the top with a beam running down out of it across the gold.",
"File:Flight into Egypt Icon Mary Evraida Church Kastoria.jpg":
 "A nineteenth-century icon from Kastoria in northern Greece. The Theotokos rides with the Child while Joseph walks ahead and turns back toward them — the gesture Byzantine painters give him for the whole journey. He is leading, and he keeps looking round to see that they are still behind him.",
"File:Cathedral (Monreale) - South arch of transept - Flight into Egypt.jpg":
 "A mosaic of the 1180s from Monreale in Sicily, worked by Greek craftsmen for a Norman king, and the order of the procession is the thing to get right. At the back, at the far left, a youth in green walks with a bundle slung on a pole over his shoulder and a long stick in his hand, driving the beast along. The ass comes next with the Theotokos riding side-saddle, haloed, in blue and rose, her hands crossed at her breast and nothing in her arms. In front of them, going first and on foot, is Joseph — an old bearded man in a pale himation with the Child sitting on his shoulders, one small hand steadying himself and the other raised in blessing. The walled city at the right with its open gate is Egypt, and a band of water runs along the bottom. The Latin above reads that Christ, with Mary his mother and Joseph, entered Egypt. Matthew's own sentence has no ass in it and no servant: he took the young child and his mother by night, and departed into Egypt — and he gives the reason a line later, that it might be fulfilled which was spoken of the Lord by the prophet, saying, Out of Egypt have I called my son.",
"File:Flight into Egypt (12 Sinai).jpg":
 "A detail from a twelfth-century Nativity icon at St Catherine's on Sinai, where the Flight is one episode along the edge of a larger feast. The ground is not gold but a warm ochre, worked in the small, quick hand these marginal scenes get, with the captions written straight onto it in red. There are five figures, not two. A youth with a staff walks behind; the ass carries the Theotokos in dark blue with the Child held in front of her in both hands; Joseph, white-bearded, walks at the beast's head and looks back; a fourth haloed figure in orange strides ahead and turns round. And at the right, standing in the doorway of a building with her hands up, is a woman who is not part of the journey at all: the red letters under her read ΡΑΧΗΛ ΚΛΑΙΟΥΣΑ, Rachel weeping. That is the next paragraph of Matthew and it is his alone — In Rama was there a voice heard, lamentation, and weeping, and great mourning, Rachel weeping for her children, and would not be comforted, because they are not. The painter has set the escape and the massacre side by side on the same few inches of board.",
"File:Menologion of Basil II - Massacre of the Innocents.jpg":
 "A miniature from the Menologion of Basil II, made in Constantinople about 985 for the emperor's own use. Herod is enthroned at the left under a canopy and gives the order; the soldiers do the work at the right. The book is a calendar of the Church's saints, and the Innocents have their own day in it — the 29th of December, four days after the Nativity.",
"File:Detail of the Massacre of the innocents mosaic at Chora (1).jpg":
 "A detail from the great fourteenth-century mosaic cycle of the Chora church in Constantinople, and the mosaicist has reduced the whole slaughter to two soldiers and one child. The child is not held up in the air: he lies on the ground on his back, and the soldier stoops over him in a short lamellar corselet and takes him by the arm. The second soldier stands at the right edge with his sword already drawn, and the blade crosses the gold above them — it is the only weapon in the panel and nothing has happened yet. The ground is the same gold that carries every feast in that church, with a band of green at the foot, and that is what makes it the hardest wall in the building to stand in front of. Matthew gives the order in a sentence and then leaves it for Jeremiah to say what it was like: Rachel weeping for her children, and would not be comforted, because they are not.",
"File:St John the Baptist Late XVII - Early XVIII Cenury St Mary Blonichka Church, Ohris Icon Gallery.jpg":
 "An Ohrid icon of the late seventeenth or early eighteenth century, of the type the Greeks call the Angel of the Desert. The Forerunner is given wings because of the prophecy Matthew quotes over him — Behold, I send my messenger before thy face — and the Greek for messenger is angelos. He holds a scroll with his own preaching, and beside him stands the dish with his head on it, so that the icon shows his whole life and its end at once.",
"File:019 Baptism of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":
 "A Greek panel signed by Athanasios Margaritis and dated 1850, from St Paraskevi at Langadas, and rubbed hard: paint is gone in patches down the whole right side. It carries no title band — the lettering other panels put across the top is not here. Two ochre rock-banks close in from either side, planted with dark trees painted as flat discs on bare stems, and between them the Jordan lies as a wide, dark blue-green pool rather than the narrow upright shaft of the Russian icons. A broad red-orange shaft comes down the middle of the dark sky between the banks, and at the bottom of it, just over Christ's head, is the dove. Christ stands waist-deep at the centre with his hand at his breast; the Forerunner leans in from the left bank with his right hand on the Lord's head and a scroll in his left; two angels wait on the right bank with their hands wrapped in their cloaks — you cover your hands to receive a king. Matthew is the Evangelist who reports the argument at the water's edge, and no painter has ever found a way to show it: I have need to be baptized of thee, and comest thou to me?",
"File:03 Baptism of Christ Icon from Saint Paraskevi Church in Adam.jpg":
 "The same feast from the village of Adam in northern Greece, on a small panel darkened almost to brown by candle smoke. A red band across the top gives the title, Η ΒΑΠΤΙΣΙΣ ΤΟΥ ΧΡΙΣΤΟΥ. This is the one panel in the gallery that paints the dove itself: a white bird with its wings spread hangs in a bank of grey-blue cloud at the top, and a fine spray of rays runs down from it to Christ's head, so that the heavens were opened unto him, and he saw the Spirit of God descending like a dove are one movement in the eye. Christ stands in water so dark it reads as black, and his arms are at his sides — he is not blessing the river, whatever the Fathers say he is doing there. The Forerunner bends over him from the left with his hand on his head; three angels stand ranked on the right bank, bowing, their hands wrapped in their garments, the nearest holding a folded cloth. Matthew alone gives the voice its exact words as a public sentence rather than a private one: This is my beloved Son, in whom I am well pleased.",
"File:0663Ha. Hermitage Museum (Hall 143). Icon of the Epiphany.jpg":
 "A Russian icon of the third quarter of the seventeenth century, from the Russian North, now in the Hermitage. The Russians keep the Greek arrangement and change its temper: the Jordan becomes a deep dark trough between red-brown banks, and the angels crowd the whole right side of the board. The Greek Church calls the feast Theophany rather than the Baptism, because what the Fathers read in it is the Trinity made plain — the Son in the water, the Spirit descending, the Father's voice.",
"File:Cathedral (Monreale) - Right wing transept - 2nd Temptation of Christ.jpg":
 "The panel that follows the first temptation along the same wall at Monreale. The devil has set Christ on a pinnacle of the temple — painted as a small domed building under his feet — and the two inscriptions carry the exchange: SI FILIUS DEI ES MITTE TE DEORSUM, if thou be the Son of God, cast thyself down, answered by SCRIPTUM EST NON TENTABIS DOMINUM DEUM TUUM, it is written, thou shalt not tempt the Lord thy God. Every answer Christ gives in this passage is a quotation from Deuteronomy.",
"File:Monreale - healing of paralytic.jpg":
 "A mosaic of the 1180s from Monreale in Sicily, and the one icon in this gallery whose own inscription belongs to another Evangelist. Along the top, above a parapet, two men lean over with a rope in each hand and lower a bed into the room, and the Latin lettered beside them — worn, but these two words are firm — reads APERVERVNT TECTVM, they uncovered the roof. Matthew has nobody on a roof. He gives the approach in half a line, they brought to him a man sick of the palsy, lying on a bed; the digging open of the roof is St Mark's and the tiling is St Luke's. What the mosaic shows below is Matthew's own. Christ sits enthroned at the left on a jewelled throne with a disciple behind him and his hand out; in the middle of the floor the paralytic is sitting up on his bed — not shouldering it and walking off, but risen on it and turned back toward Christ with both arms out; and at the right a knot of scribes in green and blue mutter together, which is the part Matthew makes the passage about: certain of the scribes said within themselves, This man blasphemeth. A second bed with a white coverlet stands behind them.",
"File:Healing of the Paralytic 04-17.jpg":
 "A fresco of 1502 by Dionisy in the Nativity cathedral at Ferapontov — the finest Russian wall-painting of its age, and the same hand and the same walls that give this reader the marriage feast and the ten virgins. The colours are Dionisy's pale rose, blue-green and ochre, and the wall is read from left to right as a sequence. Christ sits at the LEFT with the apostles behind him and his hand raised in speech. Below and in front of him the paralytic still lies on a low bed with a crowd of dark-robed men pressed over him. Then, in the middle of the wall, the same man walks away upright with the bed on his shoulders, which is the last thing Matthew reports: and he arose, and departed to his house. At the right stand the people who watched it, in the heavy dark robes Russian painters give the scribes. There is no roof anywhere in this fresco and no crowd in a doorway — nothing of the getting in, only the getting up and the going out, which is exactly the part of the story Matthew tells.",
"File:Matthew the Evangelist - icon.jpeg":
 "A Russian icon from Palekh, the icon-painting town in the Ivanovo region, painted about the middle of the nineteenth century. Matthew sits at his writing desk with the angel at his shoulder. The angel is his symbol among the four living creatures, given to him because his Gospel opens with the human descent of Christ — the genealogy this reader began with. Like the Greek icon beside it, this is the apostle's own portrait rather than a picture of his calling.",
"File:Raising of Jairus' daughter 03-19.jpg":
 "Dionisy's fresco at Ferapontov, 1502. The girl lies on a high bed across the middle of the wall and Christ comes to her from the right; the crowd Matthew describes — the minstrels and the people making a noise — is pressed into the left of the scene. Russian wall-painting of this school keeps its figures long and almost weightless, so that the whole miracle seems to happen without effort, which is the point of it.",
"File:Tokalı Kilise Raising of daughter of Jairus - 2004 6964.jpg":
 "From the Tokalı church at Göreme in Cappadocia, one of the churches cut into the rock there, whose paintings belong to the tenth century. The Cappadocian painters worked quickly and plainly on a rough surface, and the miracle is cut down to what it needs: the bed, the child, and the hand of Christ reaching for hers.",
"File:Mosaic of the exorcism of the Gerasene demoniac from the Basilica of Sant'Apollinare Nuovo.jpg":
 "One of the oldest surviving images of this miracle: an early sixth-century mosaic in Sant'Apollinare Nuovo at Ravenna, made while the city still worked in the Byzantine manner. Christ stands in the purple with an apostle beside him, the possessed man crouches naked in the middle, and the swine are already running down the slope into the water at the right. Ravenna paints one possessed man where Matthew names two — Mark and Luke tell the miracle with one — so what fixes this as Matthew's scene is the herd going over the edge.",
"File:Synaxis of the Twelve Apostles Dimitar Molerov Rila Monastery 1835.jpg":
 "A Bulgarian icon of 1835 by Dimitar Molerov, from the Rila monastery. The Synaxis is the feast of the 30th of June, the day after Peter and Paul, on which the Church commemorates all twelve together — which is why it is the image set over their sending out rather than any picture of the sending itself. Molerov ranks them close together, each with his scroll or his book.",
"File:The Twelve Apostles, with later gilding, Greek, Late Byzantine, early 1300s, tempera and gold leaf on wood panel - Princeton University Art Museum - DSC06701.jpg":
 "A late Byzantine panel of the early fourteenth century, tempera and gold leaf on wood, now in the Princeton University Art Museum; the gilding on it is a later addition. The twelve stand in three close ranks against gold, so tightly packed that the haloes overlap — a company rather than twelve portraits, which is exactly what Matthew's list of their names is.",
"File:Prophetes Ionas Dionysiou.jpg":
 "The prophet standing with his scroll, from the same Athonite programme of 1547 that gives this passage its icon of him cast up by the sea. Here he is simply the man — no whale, no Nineveh. The Church reads him as the sign Christ names in these verses: as Jonah was three days and three nights in the whale's belly, so shall the Son of man be three days and three nights in the heart of the earth.",
"File:103 Beheading of Saint John the Baptist Icon from Saint Paraskevi Church in Langadas.jpg":
 "A Greek icon of 1927 from Langadas, given by a donor whose name is written into its inscription. It shows nothing but the head of the Forerunner lying on its dish, which is verse 11 of this passage and no more of it: his head was brought in a charger, and given to the damsel. The Church keeps the day of the beheading as a strict fast.",
"File:19 Beheading of Saint John the Baptist Icon in Assumption of Mary Church in Agios Vasileios.jpg":
 "A village icon of the whole scene. The executioner stands over the body with his sword still raised, the prison is the barred window behind him, and Salome waits at the right with the dish already held out. Matthew tells it as a court story — a birthday, a dance, a rash oath — and the icon keeps the palace wall in the background to say so.",
"File:Feeding the multitude, Sant'Apollinare Nuovo, Ravenna.jpg":
 "A sixth-century mosaic from Sant'Apollinare Nuovo at Ravenna. Christ stands at the centre in the purple with his hands out to either side, and two disciples hold up the loaves and the fishes to him: the miracle caught at the blessing rather than the distribution. There are five figures and no landscape at all — sixth-century Ravenna tells the story with nothing to spare.",
"File:042 Transfiguration of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":
 "Signed by the painter Stavros Margaritis of Kolakia and dated 1885, with Peter, John and James named in the inscription. Christ stands in a white mandorla with Moses and Elias turned in toward him, and the three disciples are thrown down the slope beneath. The Greek word the Gospel uses is metamorphosis — he was changed; and the Fathers insist the light was his own, not lent to him.",
"File:Icon of the Transfiguration from Saint Catherine's, Sinai.jpg":
 "Another twelfth-century panel from the monastery of St Catherine on Sinai, where the mountain of Moses stands over the wall. The ground is gold and the hill green, the mandorla is left open rather than filled with rays, and the three disciples fall in three different directions — the painter's way of saying that not one of them could stay standing.",
"File:Icon of transfiguration (Spaso-Preobrazhensky Monastery, Yaroslavl).jpg":
 "A large Russian panel of about 1516, over five feet high, from the Saviour-Transfiguration monastery at Yaroslavl — the house named for this feast. Russian painters add what the Greeks usually leave out: Christ leading the three up the mountain at one side and bringing them down at the other, so that the icon carries the whole of Matthew 17 at once — the ascent, the vision, and the charge on the way down to tell the vision to no man.",
"File:Ravenna — The Good Shepherd mosaic.jpg":
 "The mosaic in the mausoleum of Galla Placidia at Ravenna, made about 425, and the best known of all the Good Shepherd images. He sits among his sheep on a rocky hillside in gold and purple, holding a tall cross like a shepherd's staff and reaching out to touch one of them. It is the same subject as the Constantinopolitan floor this passage leads with, but here the shepherd is unmistakably the Lord enthroned — the ninety and nine left on the hills, and the hand already out toward the one.",
"File:005 Entry into Jerusalem Icon from Saint Paraskevi Church in Langadas.jpg":
 "Inscribed Η ΒΑΙΟΦΟΡΟC, the Palm-bearing, which is the Greek name of the feast. Christ rides side-saddle on the ass with the disciples massed behind him, the mount of Olives at his back and the gate of the city ahead; children spread garments in the road and one of them is up in the palm tree. Matthew ends the passage with the city moved and asking, Who is this?",
"File:18 Triumphal entry into Jerusalem Icon from Saint Paraskevi Church in Adam..jpg":
 "Signed by Athanasios of Adam and dated 1846, from the same northern Greek village tradition as several icons in this reader. The whole panel is built on the diagonal of the animal's walk, from the rock at the left to the wall at the right, so that the icon has the movement of a procession in it — which is what the feast is: the Church walks this passage every Palm Sunday with branches in its hands.",
"File:Entry into Jerusalem (Afon icon).jpg":
 "A sixteenth-century Athonite icon, and the sparest of the three. Christ in a dark blue mantle rides against an almost bare red-gold ground; the disciples are a single mass behind him, the tree and the city are reduced nearly to signs. Athonite painting of this century strips a feast down to its one gesture and trusts the gesture to carry it.",
"File:Rossano Gospels - Cleansing of the Temple.jpg":
 "A page from the Rossano Gospels, a Greek Gospel book of the sixth century written in silver on parchment dyed purple, and one of the oldest illustrated Gospel manuscripts that survives. The page is laid out as an argument in two registers. Across the top runs the scene, headed in gold ΠΕΡΙ ΤΩΝ ΕΚΒΛΗΘΕΝΤΩΝ ΕΚ ΤΟΥ ΙΕΡΟΥ — concerning those cast out of the temple: Christ in a gold himation at the left with two figures behind him, a money-changer bent over his table in the middle of the band, a man carrying a cage of doves, and two oxen being hauled out at the right-hand edge. Beneath it are four prophets, and they are not standing and they hold nothing. They are half-figures cut off at a ledge, each with one hand raised, and each one's text is written out on the purple page below him in a column of Greek — the words are on the leaf, not on scrolls. Their names are lettered above their heads: ΔΑΔ, David, twice, and both Davids are crowned; ΩΣΗΕ, Hosea; and ΗΣΑΙΑΣ, Isaiah. That is the manuscript's whole method — prophecy and event on one opening, with the joining left to the reader. Matthew does the same thing twice inside the passage, quoting first My house shall be called the house of prayer; but ye have made it a den of thieves, and then, when the chief priests object to the children crying in the temple, Out of the mouth of babes and sucklings thou hast perfected praise.",
"File:Fig tree cursed 04-16.jpg":
 "Dionisy's fresco at the Ferapontov monastery, 1502. Christ stands with the disciples at the left and the tree at the right has already gone bare; the buildings of the city lean in behind them. The Fathers read the tree as the temple Christ has just cleansed — full of leaves, with nothing on it to eat — which is why the icon is painted inside the walls of a city rather than out on a road.",
"File:Ten virgins 05-15.jpg":
 "Dionisy's fresco of the parable, 1502. Christ sits enthroned at the centre as the bridegroom; the virgins come toward him in two files, the ones with their lamps burning and the ones who have run out. Orthodox churches carry very few parables on their walls — this one cycle at Ferapontov gives this reader both the marriage feast and the ten virgins, and there is almost nowhere else to look for them.",
"File:John Tokhabi, Last Judgment, around 1100. Icon, tempera. St Catherine monastery on Sinai, Egypt.jpg":
 "An icon of about 1100 from the monastery of St Catherine on Sinai, signed in Georgian by its painter, John Tokhabi — among the earliest full Last Judgments to survive on a panel rather than a wall. Read it in registers. Two benches of apostles sit enthroned across the top, and between them the paint is gone down to the bare wood: the centre of the panel, where Christ sat in judgment with his mother and the Forerunner beside him, has been destroyed. Below the benches run the written sentences of Matthew 25; the river of fire comes down out of them, the ranks of the saints stand in order the whole length of the left side, and the torments are set out in labelled cells at the lower right. What the icon has lost is its centre; what it keeps is everything the centre was judging.",
"File:05 Last Supper Icon from Saint Paraskevi Church in Adam.jpg":
 "Signed by Asterios Ioannou Anagnostos and dated 1898, inscribed ὁ δεῖπνος ὁ μυστικός — the Mystical Supper, which is what the Orthodox Church calls this meal. A basin stands in the middle of the cloth with a flask and cups around it, John leans against the Lord, and one arm is stretched right across the table: the reach is how the painters show the hand that dipped in the dish with him, without having to name the man.",
"File:Kirillo-Belozersky iconostasis 12 - Last Supper.jpg":
 "From the festival tier of the iconostasis of the Dormition cathedral at the Kirillo-Belozersky monastery, painted in 1497 — one of the great surviving Russian icon screens. Christ is set at the left end rather than the middle, the table is tilted up toward the viewer so that nothing on it can be hidden, and the apostles run round it in one unbroken curve — with one arm reaching down over the cloth to a footed vessel, which is how these icons name the betrayer without painting his face. An icon from an iconostasis was made to be seen from below and at a distance, which is why it is composed so simply.",
"File:Gethsemane Dionysiou.jpg":
 "The same subject as the icon this passage leads with, from the katholikon of Dionysiou; Commons gives this fresco to Theophanes the Cretan, who painted the Stavronikita version, though the Dionysiou programme as a whole is usually given to Tzortzis. Christ is painted four times across the rock, each figure lettered ΙΣ ΧΣ: three times kneeling in prayer, and once standing with his hand out over the disciples. Matthew has him go away and come back three times, and the fresco puts the going and the coming in one frame, with the disciples heaped asleep at the right.",
"File:Cathedral (Monreale) - Right wing transept - Agony in the Garden.jpg":
 "The Sicilian mosaic, with VIGILATE ET ORATE lettered into the gold — watch and pray, the words Matthew gives Christ at this hour. He is set down twice: kneeling at the top with the angel bending out of the gold toward him, and again standing at the right with his hand out over the disciples, who are heaped asleep across the whole lower half. The angel is Luke's detail rather than Matthew's. The mosaicists give the sleeping men as much of the picture as the prayer, which is fair to the text: half of what Matthew reports here is what the disciples could not do.",
"File:Judas's kiss (Monreale).jpg":
 "The Monreale mosaic of the betrayal, with TRADITIO — the handing over — written above it. The crowd fills the whole ground with staves and torches, and at the centre of it Judas has both arms round the Lord's shoulder and their two heads are together. What Matthew records is what met the kiss: Friend, wherefore art thou come?",
"File:Kiss of Judas (Church of Saint Nicolas the Orphan).jpg":
 "A fourteenth-century fresco from the church of St Nicholas Orphanos in Thessaloniki, one of the finest small Palaiologan programmes anywhere. The painter crowds the top of the frame with spears, swords and curved blades and a lantern carried in above them, and sets the kiss over at the right of the press, so that the arrest is already happening around the two figures while they are still face to face.",
"File:Christ before Caiaphas, GRACANICA 1 090A7764.jpg":
 "From the north aisle of Gračanica, about 1320. Caiaphas sits raised on his seat with the elders around him and Christ stands before them wrapped in his mantle, his hands not shown at all — which is how this fresco paints the silence Matthew reports, until the high priest puts him on oath. The Athonite fresco this passage leads with names both Annas and Caiaphas in its inscription; this one paints only the second hearing, and the verdict.",
"File:Judas hangs himself. Gelati fresco.JPG":
 "An eighteenth-century fresco in the Gelati monastery in Georgia, an Orthodox house founded in the twelfth century. Judas hangs from the tree alone, in an empty landscape — no crowd, no city, nothing but bare rock, where the Athonite fresco beside it sets the hanging in the corner of a crowded wall. This is the only Gospel that reports the end of him, and the Church paints it very seldom.",
"File:Pilate judgement (icon).jpg":
 "A fifteenth-century Russian panel of the trial. Pilate is raised on his judgment seat with his counsellors, the accusers press in from the left, and the one gold halo in the panel marks Christ among them. The icon this passage leads with shows only the washing of the hands; this one shows the hearing those hands were washed after — Matthew's Pilate knows exactly what he is doing, and does it anyway.",
"File:Flagellation of Christ (icon).jpg":
 "A fragment of a fifteenth-century Novgorod double-sided tablet icon — a small painted board of the kind laid out on a stand for the day it belonged to. Christ is bound to the column and two men work at him with scourges, one on either side. It is a single verse of this passage: and when he had scourged Jesus, he delivered him to be crucified.",
"File:Crucifixion Icon Sinai 12th century.jpg":
 "A small Comnenian panel of the second half of the twelfth century, twenty-eight centimetres high, from St Catherine's on Sinai. The Theotokos stands at the left and John at the right — the oldest arrangement of all — with small saints ranged in the borders. The body is given the long curve that twelfth-century painters used to show a death that is not a defeat: he is not slumped on the cross, he is laid along it.",
"File:024 Crucifixion of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":
 "A Greek icon dated 1855. It fills the ground behind the cross with the walls of Jerusalem and puts the women and the centurion Matthew names at its foot, and in the rock beneath there is a skull: the tradition that Golgotha, the place of a skull, is where Adam was buried, so that the blood runs down onto the first man. Matthew is the evangelist who reports the graves opening at that moment.",
"File:Double-sided icon - Crucifixion and Hodegetria (9-13th c., Byzantine museum).jpg":
 "The Crucifixion, with the Theotokos at Christ's right hand and John at his left, two angels bending in above the arms of the Cross and red stars scattered over the whole gold ground. It is the front of a double-sided processional icon, the oldest panel in the Byzantine and Christian Museum in Athens, with three layers of painting one on top of another from repeated repair. The Virgin Hodegetria is painted on its back. Icons like this were carried out of the church in procession on a pole, which is why both faces had to be finished — whichever way it was turned, someone was looking at it.",
"File:Lamentation icon Nerezi MK.jpg":
 "The most famous Lamentation in Byzantine painting: the fresco of 1164 in the church of St Panteleimon at Nerezi, above Skopje. The Theotokos has her face pressed against her Son's and John bends over his hand. Before Nerezi this scene is composed and still; after it the figures grieve, and every later Epitaphios in the Orthodox world is working from what the painter of this wall did first.",
"File:Lamentation by Emmanuel Lambardos (Byzantine museum).jpg":
 "Signed by the Cretan painter Emmanuel Lambardos in the seventeenth century, repeating a type worked out on Crete two hundred years earlier. Cretan workshops of this period painted for Orthodox and Venetian buyers both, and could work in either manner on demand; here Lambardos keeps the Byzantine arrangement exactly — the body laid on the stone, the Theotokos at the head of it, the myrrh-bearers standing behind.",
"File:09 Epitaphios Icon in Assumption of Mary Church in Agios Vasileios.jpg":
 "The title band along the top has rubbed back almost to the bare board; what survives of the lettering is read as Ο Ε[ΠΙ]ΤΑΦΙΟС ΘΡΗΝΟС, the lament at the tomb. That is the name of the icon and also of the service the Church sings on the night of Great Friday, when a cloth embroidered or painted with this very scene is carried in procession round the outside of the church. The icon is the service standing still.",
"File:Sealing of Christ's Tomb (Russia, 19th c.).jpg":
 "A late nineteenth-century Russian panel of exactly these five verses — a rare thing to find painted at all. A slab is set across the mouth of the cave with the seal on it, an official stands upright before it with his hand raised, directing the work, and two guards have already sat down in their armour on either side. A group of haloed figures watches from behind the tomb. Matthew alone reports the watch and the sealing, and this icon is painted from his text and from nothing else.",
"File:Sleeping soldiers by Christ's tomb, Mileševa.jpg":
 "From Mileševa in Serbia, painted about 1235. The soldiers set to make the tomb sure are shown asleep in their armour, packed one against another — the lower register of the composition whose upper half is the great white angel at the empty tomb. Set the two halves together and the passage answers itself: the watch that was posted to keep the body in is asleep when it goes out.",
};
