// Pericope -> the Orthodox iconographic subject a passage of John would carry.
// tier a = an icon of THIS scene exists in Orthodox iconography
// tier b = the Church attaches a type icon to the passage without depicting its verses
// tier c = no traditional icon; keep the plain verse row
// kw = keywords matched against the harvested Byzantine/Orthodox pool
module.exports = {
 prologue:    {tier:'b', subj:'St John the Theologian writing the Prologue (with Prochoros)', kw:[['john','theolog'],['john','evangelist'],['prochor']]},
 witness1:    {tier:'a', subj:'St John the Forerunner questioned by the priests and Levites', kw:[['forerunner'],['prodromos'],['baptist','priest']]},
 lamb:        {tier:'a', subj:'The Forerunner points to the Lamb of God', kw:[['lamb','god'],['amnos'],['behold','lamb'],['baptist','jesus']]},
 firstdisciples:{tier:'a', subj:'The calling of Andrew the First-called and Peter', kw:[['andrew'],['first','called'],['protoklet']]},
 nathanael:   {tier:'a', subj:'The calling of Philip and Nathanael', kw:[['nathanael'],['nathaniel'],['philip','call'],['fig','tree']]},
 cana:        {tier:'a', subj:'The Marriage at Cana', kw:[['cana'],['gamos'],['water','wine']]},
 temple2:     {tier:'a', subj:'The Cleansing of the Temple', kw:[['cleansing','temple'],['money','changer'],['expulsion'],['tradesmen'],['merchants']]},
 nicodemus:   {tier:'a', subj:'Christ and Nicodemus', kw:[['nicodem']]},
 witness3:    {tier:'b', subj:'St John the Forerunner', kw:[['forerunner'],['prodromos']]},
 samaritan:   {tier:'a', subj:'Christ and the Samaritan woman (St Photini) at Jacob’s well', kw:[['samarit'],['photini'],['photeine'],['well','woman']]},
 harvest4:    {tier:'c', subj:'', kw:[]},
 nobleman:    {tier:'a', subj:'The healing of the nobleman’s son', kw:[['nobleman'],['royal','official'],['basilikos'],['centurion','son']]},
 bethesda:    {tier:'a', subj:'The healing of the paralytic at the pool of Bethesda', kw:[['bethesda'],['paralytic'],['paralyt'],['sheep','pool']]},
 sonfather:   {tier:'c', subj:'', kw:[]},
 witnesses5:  {tier:'c', subj:'', kw:[]},
 feeding:     {tier:'a', subj:'The Multiplication of the Loaves and Fishes', kw:[['multiplication'],['loaves'],['five','thousand'],['feeding']]},
 walking:     {tier:'a', subj:'Christ walking on the sea', kw:[['walking','water'],['walks','sea'],['walking','sea']]},
 bread6:      {tier:'c', subj:'', kw:[]},
 breadlife:   {tier:'c', subj:'', kw:[]},
 hardsaying:  {tier:'c', subj:'', kw:[]},
 brethren:    {tier:'c', subj:'', kw:[]},
 midfeast:    {tier:'a', subj:'Mid-Pentecost: Christ teaching in the temple in the midst of the feast', kw:[['mid','pentecost'],['mesopentekost'],['prepolovenie'],['midfeast']]},
 livingwater: {tier:'c', subj:'', kw:[]},
 adulteress:  {tier:'a', subj:'Christ and the woman taken in adultery', kw:[['adulter'],['moichal']]},
 light8:      {tier:'c', subj:'', kw:[]},
 truth8:      {tier:'c', subj:'', kw:[]},
 abraham8:    {tier:'c', subj:'', kw:[]},
 blindman:    {tier:'a', subj:'The healing of the man born blind (Siloam)', kw:[['born','blind'],['man','blind'],['typhl'],['siloam']]},
 inquiry9:    {tier:'c', subj:'', kw:[]},
 seeing9:     {tier:'c', subj:'', kw:[]},
 shepherd:    {tier:'a', subj:'Christ the Good Shepherd', kw:[['good','shepherd'],['shepherd']]},
 dedication:  {tier:'c', subj:'', kw:[]},
 lazarussick: {tier:'c', subj:'', kw:[]},
 resurrectionlife:{tier:'a', subj:'Martha and Mary meet Christ before the raising', kw:[['martha'],['mary','martha']]},
 lazarus:     {tier:'a', subj:'The Raising of Lazarus', kw:[['lazar']]},
 caiaphas11:  {tier:'c', subj:'', kw:[]},
 anointing:   {tier:'a', subj:'Mary of Bethany anoints the feet of Christ', kw:[['anoint'],['bethany'],['spikenard'],['myrrh','feet']]},
 entry:       {tier:'a', subj:'The Entry into Jerusalem (Palm Sunday)', kw:[['entry','jerusalem'],['palm','sunday'],['baiophor'],['vaiophor']]},
 greeks:      {tier:'c', subj:'', kw:[]},
 unbelief12:  {tier:'c', subj:'', kw:[]},
 washing:     {tier:'a', subj:'The Washing of the Feet (the Niptir)', kw:[['washing','feet'],['washing','of','the','feet'],['niptir'],['nipter'],['foot','washing']]},
 betrayer:    {tier:'a', subj:'The Mystical Supper (the sop given to Judas)', kw:[['last','supper'],['mystical','supper'],['deipnos']]},
 newcommandment:{tier:'c', subj:'', kw:[]},
 way:         {tier:'c', subj:'', kw:[]},
 comforter:   {tier:'c', subj:'', kw:[]},
 vine:        {tier:'a', subj:'Christ the True Vine (the Ampelos)', kw:[['true','vine'],['vine'],['ampelos']]},
 hatred15:    {tier:'c', subj:'', kw:[]},
 spirit16:    {tier:'c', subj:'', kw:[]},
 sorrow16:    {tier:'c', subj:'', kw:[]},
 prayer17:    {tier:'c', subj:'', kw:[]},
 arrest:      {tier:'a', subj:'The Betrayal — the Kiss of Judas and the arrest in the garden', kw:[['kiss','judas'],['judas','kiss'],['betrayal'],['arrest'],['prodosia']]},
 annas:       {tier:'a', subj:'Christ before Annas and Caiaphas; the denial of Peter', kw:[['annas'],['caiaphas'],['denial'],['peter','denial'],['alektor']]},
 pilate18:    {tier:'a', subj:'Christ before Pilate', kw:[['pilate']]},
 eccehomo:    {tier:'a', subj:'Behold the Man — the mocking, the crown of thorns and the purple robe', kw:[['ecce','homo'],['mocking'],['flagellation'],['scourging'],['crown','thorns'],['bridegroom'],['nymphios']]},
 crucifixion: {tier:'a', subj:'The Crucifixion, with the Theotokos and St John at the cross', kw:[['crucifix'],['stavrosis'],['golgotha']]},
 death19:     {tier:'a', subj:'The death of Christ and the piercing of his side', kw:[['crucifix'],['longinus'],['piercing']]},
 burial:      {tier:'a', subj:'The Burial of Christ by Joseph and Nicodemus (the Epitaphios)', kw:[['entombment'],['burial'],['epitaph'],['lamentation'],['deposition']]},
 tomb20:      {tier:'a', subj:'Peter and John run to the empty tomb', kw:[['peter','john','tomb'],['mnemeion'],['empty','tomb']]},
 magdalene:   {tier:'a', subj:'Christ appears to Mary Magdalene — Touch me not', kw:[['noli','tangere'],['magdalene'],['me','mou','aptou'],['touch','me','not']]},
 doorsshut:   {tier:'a', subj:'Christ appears to the disciples, the doors being shut', kw:[['doors','shut'],['appear','disciple'],['closed','doors']]},
 thomas:      {tier:'a', subj:'The Belief of Thomas (the Psilaphisis)', kw:[['thomas'],['psilaph'],['incredulity'],['doubting']]},
 tiberias:    {tier:'a', subj:'The appearance at the sea of Tiberias — the miraculous draught', kw:[['tiberias'],['miraculous','draught'],['catch','fish'],['draught','fish']]},
 feedsheep:   {tier:'a', subj:'Feed my sheep — Christ restores Peter', kw:[['feed','sheep'],['feed','my'],['peter','sheep']]},
 beloved:     {tier:'b', subj:'St John the Theologian', kw:[['john','theolog'],['john','evangelist']]},
};
