// Prose readings, keyed by Commons file title. Each says where the icon was made, what it
// shows, and what in it answers to John's verses — nothing the picture does not show.
module.exports={
"File:John the Evangelist and Prochorus by E.Lambardos (1602).jpg":
 "A Cretan icon signed at its foot by Emmanuel Lambardos in 1602. It is the Church's own picture of this Gospel being written. John, whom the Church calls the Theologian, sits in the cave on Patmos with his head turned back toward a ray that comes down out of heaven; his disciple Prochoros sits at a desk and writes what he hears. The Church reads these verses at the Divine Liturgy of Pascha, and this is the icon it sets over them. It is not a picture of the Word before time, which cannot be painted, but of the moment the words In the beginning was the Word were given to a man to write. St John Chrysostom marks what was new in them: while all the other Evangelists begin with the Incarnation, John, passing over the Conception and Nativity, speaks immediately of the Eternal Generation.",
"File:049 Saint John the Baptist Icon 2 from Saint Paraskevi Church in Langadas.jpg":
 "A Greek village icon from the church of St Paraskevi at Langadas, made before the twentieth century. Its Commons file name calls it the Baptist, but the inscription names the other John: Ο ΑΓΙΟΣ ΙΩΑΝΝΗΣ, followed in a smaller hand by ο Βαγγελιστής, the Evangelist. He is painted as the Church always paints him in old age, bald-browed and white-bearded, seated at a writing desk with a pen in his hand, and beside him on the desk a haloed eagle. This is not a picture of the Prologue's verses — nothing can be — but it is the icon the Church sets over them: the Evangelist at the moment of writing In the beginning was the Word.",
"File:Agios Ioannes Prochoros Dionysiou.jpg":
 "A fresco on a pendentive of the katholikon of Dionysiou on Mount Athos, 1547 — one of the four curved triangles beneath the dome where Byzantine churches set the four Evangelists. The inscriptions name Ο ΑΓΙΟΣ ΙΩ(ΑΝΝΗΣ) Ο ΘΕΟΛΟΓΟΣ and Ο ΑΓΙΟΣ ΠΡΟΧΟΡΟΣ. It is the same subject as the Lambardos icon: the old apostle seated in the mouth of the cave with his hand at his chin, a ray coming down from a segment of heaven at the top of the frame, and Prochoros at the desk writing.",
"File:Prodromos Didaskon Ioudaious Dionysiou.jpg":
 "A fresco from the Forerunner cycle at Dionysiou on Mount Athos, 1547. The inscription reads Ο ΠΡΟΔΡΟΜΟΣ ΔΙΔΑΣΚΩΝ ΤΟΥΣ ΙΟΥΔΑΙΟΥΣ — the Forerunner teaching the Jews. John stands barefoot in the wilderness in his garment of hair, a tall staff with a cross in his left hand and his right hand raised as he speaks. On his right stand elders in long robes; on his left, armed soldiers. The painter has put the whole of his preaching in one frame, and the soldiers come from St Luke, where they too ask him what they should do. In John's Gospel the question put to him is who he is. The priests and Levites sent from Jerusalem ask whether he is the Christ, or Elias, or that prophet; he answers only, I am the voice of one crying in the wilderness. St Augustine: they would not have sent, unless they had been impressed by his lofty exercise of authority, in daring to baptize.",
"File:Αμφιπρόσωπη εικόνα με τον Άγιο Γεώργιο και τον Άγιο Ανδρέα Β΄ μισό 12ου αι. - Α΄ μισό 18ου αι. Βέροια, Ιερός ναός Αγίου Ανδρέα 2.jpg":
 "One face of a double-sided icon from the church of St Andrew at Veria in Macedonia; its Commons page dates it between the second half of the twelfth century and the first half of the eighteenth. It is a portrait, not a scene: the Church has no icon of two disciples following Christ home at the tenth hour. What it does have is the apostle's own icon, and the scroll in his hand carries the one sentence the Gospel gives him in this passage — ΕΥΡΙΚΑΜΕΝ ΤΟΝ ΜΕΣΣΙΑΝ in the painter's spelling, we have found the Messias. Andrew was the first of the Twelve to follow Christ, which is why the Church calls him Protokletos, the First-called, and the first thing he did was to go and find his brother.",
"File:Andrew (Kirillo-Belozersk).jpg":
 "A tall panel from the Kirillo-Belozersky monastery in the Russian North, painted at the end of the fifteenth century and credited to the school of Dionisy. Andrew stands barefoot with a scroll in his hand, turned a little to one side, as the apostles stand in the Deesis row of an iconostasis facing Christ at its centre. That is his whole story in this chapter: he was the Forerunner's disciple, turned at a word toward Christ, and brought his brother with him. St Bede: this is truly to find the Lord, to have fervent love for Him, together with a care for our brother's salvation.",
"File:Christos Kana Galilaias.jpg":
 "A fresco from the katholikon of Dionysiou on Mount Athos, 1547. The inscription across the top reads Ο ΧΣ ΕΝ ΚΑΝΑ ΤΗΣ ΓΑΛΙΛΑΙΑΣ … ΤΟ ΥΔΩΡ ΟΙΝΟΝ — Christ in Cana of Galilee making the water wine; the verb is damaged. The Mother of God stands at the left with her hand raised toward her Son; Christ sits at the head of the table and stretches his hand over it. The couple and the guests sit behind the table, and in front of it a servant, bent double, pours from a jar beside the stone waterpots. Toward the right end an old man in green holds up a glass: the governor of the feast, tasting. St John Chrysostom explains why it went to him: the guests might be thought drunken, but the attendants must have been sober, and the governor of the feast would of course be perfectly sober.",
"File:Cathedral (Monreale) - North arch of transept - Wedding at Cana.jpg":
 "A twelfth-century mosaic from the cathedral of Monreale in Sicily, worked by Byzantine craftsmen. The Latin inscription reads IESUS SEDENS AD NUPTIAS DE AQUA FECIT VINUM — Jesus, sitting at the wedding, made wine of water. The feast is laid out at a round table under a colonnade at the left; to the right, across the arch, the servants are at work among the tall jars. The mosaic gives more room to the servants than to the guests, as John does: it is they who fill the pots, they who draw, and they who know.",
"File:StNikita122general.jpg":
 "A fresco from the monastery church of St Nikita near Skopje, painted in the fourteenth century. The wedding is a long feast under an arcade, with the guests crowded along the table and servants at the ends; Christ sits at the left end of the table, and a small child stands in front of it. The painters of the Serbian court churches set the miracle among ordinary people at an ordinary meal, which is how Chrysostom reads it: they invited our Lord not as a great person, but merely as one they knew, one of the many.",
"File:Christ banish tradesmen from Temple (Monreale).jpg":
 "A twelfth-century mosaic from Monreale in Sicily. The same mosaic is shown in the Matthew reader, but its central detail is John's: only John says that Christ made a scourge of small cords, and here he raises it over his head in his right hand while his left sweeps across the money-changers' table, scattering the coins. The traders draw back under the Temple arcade; oxen and sheep are driven out at the foot of the picture, and a cage of doves hangs from a pole above them. John puts this at the first Passover of the ministry, and gives Christ's word to the dove-sellers — make not my Father's house an house of merchandise — and the sign he offers: Destroy this temple, and in three days I will raise it up.",
"File:Samaritan Woman Dionysiou.jpg":
 "A fresco from the katholikon of Dionysiou on Mount Athos, 1547. Christ sits on a rock to the left of the well, a scroll in his hand; the woman stands on the right with the rope still in her hand and her waterpot on the ground beside the well-head. Behind the hill the disciples come back from the city, where they had gone to buy food, and look over at the two of them; the city of Sychar stands on the right. The Church reads this Gospel on the fifth Sunday of Pascha and honours the woman as St Photini, an equal of the apostles, because she left her waterpot and went into the city to say, Come, see a man. A four-line inscription above the disciples is too worn in this photograph to read with confidence. St Augustine: He who asked to drink, however, out of the woman's vessel, thirsted for the woman's faith.",
"File:Photina of Protat.JPG":
 "A fresco in the Protaton church at Karyes on Mount Athos, painted about 1300 and credited on its Commons page to Manuel Panselinos, whose work at the Protaton is the high point of the Palaiologan school. Christ sits on the left with a scroll; the well between them is built as a square stone well-head; the woman stands at the right with her jug held down at her side, in front of the walls of the city. There are no disciples and no hill: the fresco keeps only the two of them and the well, which is what John's account keeps too until the woman runs off.",
"File:Jésus et la Samaritaine. Fresque parTheophanes le Crétois, Monastère de Stavronikita, Mont Athos, 16e siècle..jpg":
 "A fresco by Theophanes the Cretan at the Stavronikita monastery on Mount Athos, in the 1540s. The composition is the Dionysiou one reversed: the woman stands at the left holding a jug, Christ sits at the right with a scroll, and the well with its quatrefoil mouth stands between them, the rope coiled at its foot. The disciples appear over the hill behind with the town beyond. Theophanes and the Dionysiou painters worked from the same Athonite models within a few years of each other, which is why the two frescoes read almost as one.",
"File:Christ anв Samaritan woman (Monreale).jpg":
 "A twelfth-century mosaic from Monreale in Sicily, worked by Byzantine craftsmen. The Latin inscription reads XPS SEDENS IUXTA PUTEUM LOQUITUR CUM SAMARITANA — Christ, sitting beside the well, speaks with the Samaritan woman. Here the well has a wooden frame and a bucket on a rope, and the woman is drawing as he speaks: she holds the rope in her hand. Christ sits at the left with his hand raised in address. St John Chrysostom: he sat down because he was wearied, and to wait for the disciples.",
"File:Christos Iomenos Paralyton Dionysiou.jpg":
 "A fresco from the katholikon of Dionysiou on Mount Athos, 1547. The titulus, Ο ΧΣ ΙΩΜΕΝΟΣ ΤΟΝ ΠΑΡΑΛΥΤΟΝ, says only Christ healing the paralytic, but the painter has set the scene where John sets it: an arcade of arched bays at the right, with the sick lying on a long couch under it, and a round stone basin in front of Christ — the pool, with its porches. The healed man stands between them and lifts his bed above his head, doing the two things he was told: take up thy bed, and walk. St John Chrysostom says the bed was the proof: the man's limbs must have become quite sound and compact, to allow him to take up his bed. The Church reads this Gospel on the fourth Sunday of Pascha, the Sunday of the Paralytic.",
"File:Cathedral (Monreale) - Right wing transept - Healing the paralytic at Bethesda.jpg":
 "A twelfth-century mosaic from Monreale in Sicily. It names the place in John's own Latin: PROBATICA PISCINA, the sheep pool, and quotes the command, SURGE TOLLE GRABATUM ET AMBULA — rise, take up thy bed, and walk. It is the one image in this gallery that paints the angel: he comes down headlong into the water between the columns to trouble it, as the text says he did at a certain season. Christ stands at the left with the disciples, and at the right the healed man walks away with his bed on his back. St Bede: it is fitly described as a sheep pool. By sheep are meant people.",
"File:Jesus healing a paralytic in Bethesda - Sant'Apollinare Nuovo - Ravenna 2016.jpg":
 "A mosaic from the upper walls of Sant'Apollinare Nuovo in Ravenna, from the early sixth century — among the oldest surviving pictures of the Gospel miracles. There is no pool and no porch, only the end of the story: the man strides away carrying his bed on his back, and Christ, in purple, stands with a disciple and raises his hand after him. The early Church painted the miracle by its proof, as Chrysostom reads it: the bed on the shoulders of the man it had carried.",
"File:035 Sunday of the Paralytic Icon from Saint Paraskevi Church in Langadas.jpg":
 "A village icon from the church of St Paraskevi at Langadas in Greece, made before the twentieth century for the feast its name gives: the Sunday of the Paralytic, the fourth Sunday of Pascha. Christ comes with two disciples from the left. The healed man is painted twice: once still lying on his bed in the lower corner, and once standing in red with the bed lifted onto his shoulder, below the walled city of Jerusalem on the hill. It is a small, worn icon made for a parish to carry out on that one Sunday of the year.",
"File:Evlogesis Pente Arton Dionysiou.jpg":
 "A fresco from the katholikon of Dionysiou on Mount Athos, 1547, with the inscription Η ΕΥΛΟΓΗΣΙΣ ΤΩΝ ΠΕΝΤΕ ΑΡΤΩΝ — the blessing of the five loaves. Christ holds out the loaves with the two fishes laid on top of them; an apostle receives them in hands covered with his mantle, as the clergy receive the Gifts; others carry the bread on to the crowd seated on the hillside, and in the foreground stand the full baskets of fragments. The same fresco is shown in the Matthew reader, whose account of this miracle it shares. John adds details the others do not have: that it was near the Passover, that Philip was asked where bread could be bought, and that the loaves were barley and belonged to a boy. A child stands in the middle distance with his hand raised; whether the painter means the lad, the fresco does not say. St John Chrysostom: the Prophets received grace by measure, whereas Christ, working this by His own absolute power, produces a kind of super abundant result.",
"File:42 Mid-Pentecost Icon from Saint Paraskevi Church in Adam.jpg":
 "An icon from the church of St Paraskevi in the village of Adam in Greece, painted in 1858 by Athanasios Vasilikos Adaminos. The inscription reads Η ΜΕΣΟΠΕΝΤΗΚΟΣΤΗ — Mid-Pentecost, the feast the Church keeps on the twenty-fifth day after Pascha, halfway to Pentecost, with this Gospel: now about the midst of the feast Jesus went up into the temple, and taught. Christ sits at the centre between the columns of the Temple with an open book on his knee; the elders sit to either side, one holding out an open scroll, others with their hands raised. The feast's icon borrows the look of the boy Jesus among the doctors, but its Gospel is this one, and here he is painted grown. St Augustine on their wonder: no one could do this, who had not read the law; no one could read who had not learnt letters; and this raised their wonder.",
"File:Prepolovenie (Annunciation Cathedral in Moscow).jpg":
 "A sixteenth-century icon from the Cathedral of the Annunciation in the Moscow Kremlin, inscribed in Slavonic Преполовение — Mid-Pentecost. Christ sits enthroned at the centre of a semicircle of seated elders, under the gables and domes of the Temple, which the Russian painter has built as a city of churches. The icon is the same feast and the same Gospel as the Greek one beside it, painted in a darker, warmer key: the teachers gathered round the one who had never learned letters.",
"File:007 Mid-Pentecost Icon from Saint Paraskevi Church in Langadas.jpg":
 "A village icon from the church of St Paraskevi at Langadas in Greece, made before the twentieth century and much darkened. Christ sits high on a stepped throne with both arms spread over the elders below him, and a red cloth is draped across the top of the picture — the icon painter's sign that a scene takes place indoors, here in the Temple. The elders at either side turn up their faces to him.",
"File:Katakrinon Pornin Dionysiou.jpg":
 "A fresco from Dionysiou on Mount Athos, 1547, painted over a doorway, whose dark arch cuts into the foot of the picture. The inscription reads Ο ΧΣ ΜΗ ΚΑΤΑΚΡΙΝΩΝ ΤΗΝ ΠΟΡΝΗΝ — Christ not condemning the harlot. Christ stoops at the left and writes on the ground with his finger, and the painter has written out what the Gospel does not say he wrote: under his hand the letters run Ο ΑΝΑΜΑΡΤΗΤΟΣ ΒΑΛΕΤΩ ΛΙΘΟΝ ΕΠ' ΑΥΤΗΝ — let the sinless one cast a stone at her. The woman stands behind him; the scribes and Pharisees crowd the middle of the picture; at the right edge one of them is already walking out. St Augustine: let the sinner be punished, but not by sinners; the law carried into effect, but not by transgressors of the law.",
"File:Monreale (catedral) Woman Caught in Adultery.jpg":
 "A twelfth-century mosaic from Monreale in Sicily. Its Latin inscription begins IUDEI TEMPTANTES DOMINUM — the Jews tempting the Lord — which is John's own reason for the question: this they said, tempting him. Christ sits at the left and bends to write on the ground; the woman stands in front of a domed building with the accusers crowded behind her, still watching him. St Augustine on why he wrote: his bowing his head is an expression of humility, and the writing on the ground signifies that his law was written on the earth which bore fruit, not on the barren stone, as before.",
"File:Christos Iomenos Typhlon.jpg":
 "A fresco from the katholikon of Dionysiou on Mount Athos, 1547. The titulus is singular — Ο ΧΣ ΙΩΜΕΝΟΣ ΤΟΝ ΤΥΦΛΟΝ, Christ healing the blind man — and the man is painted twice, which is how an icon tells a story that happens in two places. In the middle Christ reaches to his eyes while the man stands with his hands open before him. On the right the same man, alone now, bends over a cross-shaped basin and lifts his hands to his face: Go, wash in the pool of Siloam. St John Chrysostom notes that Christ made the clay with spittle, not water, so that it should be plain the sight came from what proceeded from his mouth and not from the pool; and that he then sent him to wash, so that the cure should not seem to be the effect of the clay. The Church reads this Gospel on the sixth Sunday of Pascha, the Sunday of the Blind Man.",
"File:Cathedral (Monreale) - Right wing transept - Healing of the blind.jpg":
 "A twelfth-century mosaic from Monreale in Sicily. The Latin inscription names the pool and the miracle in John's terms: NATATORIA SILOE, the pool of Siloam, and IESUS CUM LUTO FACTO EX SPUTO APERUIT OCULOS CAECI NATI — Jesus with clay made of spittle opened the eyes of the man born blind. At the left Christ lays his hand on the man's eyes as he leans on his stick; at the right the same man crouches at a stream running down out of the rock and washes. The phrase caeci nati, born blind, is what separates this miracle from every other healing of the blind in the Gospels.",
"File:Christ Healing the Blind (Tzanes).png":
 "A Cretan icon by the priest Emmanuel Tzanes, dated 1686, with the inscription Η ΙΑΣΙΣ ΤΟΥ ΤΥΦΛΟΥ, the healing of the blind man. It tells the whole of John 9 in one panel. In the foreground Christ, among the crowd of apostles, touches the eyes of a man who leans on a stick with a gourd hanging at his waist. Behind, at the left, a small figure washes at a stone fountain — the pool of Siloam — and inside the open building at the centre stand men in debate, where the Pharisees will question the healed man and his parents and cast him out.",
"File:008 Sunday of the Blind Man Icon from Saint Paraskevi Church in Langadas.jpg":
 "A village icon from the church of St Paraskevi at Langadas in Greece, made before the twentieth century for the sixth Sunday of Pascha, the Sunday of the Blind Man. It is worn and darkened, but its one action is clear: Christ, with the apostles behind him, reaches out to touch the eyes of the young man in red who stands before him. The whole feast is gathered into the touch.",
"File:Egersis Lazarou Dionysiou.jpg":
 "A fresco from the katholikon of Dionysiou on Mount Athos, 1547, inscribed Η ΕΓΕΡΣΙΣ ΤΟΥ ΛΑΖΑΡΟΥ — the raising of Lazarus. It is the icon of Lazarus Saturday, the day before Palm Sunday, whose hymn says Christ raised Lazarus to confirm the common resurrection before his own Passion. Christ stands with the apostles behind him and stretches his hand toward the tomb; Lazarus stands upright in the dark mouth of the cave, wound in grave-clothes, with a halo; a young man unwinds the bands while another carries off the slab. The two sisters are at Christ's feet, one kneeling and one prostrate, and the Jews of Jerusalem crowd the hill between. St John Chrysostom: their hands take away the stone, their ears hear Christ's voice, their eyes see Lazarus come forth.",
"File:Lazarus Miracle Icon Sinai 12th century.jpg":
 "A twelfth-century Byzantine icon from the monastery of St Catherine at Sinai, probably one panel of a festal row. Lazarus stands in the doorway of a small arched tomb, white from head to foot in his grave-clothes; a man in red holds the loose end of the bands. The sisters lie at Christ's feet, and two young men at the right carry away the stone lid. Christ, holding a scroll, raises his hand in blessing toward the tomb.",
"File:Cathedral (Monreale) - Right wing transept - Rising of Lazarus.jpg":
 "A twelfth-century mosaic from Monreale in Sicily, inscribed RESUSCITATIO LAZARI — the raising of Lazarus. Lazarus stands bound in a tall arched tomb cut into the hill; one man lifts away the door-slab, another holds his mantle to his nose, and a sister lies prostrate at Christ's feet while the other kneels behind her. Christ stands at the head of the apostles with his hand out toward the tomb. St Augustine on the stone: the dead under the stone is the guilty under the Law, for the Law was graven on stone; take away the stone, proclaim grace.",
"File:RossanoGospelsFolio001rRaisingLazarus.jpg":
 "The first surviving leaf of the Rossano Gospels, a Greek Gospel book written in silver on purple parchment in the sixth century, one of the oldest illustrated Gospel books in existence. Across the top the whole story runs from left to right: Christ with the apostles, the sisters at his feet, the crowd, and Lazarus standing wrapped in the mouth of a rock tomb with a man in red beside him. Below, four prophets point up at the miracle, each above a line of his own prophecy — the Byzantine way of saying that the raising of Lazarus fulfilled what had been written.",
"File:Cathedral (Monreale) - Right wing transept - Entry into Jerusalem.jpg":
 "A twelfth-century mosaic from Monreale in Sicily, inscribed RAMOS PALMARUM — branches of palms, the words of John's own verse in Latin. Of the four Evangelists only John says the branches were of palm, and this mosaic is built round them. Christ rides side-saddle on the ass, blessing, a scroll in his hand; the apostles follow behind. In front of him a boy has climbed a palm tree and throws down branches, the elders come out of the gate of Jerusalem holding palms, and children spread their clothes under the ass's feet. St Augustine: the branches of palms are songs of praise, for the victory which our Lord was about to obtain by his death over death.",
"File:Hosios Loukas Crypt - Entry into Jerusalem 01.jpg":
 "A fresco in the crypt of the monastery of Hosios Loukas in Boeotia, painted in the eleventh century and much damaged. Christ rides a white ass up to the gate of Jerusalem, where the elders stand in a group to meet him; one apostle walks behind. Even with most of the lower half gone, the three parts the Church always paints are there: the Lord, the one who follows, and the city that comes out.",
"File:Entry into Jerusalem of Kirillo-Belozersky iconostasis (15th century, Russia).jpg":
 "A panel from the festal row of the iconostasis of the Kirillo-Belozersky monastery in the Russian North, 1497. Christ rides out from behind the hill with the apostles crowded after him; a tree stands in the middle with its branches cut; the people of Jerusalem wait at the right before the white city, and at the feet of the ass small children spread out their clothes. The painter keeps the Greek composition exactly and gives it the Northern palette.",
"File:Nipter Dionysiou.jpg":
 "A fresco from the katholikon of Dionysiou on Mount Athos, 1547, inscribed Ο ΝΙΠΤΗΡ — the washing. Christ stands at the left girded with the towel, the basin at his feet and the ewer on the floor behind him. Peter sits highest on the bench with one hand pressed to his head — Lord, not my feet only, but also my hands and my head — while Christ holds his foot and answers him with a raised hand. The other apostles sit round the table loosening their sandals and waiting their turn. St Augustine reads every movement as the Incarnation: he laid aside his garments, when, being in the form of God, he emptied himself; he girded himself with a towel, took upon him the form of a servant.",
"File:Feet washing (Nea Moni).jpg":
 "A detail of the eleventh-century mosaic in the katholikon of Nea Moni on Chios. Only two figures and a basin: Christ, girded with the towel, bends and takes Peter's foot in his hands; Peter, seated, lifts his hand to his head. The gold ground behind them has worn away in patches, and the stillness of the two faces is what is left. Chrysostom: see what humility he shows, not only in washing their feet, but in other things.",
"File:Christ washes apostles' feet (Monreale).jpg":
 "A twelfth-century mosaic from Monreale in Sicily, inscribed MANDATUM — the commandment, from Christ's words that same night, A new commandment I give unto you; it is the Latin Church's name for the rite. Christ bends over the basin with the towel spread in his hands; Peter sits above him with his hand at his head; the other apostles sit along the bench under the arcade, some already barefoot.",
"File:Washing the feets (1420s, Sergiev Posad).jpg":
 "A panel from the festal row of the iconostasis of the Trinity Cathedral at the Trinity-Sergius Lavra near Moscow, painted in the 1420s; its Commons page credits the workshop of Daniel Chorny. Christ stands at the left with the towel and basin, bent toward Peter; the apostles are gathered in a close group on the stepped bench before a tall building. The paint has flaked away across the top, but the gesture of the Master stooping to the disciple is intact.",
"File:Monreale-cattedrale-mosaik-abendmahl.JPG":
 "A twelfth-century mosaic from Monreale in Sicily, inscribed CENA DOMINI — the Supper of the Lord. The table is a long white cloth set with bread and bowls; the apostles sit behind it in a row, and Christ at the left end with the beloved disciple leaning on his breast. One figure is on the wrong side of the table: Judas, alone on the near side, reaching toward the dish. John's is the only Gospel that tells how the traitor was pointed out — He it is, to whom I shall give a sop, when I have dipped it — and the mosaic gives Judas the place that sets him apart from the others. St John Chrysostom: even if a partaking of the same table did not shame him, a partaking of the same bread might have.",
"File:Last Supper by Theophanes the Cretan.jpg":
 "A fresco by Theophanes the Cretan, from the middle of the sixteenth century, inscribed Ο ΔΕΙΠΝΟΣ Ο ΜΥΣΤΙΚΟΣ — the Mystical Supper, the name the Orthodox Church gives this night. Christ sits at the left end of an oval table; John leans against him; and in the middle one apostle in red stretches his arm right across the table toward the dish. That is Judas, painted in the act that gave him away: he that dippeth his hand with me in the dish. The rest sit round the table and turn to one another.",
"File:S. Apollinare Nuovo Last Supper.jpg":
 "A mosaic from the upper wall of Sant'Apollinare Nuovo in Ravenna, from the early sixth century. The table is the curved couch of a late Roman dinner: Christ, in purple, reclines at the left end, and the apostles lie in a crescent behind the cloth, with two great fish laid out on the dish before them. It is how the first Christian painters imagined this night, before the Byzantine composition with the beloved disciple and the reaching hand took its fixed form.",
"File:Christ the True Vine icon (Athens, 16th century).jpg":
 "A Cretan icon of the sixteenth century in Athens, inscribed Η ΑΜΠΕΛΟΣ — the Vine. A single vine rises from the ground at the foot of the panel; Christ sits enthroned where the trunk divides, and the twelve apostles sit in its branches, six to a side, holding their books and scrolls among the leaves and grapes. The book on Christ's knee opens with this chapter's first words, ΕΓΩ ΕΙΜΙ Η ΑΜΠΕΛΟΣ Η ΑΛΗΘΙΝΗ — I am the true vine. It is a picture of a saying, not of an event, and it paints the saying exactly: the branches grow out of him and have no root of their own. St Augustine: the vine and the branches are of the same nature.",
"File:Tree of Jesus Signed by Angelos.png":
 "A Cretan icon of the first half of the fifteenth century, signed at its foot ΧΕΙΡ ΑΓΓΕΛΟΥ — the hand of Angelos, the painter Angelos Akotantos, who fixed this type for the Cretan school. Christ appears half-length out of the vine with his arms spread along its branches, and the branches curl round into rings, each ring holding an apostle. The open book reads ΕΓΩ ΕΙΜΙ Η ΑΜΠΕΛΟΣ, ΥΜΕΙΣ ΤΑ ΚΛΗΜΑΤΑ — I am the vine, ye are the branches. The later Athens icon beside it is this design grown into a whole tree.",
"File:Kiss of Judas (mosaic in Nea Moni).jpg":
 "An eleventh-century mosaic in the katholikon of Nea Moni on Chios. The inscription across the top quotes St Luke, ΙΟΥΔΑ ΦΙΛΗΜΑΤΙ ΠΑΡΑΔΙΔΩΣ ΤΟΝ ΥΙΟΝ ΤΟΥ ΑΝΘΡΩΠΟΥ — Judas, betrayest thou the Son of man with a kiss? — and the heads of Christ and Judas, embracing at the left, are lost where the mosaic has fallen away. The kiss is not in John's account; the Church's icon of the betrayal gathers all four Gospels into one picture. What John adds is on the right: a grey-haired apostle holding a knife to the ear of a young man with a shield. Only John names them — Simon Peter having a sword drew it, and smote the high priest's servant, and cut off his right ear. The servant's name was Malchus. Over the crowd rise the torches John mentions. Blessed Theophylact: they carry torches and lanterns, to guard against Christ escaping in the dark.",
"File:Judas's Kiss mosaic in Sant'Apollinare Nuovo (Ravenna).jpg":
 "A mosaic from the upper wall of Sant'Apollinare Nuovo in Ravenna, from the early sixth century. Judas kisses Christ in the middle of the picture; at the left come the armed men with torches and spears; at the right stand the apostles, and one of them holds a sword. Christ, in purple, does not draw back. John tells it the other way round from the others: Jesus therefore, knowing all things that should come upon him, went forth, and said unto them, Whom seek ye?",
"File:Jesus before Pontius Pilate - Stavronikita monastery, Mt Athos - Theophanes of Crete, 16th c..jpg":
 "A fresco by Theophanes the Cretan at the Stavronikita monastery on Mount Athos, in the 1540s. Its Commons title calls it Christ before Pilate, but its painted inscription reads ΚΡΙΝΟΜΕΝΟΣ ΥΠΟ ΑΝΝΑ ΚΑΙ ΚΑΙΑΦΑ — being judged by Annas and Caiaphas. John is the only Evangelist who says Christ was taken to Annas first, father in law to Caiaphas, before being sent on bound to Caiaphas. Two elders sit enthroned side by side on the right; Christ stands before them at the left, a guard at his shoulder taking hold of him, soldiers behind; a lamp hangs from the ceiling. St Augustine on his answer to the officer who struck him: what can be truer, gentler, kinder, than this answer?",
"File:Ravenna, sant'apollinare nuovo, int., storie cristologiche, epoca di teodorico 07.1 rinnegamento di pietro.jpg":
 "A mosaic from Sant'Apollinare Nuovo in Ravenna, from the early sixth century. Two figures only: a woman standing in a doorway, pointing, and Peter before her with his hand raised in denial. It is John's version of the first denial exactly: then saith the damsel that kept the door unto Peter, Art not thou also one of this man's disciples? He saith, I am not. St John Chrysostom notes that it was John himself, known to the high priest, who spoke to her that kept the door, and brought in Peter.",
"File:Icon Peter's denial FULL.jpeg":
 "A Russian icon of about 1500 in four scenes, read from the top left. First the arrest in the garden: Judas kisses Christ, the soldiers crowd in with spears, and a man kneels at the lower left of that scene. Then Christ is led before the high priests, who sit at a table under a canopy. Below at the left is Peter in the courtyard: servants sit round a fire on the ground, and on a column above them stands the cock. The last scene shows Christ standing before a judge enthroned under a dome. The first three follow John 18 in order, and the fire is John's own detail: the servants and officers stood there, who had made a fire of coals; for it was cold: and Peter stood with them, and warmed himself.",
"File:Cathedral (Monreale) - Right wing transept - Before Pilate.jpg":
 "A twelfth-century mosaic from Monreale in Sicily, inscribed IHS DUCTUS EST ANTE PILATUM — Jesus was led before Pilate — and, over the governor's head, PILATUS. Pilate sits enthroned inside the colonnade of the judgment hall with a soldier standing behind him holding a sword; Christ stands outside it with a crowd of elders behind him, and his hand and Pilate's reach toward each other across the columns. The picture keeps a detail John alone records: the Jews would not go into the judgment hall, lest they should be defiled, so Pilate went out to them, and went in and out between them and his prisoner. St Augustine: they feared to be defiled by the judgment hall of a foreign prefect; to shed the blood of an innocent brother they feared not.",
"File:Kirillo-Belozersky iconostasis - Kremlin exhibition - Before Pilatus by shakko.jpg":
 "A panel from the Passion row of the iconostasis of the Kirillo-Belozersky monastery in the Russian North, 1497, photographed at an exhibition in the Moscow Kremlin. Christ stands alone at the left, very still; Pilate sits on a raised throne among his counsellors and the priests, who crowd round him and lean toward him. Of John's long dialogue between them the icon keeps the one fact beneath it all: one man stands, and the other sits in judgment on him.",
"File:Empaigmos Dionysiou.jpg":
 "A fresco from the katholikon of Dionysiou on Mount Athos, 1547, inscribed Ο ΤΟΥ ΧΡΙΣΤΟΥ ΕΜΠΑΙΓΜΟΣ — the mocking of Christ. He stands on a low block at the centre, facing out, in the purple robe with the crown of thorns on his head and a reed in his hand. The soldiers crowd round him: in front they kneel in mock homage, behind they blow trumpets, beat drums and strike cymbals. It is exactly the figure Pilate brought out: then came Jesus forth, wearing the crown of thorns, and the purple robe. And Pilate saith unto them, Behold the man! St Bede: though the soldiers did this in mockery, yet to us their acts have a meaning; by the crown of thorns is signified the taking of our sins upon him.",
"File:Mastigosis Dionysiou.jpg":
 "A fresco from Dionysiou on Mount Athos, 1547, inscribed Η ΜΑΣΤΙΓΩΣΙΣ — the scourging. Christ is bound to a column with his arms raised above his head, stripped to a loincloth; two men in red and green swing whips at him from either side. John gives the scourging one line, at the head of this chapter: then Pilate therefore took Jesus, and scourged him. St Augustine: Pilate seems to have done this for no reason but to satisfy the malice of the Jews with some punishment short of death.",
"File:Crucifixion, Early XIV Century, St Mary Perivleptos Church, Ohrid Icon Gallery.jpg":
 "A Byzantine icon of the early fourteenth century from the church of the Theotokos Peribleptos at Ohrid, now in the Ohrid icon gallery. It is the Crucifixion as John tells it and as the Church paints it: only two figures stand at the cross, the Mother of God on the left and the beloved disciple on the right, with the wall of Jerusalem behind them. The inscriptions name them — ΜΡ ΘΥ, Mother of God, and Ο ΑΓΙΟΣ ΙΩΑΝΝΗΣ Ο ΘΕΟΛΟΓΟΣ — and across the top runs Η ΣΤΑΥΡΩΣΙΣ, the Crucifixion. St Ambrose: none of the Evangelists hath told me this except John — how that from the cross whereon he hung, he called to his mother.",
"File:Crucifixion, II Half of XIII Century, St Mary Perivleptos Church, Ohrid Icon Gallery.jpg":
 "A Byzantine icon from the second half of the thirteenth century, also from the Peribleptos church at Ohrid. The same three figures as the icon beside it, painted a generation earlier: Christ on the cross with his head fallen on his shoulder, the Mother of God at the left with her hands raised toward him, and John at the right bowed in grief. Here too the cross stands on the rock over the dark cave with the skull, and an angel flies at each end of the beam.",
"File:Diamersis Himation Christou Dionysiou.jpg":
 "A fresco from Dionysiou on Mount Athos, 1547, inscribed Ο ΔΙΑΜΕΡΙΣΜΟΣ ΤΩΝ ΙΜΑΤΙΩΝ ΧΡΙΣΤΟΥ — the parting of Christ's garments. Three soldiers sit on the ground under the rock and handle the clothes spread across their knees. John is the Evangelist who tells this most exactly: they made four parts of his garments, to every soldier a part; and also his coat, which was without seam, woven from the top throughout, and for that they cast lots rather than tear it — that the scripture might be fulfilled, They parted my raiment among them, and for my vesture they did cast lots.",
"File:Great Lavra Monastery Katholikon Church Crucifixion, Theophanes the Cretan 1535.jpg":
 "A detail of the Crucifixion in the katholikon of the Great Lavra on Mount Athos, painted by Theophanes the Cretan in 1535. It shows the part of the scene that belongs to these verses. On the left a helmeted soldier thrusts a spear up into Christ's side: one of the soldiers with a spear pierced his side, and forthwith came there out blood and water. On the right a man in green lifts a sponge on a long reed and carries the bucket of vinegar: I thirst — they filled a spunge with vinegar, and put it upon hyssop, and put it to his mouth. Two angels fly beside the cross holding chalices. St John Chrysostom: when you approach the awful cup, approach it as if you were about to drink out of Christ's side.",
"File:Cathedral (Monreale) - Left wing transept - West wall - Crucifixion.jpg":
 "A twelfth-century mosaic from Monreale in Sicily, inscribed CRUCIFIXIO IESU CHRISTI, with INRI on the title board — the initials of Jesus of Nazareth, King of the Jews, in the Latin that John says was one of its three languages. Christ hangs on the cross with angels above the beam; the Mother of God and the other women stand at the left, John at the right, and beside him a soldier with a spear, the one who pierced his side. Chrysostom: the title was written in three languages, that all might read it.",
"File:Apokalthelosis Dionysiou.jpg":
 "A fresco from the katholikon of Dionysiou on Mount Athos, 1547, inscribed Η ΑΠΟΚΑΘΗΛΩΣΙΣ — the unnailing, the taking down from the cross. It paints the first half of John's verses: after this Joseph of Arimathaea besought Pilate that he might take away the body of Jesus; there came also Nicodemus. The old man holding the body under the arms as it comes down is Joseph; the Mother of God takes her Son's face against her own; John stands bowed with his hand at his cheek; at the foot of the cross a kneeling man draws the nails from the feet with pincers, the tool basket beside him — Nicodemus in the Church's reading. The women stand at the left. St John Chrysostom: Joseph was a person of rank, and known to Pilate; so he went to him, and the favour was granted.",
"File:Cathedral (Monreale) - Left wing transept - North wall - Entombment.jpg":
 "A twelfth-century mosaic from Monreale in Sicily. Its inscription, where it can be seen, reads CORP(US) XP(ISTI) PON(I)TUR ... IN SEPULCRO — the body of Christ is laid in the tomb. The body, wound in white linen, is carried toward the arched door of a tomb cut in the hill; the Mother of God bends over the head, and angels hover above. At the foot of the scene stand small jars — the spices Nicodemus brought: a mixture of myrrh and aloes, about an hundred pound weight. St Bede: then took they the body of Jesus, and wound it in linen clothes with the spices, as the manner of the Jews is to bury.",
"File:Kirillo-Belozersky iconostasis 18 - Entombment.jpg":
 "A panel from the festal row of the Kirillo-Belozersky iconostasis in the Russian North, 1497. The body of Christ lies wound in white on the long slab of the tomb, under the empty cross with two angels; the Mother of God bends her face to his, the women stand behind with their hands raised, and at the right Joseph and Nicodemus stoop at the feet. It is the Russian form of the Epitaphios: the whole Church gathered round the body laid in the garden tomb.",
"File:Etesatou Ioseph Somatou Christou.jpg":
 "A fresco from Dionysiou on Mount Athos, 1547, inscribed ΗΤΗΣΑΤΟ ΙΩΣΗΦ ΤΟ ΣΩΜΑ ΤΟΥ ΙΗΣΟΥ — Joseph asked for the body of Jesus. Pilate sits enthroned in red with a crown, a soldier behind him; Joseph, an old man with a halo, stands before him with his hands held out. It is the first act of the burial in all four Gospels, and the verse this passage begins with: Joseph of Arimathaea besought Pilate that he might take away the body of Jesus: and Pilate gave him leave.",
"File:Mnemeion Christou Dionysiou.jpg":
 "A fresco from the katholikon of Dionysiou on Mount Athos, 1547. The inscription at the top left is John's own sentence: Ο ΔΕ ΠΕΤΡΟΣ ΚΑΙ ΙΩ(ΑΝΝΗΣ) ΕΔΡΑΜΟΝ ΕΠΙ ΤΟ ΜΝΗΜΕΙΟΝ — Peter and John ran to the tomb. The painter follows the order of the verses. John, the younger and beardless, has come first and stays behind the rock looking on; Peter, grey-bearded, has come up after him and stands over the open sepulchre with his hands spread. Inside it, under the words Ο ΑΓΙΟΣ ΤΑΦΟΣ, the holy tomb, lie the linen grave-clothes still bound in their bands, and at the head end, apart from them, the napkin. There is no stone, no angel and no guard in the picture: it shows only what the two disciples saw. Chrysostom reads that sight as the proof: had anyone carried the body away, they would not have stripped it, nor stopped to wrap the napkin and lay it in a place by itself.",
"File:Emphania Soteros Dionysiou.jpg":
 "A fresco from the katholikon of Dionysiou on Mount Athos, 1547. The inscription across the top reads Η ΜΕΤΑ ΤΗΝ ΕΓΕΡΣΙΝ ΠΡΟΣ ΤΗΝ ΜΑΓΔΑΛΗΝΗΝ ΜΑΡΙΑΝ ΤΟΥ ΣΩΤΗΡΟΣ ΕΜΦΑΝΕΙΑ — the appearing of the Saviour to Mary Magdalene after the Resurrection. The painter has written the dialogue into the picture. Beside Mary, kneeling with her hands stretched out, is her word ΡΑΒΒΟΥΝΙ; beside Christ, standing with a scroll and turning his hand away, is his ΜΗ ΜΟΥ ΑΠΤΟΥ, Touch me not. On the rock between them is her first question, when she took him for the gardener: ΚΥΡΙΕ, ΕΙ ΣΥ ΕΒΑΣΤΑΣΑΣ ΑΥΤΟΝ, ΕΙΠΕ ΜΟΙ ΠΟΥ ΕΘΗΚΑΣ ΑΥΤΟΝ, ΚΑΓΩ ΑΥΤΟΝ ΑΡΩ — Sir, if thou have borne him hence, tell me where thou hast laid him, and I will take him away. At the left stands the empty tomb, labelled Ο ΑΓΙΟΣ ΤΑΦΟΣ. St Gregory: she loved and doubted: she saw, and did not recognise him.",
"File:Noli me tangere (16th c., Cretan).jpg":
 "A sixteenth-century Cretan icon. Mary kneels in red at the left before the open tomb, reaching toward Christ; he stands above her and holds his hand out over her head, and a tree grows from the rock between them — the garden of John's account: in the place where he was crucified there was a garden, and in the garden a new sepulchre. A painted inscription at her shoulder records the words that pass between them.",
"File:Touch Me Not (Noli me tangere), Lambardos Emmanuel, Municipal Gallery of Corfu, 04.jpg":
 "An icon by the Cretan painter Emmanuel Lambardos, in the Municipal Gallery of Corfu, with a rounded top. The composition is the same as the Cretan icon beside it: Mary kneeling in red before the open tomb, where the grave-clothes lie, Christ above her with his hand extended, a tree between them, and the rays of heaven breaking in at the top. A column of painted text between them gives her words and his.",
"File:Psilapheses Thoma Dionysiou.jpg":
 "A fresco from the katholikon of Dionysiou on Mount Athos, 1547, inscribed Η ΨΗΛΑΦΗΣΙΣ ΤΟΥ ΘΩΜΑ — the touching of Thomas, the name the Church gives this feast on the Sunday after Pascha. Christ stands in front of a closed door, the doors being shut, and lifts his right arm to bare the wound in his side; Thomas, young and beardless in a red cloak, stretches out his hand to it. The other apostles stand in two groups under the arches, Peter at the front of the right-hand group. St Gregory: our Lord gave that flesh to be touched which he had introduced through shut doors — incorruptible, and yet palpable. St Augustine: Thomas saw and touched the man, and confessed the God whom he neither saw nor touched: My Lord and my God.",
"File:Incredulity of Saint Thomas,, Early XIV Century, St Mary Perivleptos Church, Ohrid Icon Gallery.jpg":
 "A Byzantine icon of the early fourteenth century from the Peribleptos church at Ohrid. Christ stands framed in a closed double door under a curtained canopy, lifting his arm to show the wound in his side; Thomas bends forward from the left and reaches to it; the other apostles stand in two close groups on either side. The shut door behind Christ is the one fixed element of this icon in every version: it is how the painters show that the Lord who is touched is the one who came in with the doors shut.",
"File:Уверение Фомы 1499 1500 Дионисий.jpg":
 "An icon of 1499–1500 by the Russian master Dionisy, from the festal row of the iconostasis of the Ferapontov monastery. Its Russian name, Уверение Фомы, means the assurance of Thomas: the Church calls the feast not his doubting but his coming to believe. Christ stands on a step before a closed door with his garment drawn back from his side; Thomas, in red, bends and reaches to it; the apostles stand to either side in Dionisy's tall, pale figures.",
"File:Kirillo-Belozersky iconostasis 21 - Doubting Thomas.jpg":
 "A panel from the festal row of the Kirillo-Belozersky iconostasis in the Russian North, 1497, painted two or three years before Dionisy's version of the same subject. Christ raises his arm and bares his side; Thomas, in green, stoops almost double to reach it; the apostles stand between the tall buildings that mark the house where they were gathered.",
"File:Evresete Dionysiou.jpg":
 "A fresco from the katholikon of Dionysiou on Mount Athos, 1547. Its inscription quotes the command: …ΕΙΣ ΤΑ ΔΕΞΙΑ ΜΕΡΗ ΤΟΥ ΠΛΟΙΟΥ ΤΟ ΔΙΚΤΥΟΝ ΚΑΙ ΕΥΡΗΣΕΤΕ — cast the net on the right side of the ship, and ye shall find. The apostles in the boat haul the net, heavy with fish; one of them points to the figure on the shore; and Peter, stripped to the waist, has thrown himself into the water and swims toward Christ, who stands at the right. On the shore the painter has put exactly what John says they found: a fire of coals, a fish laid on it, and a loaf of bread. The lower right of the fresco is hidden in this photograph by the carved woodwork standing in front of it. St John Chrysostom: he no longer works upon already existing materials, but in a still more wonderful way.",
"File:Cathedral (Monreale) - Left wing transept - Miraculous catch of fish.jpg":
 "A twelfth-century mosaic from Monreale in Sicily. The Latin inscription reads PETRO MERGENTE SE IN MARE … TRAHENTIBUS DISCIPULIS PLENUM RETE — Peter plunging into the sea, the disciples drawing the full net. Christ stands on the shore at the left beside a small fire with a fish on it; two apostles in the boat haul the bulging net; Peter swims across the waves toward him with his arms reaching out. The mosaic keeps all three of John's details: the net that does not break, the disciple who cannot wait, and the meal already made.",
"File:Miracle of Christ at the Sea of Tiberias, GRACANICA 1 080A9396.jpg":
 "A fresco in the monastery church of Gračanica in Kosovo, painted in the early fourteenth century and much worn. The boat with its sail rides the grey water, the apostles bending to the net full of fish at the stern; a figure in the water swims toward the shore, where Christ stands at the right edge of the picture. The loss of paint has taken the faces, but not the composition, which is the one every Byzantine painter of this scene used.",
};
