// Positioned markers: [label, explanation, top%, left%]. Coordinates are read off a 10% grid
// over src/img/<key>.webp and checked by drawing them back (BOOK=john python3 src/tools/overlay.py).
// Keep every coordinate inside 9–92; assemble.js clamps outside that.
module.exports={
"File:John the Evangelist and Prochorus by E.Lambardos (1602).jpg":[
 ["The inscription", "Ο ΑΓ(ΙΟΣ) ΙΩ(ΑΝΝΗΣ) Ο ΘΕΟΛΟΓΟΣ — St John the Theologian. Of the four Evangelists only John is called by that name, because only his Gospel begins with God before the world, and not with a birth or a genealogy.", "9%", "45%"],
 ["The ray from heaven", "A segment of heaven in the corner sends a ray down into the cave toward John's head. What he says does not come out of his own memory: it is given from above.", "20%", "24%"],
 ["John listening", "He does not write. He has turned his head away from the desk toward the ray, with his hand raised, as one who is listening. The old man who leaned on the Lord's breast at supper is painted receiving.", "44%", "36%"],
 ["Prochoros writing", "Prochoros, one of the seven deacons of the Acts, whom tradition makes John's disciple and scribe, bends over the page and writes. The icon puts the Gospel's first reader and its first copyist in the same frame.", "66%", "62%"],
 ["The cave of Patmos", "The two sit in the dark mouth of a cave. The Church's tradition places John on the island of Patmos, where he says he was for the word of God, and paints him there writing both his Revelation and his Gospel.", "35%", "80%"],
 ["The painter's signature", "Along the foot runs the signature, ΧΕΙΡ ΕΜΜΑΝΟΥΗΛ ΤΟΥ ΛΑΜΠΑΡΔΟΥ — the hand of Emmanuel Lambardos — with the year. Cretan painters signed as craftsmen, not as authors: the hand is named, not the vision.", "92%", "50%"],
],
"File:049 Saint John the Baptist Icon 2 from Saint Paraskevi Church in Langadas.jpg":[
 ["The inscription", "Ο ΑΓΙΟΣ ΙΩΑΝΝΗΣ, and after it in a smaller, fainter hand ο Βαγγελιστής — the Evangelist. The painted name overrules the file name, which calls this icon the Baptist.", "10%", "50%"],
 ["John, old and writing", "The Church paints the Evangelist as an old man: he wrote his Gospel last of the four, when the others had been written. He sits at his desk with the pen at the page.", "38%", "47%"],
 ["The eagle on the desk", "A haloed eagle stands beside the book. In Greek icons of this age it is the sign of John among the four living creatures of Ezekiel's vision and of the Apocalypse — the one that flies highest, as his Gospel begins above time, with the Word who was in the beginning with God.", "46%", "80%"],
 ["The pen at the page", "His hand is at the page: the icon's subject is the act of writing the Gospel down, not a scene from it.", "52%", "60%"],
],
"File:Prodromos Didaskon Ioudaious Dionysiou.jpg":[
 ["The inscription", "Ο ΠΡΟΔΡΟΜΟΣ ΔΙΔΑΣΚΩΝ ΤΟΥΣ ΙΟΥΔΑΙΟΥΣ — the Forerunner teaching the Jews.", "9%", "35%"],
 ["His hand raised", "He speaks with his right hand up. In John's account everything he says points away from himself: I am not the Christ; there standeth one among you, whom ye know not.", "20%", "33%"],
 ["The staff and the cross", "He carries a tall reed staff ending in a cross. The Forerunner's cross in icons is the sign of the One he is sent to point out.", "10%", "56%"],
 ["The envoys from Jerusalem", "The elders at his right are the kind of men John says were sent: priests and Levites from Jerusalem. St Augustine: they had doubts whether it might not be the Christ, who was baptizing, which doubts however they were afraid to profess openly.", "35%", "20%"],
 ["The soldiers", "The armed men at his left are not in John's Gospel. They are from St Luke, where soldiers too come to be baptized and ask, What shall we do? The fresco paints all his hearers together.", "40%", "82%"],
 ["The garment of hair", "He is barefoot and clothed in camel's hair, as the Gospels describe him. He is sent from the desert, not from the Temple, though he was a priest's son.", "60%", "45%"],
],
"File:Αμφιπρόσωπη εικόνα με τον Άγιο Γεώργιο και τον Άγιο Ανδρέα Β΄ μισό 12ου αι. - Α΄ μισό 18ου αι. Βέροια, Ιερός ναός Αγίου Ανδρέα 2.jpg":[
 ["The scroll", "ΕΥΡΙΚΑΜΕΝ ΤΟΝ ΜΕΣΣΙΑΝ — we have found the Messias, John 1:41. St John Chrysostom: this exclamation, We have found, expresses a longing for His coming, turned to exultation, now that He was really come.", "88%", "55%"],
 ["The inscription", "Ο ΑΓΙΟΣ ΑΝΔΡΕΑΣ, split to either side of the halo. The Church keeps his feast on the 30th of November.", "36%", "84%"],
 ["The First-called", "Andrew is painted with the thick, disordered grey hair and beard that mark him in every Orthodox icon. He was a disciple of the Forerunner before he was Christ's, and followed Jesus the moment John pointed him out: Behold the Lamb of God.", "30%", "50%"],
],
"File:Christos Kana Galilaias.jpg":[
 ["The inscription", "Ο ΧΣ ΕΝ ΚΑΝΑ ΤΗΣ ΓΑΛΙΛΑΙΑΣ … ΤΟ ΥΔΩΡ ΟΙΝΟΝ — Christ in Cana of Galilee making the water wine.", "9%", "55%"],
 ["The Mother of God", "She stands and turns to her Son: They have no wine. Then she tells the servants, Whatsoever he saith unto you, do it — the last words the Gospels give her. St John Chrysostom: he did what his mother told him, in order to show plainly, that he was not under subjection to the hour.", "25%", "13%"],
 ["Christ's hand over the feast", "He sits at the head and reaches his hand out over the table. He does not touch the water; he tells the servants to fill the pots and draw, and the miracle is done in the drawing.", "45%", "32%"],
 ["The stone waterpots", "Six waterpots of stone, after the manner of the purifying of the Jews. Chrysostom: the Evangelist says so expressly, to show that those vessels were never used to hold wine, and no one could say a thin wine had been made from the dregs.", "82%", "35%"],
 ["The servant drawing", "The servant bends and pours. They filled them up to the brim; and the ruler of the feast knew not whence it was: but the servants which drew the water knew.", "63%", "53%"],
 ["The governor of the feast", "The old man in green toward the end of the table holds up a glass. Thou hast kept the good wine until now — the witness is the one man at the table who did not see it done.", "38%", "73%"],
 ["The newly married", "The figure crowned at the centre of the table is one of the couple: the Orthodox marriage service crowns both bride and groom, and reads this Gospel. Chrysostom: he who disdained not to take upon Him the form of a servant, disdained not to come to the marriage of servants.", "28%", "60%"],
],
"File:Christ banish tradesmen from Temple (Monreale).jpg":[
 ["The scourge of cords", "He raises the whip over his head. When he had made a scourge of small cords, he drove them all out of the temple — John alone records the scourge.", "28%", "14%"],
 ["Christ", "He strides into the traders with his mantle flying. His disciples remembered that it was written, The zeal of thine house hath eaten me up.", "42%", "30%"],
 ["The overturned table", "His hand sweeps the money-changers' table and the coins scatter over it. He poured out the changers' money, and overthrew the tables.", "72%", "52%"],
 ["The cage of doves", "A cage hangs from a pole over the traders' heads. To them that sold doves he said, Take these things hence; make not my Father's house an house of merchandise.", "30%", "68%"],
 ["The traders", "The sellers shrink back under the arcade with their hands raised.", "45%", "62%"],
 ["The oxen and sheep", "At the foot the animals are driven out. He drove them all out of the temple, and the sheep, and the oxen.", "85%", "88%"],
 ["The Temple arcade", "The arches and columns are the Temple's porticoes. Destroy this temple, and in three days I will raise it up. But he spake of the temple of his body.", "14%", "42%"],
],
"File:Samaritan Woman Dionysiou.jpg":[
 ["Christ sitting on the rock", "Jesus therefore, being wearied with his journey, sat thus on the well. St John Chrysostom: not on a seat, or a couch, but on the first place He saw — upon the ground. St Augustine: strong, because in the beginning was the Word; weak, because the Word was made flesh.", "50%", "26%"],
 ["The well of Jacob", "The well-head stands between them, its mouth dark. The woman says it is deep and that Jacob gave it; Christ offers water of which whosoever drinketh shall never thirst.", "62%", "49%"],
 ["The waterpot", "Her jug stands on the ground at the well. It is the one object the Gospel follows after the conversation: she left her waterpot, and went her way into the city.", "78%", "64%"],
 ["The woman with the rope", "She holds the rope she came to draw with; it trails down to the ground. Sir, thou hast nothing to draw with, and the well is deep. The Church calls her St Photini, the enlightened one.", "48%", "70%"],
 ["The disciples returning", "They come over the hill from the town, where they had gone to buy meat. John says they marvelled that he talked with the woman: yet no man said, What seekest thou?", "26%", "49%"],
 ["Sychar", "The city on the right is Sychar in Samaria, where she will go and bring the townspeople out to him.", "20%", "88%"],
],
"File:Christos Iomenos Paralyton Dionysiou.jpg":[
 ["The porches", "The arcade at the right has a row of arched bays: a pool, which is called in the Hebrew tongue Bethesda, having five porches. St Augustine reads the five porches as the five books of Moses, which showed the sick their sickness but could not heal it.", "22%", "72%"],
 ["The sick waiting", "Under the porches the sick lie side by side on a long couch — in these lay a great multitude of impotent folk, of blind, halt, withered, waiting for the moving of the water. Of all of them Christ heals one.", "50%", "82%"],
 ["The pool", "The round stone basin in front of Christ is the pool. An angel troubled the water at a certain season and the first to step in was healed; the man had no one to put him in, and he was not healed by the water at all.", "64%", "39%"],
 ["The man carrying his bed", "Rise, take up thy bed, and walk. Chrysostom: He not only heals, but bids him carry his bed also. This was to show the cure was really miraculous, and not a mere effect of the imagination.", "38%", "52%"],
 ["The word of Christ", "Christ raises his hand toward the man. He asked first, Wilt thou be made whole? — and Chrysostom says it was asked not for his own information but to bring to light the great patience of a man who had waited thirty and eight years.", "42%", "33%"],
 ["The titulus", "Ο ΧΣ ΙΩΜΕΝΟΣ ΤΟΝ ΠΑΡΑΛΥΤΟΝ — Christ healing the paralytic. The words do not name the place; the porches and the pool do.", "9%", "45%"],
 ["The disciples", "They stand behind Christ in a close group. John does not mention them at the pool; the painter gives Christ his usual company.", "35%", "12%"],
],
"File:Evlogesis Pente Arton Dionysiou.jpg":[
 ["The inscription", "Η ΕΥΛΟΓΗΣΙΣ ΤΩΝ ΠΕΝΤΕ ΑΡΤΩΝ — the blessing of the five loaves.", "9%", "52%"],
 ["The loaves and the two fishes", "Christ holds out the bread with the two small fishes lying on it. Blessed Theophylact: Andrew is in the same perplexity that Philip is; only he has rather higher notions of our Lord — There is a lad here, which hath five barley loaves, and two small fishes: but what are they among so many?", "35%", "26%"],
 ["Veiled hands", "The apostle receives the bread in hands covered by his mantle, the way the Church receives what is holy. Jesus took the loaves; and when he had given thanks, he distributed to the disciples: the verbs of the Mystical Supper.", "46%", "42%"],
 ["The multitude on the grass", "The crowd sits on the green hillside. Now there was much grass in the place — Blessed Theophylact notes it was the time of the Passover, the first month of the spring.", "22%", "65%"],
 ["A child in the crowd", "A small figure in red stands among them with his arm raised. Only John says the loaves came from a lad; the painter may mean him, but nothing in the fresco says so.", "48%", "80%"],
 ["The baskets of fragments", "Gather up the fragments that remain, that nothing be lost; and they filled twelve baskets. St Augustine: the fragments are the deeper truths the multitude cannot take in, entrusted to the Twelve to teach afterwards.", "85%", "31%"],
],
"File:42 Mid-Pentecost Icon from Saint Paraskevi Church in Adam.jpg":[
 ["The inscription", "Η ΜΕΣΟΠΕΝΤΗΚΟΣΤΗ — Mid-Pentecost. The feast falls on the Wednesday of the fourth week of Pascha and takes its Gospel from this chapter: about the midst of the feast.", "16%", "58%"],
 ["Christ teaching from the book", "He sits in the Temple with the book open on his knee. My doctrine is not mine, but his that sent me. St John Chrysostom: that he says, Is not mine own, shows very strongly that his doctrine and the Father's are one.", "55%", "47%"],
 ["The scroll of the Law", "The elder at the left holds out an open scroll. Christ's argument in this passage is from the Law itself: Did not Moses give you the law, and yet none of you keepeth the law?", "62%", "22%"],
 ["The elders marvelling", "The teachers turn toward him with their hands raised. How knoweth this man letters, having never learned? Chrysostom: see how perverse they are even in their admiration. It is not his doctrine they admire, but another thing altogether.", "42%", "74%"],
 ["The Temple", "The columns and the arched niche behind mark the place: he went up into the Temple and taught openly, though he had come up to the feast in secret.", "22%", "33%"],
],
"File:Katakrinon Pornin Dionysiou.jpg":[
 ["The inscription", "Ο ΧΣ ΜΗ ΚΑΤΑΚΡΙΝΩΝ ΤΗΝ ΠΟΡΝΗΝ — Christ not condemning the harlot. The fresco is named for his last words to her: Neither do I condemn thee: go, and sin no more.", "9%", "60%"],
 ["Christ stooping to write", "Jesus stooped down, and with his finger wrote on the ground, as though he heard them not. St Bede: his writing with his finger on the ground perhaps showed, that it was he who had written the law on stone.", "60%", "30%"],
 ["The words on the ground", "Beneath his finger the painter has written Ο ΑΝΑΜΑΡΤΗΤΟΣ ΒΑΛΕΤΩ ΛΙΘΟΝ ΕΠ' ΑΥΤΗΝ — the saying of verse 7. The Gospel does not tell us what he wrote; the fresco writes what he said.", "72%", "34%"],
 ["The woman", "She stands apart at the left, in red, her hand raised. They set her in the midst; when the others had gone, Jesus was left alone, and the woman standing in the midst. St Augustine: there were left however two, the pitiable, and the pitiful.", "32%", "12%"],
 ["The scribes and Pharisees", "The accusers crowd the middle of the fresco, some still pointing, some turning to look at one another. This they said, tempting him, that they might have to accuse him.", "40%", "52%"],
 ["One going out", "At the right edge one of them is walking out of the picture. They which heard it, being convicted by their own conscience, went out one by one, beginning at the eldest, even unto the last.", "48%", "91%"],
],
"File:Christos Iomenos Typhlon.jpg":[
 ["The titulus", "Ο ΧΣ ΙΩΜΕΝΟΣ ΤΟΝ ΤΥΦΛΟΝ — Christ healing the blind man, singular. It is one man, blind from his birth.", "9%", "50%"],
 ["The hand at his eyes", "Christ reaches to the man's face: he spat on the ground, and made clay of the spittle, and anointed the eyes. Chrysostom: he wished to show that he was the Creator, who in the beginning used clay for the formation of man.", "42%", "45%"],
 ["The walking stick", "A stick stands upright between Christ and the man, the stick of someone who has never seen the road. It is still in the frame after the anointing: he does not yet see, and must first go and wash.", "72%", "43%"],
 ["The man washing", "At the right the same man bends his face to the water — he went his way therefore, and washed, and came seeing. He is alone: Christ is not with him at the pool.", "52%", "80%"],
 ["The pool of Siloam", "The basin is shaped as a cross. John gives the name and its meaning, Siloam, which is by interpretation, Sent. St Augustine reads the washing as baptism in the One who was sent: the man was anointed as a catechumen and enlightened only when he had washed.", "73%", "85%"],
 ["The disciples", "They stand behind Christ in a block. It was they who asked, Who did sin, this man, or his parents, that he was born blind? — Neither, but that the works of God should be made manifest in him.", "36%", "12%"],
],
"File:Egersis Lazarou Dionysiou.jpg":[
 ["The inscription", "Η ΕΓΕΡΣΙΣ ΤΟΥ ΛΑΖΑΡΟΥ — the raising of Lazarus.", "9%", "52%"],
 ["Christ's word", "His hand is stretched out toward the tomb: Lazarus, come forth. St John Chrysostom: he does not say, Arise, but, Come forth, speaking to the dead as if he were alive. His words show humility, his acts power.", "42%", "46%"],
 ["Lazarus bound", "He stands in the cave still wound in the bands, his face bound about with a napkin. Chrysostom: he came forth bound, that none might suspect that he was a mere phantom; and this very fact of coming forth bound was itself a miracle.", "38%", "82%"],
 ["Loose him", "A young man unwinds the grave-clothes. Jesus saith unto them, Loose him, and let him go — Chrysostom: that by going near and touching him they might be certain he was the very person.", "62%", "64%"],
 ["The stone taken away", "A man bends under the slab of the tomb and carries it off. Chrysostom asks why Christ did not move the stone himself, and answers: in order that the miracle might take place in the sight of all.", "75%", "84%"],
 ["Martha and Mary", "The sisters are at his feet, one kneeling and one lying prostrate. Lord, if thou hadst been here, my brother had not died.", "80%", "50%"],
 ["The Jews who came to mourn", "The crowd from Jerusalem fills the hill behind. Many of the Jews which came to Mary, and had seen the things which Jesus did, believed on him — and some went their ways to the Pharisees.", "28%", "58%"],
],
"File:Cathedral (Monreale) - Right wing transept - Entry into Jerusalem.jpg":[
 ["The inscription", "RAMOS PALMARUM — branches of palm trees. John alone names the tree: took branches of palm trees, and went forth to meet him.", "11%", "30%"],
 ["Christ on the ass", "He rides sitting sideways, blessing with one hand and holding a scroll. St John Chrysostom: he did not enter at the head of an army, but simply riding on an ass. Behold, thy King cometh, sitting on an ass's colt.", "40%", "33%"],
 ["The boy in the palm tree", "A child sits in the top of the palm and cuts the branches, and two of them are falling through the air. It is the detail that every Orthodox icon of the feast keeps.", "18%", "53%"],
 ["The people of Jerusalem", "The elders come out of the city gate with palms in their hands. In John the crowd goes out from Jerusalem to meet him, because they had heard he raised Lazarus: for this cause the people also met him.", "50%", "73%"],
 ["Clothes spread in the way", "Children bend and spread their garments under the ass's feet, as a road is laid before a king.", "85%", "68%"],
 ["The disciples following", "The apostles walk behind. These things understood not his disciples at the first: but when Jesus was glorified, then remembered they that these things were written of him.", "38%", "17%"],
 ["The gate of Jerusalem", "The city is a tall gate-tower at the right, crowded with faces. The feast is the Sunday before Pascha, and the Passion begins inside these walls.", "25%", "88%"],
],
"File:Nipter Dionysiou.jpg":[
 ["The inscription", "Ο ΝΙΠΤΗΡ — the washing. The same word names the service the Church performs on Holy Thursday, when a bishop washes the feet of twelve of his clergy.", "9%", "45%"],
 ["The towel", "Christ is girded with the towel. He riseth from supper, and laid aside his garments; and took a towel, and girded himself. St John Chrysostom: it was a thing worthy of him who came from God and went to God, to trample upon all pride.", "50%", "20%"],
 ["The basin", "After that he poureth water into a bason. The basin stands on its foot at the edge of the bench, below Peter.", "66%", "33%"],
 ["Peter's hand at his head", "Peter presses his hand to his head: first Thou shalt never wash my feet, and then, when told he would have no part with Christ, Lord, not my feet only, but also my hands and my head.", "25%", "42%"],
 ["Christ answering", "Christ holds Peter's foot and raises his other hand to speak. What I do thou knowest not now; but thou shalt know hereafter. If I wash thee not, thou hast no part with me.", "38%", "29%"],
 ["The others waiting", "Around the table the other apostles bend to untie their sandals. Chrysostom: all the rest put out their feet, certain that so great a one would not want to wash them without reason.", "78%", "57%"],
 ["The ewer", "The water jug stands on the floor. If I then, your Lord and Master, have washed your feet; ye also ought to wash one another's feet.", "86%", "9%"],
],
"File:Monreale-cattedrale-mosaik-abendmahl.JPG":[
 ["The inscription", "CENA DOMINI — the Lord's Supper. John does not tell the institution of the Eucharist at all; his account of this night is the washing of the feet, the sop and the long discourse.", "18%", "52%"],
 ["Christ at the head", "He sits at the end of the table. He was troubled in spirit, and testified: Verily, verily, I say unto you, that one of you shall betray me.", "52%", "25%"],
 ["John on his breast", "The beloved disciple leans against him. St Bede: that he lay in the bosom, and upon the breast, was not only an evidence of present love, but also a sign of the future, of those new and mysterious doctrines which he was afterwards commissioned to reveal to the world.", "56%", "35%"],
 ["Judas on the near side", "One apostle sits apart on the viewer's side of the table and reaches toward the food. And when he had dipped the sop, he gave it to Judas Iscariot. After the sop Satan entered into him.", "73%", "52%"],
 ["The dish", "The bowls stand along the cloth; the sign Christ gives is the most ordinary act of the meal, a morsel dipped and handed across.", "64%", "45%"],
 ["The others looking at one another", "Along the table the apostles turn to each other. Then the disciples looked one on another, doubting of whom he spake — and no man at the table knew for what intent he said it.", "50%", "65%"],
],
"File:Christ the True Vine icon (Athens, 16th century).jpg":[
 ["The inscription", "Η ΑΜΠΕΛΟΣ — the Vine, divided to either side of the top of the tree.", "9%", "36%"],
 ["The Gospel book", "The open book on his knee begins ΕΓΩ ΕΙΜΙ Η ΑΜΠΕΛΟΣ Η ΑΛΗΘΙΝΗ, I am the true vine, and my Father is the husbandman.", "35%", "48%"],
 ["Christ in the vine", "He sits where the trunk opens into its branches, his arms spread along them. St Hilary: he unfolds the mystery of his assumption of flesh, whereby he supports us, as the vine does its branches.", "22%", "48%"],
 ["The apostles in the branches", "Each apostle sits on a branch, turned toward the centre. I am the vine, ye are the branches: he that abideth in me, and I in him, the same bringeth forth much fruit.", "30%", "16%"],
 ["The grapes", "Clusters of grapes hang among the leaves. Herein is my Father glorified, that ye bear much fruit. St John Chrysostom: by fruit is meant life, i.e. that no one can be in him without good works.", "12%", "57%"],
 ["The one trunk", "Every branch comes from the one stock that rises out of the ground. As the branch cannot bear fruit of itself, except it abide in the vine; no more can ye, except ye abide in me. Without me ye can do nothing.", "78%", "47%"],
],
"File:Kiss of Judas (mosaic in Nea Moni).jpg":[
 ["The inscription", "ΙΟΥΔΑ ΦΙΛΗΜΑΤΙ ΠΑΡΑΔΙΔΩΣ ΤΟΝ ΥΙΟΝ ΤΟΥ ΑΝΘΡΩΠΟΥ — Judas, betrayest thou the Son of man with a kiss? The words are St Luke's; John's account has no kiss at all.", "9%", "50%"],
 ["Christ and Judas", "At the left Judas throws his arms round Christ. Both faces are lost where the tesserae have fallen. In John, Christ goes out to meet them himself, and asks, Whom seek ye?", "35%", "22%"],
 ["Peter's knife", "Peter, grey-haired, holds a blade to the young man's ear. John alone names both of them. Put up thy sword into the sheath: the cup which my Father hath given me, shall I not drink it?", "36%", "67%"],
 ["Malchus", "The young man with the shield and the halberd is the high priest's servant. The servant's name was Malchus — a detail only John gives, who was known to the high priest's household.", "36%", "58%"],
 ["Torches and weapons", "Above the soldiers rise the flame of a torch and the heads of spears. Judas came with lanterns and torches and weapons. St Augustine: the eternal day was so obscured by his human body, that he was sought for with lanterns and torches, to be slain in the darkness.", "14%", "76%"],
 ["The band of soldiers", "Behind them crowd the helmeted men of the band. When he said unto them, I am he, they went backward, and fell to the ground. St Augustine: without a blow, one word struck, drove back, prostrated a crowd fierce with hatred, terrible with arms.", "28%", "47%"],
],
"File:Jesus before Pontius Pilate - Stavronikita monastery, Mt Athos - Theophanes of Crete, 16th c..jpg":[
 ["The inscription", "ΚΡΙΝΟΜΕΝΟΣ ΥΠΟ ΑΝΝΑ ΚΑΙ ΚΑΙΑΦΑ — being judged by Annas and Caiaphas. The painted title overrules the file name.", "9%", "42%"],
 ["Christ before the high priests", "He stands with his head bowed toward them. I spake openly to the world; in secret have I said nothing. Why askest thou me? ask them which heard me.", "52%", "32%"],
 ["The guard taking hold of him", "A man at his shoulder lays hold on him. The band took Jesus, and bound him, and led him away to Annas first. John also records that an officer struck him with the palm of his hand.", "42%", "42%"],
 ["Annas and Caiaphas", "The two elders sit enthroned side by side. Annas had been high priest and his son-in-law Caiaphas held the office that year; John names both, and says Annas sent him bound unto Caiaphas.", "45%", "70%"],
 ["The soldiers", "Helmeted soldiers crowd behind Christ — the band and officers from the chief priests who took him in the garden.", "27%", "44%"],
 ["The hanging lamp", "A lamp hangs from the roof: it is night, and the scene is indoors. Outside in the courtyard Peter stands at the fire of coals, for it was cold.", "18%", "46%"],
],
"File:Cathedral (Monreale) - Right wing transept - Before Pilate.jpg":[
 ["The inscription", "IHS DUCTUS EST ANTE PILATUM — Jesus was led before Pilate.", "14%", "32%"],
 ["Pilate enthroned", "PILATUS, written over his head. He sits in the hall of judgment and questions him: Art thou the King of the Jews? Christ's answer is John's alone: My kingdom is not of this world.", "48%", "70%"],
 ["Christ answering", "He stands with his hand stretched toward the governor. To this end was I born, and for this cause came I into the world, that I should bear witness unto the truth. Pilate saith unto him, What is truth?", "50%", "42%"],
 ["The elders outside", "The chief priests and elders stand behind Christ outside the colonnade. They themselves went not into the judgment hall, lest they should be defiled; but that they might eat the passover.", "45%", "17%"],
 ["The soldier with the sword", "A soldier stands at Pilate's shoulder with a drawn sword: the governor's power of life and death, which the Jews had not — It is not lawful for us to put any man to death.", "42%", "86%"],
 ["The columns between them", "The hall's columns stand between Christ and Pilate, and the painter makes their hands meet across them. In John, Pilate goes out to the Jews and back in to Christ seven times.", "48%", "57%"],
],
"File:Empaigmos Dionysiou.jpg":[
 ["The inscription", "Ο ΤΟΥ ΧΡΙΣΤΟΥ ΕΜΠΑΙΓΜΟΣ — the mocking of Christ.", "9%", "52%"],
 ["The crown of thorns", "The soldiers platted a crown of thorns, and put it on his head. St Bede: instead of a diadem, they put upon him a crown of thorns — the thorns which the earth of our body brings forth.", "26%", "44%"],
 ["The purple robe", "They put on him a purple robe. Bede: Matthew says, a scarlet robe, but scarlet and purple are different names for the same color.", "45%", "44%"],
 ["The reed for a sceptre", "He holds a reed across his body in place of a sceptre.", "42%", "50%"],
 ["Kneeling in mockery", "Before him the soldiers bend the knee: Hail, King of the Jews! and they smote him with their hands.", "68%", "70%"],
 ["Trumpets and drums", "Behind him they blow horns and beat a drum, as a king's entry is announced. St Augustine: not the insignia of empire, but the marks of ridicule.", "25%", "86%"],
 ["Behold the man", "He stands on a step, facing the viewer, as Pilate brought him out to the crowd. Behold the man! St John Chrysostom: that the Jews might cease from their fury, seeing him thus insulted, Pilate brought out Jesus before them crowned.", "90%", "53%"],
],
"File:Crucifixion, Early XIV Century, St Mary Perivleptos Church, Ohrid Icon Gallery.jpg":[
 ["The inscription", "Η ΣΤΑΥΡΩΣΙΣ — the Crucifixion, split to either side of the top of the cross, with an angel in each upper corner.", "14%", "26%"],
 ["The title on the cross", "The board at the top reads Ο ΒΑΣΙΛΕΥΣ ΤΗΣ ΔΟΞΗΣ, the King of glory, where Pilate's title stood. St John Chrysostom: as letters are inscribed on a trophy declaring the victory, so Pilate wrote a title on Christ's cross.", "11%", "50%"],
 ["Christ on the cross", "His head is bowed and his eyes are closed. Orthodox icons paint Christ on the cross already dead, and at peace: It is finished: and he bowed his head, and gave up the ghost.", "35%", "48%"],
 ["The Mother of God", "ΜΡ ΘΥ. She stands at the left with her hand raised to her face. Now there stood by the cross of Jesus his mother. When Jesus therefore saw his mother, he saith unto his mother, Woman, behold thy son!", "55%", "22%"],
 ["John the Theologian", "Ο ΑΓΙΟΣ ΙΩΑΝΝΗΣ Ο ΘΕΟΛΟΓΟΣ. The disciple whom he loved stands at the right with his head bowed on his hand. Then saith he to the disciple, Behold thy mother! And from that hour that disciple took her unto his own home.", "52%", "72%"],
 ["Golgotha and the skull", "The cross stands in a cleft of the rock of Golgotha, the place of a skull; in the dark hollow at its foot lies a skull, which the Church's tradition says is Adam's.", "88%", "50%"],
 ["The wall of Jerusalem", "The long low wall behind them is the city wall. The place where Jesus was crucified was nigh to the city, which is why, John says, many of the Jews read the title.", "55%", "57%"],
],
"File:Great Lavra Monastery Katholikon Church Crucifixion, Theophanes the Cretan 1535.jpg":[
 ["The spear in his side", "The soldier drives his spear into Christ's side. St Augustine: the Evangelist has expressed himself cautiously; not struck, or wounded, but opened his side: whereby was opened the gate of life, from whence the sacraments of the Church flowed.", "40%", "35%"],
 ["The sponge on the reed", "The man at the right raises a sponge on a long reed. Blessed Theophylact: some say that the hyssop is put here for reed, its leaves being like a reed.", "28%", "76%"],
 ["The bucket of vinegar", "He carries the vessel of vinegar in his other hand. There was set a vessel full of vinegar. St Augustine: knowing the prophecy in the Psalms, And when I was thirsty, they gave me vinegar to drink, he said, I thirst.", "70%", "80%"],
 ["The angels with chalices", "Two angels fly at either side of the cross holding cups. The icon paints what the Church says of this wound: the blood and the water of the side are the Eucharist and Baptism.", "21%", "78%"],
 ["His head bowed", "It is finished: and he bowed his head, and gave up the ghost. They brake not his legs, because he was dead already.", "14%", "56%"],
 ["IC XC", "The letters of his name, Jesus Christ, are written on the beam of the cross to either side of his head.", "10%", "38%"],
],
"File:Apokalthelosis Dionysiou.jpg":[
 ["The inscription", "Η ΑΠΟΚΑΘΗΛΩΣΙΣ — the taking down from the nails. The Church sings of it on Holy Friday: Joseph with Nicodemus took thee down from the tree.", "9%", "37%"],
 ["Joseph receiving the body", "The grey-bearded man holds the body as it is lowered. Joseph of Arimathaea, being a disciple of Jesus, but secretly for fear of the Jews, besought Pilate that he might take away the body.", "20%", "45%"],
 ["The Mother of God", "She presses her Son's face to hers as he comes down into her arms.", "24%", "30%"],
 ["John bowed", "The beloved disciple stands with his head on his hand, the same gesture he has at the cross.", "40%", "60%"],
 ["Drawing the nails", "A man kneels at the foot of the cross and draws the nails from the feet with pincers. There came also Nicodemus, which at the first came to Jesus by night, and brought a mixture of myrrh and aloes.", "64%", "61%"],
 ["The basket of tools", "The basket of the ladder-men stands on the rock beside him, with the tools of the unnailing.", "82%", "56%"],
 ["The skull under Golgotha", "In the black cleft under the cross lies the skull the Church calls Adam's.", "88%", "48%"],
 ["The women", "The myrrh-bearing women stand grieving at the left; Mary Magdalene, who stood by the cross, will be the first at the tomb.", "48%", "14%"],
],
"File:Mnemeion Christou Dionysiou.jpg":[
 ["The inscription", "Ο ΔΕ ΠΕΤΡΟΣ ΚΑΙ ΙΩ(ΑΝΝΗΣ) ΕΔΡΑΜΟΝ ΕΠΙ ΤΟ ΜΝΗΜΕΙΟΝ — but Peter and John ran to the tomb. The painter wrote the verse he was painting at the head of it.", "12%", "30%"],
 ["John, who came first", "The younger disciple, beardless, looks out from behind the rock. John says of himself that he outran Peter and came first to the sepulchre, stooped and looked in, yet went he not in.", "27%", "21%"],
 ["Peter, who went in", "Peter, grey-bearded, has come up after him and stands over the open tomb with his hands spread. Chrysostom: being of a more fervid temper, he pursued the search, and examined every thing.", "35%", "40%"],
 ["The linen clothes lying", "The grave-clothes lie in the sepulchre still in their bands, with no body in them. Chrysostom: had they carried Him away, they would not have stripped Him.", "73%", "35%"],
 ["The napkin apart", "At the head end, separate from the linen, lies the napkin that was about his head — not lying with the linen clothes, but wrapped together in a place by itself. Chrysostom reads it as proof against theft: no thief would stop to fold it.", "74%", "70%"],
 ["Ο ΑΓΙΟΣ ΤΑΦΟΣ", "The holy tomb. It is painted open and empty: there is no stone, no seal and no watch in this fresco, only what the two apostles saw.", "60%", "64%"],
],
"File:Emphania Soteros Dionysiou.jpg":[
 ["The inscription", "Η ΜΕΤΑ ΤΗΝ ΕΓΕΡΣΙΝ ΠΡΟΣ ΤΗΝ ΜΑΓΔΑΛΗΝΗΝ ΜΑΡΙΑΝ ΤΟΥ ΣΩΤΗΡΟΣ ΕΜΦΑΝΕΙΑ — the appearing of the Saviour to Mary Magdalene after the Resurrection.", "9%", "50%"],
 ["Touch me not", "ΜΗ ΜΟΥ ΑΠΤΟΥ, written beside Christ. Touch me not; for I am not yet ascended to my Father: but go to my brethren. She who came to anoint a body is sent as the first herald of the Resurrection.", "22%", "45%"],
 ["Rabboni", "ΡΑΒΒΟΥΝΙ, written over Mary's head. Jesus saith unto her, Mary. She turned herself, and saith unto him, Rabboni; which is to say, Master.", "42%", "30%"],
 ["Her question on the rock", "ΚΥΡΙΕ, ΕΙ ΣΥ ΕΒΑΣΤΑΣΑΣ ΑΥΤΟΝ… — Sir, if thou have borne him hence, tell me where thou hast laid him. St John Chrysostom: because he appeared as a common person, she thought him the gardener.", "62%", "50%"],
 ["Mary kneeling", "She kneels with her hands stretched toward him. St Augustine: though the men returned, the stronger love of the woman fixed her to the spot.", "70%", "25%"],
 ["Christ turning his hand away", "He stands in a blue himation with a scroll in one hand, and holds the other down and away from her.", "55%", "48%"],
 ["The holy tomb", "Ο ΑΓΙΟΣ ΤΑΦΟΣ — the empty sepulchre, cut in the rock at the left. She stood without at the sepulchre weeping, and saw two angels in white sitting where the body of Jesus had lain.", "50%", "14%"],
],
"File:Psilapheses Thoma Dionysiou.jpg":[
 ["The inscription", "Η ΨΗΛΑΦΗΣΙΣ ΤΟΥ ΘΩΜΑ — the touching of Thomas. The Sunday after Pascha is named for him.", "9%", "30%"],
 ["The house, the doors being shut", "The painter builds the house round them as a closed wall of arches under a single gable, with no opening in it. When the doors were shut where the disciples were assembled for fear of the Jews, came Jesus and stood in the midst. St Augustine: the shut door did not hinder the body, wherein Divinity resided.", "14%", "50%"],
 ["The wound in his side", "He lifts his arm to open his garment at the side. Reach hither thy hand, and thrust it into my side. St Augustine: he might, had he pleased, have wiped all spot and trace of wound from his glorified body; but he had reasons for retaining them.", "48%", "45%"],
 ["Thomas's hand", "Thomas reaches out. Except I shall see in his hands the print of the nails, and thrust my hand into his side, I will not believe. St John Chrysostom: to show that he heard what Thomas said to the disciples, Christ uses the same words.", "52%", "36%"],
 ["Thomas", "The apostle in red, called Didymus. Be not faithless, but believing. Then Thomas answered and said unto him, My Lord and my God.", "58%", "27%"],
 ["Peter and the others", "The rest stand in two groups under the arches. Blessed are they that have not seen, and yet have believed — the word said over their heads to everyone who comes after.", "55%", "72%"],
],
"File:Evresete Dionysiou.jpg":[
 ["The inscription", "…ΕΙΣ ΤΑ ΔΕΞΙΑ ΜΕΡΗ ΤΟΥ ΠΛΟΙΟΥ ΤΟ ΔΙΚΤΥΟΝ ΚΑΙ ΕΥΡΗΣΕΤΕ — cast the net on the right side of the ship, and ye shall find.", "9%", "80%"],
 ["The net full of fish", "They cast therefore, and now they were not able to draw it for the multitude of fishes — an hundred and fifty and three: and for all there were so many, yet was not the net broken.", "78%", "14%"],
 ["It is the Lord", "One of the apostles points to the shore. That disciple therefore whom Jesus loved saith unto Peter, It is the Lord. St Bede: he recognized our Lord either by the miracle, or by the sound of his voice.", "30%", "60%"],
 ["Peter in the sea", "Peter has thrown himself into the water and swims to Christ. He girt his fisher's coat unto him, for he was naked, and did cast himself into the sea. Bede: he went to Jesus with the ardour with which he did every thing.", "72%", "70%"],
 ["Christ on the shore", "He stands at the water's edge. When the morning was now come, Jesus stood on the shore: but the disciples knew not that it was Jesus. Children, have ye any meat?", "30%", "90%"],
 ["The fire of coals, the fish and the bread", "On the shore lie a heap of glowing coals with a fish on them, and a loaf. They saw a fire of coals there, and fish laid thereon, and bread. Come and dine.", "80%", "78%"],
 ["The boat", "The seven are together in one boat: Simon Peter, Thomas, Nathanael, the sons of Zebedee and two others. That night they caught nothing.", "40%", "30%"],
],
"File:Agios Ioannes Prochoros Dionysiou.jpg":[
 ["The inscription", "Ο ΑΓ(ΙΟΣ) ΙΩ(ΑΝΝΗΣ) Ο ΘΕΟΛΟΓΟΣ — St John the Theologian, the name the Church gives only to him among the Evangelists.", "31%", "47%"],
 ["The ray from heaven", "A small segment of heaven, set with rays, sends its light down into the cave toward the old apostle. What he gives his scribe is received, not remembered.", "31%", "38%"],
 ["John, his hand at his chin", "He sits back from the desk with his hand at his chin, in the posture of one who listens and ponders before he speaks.", "51%", "42%"],
 ["Prochoros writing", "Ο ΑΓ(ΙΟΣ) ΠΡΟΧΟΡΟΣ is inscribed beside him. The young disciple bends over the page on his knee and writes what John speaks.", "63%", "58%"],
 ["The desk", "Between them stands the writing desk with its ink-pot. The Gospel is painted coming into being here, between the one who hears and the one who writes.", "68%", "50%"],
 ["The cave", "The two sit in the dark mouth of a cave in the rock. The Church's tradition places the writing on the island of Patmos, in a cave that is still shown there.", "42%", "33%"],
 ["The pendentive", "The fresco fills one of the four curved triangles that carry the dome. Byzantine churches set the four Evangelists there, so that the Gospel holds up the image of heaven above it.", "78%", "31%"],
],
"File:Andrew (Kirillo-Belozersk).jpg":[
 ["The inscription", "ОА АНДРЕИ: the two letters ОА keep the Greek abbreviation for the saint, and then his name in Slavonic, Andrew.", "9%", "68%"],
 ["His head, turned aside", "He does not face us. His head bows and turns toward the left, toward the centre of the row where Christ would stand.", "13%", "32%"],
 ["The scroll", "He carries a closed scroll in both hands: an apostle is one who has been given a message to take.", "38%", "23%"],
 ["Bowed toward the centre", "The whole figure leans one way, as the apostles stand in the Deesis row of an iconostasis, turned in prayer toward Christ. One of the two which heard John speak, and followed him, was Andrew.", "25%", "55%"],
 ["The bare feet", "He stands barefoot, as apostles are always painted: sent out with nothing of their own.", "91%", "35%"],
],
"File:Cathedral (Monreale) - North arch of transept - Wedding at Cana.jpg":[
 ["The inscription", "IESUS SEDENS AD NUPTIAS DE AQUA FECIT VINUM — Jesus, sitting at the wedding, made wine of water. Both Jesus was called, and his disciples, to the marriage.", "9%", "22%"],
 ["Christ at the table", "He sits at the left end of the round table with the cross in his halo. The mosaic names him sitting: he is a guest at this feast before he is its host.", "36%", "9%"],
 ["His Mother", "The mother of Jesus was there, and she sits beside him in her dark veil. It is she who notices first: They have no wine.", "31%", "12%"],
 ["A crowned guest", "One figure at the table wears a crown. In the Orthodox marriage service the bride and bridegroom are both crowned, and the crown marks this guest as one of the couple.", "25%", "27%"],
 ["The table", "The round table under the colonnade is laid with dishes and cups. The feast is ordinary, and the mosaic keeps it so.", "48%", "24%"],
 ["The servant with the cup", "A servant lifts a cup and carries it toward the table. Draw out now, and bear unto the governor of the feast.", "28%", "65%"],
 ["The servant pouring", "Another tips a jug into a tall jar. Fill the waterpots with water. And they filled them up to the brim.", "17%", "76%"],
 ["The water pots", "The tall jars stand in a row at the end of the arch, where the servants work. The servants which drew the water knew.", "20%", "90%"],
],
"File:StNikita122general.jpg":[
 ["The inscription", "The title over the arcade is in Slavonic and ends with the word БРАКЪ, the marriage.", "9%", "34%"],
 ["Christ at the end of the table", "He sits apart at the left end, haloed, with his hand raised. The feast goes on down the length of the table without looking at him.", "40%", "9%"],
 ["The arcade", "The wedding is set under a long colonnade hung with a curtain, the painters' way of saying the scene is indoors.", "22%", "50%"],
 ["The guests raising cups", "Along the far side of the table the guests lift their cups. Every man at the beginning doth set forth good wine.", "37%", "25%"],
 ["The table", "The table runs the width of the wall, laid with bowls and dishes. The Serbian painters give the whole of an ordinary wedding meal.", "51%", "57%"],
 ["The child", "A small child stands in front of the table, at the feet of the guests: the painters set the miracle among a household, children and all.", "84%", "51%"],
 ["The servant", "At the right end a servant in a short tunic stoops at the table's edge. It is the servants, not the guests, who know where the wine came from.", "70%", "83%"],
],
"File:Photina of Protat.JPG":[
 ["Christ seated", "He sits on the left with his feet bare. Jesus therefore, being wearied with his journey, sat thus on the well.", "30%", "17%"],
 ["His hand, speaking", "His right hand is open toward her, the gesture of speech; the other holds a scroll. Give me to drink.", "43%", "23%"],
 ["The well", "The well-head is built of stone, square and stepped, standing between them. Jacob's well was there.", "63%", "47%"],
 ["The woman", "She stands on the right in a long dress and a red cloak, facing him across the well.", "30%", "77%"],
 ["Her raised hand", "Her hand is lifted in question. How is it that thou, being a Jew, askest drink of me, which am a woman of Samaria?", "31%", "64%"],
 ["The water jar", "She holds her jar down at her side, not yet filled. Before the scene is done she will leave it behind: the woman then left her waterpot.", "60%", "82%"],
 ["The city", "Behind her rise the walls and towers of a city of Samaria, which is called Sychar. That is where she will run to say, Come, see a man.", "14%", "64%"],
],
"File:Jésus et la Samaritaine. Fresque parTheophanes le Crétois, Monastère de Stavronikita, Mont Athos, 16e siècle..jpg":[
 ["The inscription", "The title at the top ends ΣΑΜΑΡΕΙ…ΔΟΣ, the Samaritan woman; the middle of the word is hidden behind the building.", "9%", "58%"],
 ["The woman", "She stands at the left in red, her veil over her head, and lifts her hand toward him as she answers.", "45%", "25%"],
 ["Her jug", "She holds a tall golden jug by its handle. There cometh a woman of Samaria to draw water.", "55%", "36%"],
 ["Christ seated", "He sits at the right on a rock with a scroll in his hand and the other hand raised to speak. Jesus therefore, being wearied with his journey, sat thus on the well.", "45%", "82%"],
 ["The well", "The well has a quatrefoil mouth and stands on a stepped base between them. Sir, thou hast nothing to draw with, and the well is deep.", "60%", "56%"],
 ["The rope", "The rope lies coiled at the foot of the well, not yet let down.", "82%", "44%"],
 ["The disciples", "Three disciples come over the hill behind. Upon this came his disciples, and marvelled that he talked with the woman.", "22%", "52%"],
 ["The town", "The walls and a doorway of the town stand at the top right, the city she will go back into.", "20%", "86%"],
],
"File:Christ anв Samaritan woman (Monreale).jpg":[
 ["The inscription", "XPS SEDENS IUXTA PUTEUM LOQUITUR CUM SAMARITANA — Christ, sitting beside the well, speaks with the Samaritan woman.", "17%", "52%"],
 ["Christ seated", "He sits at the left with a scroll in his hand, turned toward her across the well.", "62%", "18%"],
 ["His raised hand", "His right hand is lifted in address. Give me to drink.", "55%", "33%"],
 ["The frame and windlass", "Over the well stands a wooden frame with a windlass, the working gear of a village well.", "35%", "52%"],
 ["The bucket", "The bucket hangs halfway down on its rope. The mosaic paints the moment she is drawing water.", "60%", "56%"],
 ["The well mouth", "The round well-head is fluted like a column. Art thou greater than our father Jacob, which gave us the well, and drank thereof himself?", "76%", "52%"],
 ["The woman drawing", "She holds the rope in her hand as he speaks to her: she came to draw water, and she is doing it.", "56%", "72%"],
 ["The woman", "She stands at the right in a pale dress with a turban-like head-dress, looking at him across the well.", "45%", "85%"],
],
"File:Cathedral (Monreale) - Right wing transept - Healing the paralytic at Bethesda.jpg":[
 ["The command", "SURGE TOLLE GRABATUM ET AMBULA — Rise, take up thy bed, and walk. The words are set across the top of the picture.", "9%", "22%"],
 ["The place", "PROBATICA PISCINA — the sheep pool. There is at Jerusalem by the sheep market a pool, which is called in the Hebrew tongue Bethesda.", "32%", "90%"],
 ["Christ", "He stands at the left with a scroll and stretches out his hand over the pool. He speaks the command; he does not touch the man.", "45%", "28%"],
 ["The disciples", "Two disciples stand behind him at the left edge.", "45%", "10%"],
 ["The angel", "The angel comes down headlong between the columns into the water. An angel went down at a certain season into the pool, and troubled the water.", "33%", "57%"],
 ["The troubled water", "The water in the basin is drawn in waves. Whosoever then first after the troubling of the water stepped in was made whole.", "57%", "50%"],
 ["The porches", "The pool is framed by columns and arches, the porches where the sick lay waiting.", "22%", "40%"],
 ["The man carrying his bed", "At the right the healed man walks away with his wooden bed on his back. And immediately the man was made whole, and took up his bed, and walked.", "55%", "76%"],
],
};
