// A readable name for every icon this reader shows, keyed by Commons file title.
module.exports={
"File:John the Evangelist and Prochorus by E.Lambardos (1602).jpg":"St John the Theologian and Prochoros — Emmanuel Lambardos, 1602",
"File:049 Saint John the Baptist Icon 2 from Saint Paraskevi Church in Langadas.jpg":"St John the Evangelist writing — Langadas, Greece, 19th c.",
"File:Agios Ioannes Prochoros Dionysiou.jpg":"St John the Theologian and Prochoros — Dionysiou, Athos, 1547",
"File:Prodromos Didaskon Ioudaious Dionysiou.jpg":"The Forerunner Teaching the Jews — Dionysiou, Athos, 1547",
"File:Αμφιπρόσωπη εικόνα με τον Άγιο Γεώργιο και τον Άγιο Ανδρέα Β΄ μισό 12ου αι. - Α΄ μισό 18ου αι. Βέροια, Ιερός ναός Αγίου Ανδρέα 2.jpg":"St Andrew the First-called — Veria, Macedonia",
"File:Andrew (Kirillo-Belozersk).jpg":"St Andrew — Kirillo-Belozersky monastery, late 15th c.",
"File:Christos Kana Galilaias.jpg":"The Marriage at Cana — Dionysiou, Athos, 1547",
"File:Cathedral (Monreale) - North arch of transept - Wedding at Cana.jpg":"The Marriage at Cana — Monreale, 12th c.",
"File:StNikita122general.jpg":"The Marriage at Cana — St Nikita near Skopje, 14th c.",
"File:Christ banish tradesmen from Temple (Monreale).jpg":"The Cleansing of the Temple — Monreale, 12th c.",
"File:Samaritan Woman Dionysiou.jpg":"Christ and the Samaritan Woman — Dionysiou, Athos, 1547",
"File:Photina of Protat.JPG":"Christ and the Samaritan Woman — Protaton, Athos, c. 1300",
"File:Jésus et la Samaritaine. Fresque parTheophanes le Crétois, Monastère de Stavronikita, Mont Athos, 16e siècle..jpg":"Christ and the Samaritan Woman — Stavronikita, Athos, 16th c.",
"File:Christ anв Samaritan woman (Monreale).jpg":"Christ and the Samaritan Woman — Monreale, 12th c.",
"File:Christos Iomenos Paralyton Dionysiou.jpg":"The Paralytic at Bethesda — Dionysiou, Athos, 1547",
"File:Cathedral (Monreale) - Right wing transept - Healing the paralytic at Bethesda.jpg":"The Paralytic at the Sheep Pool — Monreale, 12th c.",
"File:Jesus healing a paralytic in Bethesda - Sant'Apollinare Nuovo - Ravenna 2016.jpg":"The Paralytic Carries his Bed — Sant'Apollinare Nuovo, Ravenna, 6th c.",
"File:035 Sunday of the Paralytic Icon from Saint Paraskevi Church in Langadas.jpg":"The Sunday of the Paralytic — Langadas, Greece, 19th c.",
"File:Evlogesis Pente Arton Dionysiou.jpg":"The Blessing of the Five Loaves — Dionysiou, Athos, 1547",
"File:42 Mid-Pentecost Icon from Saint Paraskevi Church in Adam.jpg":"Mid-Pentecost — Athanasios Vasilikos of Adam, 1858",
"File:Prepolovenie (Annunciation Cathedral in Moscow).jpg":"Mid-Pentecost — Cathedral of the Annunciation, Moscow, 16th c.",
"File:007 Mid-Pentecost Icon from Saint Paraskevi Church in Langadas.jpg":"Mid-Pentecost — Langadas, Greece, 19th c.",
"File:Katakrinon Pornin Dionysiou.jpg":"Christ and the Woman Taken in Adultery — Dionysiou, Athos, 1547",
"File:Monreale (catedral) Woman Caught in Adultery.jpg":"Christ and the Woman Taken in Adultery — Monreale, 12th c.",
"File:Christos Iomenos Typhlon.jpg":"The Man Born Blind — Dionysiou, Athos, 1547",
"File:Cathedral (Monreale) - Right wing transept - Healing of the blind.jpg":"The Man Born Blind at Siloam — Monreale, 12th c.",
"File:Christ Healing the Blind (Tzanes).png":"The Healing of the Blind Man — Emmanuel Tzanes, 1686",
"File:008 Sunday of the Blind Man Icon from Saint Paraskevi Church in Langadas.jpg":"The Sunday of the Blind Man — Langadas, Greece, 19th c.",
"File:Egersis Lazarou Dionysiou.jpg":"The Raising of Lazarus — Dionysiou, Athos, 1547",
"File:Lazarus Miracle Icon Sinai 12th century.jpg":"The Raising of Lazarus — Sinai, 12th c.",
"File:Cathedral (Monreale) - Right wing transept - Rising of Lazarus.jpg":"The Raising of Lazarus — Monreale, 12th c.",
"File:RossanoGospelsFolio001rRaisingLazarus.jpg":"The Raising of Lazarus — Rossano Gospels, 6th c.",
"File:Cathedral (Monreale) - Right wing transept - Entry into Jerusalem.jpg":"The Entry into Jerusalem — Monreale, 12th c.",
"File:Hosios Loukas Crypt - Entry into Jerusalem 01.jpg":"The Entry into Jerusalem — crypt of Hosios Loukas, 11th c.",
"File:Entry into Jerusalem of Kirillo-Belozersky iconostasis (15th century, Russia).jpg":"The Entry into Jerusalem — Kirillo-Belozersky iconostasis, 1497",
"File:Nipter Dionysiou.jpg":"The Washing of the Feet — Dionysiou, Athos, 1547",
"File:Feet washing (Nea Moni).jpg":"The Washing of the Feet — Nea Moni, Chios, 11th c.",
"File:Christ washes apostles' feet (Monreale).jpg":"The Washing of the Feet — Monreale, 12th c.",
"File:Washing the feets (1420s, Sergiev Posad).jpg":"The Washing of the Feet — Trinity Lavra, Sergiev Posad, 1420s",
"File:Monreale-cattedrale-mosaik-abendmahl.JPG":"The Supper: the Sop Given to Judas — Monreale, 12th c.",
"File:Last Supper by Theophanes the Cretan.jpg":"The Mystical Supper — Theophanes the Cretan, 16th c.",
"File:S. Apollinare Nuovo Last Supper.jpg":"The Supper — Sant'Apollinare Nuovo, Ravenna, 6th c.",
"File:Christ the True Vine icon (Athens, 16th century).jpg":"Christ the True Vine — Athens, 16th c.",
"File:Tree of Jesus Signed by Angelos.png":"Christ the True Vine — Angelos Akotantos, Crete, 15th c.",
"File:Kiss of Judas (mosaic in Nea Moni).jpg":"The Betrayal and Arrest — Nea Moni, Chios, 11th c.",
"File:Judas's Kiss mosaic in Sant'Apollinare Nuovo (Ravenna).jpg":"The Betrayal — Sant'Apollinare Nuovo, Ravenna, 6th c.",
"File:Jesus before Pontius Pilate - Stavronikita monastery, Mt Athos - Theophanes of Crete, 16th c..jpg":"Christ Judged by Annas and Caiaphas — Stavronikita, Athos, 16th c.",
"File:Ravenna, sant'apollinare nuovo, int., storie cristologiche, epoca di teodorico 07.1 rinnegamento di pietro.jpg":"Peter and the Doorkeeper — Sant'Apollinare Nuovo, Ravenna, 6th c.",
"File:Icon Peter's denial FULL.jpeg":"The Arrest and the Denial of Peter — Russian icon, c. 1500",
"File:Cathedral (Monreale) - Right wing transept - Before Pilate.jpg":"Christ Led before Pilate — Monreale, 12th c.",
"File:Kirillo-Belozersky iconostasis - Kremlin exhibition - Before Pilatus by shakko.jpg":"Christ before Pilate — Kirillo-Belozersky iconostasis, 1497",
"File:Empaigmos Dionysiou.jpg":"The Mocking of Christ — Dionysiou, Athos, 1547",
"File:Mastigosis Dionysiou.jpg":"The Scourging of Christ — Dionysiou, Athos, 1547",
"File:Crucifixion, Early XIV Century, St Mary Perivleptos Church, Ohrid Icon Gallery.jpg":"The Crucifixion — Ohrid, early 14th c.",
"File:Crucifixion, II Half of XIII Century, St Mary Perivleptos Church, Ohrid Icon Gallery.jpg":"The Crucifixion — Ohrid, second half of the 13th c.",
"File:Diamersis Himation Christou Dionysiou.jpg":"The Parting of Christ's Garments — Dionysiou, Athos, 1547",
"File:Great Lavra Monastery Katholikon Church Crucifixion, Theophanes the Cretan 1535.jpg":"The Crucifixion, with the Lance and the Sponge — Theophanes the Cretan, Great Lavra, 1535",
"File:Cathedral (Monreale) - Left wing transept - West wall - Crucifixion.jpg":"The Crucifixion — Monreale, 12th c.",
"File:Apokalthelosis Dionysiou.jpg":"The Descent from the Cross — Dionysiou, Athos, 1547",
"File:Cathedral (Monreale) - Left wing transept - North wall - Entombment.jpg":"The Burial of Christ — Monreale, 12th c.",
"File:Kirillo-Belozersky iconostasis 18 - Entombment.jpg":"The Burial of Christ — Kirillo-Belozersky iconostasis, 1497",
"File:Etesatou Ioseph Somatou Christou.jpg":"Joseph Asks Pilate for the Body — Dionysiou, Athos, 1547",
"File:Mnemeion Christou Dionysiou.jpg":"Peter and John at the Tomb — Dionysiou, Athos, 1547",
"File:Emphania Soteros Dionysiou.jpg":"Christ Appears to Mary Magdalene — Dionysiou, Athos, 1547",
"File:Noli me tangere (16th c., Cretan).jpg":"Touch Me Not — Cretan icon, 16th c.",
"File:Touch Me Not (Noli me tangere), Lambardos Emmanuel, Municipal Gallery of Corfu, 04.jpg":"Touch Me Not — Emmanuel Lambardos, Corfu",
"File:Psilapheses Thoma Dionysiou.jpg":"The Touching of Thomas — Dionysiou, Athos, 1547",
"File:Incredulity of Saint Thomas,, Early XIV Century, St Mary Perivleptos Church, Ohrid Icon Gallery.jpg":"The Belief of Thomas — Ohrid, early 14th c.",
"File:Уверение Фомы 1499 1500 Дионисий.jpg":"The Belief of Thomas — Dionisy, 1500",
"File:Kirillo-Belozersky iconostasis 21 - Doubting Thomas.jpg":"The Belief of Thomas — Kirillo-Belozersky iconostasis, 1497",
"File:Evresete Dionysiou.jpg":"The Appearance at the Sea of Tiberias — Dionysiou, Athos, 1547",
"File:Cathedral (Monreale) - Left wing transept - Miraculous catch of fish.jpg":"The Appearance at the Sea of Tiberias — Monreale, 12th c.",
"File:Miracle of Christ at the Sea of Tiberias, GRACANICA 1 080A9396.jpg":"The Appearance at the Sea of Tiberias — Gračanica, 14th c.",
};
