// Passage types, key verses and scripture summaries for the Gospel of John. `keyVerse`
// pulls the KJV text automatically. The summaries retell the verses in the passage — they
// add nothing the text does not say. Type icons (tierB) are declared here as they are wired.
module.exports={

 // ---- chapter 1 ----
 prologue:{tierB:true,type:'Teaching',keyVerse:14,
  story:"John opens not in Bethlehem but before time: In the beginning was the Word, and the Word was with God, and the Word was God. All things were made by him. In him was life, and the life was the light of men, shining in a darkness that could not overcome it. A man sent from God, whose name was John, came to bear witness of that Light. The Word came to his own, and his own received him not; but to as many as received him he gave power to become the sons of God. And the Word was made flesh, and dwelt among us, full of grace and truth. No man hath seen God at any time; the only begotten Son hath declared him."},
 witness1:{type:'Event',keyVerse:23,
  story:"The Jews sent priests and Levites from Jerusalem to ask John, Who art thou? He confessed, and denied not: I am not the Christ. Not Elias; not that prophet. Then who? I am the voice of one crying in the wilderness, Make straight the way of the Lord, as said the prophet Esaias. Pressed on why he baptized, he answered: I baptize with water, but there standeth one among you whom ye know not, whose shoe’s latchet I am not worthy to unloose. These things were done in Bethabara beyond Jordan."},
 lamb:{type:'Event',keyVerse:29,
  story:"The next day John saw Jesus coming and said, Behold the Lamb of God, which taketh away the sin of the world. This is he of whom I said, After me cometh a man which is preferred before me, for he was before me. John bore record that he had seen the Spirit descending from heaven like a dove and abiding upon him — the sign he had been given by which to know the one who baptizes with the Holy Ghost. And I saw, and bare record, that this is the Son of God."},
 firstdisciples:{tierB:true,type:'Event',keyVerse:41,
  story:"Again the next day John stood with two of his disciples, and looking upon Jesus as he walked, he said, Behold the Lamb of God. The two followed Jesus, who turned and asked, What seek ye? Rabbi, where dwellest thou? Come and see. They abode with him that day, about the tenth hour. One of the two was Andrew, Simon Peter’s brother. He first findeth his own brother Simon and saith, We have found the Messias. He brought him to Jesus, who looked on him and said, Thou art Simon the son of Jona: thou shalt be called Cephas — a stone."},
 nathanael:{type:'Event',keyVerse:51,
  story:"The day following Jesus went into Galilee, found Philip, and said, Follow me. Philip found Nathanael: We have found him of whom Moses and the prophets did write, Jesus of Nazareth. Can there any good thing come out of Nazareth? Come and see. Jesus saw Nathanael coming and said, Behold an Israelite indeed, in whom is no guile — before Philip called thee, when thou wast under the fig tree, I saw thee. Rabbi, thou art the Son of God, the King of Israel. Thou shalt see greater things: heaven open, and the angels of God ascending and descending upon the Son of man."},

 // ---- chapter 2 ----
 cana:{type:'Miracle',keyVerse:11,
  story:"On the third day there was a marriage in Cana of Galilee, and the mother of Jesus was there; Jesus and his disciples were called to it. When the wine failed she said to him, They have no wine, and to the servants, Whatsoever he saith unto you, do it. Six stone waterpots stood there for the purifying of the Jews. Fill them with water, he said; and they filled them to the brim. Draw out now, and bear unto the governor of the feast. The ruler tasted the water made wine and called the bridegroom: thou hast kept the good wine until now. This beginning of miracles did Jesus in Cana, and manifested forth his glory; and his disciples believed on him."},
 temple2:{type:'Event',keyVerse:19,
  story:"At the Passover Jesus went up to Jerusalem and found in the temple those that sold oxen and sheep and doves, and the changers of money sitting. He made a scourge of small cords and drove them all out, poured out the changers’ money and overthrew the tables: Make not my Father’s house an house of merchandise. His disciples remembered, The zeal of thine house hath eaten me up. Asked for a sign, he said, Destroy this temple, and in three days I will raise it up. Forty and six years was this temple in building — but he spake of the temple of his body, as the disciples understood when he was risen."},

 // ---- chapter 3 ----
 nicodemus:{type:'Teaching',keyVerse:16,
  story:"Nicodemus, a Pharisee and a ruler of the Jews, came to Jesus by night: we know that thou art a teacher come from God. Jesus answered, Except a man be born again, he cannot see the kingdom of God. How can a man be born when he is old? Except a man be born of water and of the Spirit, he cannot enter. The wind bloweth where it listeth; so is every one that is born of the Spirit. As Moses lifted up the serpent in the wilderness, even so must the Son of man be lifted up. For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life. Light is come into the world, and men loved darkness rather than light."},
 witness3:{type:'Event',keyVerse:30,
  story:"Jesus and his disciples came into Judaea and baptized; John was baptizing in Aenon near Salim, for he was not yet cast into prison. John’s disciples complained that all men came to Jesus. John answered, A man can receive nothing, except it be given him from heaven. I said, I am not the Christ, but that I am sent before him. He that hath the bride is the bridegroom; the friend of the bridegroom rejoiceth greatly because of the bridegroom’s voice. He must increase, but I must decrease. He that cometh from above is above all; he whom God hath sent speaketh the words of God. He that believeth on the Son hath everlasting life."},

 // ---- chapter 4 ----
 samaritan:{type:'Event',keyVerse:14,
  story:"Leaving Judaea for Galilee, Jesus must needs go through Samaria, and came to Jacob’s well at Sychar. Wearied with his journey, he sat on the well about the sixth hour. A woman of Samaria came to draw water, and he said, Give me to drink. The Jews have no dealings with the Samaritans. If thou knewest the gift of God, thou wouldest have asked of him, and he would have given thee living water — a well of water springing up into everlasting life. Go, call thy husband. I have no husband. Thou hast had five husbands. Sir, I perceive that thou art a prophet. God is a Spirit: they that worship him must worship him in spirit and in truth. I know that Messias cometh. I that speak unto thee am he."},
 harvest4:{type:'Event',keyVerse:35,
  story:"The disciples returned and marvelled that he talked with the woman. She left her waterpot, went into the city and said, Come, see a man which told me all things that ever I did: is not this the Christ? The disciples pressed him to eat. My meat is to do the will of him that sent me, and to finish his work. Lift up your eyes and look on the fields; for they are white already to harvest. Many of the Samaritans believed because of the woman’s saying, and besought him to tarry; he abode two days, and many more believed for his own word: we know that this is indeed the Christ, the Saviour of the world."},
 nobleman:{type:'Miracle',keyVerse:50,
  story:"Coming into Galilee, Jesus returned to Cana, where he made the water wine. A nobleman of Capernaum whose son was at the point of death came and besought him to come down and heal him. Except ye see signs and wonders, ye will not believe. Sir, come down ere my child die. Jesus saith, Go thy way; thy son liveth. The man believed the word and went. His servants met him on the road: thy son liveth — the fever left him yesterday at the seventh hour, the same hour in which Jesus had spoken. Himself believed, and his whole house. This is the second miracle that Jesus did in Galilee."},

 // ---- chapter 5 ----
 bethesda:{type:'Miracle',keyVerse:8,
  story:"At a feast in Jerusalem, by the sheep market, lay the pool called Bethesda with five porches, and in them a great multitude of the impotent, blind, halt and withered, waiting for the moving of the water; an angel went down at a certain season and troubled it, and whoever stepped in first was made whole. A man had lain there thirty and eight years. Wilt thou be made whole? Sir, I have no man to put me into the pool. Jesus saith, Rise, take up thy bed, and walk. Immediately he was made whole. It was the sabbath, and the Jews said it was not lawful to carry the bed. Later Jesus found him in the temple: sin no more, lest a worse thing come unto thee. The Jews sought to slay him, because he said that God was his Father, making himself equal with God."},
 sonfather:{type:'Teaching',keyVerse:24,
  story:"Jesus answered them: The Son can do nothing of himself, but what he seeth the Father do; for what things soever he doeth, these also doeth the Son likewise. As the Father raiseth up the dead and quickeneth them, even so the Son quickeneth whom he will. The Father hath committed all judgment unto the Son, that all men should honour the Son, even as they honour the Father. He that heareth my word, and believeth on him that sent me, hath everlasting life, and is passed from death unto life. The hour is coming when all that are in the graves shall hear his voice and come forth. I can of mine own self do nothing: I seek not mine own will, but the will of the Father which hath sent me."},
 witnesses5:{type:'Teaching',keyVerse:39,
  story:"If I bear witness of myself, my witness is not true — there is another. Ye sent unto John, and he bare witness unto the truth; he was a burning and a shining light, and ye were willing for a season to rejoice in his light. But I have greater witness than that of John: the works which the Father hath given me to finish. The Father himself hath borne witness of me. Search the scriptures; for in them ye think ye have eternal life: and they are they which testify of me. And ye will not come to me, that ye might have life. Had ye believed Moses, ye would have believed me: for he wrote of me."},

 // ---- chapter 6 ----
 feeding:{type:'Miracle',keyVerse:11,
  story:"Jesus went over the sea of Galilee, and a great multitude followed him for the miracles he did on the diseased. He went up into a mountain and sat with his disciples; the passover was nigh. Seeing the company, he said to Philip, Whence shall we buy bread, that these may eat? Two hundred pennyworth is not sufficient. Andrew said, There is a lad here with five barley loaves and two small fishes: but what are they among so many? Make the men sit down. About five thousand sat on the grass. Jesus took the loaves, gave thanks, and distributed; likewise of the fishes, as much as they would. They filled twelve baskets with the fragments. The people said, This is of a truth that prophet; and perceiving they would make him a king, he departed into a mountain alone."},
 walking:{type:'Miracle',keyVerse:20,
  story:"At evening the disciples went down to the sea, entered a ship and went toward Capernaum. It was dark, and Jesus was not come to them. A great wind blew, and the sea arose. When they had rowed about five and twenty or thirty furlongs, they saw Jesus walking on the sea and drawing nigh unto the ship; and they were afraid. But he saith unto them, It is I; be not afraid. Then they willingly received him into the ship, and immediately the ship was at the land whither they went."},
 bread6:{type:'Teaching',keyVerse:35,
  story:"The people, finding Jesus at Capernaum, were asked why they sought him: not because ye saw the miracles, but because ye did eat of the loaves. Labour not for the meat which perisheth, but for that meat which endureth unto everlasting life. What shall we do? This is the work of God, that ye believe on him whom he hath sent. Our fathers did eat manna in the desert. Moses gave you not that bread from heaven; my Father giveth you the true bread, he which cometh down from heaven and giveth life unto the world. Lord, evermore give us this bread. I am the bread of life: he that cometh to me shall never hunger. All that the Father giveth me shall come to me; and I will raise him up at the last day."},
 breadlife:{type:'Teaching',keyVerse:51,
  story:"The Jews murmured: Is not this Jesus, the son of Joseph? How is it that he saith, I came down from heaven? No man can come to me, except the Father draw him. Your fathers did eat manna in the wilderness, and are dead. I am the living bread which came down from heaven: if any man eat of this bread, he shall live for ever; and the bread that I will give is my flesh, which I will give for the life of the world. Except ye eat the flesh of the Son of man, and drink his blood, ye have no life in you. My flesh is meat indeed, and my blood is drink indeed. He that eateth me, even he shall live by me. These things said he in the synagogue at Capernaum."},
 hardsaying:{type:'Event',keyVerse:68,
  story:"Many of his disciples said, This is an hard saying; who can hear it? Doth this offend you? What and if ye shall see the Son of man ascend up where he was before? It is the spirit that quickeneth; the flesh profiteth nothing: the words that I speak unto you, they are spirit, and they are life. From that time many of his disciples went back, and walked no more with him. Will ye also go away? Simon Peter answered, Lord, to whom shall we go? thou hast the words of eternal life. And we believe and are sure that thou art that Christ, the Son of the living God. Have not I chosen you twelve, and one of you is a devil? He spake of Judas Iscariot."},

 // ---- chapter 7 ----
 brethren:{type:'Event',keyVerse:6,
  story:"Jesus walked in Galilee, for the Jews sought to kill him in Jewry. The feast of tabernacles was at hand, and his brethren said, Depart hence into Judaea, that thy disciples may see the works thou doest: if thou do these things, shew thyself to the world. For neither did his brethren believe in him. My time is not yet come: but your time is alway ready. The world cannot hate you; but me it hateth, because I testify of it, that the works thereof are evil. When his brethren were gone up, then went he also up unto the feast, not openly, but as it were in secret. The Jews sought him: Where is he? Some said, He is a good man; others, Nay, he deceiveth the people."},
 midfeast:{type:'Event',keyVerse:37,
  story:"About the midst of the feast Jesus went up into the temple and taught. The Jews marvelled: How knoweth this man letters, having never learned? My doctrine is not mine, but his that sent me. If any man will do his will, he shall know of the doctrine. Did not Moses give you the law, and yet none of you keepeth the law? Why go ye about to kill me? He reminded them that they circumcise on the sabbath: judge not according to the appearance, but judge righteous judgment. Some of Jerusalem said, Is not this he whom they seek to kill? and lo, he speaketh boldly. Ye both know me, and ye know whence I am: he that sent me is true, whom ye know not. The Pharisees sent officers to take him. Yet a little while am I with you, and then I go unto him that sent me."},
 livingwater:{type:'Teaching',keyVerse:38,
  story:"In the last day, that great day of the feast, Jesus stood and cried, If any man thirst, let him come unto me, and drink. He that believeth on me, out of his belly shall flow rivers of living water. This spake he of the Spirit, which they that believe on him should receive: for the Holy Ghost was not yet given, because Jesus was not yet glorified. The people were divided: Of a truth this is the Prophet; this is the Christ; shall Christ come out of Galilee? The officers returned without him: Never man spake like this man. Nicodemus said, Doth our law judge any man before it hear him? Search, and look: for out of Galilee ariseth no prophet. And every man went unto his own house."},

 // ---- chapter 8 ----
 adulteress:{type:'Event',keyVerse:11,
  story:"Jesus went unto the mount of Olives, and early in the morning came again into the temple and taught. The scribes and Pharisees brought a woman taken in adultery and set her in the midst: Moses commanded that such should be stoned; but what sayest thou? — tempting him, that they might have to accuse him. Jesus stooped down and with his finger wrote on the ground. He that is without sin among you, let him first cast a stone at her. Convicted by their own conscience, they went out one by one, beginning at the eldest. Woman, where are those thine accusers? hath no man condemned thee? No man, Lord. Neither do I condemn thee: go, and sin no more."},
 light8:{type:'Teaching',keyVerse:12,
  story:"I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life. The Pharisees said his record was not true because he bore it of himself. I know whence I came, and whither I go. It is written in your law that the testimony of two men is true: I bear witness of myself, and the Father that sent me beareth witness of me. Where is thy Father? Ye neither know me, nor my Father. These words spake Jesus in the treasury, and no man laid hands on him; for his hour was not yet come. I go my way, and ye shall die in your sins: for if ye believe not that I am he, ye shall die in your sins. When ye have lifted up the Son of man, then shall ye know that I am he. As he spake these words, many believed on him."},
 truth8:{type:'Teaching',keyVerse:32,
  story:"To the Jews which believed on him Jesus said, If ye continue in my word, then are ye my disciples indeed; and ye shall know the truth, and the truth shall make you free. We be Abraham’s seed, and were never in bondage. Whosoever committeth sin is the servant of sin. If the Son therefore shall make you free, ye shall be free indeed. If ye were Abraham’s children, ye would do the works of Abraham; but now ye seek to kill me. If God were your Father, ye would love me. Ye are of your father the devil, and the lusts of your father ye will do: he was a murderer from the beginning, and abode not in the truth. He that is of God heareth God’s words."},
 abraham8:{type:'Teaching',keyVerse:58,
  story:"The Jews answered, Say we not well that thou art a Samaritan, and hast a devil? I have not a devil; but I honour my Father, and ye do dishonour me. Verily, verily, I say unto you, If a man keep my saying, he shall never see death. Art thou greater than our father Abraham, which is dead? Your father Abraham rejoiced to see my day: and he saw it, and was glad. Thou art not yet fifty years old, and hast thou seen Abraham? Verily, verily, I say unto you, Before Abraham was, I am. Then took they up stones to cast at him: but Jesus hid himself, and went out of the temple, going through the midst of them."},

 // ---- chapter 9 ----
 blindman:{type:'Miracle',keyVerse:7,
  story:"As Jesus passed by, he saw a man which was blind from his birth. Master, who did sin, this man, or his parents, that he was born blind? Neither: but that the works of God should be made manifest in him. As long as I am in the world, I am the light of the world. He spat on the ground, made clay of the spittle, anointed the eyes of the blind man with the clay, and said, Go, wash in the pool of Siloam (which is by interpretation, Sent). He went his way, washed, and came seeing. The neighbours asked, Is not this he that sat and begged? Some said, This is he: others, He is like him. He said, I am he. A man that is called Jesus made clay, and anointed mine eyes, and I received sight."},
 inquiry9:{type:'Event',keyVerse:25,
  story:"They brought him to the Pharisees; it was the sabbath day when Jesus made the clay. Some said, This man is not of God, because he keepeth not the sabbath; others, How can a man that is a sinner do such miracles? What sayest thou of him? He is a prophet. The Jews called his parents, who said he was born blind but would not say how he now saw, for fear of being put out of the synagogue: he is of age; ask him. Give God the praise: we know that this man is a sinner. Whether he be a sinner or no, I know not: one thing I know, that, whereas I was blind, now I see. If this man were not of God, he could do nothing. Thou wast altogether born in sins, and dost thou teach us? And they cast him out."},
 seeing9:{type:'Event',keyVerse:38,
  story:"Jesus heard that they had cast him out, and finding him said, Dost thou believe on the Son of God? Who is he, Lord, that I might believe on him? Thou hast both seen him, and it is he that talketh with thee. Lord, I believe. And he worshipped him. For judgment I am come into this world, that they which see not might see; and that they which see might be made blind. Some of the Pharisees which were with him heard these words: Are we blind also? If ye were blind, ye should have no sin: but now ye say, We see; therefore your sin remaineth."},

 // ---- chapter 10 ----
 shepherd:{type:'Teaching',keyVerse:11,
  story:"He that entereth not by the door into the sheepfold, but climbeth up some other way, the same is a thief and a robber; the shepherd enters by the door, and the sheep hear his voice, and he calleth his own sheep by name and leadeth them out. I am the door: by me if any man enter in, he shall be saved. The thief cometh to steal, and to kill, and to destroy: I am come that they might have life more abundantly. I am the good shepherd: the good shepherd giveth his life for the sheep. The hireling fleeth, because he careth not for the sheep. I know my sheep, and am known of mine. Other sheep I have, which are not of this fold: there shall be one fold, and one shepherd. I lay down my life, that I might take it again. No man taketh it from me."},
 dedication:{type:'Event',keyVerse:30,
  story:"It was at Jerusalem the feast of the dedication, and it was winter; Jesus walked in the temple in Solomon’s porch. If thou be the Christ, tell us plainly. I told you, and ye believed not: the works that I do in my Father’s name, they bear witness of me. My sheep hear my voice, and I know them, and they follow me: and I give unto them eternal life; and they shall never perish, neither shall any man pluck them out of my hand. I and my Father are one. They took up stones again to stone him — for blasphemy, because that thou, being a man, makest thyself God. Though ye believe not me, believe the works. He escaped out of their hand and went away beyond Jordan, where John at first baptized; and many believed on him there."},

 // ---- chapter 11 ----
 lazarussick:{type:'Event',keyVerse:4,
  story:"A certain man was sick, named Lazarus, of Bethany, the town of Mary and her sister Martha. His sisters sent unto him, saying, Lord, behold, he whom thou lovest is sick. This sickness is not unto death, but for the glory of God. Jesus loved Martha, and her sister, and Lazarus; yet he abode two days still in the same place. Let us go into Judaea again. Master, the Jews of late sought to stone thee. Our friend Lazarus sleepeth; but I go, that I may awake him out of sleep. Then said Jesus plainly, Lazarus is dead. And I am glad for your sakes that I was not there, to the intent ye may believe. Thomas said unto his fellow disciples, Let us also go, that we may die with him."},
 resurrectionlife:{type:'Event',keyVerse:25,
  story:"When Jesus came, Lazarus had lain in the grave four days already. Martha went and met him: Lord, if thou hadst been here, my brother had not died. Thy brother shall rise again. I know that he shall rise again in the resurrection at the last day. I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live. Believest thou this? Yea, Lord: I believe that thou art the Christ, the Son of God. Mary came and fell down at his feet, weeping, and the Jews weeping with her. Jesus groaned in the spirit, and was troubled. Where have ye laid him? Lord, come and see. Jesus wept. Behold how he loved him!"},
 lazarus:{type:'Miracle',keyVerse:43,
  story:"Jesus came to the grave — a cave, and a stone lay upon it. Take ye away the stone. Martha saith, Lord, by this time he stinketh: for he hath been dead four days. Said I not unto thee, that, if thou wouldest believe, thou shouldest see the glory of God? They took away the stone. Jesus lifted up his eyes: Father, I thank thee that thou hast heard me. And he cried with a loud voice, Lazarus, come forth. And he that was dead came forth, bound hand and foot with graveclothes, and his face bound about with a napkin. Loose him, and let him go."},
 caiaphas11:{type:'Event',keyVerse:50,
  story:"Many of the Jews which had seen what Jesus did believed on him; but some went to the Pharisees. The chief priests gathered a council: What do we? If we let him alone, all men will believe on him, and the Romans shall come and take away our place and nation. Caiaphas, being the high priest that same year, said, It is expedient for us that one man should die for the people, and that the whole nation perish not. This spake he not of himself, but prophesied that Jesus should die for that nation, and gather together in one the children of God that were scattered abroad. From that day forth they took counsel to put him to death. Jesus walked no more openly, but went to Ephraim. The passover was nigh; and they gave a commandment that if any man knew where he were, he should shew it."},

 // ---- chapter 12 ----
 anointing:{type:'Event',keyVerse:3,
  story:"Six days before the passover Jesus came to Bethany, where Lazarus was which had been dead. They made him a supper; Martha served, and Lazarus sat at the table. Mary took a pound of ointment of spikenard, very costly, anointed the feet of Jesus and wiped his feet with her hair; and the house was filled with the odour of the ointment. Judas Iscariot said, Why was not this ointment sold for three hundred pence, and given to the poor? — not that he cared for the poor, but because he was a thief and had the bag. Let her alone: against the day of my burying hath she kept this. The poor always ye have with you; but me ye have not always. The chief priests consulted that they might put Lazarus also to death, because by reason of him many believed on Jesus."},
 entry:{type:'Feast',keyVerse:13,
  story:"On the next day much people that were come to the feast, hearing that Jesus was coming to Jerusalem, took branches of palm trees and went forth to meet him, crying, Hosanna: Blessed is the King of Israel that cometh in the name of the Lord. Jesus, having found a young ass, sat thereon; as it is written, Fear not, daughter of Sion: behold, thy King cometh, sitting on an ass’s colt. His disciples understood not these things at the first, but when Jesus was glorified they remembered. The people that were with him when he called Lazarus out of his grave bare record; for this cause the people met him. The Pharisees said among themselves, Perceive ye how ye prevail nothing? behold, the world is gone after him."},
 greeks:{type:'Teaching',keyVerse:24,
  story:"Certain Greeks that came up to worship at the feast said to Philip, Sir, we would see Jesus. Jesus answered, The hour is come, that the Son of man should be glorified. Except a corn of wheat fall into the ground and die, it abideth alone: but if it die, it bringeth forth much fruit. He that loveth his life shall lose it. Now is my soul troubled; and what shall I say? Father, save me from this hour: but for this cause came I unto this hour. Father, glorify thy name. Then came there a voice from heaven: I have both glorified it, and will glorify it again. Now is the judgment of this world: now shall the prince of this world be cast out. And I, if I be lifted up from the earth, will draw all men unto me. This he said, signifying what death he should die. Walk while ye have the light."},
 unbelief12:{type:'Teaching',keyVerse:46,
  story:"Though he had done so many miracles before them, yet they believed not on him: that the saying of Esaias might be fulfilled, Lord, who hath believed our report? He hath blinded their eyes, and hardened their heart. These things said Esaias, when he saw his glory, and spake of him. Nevertheless among the chief rulers also many believed on him; but because of the Pharisees they did not confess him, for they loved the praise of men more than the praise of God. Jesus cried, He that believeth on me, believeth on him that sent me. I am come a light into the world, that whosoever believeth on me should not abide in darkness. I came not to judge the world, but to save the world: the word that I have spoken, the same shall judge him in the last day. The Father gave me a commandment, what I should say; and his commandment is life everlasting."},

 // ---- chapter 13 ----
 washing:{type:'Event',keyVerse:14,
  story:"Before the feast of the passover, Jesus, knowing that his hour was come that he should depart out of this world unto the Father, having loved his own which were in the world, he loved them unto the end. Supper being ended, he riseth, laid aside his garments, took a towel and girded himself, poured water into a bason, and began to wash the disciples’ feet. Peter saith, Lord, dost thou wash my feet? Thou shalt never wash my feet. If I wash thee not, thou hast no part with me. Lord, not my feet only, but also my hands and my head. Ye are clean, but not all: for he knew who should betray him. Know ye what I have done to you? If I, your Lord and Master, have washed your feet; ye also ought to wash one another’s feet: for I have given you an example."},
 betrayer:{type:'Event',keyVerse:21,
  story:"I speak not of you all: I know whom I have chosen; but that the scripture may be fulfilled, He that eateth bread with me hath lifted up his heel against me. Jesus was troubled in spirit and testified, Verily, verily, I say unto you, that one of you shall betray me. The disciples looked one on another, doubting of whom he spake. There was leaning on Jesus’ bosom one of his disciples, whom Jesus loved; Simon Peter beckoned to him to ask who it should be. Lord, who is it? He it is, to whom I shall give a sop. And when he had dipped the sop, he gave it to Judas Iscariot. After the sop Satan entered into him. That thou doest, do quickly. No man at the table knew for what intent he spake this. He then, having received the sop, went immediately out: and it was night."},
 newcommandment:{type:'Teaching',keyVerse:34,
  story:"When he was gone out, Jesus said, Now is the Son of man glorified, and God is glorified in him. Little children, yet a little while I am with you; whither I go, ye cannot come. A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another. By this shall all men know that ye are my disciples, if ye have love one to another. Simon Peter said, Lord, whither goest thou? Whither I go, thou canst not follow me now; but thou shalt follow me afterwards. Why cannot I follow thee now? I will lay down my life for thy sake. Wilt thou lay down thy life for my sake? Verily, verily, I say unto thee, The cock shall not crow, till thou hast denied me thrice."},

 // ---- chapter 14 ----
 way:{type:'Teaching',keyVerse:6,
  story:"Let not your heart be troubled: ye believe in God, believe also in me. In my Father’s house are many mansions: I go to prepare a place for you, and I will come again, and receive you unto myself. Thomas saith, Lord, we know not whither thou goest; and how can we know the way? I am the way, the truth, and the life: no man cometh unto the Father, but by me. Philip saith, Lord, shew us the Father. Have I been so long time with you, and yet hast thou not known me, Philip? he that hath seen me hath seen the Father. I am in the Father, and the Father in me. He that believeth on me, the works that I do shall he do also; and greater works than these, because I go unto my Father. Whatsoever ye shall ask in my name, that will I do."},
 comforter:{type:'Teaching',keyVerse:27,
  story:"If ye love me, keep my commandments. And I will pray the Father, and he shall give you another Comforter, that he may abide with you for ever; even the Spirit of truth, whom the world cannot receive. I will not leave you comfortless: I will come to you. He that hath my commandments, and keepeth them, he it is that loveth me; and my Father will love him, and we will come unto him, and make our abode with him. The Comforter, which is the Holy Ghost, whom the Father will send in my name, he shall teach you all things, and bring all things to your remembrance. Peace I leave with you, my peace I give unto you: not as the world giveth. Let not your heart be troubled, neither let it be afraid. My Father is greater than I. The prince of this world cometh, and hath nothing in me. Arise, let us go hence."},

 // ---- chapter 15 ----
 vine:{type:'Teaching',keyVerse:5,
  story:"I am the true vine, and my Father is the husbandman. Every branch in me that beareth not fruit he taketh away: and every branch that beareth fruit, he purgeth it, that it may bring forth more fruit. Abide in me, and I in you. As the branch cannot bear fruit of itself, except it abide in the vine; no more can ye, except ye abide in me. I am the vine, ye are the branches: without me ye can do nothing. Herein is my Father glorified, that ye bear much fruit. As the Father hath loved me, so have I loved you: continue ye in my love. This is my commandment, That ye love one another, as I have loved you. Greater love hath no man than this, that a man lay down his life for his friends. Henceforth I call you not servants, but friends. Ye have not chosen me, but I have chosen you, and ordained you, that ye should go and bring forth fruit."},
 hatred15:{type:'Teaching',keyVerse:20,
  story:"If the world hate you, ye know that it hated me before it hated you. If ye were of the world, the world would love his own: but because ye are not of the world, but I have chosen you out of the world, therefore the world hateth you. Remember the word that I said unto you, The servant is not greater than his lord. If they have persecuted me, they will also persecute you. All these things will they do unto you for my name’s sake, because they know not him that sent me. If I had not done among them the works which none other man did, they had not had sin. They hated me without a cause. When the Comforter is come, the Spirit of truth which proceedeth from the Father, he shall testify of me: and ye also shall bear witness, because ye have been with me from the beginning."},

 // ---- chapter 16 ----
 spirit16:{type:'Teaching',keyVerse:13,
  story:"These things have I spoken unto you, that ye should not be offended. They shall put you out of the synagogues: yea, the time cometh, that whosoever killeth you will think that he doeth God service. Now I go my way to him that sent me; and sorrow hath filled your heart. It is expedient for you that I go away: for if I go not away, the Comforter will not come unto you. When he is come, he will reprove the world of sin, and of righteousness, and of judgment. I have yet many things to say unto you, but ye cannot bear them now. When he, the Spirit of truth, is come, he will guide you into all truth; he shall glorify me: for he shall receive of mine, and shall shew it unto you. All things that the Father hath are mine."},
 sorrow16:{type:'Teaching',keyVerse:33,
  story:"A little while, and ye shall not see me: and again, a little while, and ye shall see me, because I go to the Father. The disciples asked among themselves what this meant. Ye shall weep and lament, but the world shall rejoice; ye shall be sorrowful, but your sorrow shall be turned into joy. A woman when she is in travail hath sorrow; but as soon as she is delivered she remembereth no more the anguish, for joy that a man is born into the world. I will see you again, and your heart shall rejoice, and your joy no man taketh from you. Ask, and ye shall receive, that your joy may be full. I came forth from the Father, and am come into the world: again, I leave the world, and go to the Father. Behold, the hour cometh, that ye shall be scattered, every man to his own, and shall leave me alone. In the world ye shall have tribulation: but be of good cheer; I have overcome the world."},

 // ---- chapter 17 ----
 prayer17:{type:'Teaching',keyVerse:21,
  story:"Jesus lifted up his eyes to heaven and said, Father, the hour is come; glorify thy Son, that thy Son also may glorify thee. This is life eternal, that they might know thee the only true God, and Jesus Christ, whom thou hast sent. I have glorified thee on the earth: I have finished the work. Glorify thou me with the glory which I had with thee before the world was. I pray for them which thou hast given me; keep through thine own name those whom thou hast given me, that they may be one, as we are. None of them is lost, but the son of perdition. Sanctify them through thy truth: thy word is truth. Neither pray I for these alone, but for them also which shall believe on me through their word; that they all may be one; as thou, Father, art in me, and I in thee. Father, I will that they whom thou hast given me be with me where I am; that they may behold my glory. I have declared unto them thy name, that the love wherewith thou hast loved me may be in them, and I in them."},

 // ---- chapter 18 ----
 arrest:{type:'Event',keyVerse:11,
  story:"Jesus went forth with his disciples over the brook Cedron into a garden, which Judas knew, for Jesus ofttimes resorted thither. Judas came with a band of men and officers from the chief priests and Pharisees, with lanterns and torches and weapons. Jesus, knowing all things that should come upon him, went forth: Whom seek ye? Jesus of Nazareth. I am he. They went backward, and fell to the ground. If ye seek me, let these go their way. Simon Peter drew a sword and smote the high priest’s servant, Malchus, and cut off his right ear. Put up thy sword into the sheath: the cup which my Father hath given me, shall I not drink it?"},
 annas:{type:'Event',keyVerse:27,
  story:"The band bound Jesus and led him away to Annas first, father in law to Caiaphas, the high priest that year — Caiaphas, which gave counsel that one man should die for the people. Simon Peter followed, with another disciple known to the high priest, who brought Peter in. The damsel that kept the door said, Art not thou also one of this man’s disciples? I am not. The servants stood at a fire of coals, and Peter warmed himself with them. The high priest asked Jesus of his disciples and his doctrine. I spake openly to the world; ask them which heard me. An officer struck him with the palm of his hand. If I have spoken evil, bear witness of the evil: but if well, why smitest thou me? Annas sent him bound unto Caiaphas. Peter denied again, and a kinsman of Malchus said, Did not I see thee in the garden with him? Peter denied again: and immediately the cock crew."},
 pilate18:{type:'Event',keyVerse:37,
  story:"They led Jesus from Caiaphas unto the hall of judgment, early; and went not in themselves, lest they should be defiled, but that they might eat the passover. Pilate went out: What accusation bring ye against this man? If he were not a malefactor, we would not have delivered him up. It is not lawful for us to put any man to death. Pilate called Jesus: Art thou the King of the Jews? My kingdom is not of this world; if it were, then would my servants fight. Art thou a king then? Thou sayest that I am a king. To this end was I born, that I should bear witness unto the truth. Every one that is of the truth heareth my voice. Pilate saith, What is truth? I find in him no fault at all. Will ye that I release the King of the Jews? Not this man, but Barabbas. Now Barabbas was a robber."},

 // ---- chapter 19 ----
 eccehomo:{type:'Event',keyVerse:5,
  story:"Pilate took Jesus and scourged him. The soldiers platted a crown of thorns and put it on his head, and put on him a purple robe, and said, Hail, King of the Jews! and smote him with their hands. Pilate brought him forth wearing the crown of thorns and the purple robe: Behold the man! The chief priests cried, Crucify him. Take ye him, and crucify him: for I find no fault in him. We have a law, and by our law he ought to die, because he made himself the Son of God. Pilate was the more afraid. Whence art thou? Jesus gave him no answer. Thou couldest have no power at all against me, except it were given thee from above. If thou let this man go, thou art not Caesar’s friend. Pilate sat in the judgment seat at the Pavement, Gabbatha, about the sixth hour of the preparation of the passover: Behold your King! We have no king but Caesar. Then delivered he him unto them to be crucified."},
 crucifixion:{type:'Event',keyVerse:26,
  story:"He bearing his cross went forth into a place called Golgotha, where they crucified him, and two other with him, on either side one, and Jesus in the midst. Pilate wrote a title, JESUS OF NAZARETH THE KING OF THE JEWS, in Hebrew, Greek and Latin. What I have written I have written. The soldiers took his garments and made four parts; but the coat was without seam, and they cast lots for it, that the scripture might be fulfilled. There stood by the cross of Jesus his mother, and his mother’s sister, Mary the wife of Cleophas, and Mary Magdalene. Seeing his mother, and the disciple standing by whom he loved, he saith unto his mother, Woman, behold thy son! Then saith he to the disciple, Behold thy mother! And from that hour that disciple took her unto his own home."},
 death19:{type:'Event',keyVerse:30,
  story:"After this, Jesus knowing that all things were now accomplished, that the scripture might be fulfilled, saith, I thirst. They filled a spunge with vinegar, put it upon hyssop, and put it to his mouth. When Jesus had received the vinegar, he said, It is finished: and he bowed his head, and gave up the ghost. Because it was the preparation, that the bodies should not remain upon the cross on the sabbath day, the Jews besought Pilate that their legs might be broken. The soldiers brake the legs of the two; but when they came to Jesus and saw that he was dead already, they brake not his legs. But one of the soldiers with a spear pierced his side, and forthwith came there out blood and water. He that saw it bare record, and his record is true. A bone of him shall not be broken. They shall look on him whom they pierced."},
 burial:{type:'Event',keyVerse:41,
  story:"Joseph of Arimathaea, a disciple of Jesus, but secretly for fear of the Jews, besought Pilate that he might take away the body; and Pilate gave him leave. There came also Nicodemus, which at the first came to Jesus by night, and brought a mixture of myrrh and aloes, about an hundred pound weight. They took the body of Jesus and wound it in linen clothes with the spices, as the manner of the Jews is to bury. In the place where he was crucified there was a garden, and in the garden a new sepulchre, wherein was never man yet laid. There laid they Jesus, because of the Jews’ preparation day; for the sepulchre was nigh at hand."},

 // ---- chapter 20 ----
 tomb20:{type:'Event',keyVerse:8,
  story:"The first day of the week cometh Mary Magdalene early, when it was yet dark, unto the sepulchre, and seeth the stone taken away. She runneth to Simon Peter and to the other disciple, whom Jesus loved: They have taken away the Lord out of the sepulchre, and we know not where they have laid him. Peter and the other disciple ran both together; the other disciple did outrun Peter and came first, stooped down and saw the linen clothes lying, yet went he not in. Simon Peter came, went into the sepulchre, and seeth the linen clothes lie, and the napkin that was about his head, not lying with the linen clothes, but wrapped together in a place by itself. Then went in also that other disciple, and he saw, and believed. For as yet they knew not the scripture, that he must rise again from the dead."},
 magdalene:{type:'Event',keyVerse:16,
  story:"Mary stood without at the sepulchre weeping, and stooping down she seeth two angels in white sitting, the one at the head, and the other at the feet, where the body of Jesus had lain. Woman, why weepest thou? Because they have taken away my Lord. She turned herself back and saw Jesus standing, and knew not that it was Jesus; she, supposing him to be the gardener, saith, Sir, if thou have borne him hence, tell me where thou hast laid him. Jesus saith unto her, Mary. She turned herself, and saith unto him, Rabboni; which is to say, Master. Touch me not; for I am not yet ascended to my Father: but go to my brethren, and say unto them, I ascend unto my Father, and your Father; and to my God, and your God. Mary Magdalene came and told the disciples that she had seen the Lord."},
 doorsshut:{type:'Event',keyVerse:22,
  story:"The same day at evening, being the first day of the week, when the doors were shut where the disciples were assembled for fear of the Jews, came Jesus and stood in the midst, and saith unto them, Peace be unto you. And when he had so said, he shewed unto them his hands and his side. Then were the disciples glad, when they saw the Lord. Peace be unto you: as my Father hath sent me, even so send I you. And when he had said this, he breathed on them, and saith unto them, Receive ye the Holy Ghost: whose soever sins ye remit, they are remitted unto them; and whose soever sins ye retain, they are retained."},
 thomas:{type:'Feast',keyVerse:28,
  story:"Thomas, one of the twelve, called Didymus, was not with them when Jesus came. We have seen the Lord. Except I shall see in his hands the print of the nails, and put my finger into the print of the nails, and thrust my hand into his side, I will not believe. After eight days again his disciples were within, and Thomas with them: then came Jesus, the doors being shut, and stood in the midst. Peace be unto you. Reach hither thy finger, and behold my hands; and reach hither thy hand, and thrust it into my side: and be not faithless, but believing. Thomas answered, My Lord and my God. Because thou hast seen me, thou hast believed: blessed are they that have not seen, and yet have believed. Many other signs did Jesus which are not written in this book: but these are written, that ye might believe that Jesus is the Christ, the Son of God."},

 // ---- chapter 21 ----
 tiberias:{type:'Event',keyVerse:7,
  story:"Jesus shewed himself again to the disciples at the sea of Tiberias. Simon Peter, Thomas, Nathanael of Cana, the sons of Zebedee and two others were together. I go a fishing. They went forth, and that night they caught nothing. When the morning was come, Jesus stood on the shore, but the disciples knew not that it was Jesus. Children, have ye any meat? No. Cast the net on the right side of the ship, and ye shall find. They were not able to draw it for the multitude of fishes. That disciple whom Jesus loved saith unto Peter, It is the Lord. Peter girt his fisher’s coat unto him and cast himself into the sea. On the land they saw a fire of coals, and fish laid thereon, and bread. The net was full of great fishes, an hundred and fifty and three: and for all there were so many, yet was not the net broken. Come and dine. This is now the third time that Jesus shewed himself to his disciples after that he was risen."},
 feedsheep:{type:'Event',keyVerse:17,
  story:"When they had dined, Jesus saith to Simon Peter, Simon, son of Jonas, lovest thou me more than these? Yea, Lord; thou knowest that I love thee. Feed my lambs. A second time: Simon, son of Jonas, lovest thou me? Yea, Lord. Feed my sheep. The third time: Lovest thou me? Peter was grieved because he said unto him the third time, Lovest thou me. Lord, thou knowest all things; thou knowest that I love thee. Feed my sheep. When thou wast young, thou girdedst thyself, and walkedst whither thou wouldest: but when thou shalt be old, thou shalt stretch forth thy hands, and another shall gird thee, and carry thee whither thou wouldest not. This spake he, signifying by what death he should glorify God. Follow me."},
 beloved:{type:'Event',keyVerse:24,
  story:"Peter, turning about, seeth the disciple whom Jesus loved following — which also leaned on his breast at supper and said, Lord, which is he that betrayeth thee? Lord, and what shall this man do? If I will that he tarry till I come, what is that to thee? follow thou me. Then went this saying abroad among the brethren, that that disciple should not die: yet Jesus said not unto him, He shall not die. This is the disciple which testifieth of these things, and wrote these things: and we know that his testimony is true. And there are also many other things which Jesus did, the which, if they should be written every one, I suppose that even the world itself could not contain the books that should be written. Amen."},
};
