// Prose readings for the remaining icons.
module.exports={
'File:Second Coming by G.Klontzas (16th c.).jpg':
 "A Cretan icon of the Second Coming \u2014 the Deutera Parousia \u2014 painted by Georgios Klontzas at the end of the sixteenth century. Christ sits in judgment in the mandorla at the top, the Theotokos and the Forerunner turned toward him in entreaty. Below them stands the Hetoimasia, the throne prepared and empty, bearing the cross; the twelve apostles are enthroned to either side. From beneath the throne the river of fire runs the whole height of the icon and gathers at the foot of it into the mouth of hell. On the left the ranks of the saved stand in order \u2014 patriarchs, bishops, monks, martyrs; along the bottom the earth and the sea give up their dead. This is the icon the Church sets against the whole of the discourse on the Mount of Olives: the sign of the Son of Man appearing in heaven, and all the tribes of the earth seeing him come with power and great glory.",
'File:Christ banish tradesmen from Temple (Monreale).jpg':
 "A twelfth-century mosaic from Monreale in Sicily, worked by Byzantine craftsmen. Christ, the scourge of cords raised in his right hand, overturns the money-changers' table \u2014 the coins are still scattered across it \u2014 while the sellers draw back with their oxen and sheep and a cage of doves hanging above them. The Latin inscription names exactly what he cast out: those selling doves and oxen, and the tables. What Matthew records next is the point of the cleansing: with the traders gone, the blind and the lame came to him in the temple and he healed them, and the children cried Hosanna to the Son of David.",
'File:Cathedral (Monreale) - North arch of transept - Adoration by the Magi.jpg':
 "A twelfth-century mosaic from Monreale in Sicily, worked by Byzantine craftsmen for a Norman king — Eastern iconography in a Western church. The Magi approach the Theotokos enthroned with the Child, offering gold, frankincense and myrrh. The Fathers read the three gifts as a confession: gold to a king, incense to God, myrrh to one who will die and be buried.",
'File:Menologion of Basil II - Flight into Egypt.jpg':
 "A miniature from the Menologion of Basil II, made in Constantinople about the year 1000 — one of the great illuminated books of Byzantium. Joseph leads the ass on which the Theotokos carries the Child out of the land of Israel by night. The icon is quiet and small: the Lord of all is a refugee on a borrowed animal.",
'File:Massacre of the Innocents (Ionian, 17th c., Byzantine museum).jpg':
 "A seventeenth-century icon of the Ionian school. The Church commemorates the fourteen thousand Holy Innocents on the 29th of December, four days after the Nativity, and counts them the first martyrs — children who bore witness by dying for Christ before they could speak. Rachel weeping for her children stands in the icon for every mother of them.",
'File:Christos Prodomo Dionysiou.jpg':
 "Christ enthroned with St John the Forerunner — the Athonite version of the Deesis, in which the Forerunner stands as intercessor beside the Lord. He is painted gaunt and wild-haired, holding a scroll with his own preaching. He is the last of the prophets and the first to point: Behold the Lamb of God.",
"File:Christ's temptation (Monreale).jpg":
 "The Temptation in the wilderness, from Monreale. The Latin inscription carries the devil’s words: If thou be the Son of God, command that these stones be made bread. The tempter is painted as a dark winged figure — a fallen angel, not a beast: the temptations of Christ are addressed to the mind, and are answered each time out of Deuteronomy.",
'File:Iomenos Asthenoun tas apo Poikilon noson.jpg':
 "Christ healing those sick of divers diseases — an Athonite fresco from the katholikon of Dionysiou on Mount Athos, painted in 1547 by a master of the Cretan school. The crowd presses in from every side and Christ reaches into it. Matthew closes chapter 4 with exactly this summary of the whole Galilean ministry.",
'File:105 Christ Enthroned Icon from Saint Paraskevi Church in Langadas.jpg':
 "Christ enthroned, from the icon collection of St Paraskevi in Langadas, northern Greece. He holds the open book — the Gospel is not an object he carries but the word he is — and blesses with the other hand. Where the Church has no narrative icon of a teaching, this is the icon she sets over it.",
'File:Christ cleans leper man.jpg':
 "The cleansing of the leper, from the Monreale mosaics. The Latin above carries the leper’s own words: Thou canst make me clean. What the icon shows and the law forbade is the touch: Jesus put forth his hand and touched him. Contact with a leper made a man unclean; here the current runs the other way.",
'File:Iomenos Gon Ekatonarchou Dionysiou.jpg':
 "Christ and the centurion, from Dionysiou on Mount Athos. The soldier kneels or stands at a distance, and the servant lies on a bed behind him. His words are said at every Orthodox Liturgy before communion, in the priest’s prayer: I am not worthy that thou shouldest enter under my roof.",
"File:Monreale - Jesus heals Simon's mother in law.jpg":
 "Peter’s mother-in-law, healed of a fever, from Monreale. Christ takes her hand and raises her; the Latin names the fever. The detail the icon preserves is what she did next: she arose, and ministered unto them. Healing in the Gospels is never an end in itself.",
'File:Hrist utišava buru na moru, manastir Gračanica.jpg':
 "Christ stilling the storm, a fresco from the monastery of Gračanica in Kosovo, built by King Milutin in 1321. The boat rides waves painted as hard scrolling ridges, the disciples crowd toward the stern, and Christ rebukes the sea. Byzantine painting shows water as pattern rather than motion — what is dangerous is not the wave but the fear.",
'File:Christos Iomenos Daimonon Takophon Dionysiou.jpg':
 "The healing of the dumb man possessed with a devil — Athos, Dionysiou, 1547. The Greek titulus painted across the top names the scene exactly: τὸν δαιμονῶντα κωφόν, the dumb demoniac. He was brought to Christ by others, because he could not ask anything for himself; and when the devil was cast out, the dumb spake. It is the last of the ten miracles Matthew gathers into chapters 8 and 9, and the one after which the Pharisees said that he cast out devils by the prince of the devils.",
'File:Christos Iomenos Paralyton Dionysiou.jpg':
 "The healing of the paralytic, from Dionysiou. The man is shown twice in the same frame — lying before Christ and walking away with his bed on his shoulder. Byzantine icons often paint two moments together, because the icon is not a photograph of an instant but the whole event held still.",
'File:090 Mathew the Apostle Icon from Saint Paraskevi Church in Langadas.jpg':
 "St Matthew the Apostle and Evangelist — the publican whose calling this passage records, and the writer of this Gospel. He is painted with the book he wrote. The Church keeps his feast on the 16th of November, and reads at it the very verses in which Christ said to him, Follow me.",
'File:Daughter of the head of synagogue is resurrected by Christ.jpg':
 "The raising of Jairus’s daughter, from Monreale. Christ takes the girl by the hand on her bed while the mourners stand by — the minstrels and the noisy crowd Matthew mentions, put outside before the miracle. The maid is not awakened but raised: the Greek word is the one used of the Resurrection.",
'File:Christos Iomenos Typhlon.jpg':
 "Christ healing a blind man — Athos, Dionysiou, 1547. The Greek titulus is singular, τὸν τυφλόν, and the man is painted twice: once before Christ, and once bending over a cross-shaped basin of water at the right. That basin is the pool of Siloam, so the fresco is the healing of the man born blind of John 9, which the Orthodox lectionary reads on the Sunday of the Blind Man — not the two blind men of Matthew 9:27–31, whose cry, Thou Son of David, have mercy on us, this passage records. It is set here because the Athonite cycle paints the blind man of the lectionary and not Matthew's pair.",
'File:Iomenos Daimonizomenon Dionysiou.jpg':
 "Christ delivering one possessed by a devil — Dionysiou, Athos. The demon is painted small and dark, leaving the man’s mouth or head, and Christ commands with a gesture rather than a struggle. Orthodox iconography gives evil no grandeur: it is shown as small, black and outmatched.",
'File:Elkomenos Prodromos Phylaken Dionysiou.jpg':
 "St John the Forerunner led away to prison — Dionysiou, Athos. The Greek titulus names the scene. It is from that prison that John sent his disciples to ask, Art thou he that should come? The greatest of those born of women is painted being dragged by a soldier, and asks a question.",
'File:Christos Pantokrator Dionysiou.jpg':
 "Christ Pantocrator in the dome of the katholikon at Dionysiou. He blesses with the right hand and holds the Gospel in the left, looking down on the whole church from the height. This is the face the Church raises over the words Come unto me, all ye that labour and are heavy laden, and I will give you rest.",
'File:Iomenos xeran echon cheira Dionysiou.jpg':
 "The healing of the man with the withered hand, in the synagogue on the sabbath — Dionysiou, Athos. The Pharisees sit on either side watching. Christ heals in front of them and asks the question the icon leaves hanging: is it lawful to do well on the sabbath days?",
'File:Iomenos Daimonizomenous Dionysiou.jpg':
 "The two demoniacs of the Gadarenes — Athos, Dionysiou, 1547. The Greek titulus is plural, τοὺς δαιμονιζομένους, and the fresco paints both the men Matthew describes: coming out of the tombs, exceeding fierce, so that no man might pass by that way. Mark and Luke tell the same miracle of one man only; St Augustine supposes that the one they name was the better known of the two, and that the whole country grieved for him.",
'File:Prophetes Ionas Ketos Dionysiou.jpg':
 "The prophet Jonah and the great fish, Dionysiou, Athos. Christ himself gave this as the only sign that would be given: as Jonas was three days and three nights in the whale’s belly, so shall the Son of man be three days and three nights in the heart of the earth. The Church reads the book of Jonah entire at the Paschal Vigil.",
'File:Theotokos Panachranta Dionysiou.jpg':
 "The Theotokos Panachranta — the All-Immaculate — from Dionysiou on Mount Athos. She is enthroned with the Child. The Church sets her image over the words Whosoever shall do the will of my Father which is in heaven, the same is my brother, and sister, and mother: she is the first and the pattern of that obedience.",
'File:Apotome Agiou Ioannou Prodromou Dionysiou.jpg':
 "The Beheading of the Forerunner, Dionysiou, Athos. The Church keeps this feast on the 29th of August as a strict fast — one of the few days of mourning in the calendar that is not for Christ himself. The icon shows both the executioner’s stroke and the head already on the charger.",
'File:Evlogesis Pente Arton Dionysiou.jpg':
 "The blessing of the five loaves — Dionysiou, Athos. Christ blesses, the disciples distribute, the multitude sits on the green grass, and the baskets of fragments stand in the foreground. He took, blessed, brake and gave: the four verbs of the Eucharist, which is why this icon is never far from the Mystical Supper.",
'File:Monreale - Peter Saved from the Waves.jpg':
 "Christ catching Peter as he begins to sink, from Monreale. The mosaic keeps the exact moment Matthew records — Jesus stretched forth his hand, and caught him. Peter is painted already half in the water: the icon is honest about how far he had got before the hand came.",
'File:Christos Iomenos Thygatera Xananaias Dionysiou.jpg':
 "Christ and the Canaanite woman, Dionysiou, Athos. She kneels and will not be sent away; her daughter lies at home. Her answer — the dogs eat of the crumbs which fall from their masters’ table — drew from Christ a word he said to no one else: O woman, great is thy faith.",
'File:Monreale - Multiplication of the Loaves and Fishes.jpg':
 "The multiplication of the loaves, from the Monreale mosaics. Christ blesses, the crowds are seated in ranks, and the baskets are gathered. Matthew records two such feedings; the second, of four thousand, follows the healings on the mountain, and the Fathers read the two together as the calling first of Israel and then of the nations.",
'File:The Good Shepherd from the Imperial Palace of Constantinople 5th-6th century AD.jpg':
 "A floor mosaic from the Great Palace of Constantinople, fifth or sixth century — one of the oldest Christian images of the shepherd. Before the Church painted Christ bearded and enthroned she painted him as a countryman with a flock. Doth he not leave the ninety and nine, and goeth into the mountains, and seeketh that which is gone astray?",
'File:Workers in the vineyard, Minuscule 269 (11th century).jpg':
 "A miniature from an eleventh-century Byzantine Gospel manuscript. The householder hires labourers at the gate in the upper register; in the lower they work the vines. The parable is the Church’s image for the vineyard passages of Matthew: the eleventh-hour labourer receives the same penny, and the last shall be first.",
'File:Christ heals two Jericho blind men.jpg':
 "The two blind men of Jericho, from Monreale. They cry out over the crowd’s rebuke — Have mercy on us, O Lord, thou Son of David — and Christ stands still and touches their eyes. The Jesus Prayer of the Orthodox Church is built out of their words.",
'File:074 Cursing the fig tree Icon from Saint Paraskevi Church in Langadas.jpg':
 "The cursing of the fig tree, a nineteenth-century Greek icon from St Paraskevi in Langadas. The tree stands full of leaves and empty of fruit, and withers at a word. The Fathers read it as a parable acted rather than spoken: a show of religion with nothing under it cannot survive the Lord’s hunger for fruit.",
'File:Parable of the Wedding Feast 04-14.jpg':
 "The parable of the wedding feast, painted by Dionisius at the Ferapontov Monastery in 1502 — the finest surviving Russian fresco cycle of its age. The tables are set and the servants go out into the highways. At the edge of the scene stands the man without a wedding garment, who came in and was cast out.",
'File:Christ, last judgment, narthex, GRACANICA 7 D39A0936.jpg':
 "Christ in glory, from the Last Judgment in the narthex of Gračanica. The narthex — the porch a worshipper passes through on the way in — is where the Orthodox Church habitually paints the Judgment, so that no one enters the nave without walking under it. Matthew 24 is its text: they shall see the Son of man coming in the clouds of heaven.",
'File:Monreale - Anointing at Bethany.jpg':
 "The anointing at Bethany, from Monreale. The woman breaks the alabaster box over Christ’s head at table while the disciples object to the waste. She hath wrought a good work upon me: in that she hath poured this ointment on my body, she did it for my burial. The Orthodox Church sings of her through Holy Wednesday.",
'File:Judas receiving money, icon of Yaroslavl (19 c, priv.coll).jpg':
 "Judas receiving the thirty pieces of silver — a nineteenth-century icon of the Yaroslavl school. The priests count out the money on the table. Thirty pieces was the price of a slave in the law of Moses, and Zechariah had already named the sum: a goodly price that I was prised at of them.",
'File:Alektor Petrou Dionysiou.jpg':
 "Peter and the cock, Dionysiou, Athos. The scene is set in the high priest’s courtyard where Peter sat with the servants; the bird is painted small on a wall or roof. Before the cock crow, thou shalt deny me thrice. The icon of the denial is also the icon of the tears that followed it.",
"File:The Lord's prayer in Gethsemane - Stavronikita monastery, Mt Athos - Theophanes of Crete, 16th c..jpg":
 "The prayer in Gethsemane, painted by Theophanes the Cretan at Stavronikita on Mount Athos in the sixteenth century — Theophanes is the master of the Cretan school and one of the great Orthodox iconographers. Christ prays alone on the rock while the three disciples sleep below. O my Father, if it be possible, let this cup pass from me: nevertheless not as I will, but as thou wilt.",
'File:Prodosia Dionysiou.jpg':
 "The Betrayal — Prodosia — from Dionysiou on Athos. Judas takes Christ by the shoulders to kiss him while the crowd closes in with swords and staves and torches; at the edge Peter strikes at Malchus. Friend, wherefore art thou come? The icon leaves Christ perfectly still at the centre of a scene made entirely of motion.",
'File:Krinomenos Christou Dionysiou.jpg':
 "Christ being judged, Dionysiou, Athos. He stands before the seated authority, bound, answering nothing. The composition is deliberately reversed from the icons of Christ enthroned: the Judge of all stands, and men sit above him.",
'File:Ypestrepseta Triakonta Argyria Ioudas.jpg':
 "Judas returning the thirty pieces of silver — Dionysiou, Athos. He casts down the money in the temple; the priests refuse it. I have sinned in that I have betrayed the innocent blood. The Fathers distinguish his remorse sharply from Peter’s repentance: both wept, but only one went back to the Lord.",
'File:Aponepsis Pilatou Dionysiou.jpg':
 "Pilate washing his hands — Dionysiou, Athos. The governor is enthroned and a servant pours water over his fingers while Christ stands to one side. I am innocent of the blood of this just person: see ye to it. The icon fixes the moment a man performs a ritual of innocence in the act of committing the crime.",
'File:Mnemeion Christou Dionysiou.jpg':
 "Peter and John at the empty tomb — Dionysiou, Athos. The inscription reads Ο ΔΕ ΠΕΤΡΟΣ ΚΑΙ ΙΩΑΝΝΗΣ ΕΔΡΑΜΟΝ ΕΠΙ ΤΟ ΜΝΗΜΕΙΟΝ, but Peter and John ran to the tomb, which is John 20:3, and the grave-clothes lie inside the open sepulchre marked Ο ΑΓΙΟΣ ΤΑΦΟΣ. There is no stone, no seal and no watch: it is not the sealing of the tomb, and it depicts no passage of Matthew. Kept only as the record of that finding.",

// Readings for the further icons of a scene. Each one says where and when it was made and
// what it does differently from the icon it stands beside — that difference is the reason it
// is here at all.
"File:Icon with the Virgin of the Tree of Jesse. 1666 (8384481474).jpg":
 "A Cretan icon of 1666 by Theodore Poulakis, recovered after a theft and now kept in the Byzantine and Christian Museum in Athens. Where the Athonite tree ranges the kings along its branches, Poulakis sets the Theotokos enthroned with the Child at the centre of the tree and turns the whole genealogy toward her: Matthew's list of forty-two generations ends in a person, not a name.",
"File:Tree of Jesse icon (17 c.).jpg":
 "A seventeenth-century Russian panel of the same subject, and the plainest way the genealogy has ever been painted: the ancestors are set out in ranks on a gold ground, generation above generation, each in his own small compartment. It reads exactly as Matthew's first chapter reads aloud — a list, and at the end of the list, Christ.",
"File:031 Nativity of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":
 "A Greek icon from the collection of St Paraskevi at Langadas, inscribed Η ΓΕΝΝΗCΙC ΤΟΥ ΧΡΙΣΤΟΥ. The cave behind the Child is painted almost black — Orthodox painters give the Nativity a dark cave and a manger shaped like a tomb, because the birth is already read in the light of the burial. Joseph sits apart at the lower left, which is where Matthew's account puts him: troubled, and told what to do in a dream.",
"File:12 Nativity of Jesus Icon in Assumption of Mary Church in Agios Vasileios.jpg":
 "The same feast from a village church of the Dormition at Agios Vasileios, on a panel a foot and a half high. The arrangement every Orthodox Nativity keeps is all here and crowded together: the dark cave at the centre, the Theotokos reclining beside the manger, the ranks of angels above, and the attendant scenes gathered around the edges of the board.",
"File:Nativity Icon Panagia Evraidos Church 19 Century.jpg":
 "A nineteenth-century Greek icon from the church of Panagia Evraidou. Its ground is landscape — green hills and a blue sky rather than gold — which is the late Greek manner, but the reading is unchanged: a single ray comes down from the star to the cave, and everything in the picture is turned toward the Child at the end of it.",
"File:Cathedral (Monreale) - North arch of transept - Journey of the Magi.jpg":
 "The panel that comes immediately before the Adoration in the Monreale cycle, and the only image in this reader of the first half of these verses: the three kings still on the road, one of them pointing back at the star. The Latin above them reads MAGI VIDENTES STELLAM IN ORIENTE VENERUNT IN HIERUSALEM — the Magi, seeing the star in the east, came to Jerusalem.",
"File:Flight into Egypt Icon Mary Evraida Church Kastoria.jpg":
 "A nineteenth-century icon from Kastoria in northern Greece. The Theotokos rides with the Child while Joseph walks ahead and turns back toward them — the gesture Byzantine painters give him for the whole journey. He is leading, and he keeps looking round to see that they are still behind him.",
"File:Cathedral (Monreale) - South arch of transept - Flight into Egypt.jpg":
 "The Sicilian mosaic version, worked by Byzantine craftsmen for a Norman king. Joseph leads the ass, a second figure walks behind, and the gate of a walled city stands ready at the right: the Latin inscription says that Christ, with Mary his mother and Joseph, goes into Egypt. The Fathers read the flight as the beginning of the exile that the whole Gospel undoes.",
"File:Flight into Egypt (12 Sinai).jpg":
 "A detail from a twelfth-century Nativity icon at St Catherine's on Sinai: the Flight painted small, as one episode along the edge of a larger feast. Gold ground, a walled city, the ass and the two travellers — the whole of Matthew 2:13–15 in a few inches of panel, which is how the Byzantine feast icons usually carry it.",
"File:Menologion of Basil II - Massacre of the Innocents.jpg":
 "A miniature from the Menologion of Basil II, made in Constantinople about 985 for the emperor's own use. Herod is enthroned at the left under a canopy and gives the order; the soldiers do the work at the right. The book is a calendar of the Church's saints, and the Innocents have their own day in it — the 29th of December, four days after the Nativity.",
"File:Detail of the Massacre of the innocents mosaic at Chora (1).jpg":
 "A detail from the great fourteenth-century mosaic cycle of the Chora church in Constantinople. The mosaicist reduces the whole slaughter to one soldier and one child held up by the ankle, and it is the hardest image in that building to stand in front of: the same gold that carries every feast in the church carries this.",
"File:St John the Baptist Late XVII - Early XVIII Cenury St Mary Blonichka Church, Ohris Icon Gallery.jpg":
 "An Ohrid icon of the late seventeenth or early eighteenth century, of the type the Greeks call the Angel of the Desert. The Forerunner is given wings because of the prophecy Matthew quotes over him — Behold, I send my messenger before thy face — and the Greek for messenger is angelos. He holds a scroll with his own preaching, and beside him stands the dish with his head on it, so that the icon shows his whole life and its end at once.",
"File:019 Baptism of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":
 "A Greek icon signed by Athanasios Margaritis and dated 1850, inscribed Η ΒΑΠΤΙCΙC ΤΟΥ ΧΡΙΣΤΟΥ. The Jordan is painted as a dark upright shaft of water with Christ standing inside it, the Forerunner on the left with his hand on the Lord's head, the angels waiting on the right with their hands covered — you cover your hands to receive a king.",
"File:03 Baptism of Christ Icon from Saint Paraskevi Church in Adam.jpg":
 "The same feast from the village of Adam in northern Greece, on a small panel. The mountains close in on both sides and the water is a narrow green channel; Christ stands in it with his hand raised in blessing over the river, which is what the Fathers say he is doing there. He does not take holiness out of the water. He puts it in.",
"File:0663Ha. Hermitage Museum (Hall 143). Icon of the Epiphany.jpg":
 "A Russian icon of the third quarter of the seventeenth century, from the Russian North, now in the Hermitage. The Russians keep the Greek arrangement and change its temper: the Jordan becomes a deep dark trough between red-brown banks, and the angels crowd the whole right side of the board. The Greek Church calls the feast Theophany rather than the Baptism, because what the Fathers read in it is the Trinity made plain — the Son in the water, the Spirit descending, the Father's voice.",
"File:Cathedral (Monreale) - Right wing transept - 2nd Temptation of Christ.jpg":
 "The panel that follows the first temptation along the same wall at Monreale. The devil has set Christ on a pinnacle of the temple — painted as a small domed building under his feet — and the two inscriptions carry the exchange: SI FILIUS DEI ES MITTE TE DEORSUM, if thou be the Son of God, cast thyself down, answered by SCRIPTUM EST NON TENTABIS DOMINUM DEUM TUUM, it is written, thou shalt not tempt the Lord thy God. Every answer Christ gives in this passage is a quotation from Deuteronomy.",
"File:Monreale - healing of paralytic.jpg":
 "The Sicilian mosaic of the same miracle. Christ is enthroned at the left, and the healed man is shown twice in one frame — lying on the bed as he is carried in, and again walking off with that bed on his shoulder. Showing one man twice is how Byzantine art tells a story in a single picture, and here the two halves of the panel are the two halves of the command: Arise, take up thy bed, and go unto thine house.",
"File:Healing of the Paralytic 04-17.jpg":
 "From the fresco cycle Dionisy painted in the Ferapontov monastery in 1502 — the finest Russian wall-painting of its age, and the same hand and the same walls that give this reader the marriage feast and the ten virgins. The colours are Dionisy's pale rose, blue-green and ochre; the bed is carried in low on the left while Christ speaks from the right, and the buildings behind them lean together as Russian painters liked to set them.",
"File:Matthew the Evangelist - icon.jpeg":
 "A Russian icon from Palekh, the icon-painting town in the Ivanovo region, painted about the middle of the nineteenth century. Matthew sits at his writing desk with the angel at his shoulder. The angel is his symbol among the four living creatures, given to him because his Gospel opens with the human descent of Christ — the genealogy this reader began with. Like the Greek icon beside it, this is the apostle's own portrait rather than a picture of his calling.",
"File:Raising of Jairus' daughter 03-19.jpg":
 "Dionisy's fresco at Ferapontov, 1502. The girl lies on a high bed across the middle of the wall and Christ comes to her from the right; the crowd Matthew describes — the minstrels and the people making a noise — is pressed into the left of the scene. Russian wall-painting of this school keeps its figures long and almost weightless, so that the whole miracle seems to happen without effort, which is the point of it.",
"File:Tokalı Kilise Raising of daughter of Jairus - 2004 6964.jpg":
 "From the Tokalı church at Göreme in Cappadocia, one of the churches cut into the rock there, whose paintings belong to the tenth century. The Cappadocian painters worked quickly and plainly on a rough surface, and the miracle is cut down to what it needs: the bed, the child, and the hand of Christ reaching for hers.",
"File:Mosaic of the exorcism of the Gerasene demoniac from the Basilica of Sant'Apollinare Nuovo.jpg":
 "One of the oldest surviving images of this miracle: an early sixth-century mosaic in Sant'Apollinare Nuovo at Ravenna, made while the city still worked in the Byzantine manner. Christ stands in the purple with an apostle beside him, the possessed man crouches naked in the middle, and the swine are already running down the slope into the water at the right. Ravenna paints one possessed man where Matthew names two — Mark and Luke tell the miracle with one — so what fixes this as Matthew's scene is the herd going over the edge.",
"File:Synaxis of the Twelve Apostles Dimitar Molerov Rila Monastery 1835.jpg":
 "A Bulgarian icon of 1835 by Dimitar Molerov, from the Rila monastery. The Synaxis is the feast of the 30th of June, the day after Peter and Paul, on which the Church commemorates all twelve together — which is why it is the image set over their sending out rather than any picture of the sending itself. Molerov ranks them close together, each with his scroll or his book.",
"File:The Twelve Apostles, with later gilding, Greek, Late Byzantine, early 1300s, tempera and gold leaf on wood panel - Princeton University Art Museum - DSC06701.jpg":
 "A late Byzantine panel of the early fourteenth century, tempera and gold leaf on wood, now in the Princeton University Art Museum; the gilding on it is a later addition. The twelve stand in three close ranks against gold, so tightly packed that the haloes overlap — a company rather than twelve portraits, which is exactly what Matthew's list of their names is.",
"File:Prophetes Ionas Dionysiou.jpg":
 "The prophet standing with his scroll, from the same Athonite programme of 1547 that gives this passage its icon of him cast up by the sea. Here he is simply the man — no whale, no Nineveh. The Church reads him as the sign Christ names in these verses: as Jonah was three days and three nights in the whale's belly, so shall the Son of man be three days and three nights in the heart of the earth.",
"File:103 Beheading of Saint John the Baptist Icon from Saint Paraskevi Church in Langadas.jpg":
 "A Greek icon of 1927 from Langadas, given by a donor whose name is written into its inscription. It shows nothing but the head of the Forerunner lying on its dish, which is verse 11 of this passage and no more of it: his head was brought in a charger, and given to the damsel. The Church keeps the day of the beheading as a strict fast.",
"File:19 Beheading of Saint John the Baptist Icon in Assumption of Mary Church in Agios Vasileios.jpg":
 "A village icon of the whole scene. The executioner stands over the body with his sword still raised, the prison is the barred window behind him, and Salome waits at the right with the dish already held out. Matthew tells it as a court story — a birthday, a dance, a rash oath — and the icon keeps the palace wall in the background to say so.",
"File:Feeding the multitude, Sant'Apollinare Nuovo, Ravenna.jpg":
 "A sixth-century mosaic from Sant'Apollinare Nuovo at Ravenna. Christ stands at the centre in the purple with his hands out to either side, and two disciples hold up the loaves and the fishes to him: the miracle caught at the blessing rather than the distribution. There are five figures and no landscape at all — sixth-century Ravenna tells the story with nothing to spare.",
"File:042 Transfiguration of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":
 "Signed by the painter Stavros Margaritis of Kolakia and dated 1885, with Peter, John and James named in the inscription. Christ stands in a white mandorla with Moses and Elias turned in toward him, and the three disciples are thrown down the slope beneath. The Greek word the Gospel uses is metamorphosis — he was changed; and the Fathers insist the light was his own, not lent to him.",
"File:Icon of the Transfiguration from Saint Catherine's, Sinai.jpg":
 "Another twelfth-century panel from the monastery of St Catherine on Sinai, where the mountain of Moses stands over the wall. The ground is gold and the hill green, the mandorla is left open rather than filled with rays, and the three disciples fall in three different directions — the painter's way of saying that not one of them could stay standing.",
"File:Icon of transfiguration (Spaso-Preobrazhensky Monastery, Yaroslavl).jpg":
 "A large Russian panel of about 1516, over five feet high, from the Saviour-Transfiguration monastery at Yaroslavl — the house named for this feast. Russian painters add what the Greeks usually leave out: Christ leading the three up the mountain at one side and bringing them down at the other, so that the icon carries the whole of Matthew 17 at once — the ascent, the vision, and the charge on the way down to tell the vision to no man.",
"File:Ravenna — The Good Shepherd mosaic.jpg":
 "The mosaic in the mausoleum of Galla Placidia at Ravenna, made about 425, and the best known of all the Good Shepherd images. He sits among his sheep on a rocky hillside in gold and purple, holding a tall cross like a shepherd's staff and reaching out to touch one of them. It is the same subject as the Constantinopolitan floor this passage leads with, but here the shepherd is unmistakably the Lord enthroned — the ninety and nine left on the hills, and the hand already out toward the one.",
"File:005 Entry into Jerusalem Icon from Saint Paraskevi Church in Langadas.jpg":
 "Inscribed Η ΒΑΙΟΦΟΡΟC, the Palm-bearing, which is the Greek name of the feast. Christ rides side-saddle on the ass with the disciples massed behind him, the mount of Olives at his back and the gate of the city ahead; children spread garments in the road and one of them is up in the palm tree. Matthew ends the passage with the city moved and asking, Who is this?",
"File:18 Triumphal entry into Jerusalem Icon from Saint Paraskevi Church in Adam..jpg":
 "Signed by Athanasios of Adam and dated 1846, from the same northern Greek village tradition as several icons in this reader. The whole panel is built on the diagonal of the animal's walk, from the rock at the left to the wall at the right, so that the icon has the movement of a procession in it — which is what the feast is: the Church walks this passage every Palm Sunday with branches in its hands.",
"File:Entry into Jerusalem (Afon icon).jpg":
 "A sixteenth-century Athonite icon, and the sparest of the three. Christ in a dark blue mantle rides against an almost bare red-gold ground; the disciples are a single mass behind him, the tree and the city are reduced nearly to signs. Athonite painting of this century strips a feast down to its one gesture and trusts the gesture to carry it.",
"File:Rossano Gospels - Cleansing of the Temple.jpg":
 "From the Rossano Gospels, a Greek Gospel book of the sixth century written in silver on parchment dyed purple — the oldest illustrated Gospel manuscript that survives. The scene runs in a band across the top of the page: Christ with his arm raised, the table going over, the sellers scattering with their oxen. Beneath it four prophets stand holding scrolls, each with the text from his own book that the painter read as pointing at the scene above — the manuscript argues its case as it illustrates it.",
"File:Fig tree cursed 04-16.jpg":
 "Dionisy's fresco at the Ferapontov monastery, 1502. Christ stands with the disciples at the left and the tree at the right has already gone bare; the buildings of the city lean in behind them. The Fathers read the tree as the temple Christ has just cleansed — full of leaves, with nothing on it to eat — which is why the icon is painted inside the walls of a city rather than out on a road.",
"File:Ten virgins 05-15.jpg":
 "Dionisy's fresco of the parable, 1502. Christ sits enthroned at the centre as the bridegroom; the virgins come toward him in two files, the ones with their lamps burning and the ones who have run out. Orthodox churches carry very few parables on their walls — this one cycle at Ferapontov gives this reader both the marriage feast and the ten virgins, and there is almost nowhere else to look for them.",
"File:John Tokhabi, Last Judgment, around 1100. Icon, tempera. St Catherine monastery on Sinai, Egypt.jpg":
 "An icon of about 1100 from the monastery of St Catherine on Sinai, signed in Georgian by its painter, John Tokhabi — among the earliest full Last Judgments to survive on a panel rather than a wall. The whole judgment is set out in registers, one above another: Christ at the top, the throne prepared beneath him, the ranks of the saints, and the river of fire running down the side of the board to the dark at its foot.",
"File:05 Last Supper Icon from Saint Paraskevi Church in Adam.jpg":
 "Signed by Asterios Ioannou Anagnostos and dated 1898, inscribed ὁ δεῖπνος ὁ μυστικός — the Mystical Supper, which is what the Orthodox Church calls this meal. The table is set with a single dish, John leans against the Lord, and one figure reaches across the cloth: the reach is how the painters show the hand that dipped in the dish with him, without having to name the man.",
"File:Kirillo-Belozersky iconostasis 12 - Last Supper.jpg":
 "From the festival tier of the iconostasis of the Dormition cathedral at the Kirillo-Belozersky monastery, painted in 1497 — one of the great surviving Russian icon screens. The table is tilted up toward the viewer so that nothing on it can be hidden, and the apostles run round it in one unbroken curve. An icon from an iconostasis was made to be seen from below and at a distance, which is why it is composed so simply.",
"File:Gethsemane Dionysiou.jpg":
 "The same subject as the icon this passage leads with, from the katholikon of Dionysiou; Commons gives this fresco to Theophanes the Cretan, who painted the Stavronikita version, though the Dionysiou programme as a whole is usually given to Tzortzis. Christ kneels alone at the top of the rock and the three disciples lie asleep below it. Matthew has him come back to them three times; the icon paints the sleep, not the waking.",
"File:Cathedral (Monreale) - Right wing transept - Agony in the Garden.jpg":
 "The Sicilian mosaic. Christ prays at the right with the angel bending down out of the gold toward him, and the disciples are heaped together asleep across the middle of the panel. The mosaicists give the sleeping men as much of the picture as the prayer, which is fair to the text: half of what Matthew reports here is what the disciples could not do.",
"File:Judas's kiss (Monreale).jpg":
 "The Monreale mosaic of the betrayal, with TRADITIO — the handing over — written above it. The crowd fills the whole ground with staves and torches, and at the centre of it Judas has both arms round the Lord's shoulder and their two heads are together. What Matthew records is what met the kiss: Friend, wherefore art thou come?",
"File:Kiss of Judas (Church of Saint Nicolas the Orphan).jpg":
 "A fourteenth-century fresco from the church of St Nicholas Orphanos in Thessaloniki, one of the finest small Palaiologan programmes anywhere. The painter crowds the frame with spears and lit torches and sets the kiss in the middle of the press, so that the arrest is already happening around the two figures while they are still face to face.",
"File:Christ before Caiaphas, GRACANICA 1 090A7764.jpg":
 "From the north aisle of Gračanica, about 1320. Caiaphas sits raised on his seat with the elders around him and Christ stands before them, bound and silent — which is the whole of what Matthew reports him doing until the high priest puts him on oath. The Athonite fresco this passage leads with names both Annas and Caiaphas in its inscription; this one paints only the second hearing, and the verdict.",
"File:Judas hangs himself. Gelati fresco.JPG":
 "An eighteenth-century fresco in the Gelati monastery in Georgia, an Orthodox house founded in the twelfth century. It shows what the Athonite fresco beside it does not: Judas hanging from the tree, alone, in an empty landscape. Matthew is the only evangelist who reports the end of him, and the Church paints it very seldom.",
"File:Pilate judgement (icon).jpg":
 "A fifteenth-century Russian panel of the trial. Pilate is raised on his judgment seat with his counsellors, the accusers press in from the left, and Christ stands among them bound. The icon this passage leads with shows only the washing of the hands; this one shows the hearing those hands were washed after — Matthew's Pilate knows exactly what he is doing, and does it anyway.",
"File:Flagellation of Christ (icon).jpg":
 "A fragment of a fifteenth-century Novgorod double-sided tablet icon — a small painted board of the kind laid out on a stand for the day it belonged to. Christ is bound to the column and two men work at him with scourges, one on either side. It is a single verse of this passage: and when he had scourged Jesus, he delivered him to be crucified.",
"File:Crucifixion Icon Sinai 12th century.jpg":
 "A small Comnenian panel of the second half of the twelfth century, twenty-eight centimetres high, from St Catherine's on Sinai. The Theotokos stands at the left and John at the right — the oldest arrangement of all — with small saints ranged in the borders. The body is given the long curve that twelfth-century painters used to show a death that is not a defeat: he is not slumped on the cross, he is laid along it.",
"File:024 Crucifixion of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":
 "A Greek icon dated 1855. It fills the ground behind the cross with the walls of Jerusalem and puts the women and the centurion Matthew names at its foot, and in the rock beneath there is a skull: the tradition that Golgotha, the place of a skull, is where Adam was buried, so that the blood runs down onto the first man. Matthew is the evangelist who reports the graves opening at that moment.",
"File:Double-sided icon - Crucifixion and Hodegetria (9-13th c., Byzantine museum).jpg":
 "The front of a double-sided processional icon, the oldest panel in the Byzantine and Christian Museum in Athens, with three layers of painting one on top of another from repeated repair. The Virgin Hodegetria is painted on its back. Icons like this were carried out of the church in procession on a pole, which is why both faces had to be finished — whichever way it was turned, someone was looking at it.",
"File:Lamentation icon Nerezi MK.jpg":
 "The most famous Lamentation in Byzantine painting: the fresco of 1164 in the church of St Panteleimon at Nerezi, above Skopje. The Theotokos has her face pressed against her Son's and John bends over his hand. Before Nerezi this scene is composed and still; after it the figures grieve, and every later Epitaphios in the Orthodox world is working from what the painter of this wall did first.",
"File:Lamentation by Emmanuel Lambardos (Byzantine museum).jpg":
 "Signed by the Cretan painter Emmanuel Lambardos in the seventeenth century, repeating a type worked out on Crete two hundred years earlier. Cretan workshops of this period painted for Orthodox and Venetian buyers both, and could work in either manner on demand; here Lambardos keeps the Byzantine arrangement exactly — the body laid on the stone, the Theotokos at the head of it, the myrrh-bearers standing behind.",
"File:09 Epitaphios Icon in Assumption of Mary Church in Agios Vasileios.jpg":
 "Inscribed Ο ΕΠΙΤΑΦΙΟC ΘΡΗΝΟC, the lament at the tomb. That is the name of the icon and also of the service the Church sings on the night of Great Friday, when a cloth embroidered or painted with this very scene is carried in procession round the outside of the church. The icon is the service standing still.",
"File:Sealing of Christ's Tomb (Russia, 19th c.).jpg":
 "A late nineteenth-century Russian panel of exactly these five verses — a rare thing to find painted at all. A Pharisee bends to press the seal onto the stone across the mouth of the tomb, with a soldier standing guard on either side of him. Matthew alone reports the watch and the sealing, and this icon is painted from his text and from nothing else.",
"File:Sleeping soldiers by Christ's tomb, Mileševa.jpg":
 "From Mileševa in Serbia, painted about 1235. The soldiers set to make the tomb sure are shown asleep in their armour, packed one against another — the lower register of the composition whose upper half is the great white angel at the empty tomb. Set the two halves together and the passage answers itself: the watch that was posted to keep the body in is asleep when it goes out.",
};
