module.exports={
'File:Second Coming by G.Klontzas (16th c.).jpg':'The Second Coming — Georgios Klontzas, Crete, late 16th c.',
'File:Christ banish tradesmen from Temple (Monreale).jpg':'The Cleansing of the Temple — Monreale, 12th c.',
'USER:icon-nativity':'The Nativity of Christ',
'File:Victor (iconographer) Tree of Jesse.png':'The Tree of Jesse — Victor of Crete, 1674',
'File:Cathedral (Monreale) - North arch of transept - Adoration by the Magi.jpg':'The Adoration of the Magi — Monreale, 12th c.',
'File:Menologion of Basil II - Flight into Egypt.jpg':'The Flight into Egypt — Menologion of Basil II, c. 1000',
'File:Massacre of the Innocents (Ionian, 17th c., Byzantine museum).jpg':'The Holy Innocents — Ionian school, 17th c.',
'File:Christos Prodomo Dionysiou.jpg':'Christ with St John the Forerunner — Dionysiou, Athos, 1547',
'File:Baptism of Christ, Early XIV Century, St Mary Perivleptos Church, Ohrid Icon Gallery.jpg':'The Theophany — Ohrid, early 14th c.',
"File:Christ's temptation (Monreale).jpg":'The Temptation of Christ — Monreale, 12th c.',
'File:Christos Didaskon Dionysiou.jpg':'Christ the Teacher — Dionysiou, Athos, 1547',
'File:Christos Apostolois Dionysiou.jpg':'Christ with the Apostles — Dionysiou, Athos, 1547',
'File:Iomenos Asthenoun tas apo Poikilon noson.jpg':'Christ Healing the Multitudes — Dionysiou, Athos, 1547',
'File:IkonaZapovediBlazhenGIM.jpg':'The Commandments of the Beatitudes — Russian icon',
'File:105 Christ Enthroned Icon from Saint Paraskevi Church in Langadas.jpg':'Christ Enthroned — Langadas, Greece, 19th c.',
'File:Christ cleans leper man.jpg':'The Cleansing of the Leper — Monreale, 12th c.',
'File:Iomenos Gon Ekatonarchou Dionysiou.jpg':'Christ and the Centurion — Dionysiou, Athos, 1547',
"File:Monreale - Jesus heals Simon's mother in law.jpg":'Healing of Peter’s Mother-in-law — Monreale, 12th c.',
'File:Hrist utišava buru na moru, manastir Gračanica.jpg':'Christ Stilling the Storm — Gračanica, 14th c.',
'File:Christos Iomenos Daimonon Takophon Dionysiou.jpg':'The Dumb Demoniac — Dionysiou, Athos, 1547',
'File:Christos Iomenos Paralyton Dionysiou.jpg':'The Healing of the Paralytic — Dionysiou, Athos, 1547',
'File:090 Mathew the Apostle Icon from Saint Paraskevi Church in Langadas.jpg':'St Matthew the Apostle — Langadas, Greece, 19th c.',
'File:Daughter of the head of synagogue is resurrected by Christ.jpg':'The Daughter of Jairus — Monreale, 12th c.',
'File:Christos Iomenos Typhlon.jpg':'The Healing of the Blind — Dionysiou, Athos, 1547',
'File:Iomenos Daimonizomenon Dionysiou.jpg':'Christ Casting Out a Devil — Dionysiou, Athos, 1547',
'File:Iomenos Daimonizomenous Dionysiou.jpg':'The Gadarene Demoniacs — Dionysiou, Athos, 1547',
'File:Synaxis of the Twelve Apostles by Constantinople master (early 14th c., Pushkin museum).jpg':'The Synaxis of the Twelve Apostles — Constantinople, early 14th c.',
'File:Elkomenos Prodromos Phylaken Dionysiou.jpg':'The Forerunner Led to Prison — Dionysiou, Athos, 1547',
'File:Christos Pantokrator Dionysiou.jpg':'Christ Pantocrator — Dionysiou, Athos, 1547',
'File:Iomenos xeran echon cheira Dionysiou.jpg':'The Man with the Withered Hand — Dionysiou, Athos, 1547',
'File:Prophetes Ionas Ketos Dionysiou.jpg':'Jonah and the Great Fish — Dionysiou, Athos, 1547',
'File:Theotokos Panachranta Dionysiou.jpg':'The Theotokos Panachranta — Dionysiou, Athos, 1547',
"File:Representation of the Sower's parable.JPEG":'The Parable of the Sower — Orthodox mosaic',
'File:Apotome Agiou Ioannou Prodromou Dionysiou.jpg':'The Beheading of the Forerunner — Dionysiou, Athos, 1547',
'File:Evlogesis Pente Arton Dionysiou.jpg':'The Blessing of the Five Loaves — Dionysiou, Athos, 1547',
'File:Monreale - Peter Saved from the Waves.jpg':'Christ Saving Peter from the Waves — Monreale, 12th c.',
'File:Christos Iomenos Thygatera Xananaias Dionysiou.jpg':'The Canaanite Woman — Dionysiou, Athos, 1547',
'File:Monreale - Multiplication of the Loaves and Fishes.jpg':'The Multiplication of the Loaves — Monreale, 12th c.',
'File:Transfiguration of Christ Icon Sinai 12th century.jpg':'The Transfiguration — Sinai, 12th c.',
'File:The Good Shepherd from the Imperial Palace of Constantinople 5th-6th century AD.jpg':'The Good Shepherd — Great Palace, Constantinople, 5th–6th c.',
'File:Workers in the vineyard, Minuscule 269 (11th century).jpg':'The Labourers in the Vineyard — Byzantine Gospel book, 11th c.',
'File:Christ heals two Jericho blind men.jpg':'The Blind Men of Jericho — Monreale, 12th c.',
'File:Baiophoros Dionysiou.jpg':'The Entry into Jerusalem — Dionysiou, Athos, 1547',
'File:074 Cursing the fig tree Icon from Saint Paraskevi Church in Langadas.jpg':'The Cursing of the Fig Tree — Langadas, Greece, 19th c.',
'File:Parable of the Wedding Feast 04-14.jpg':'The Wedding Feast — Dionisius, Ferapontov Monastery, 1502',
'File:Christ, last judgment, narthex, GRACANICA 7 D39A0936.jpg':'Christ in Glory, from the Last Judgment — Gračanica, 14th c.',
'File:RossGospWiseFoolVirginsF4.jpg':'The Wise and Foolish Virgins — Rossano Gospels, 6th c.',
'File:Separation of Sheep and Goats MET cdi24-144-4s1.jpg':'The Separation of the Sheep and the Goats — Ravenna, 6th c.',
'File:Monreale - Anointing at Bethany.jpg':'The Anointing at Bethany — Monreale, 12th c.',
'File:Judas receiving money, icon of Yaroslavl (19 c, priv.coll).jpg':'Judas Receiving the Silver — Yaroslavl school, 19th c.',
'File:Deipnos Mystikos Dionysiou.jpg':'The Mystical Supper — Dionysiou, Athos, 1547',
'File:Alektor Petrou Dionysiou.jpg':'Peter and the Cock — Dionysiou, Athos, 1547',
"File:The Lord's prayer in Gethsemane - Stavronikita monastery, Mt Athos - Theophanes of Crete, 16th c..jpg":'The Prayer in Gethsemane — Theophanes the Cretan, Stavronikita, 16th c.',
'File:Prodosia Dionysiou.jpg':'The Betrayal — Dionysiou, Athos, 1547',
'File:Krinomenos Christou Dionysiou.jpg':'Christ Judged — Dionysiou, Athos, 1547',
'File:Ypestrepseta Triakonta Argyria Ioudas.jpg':'Judas Returns the Thirty Pieces — Dionysiou, Athos, 1547',
'File:Aponepsis Pilatou Dionysiou.jpg':'Pilate Washing His Hands — Dionysiou, Athos, 1547',
'File:Stavrosis Dionysiou.jpg':'The Crucifixion — Dionysiou, Athos, 1547',
'File:Epitaphios Threnos Dionysiou.jpg':'The Lamentation at the Tomb — Dionysiou, Athos, 1547',
'File:Mnemeion Christou Dionysiou.jpg':'The Sealed Tomb — Dionysiou, Athos, 1547',
'File:Ide Topos pou Ekato Dionysiou.jpg':'“Behold the Place Where the Lord Lay” — Dionysiou, Athos, 1547',

// The further icons of a scene the Church has painted more than once. Each names its own
// place and date: the point of a second icon is that it was made somewhere else, by someone else.
"File:Icon with the Virgin of the Tree of Jesse. 1666 (8384481474).jpg":"The Tree of Jesse — Theodore Poulakis, Crete, 1666",
"File:Tree of Jesse icon (17 c.).jpg":"The Tree of Jesse — Russian, 17th c.",
"File:031 Nativity of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":"The Nativity — Langadas, Greece, before 1900",
"File:12 Nativity of Jesus Icon in Assumption of Mary Church in Agios Vasileios.jpg":"The Nativity — Agios Vasileios, Greece, before 1900",
"File:Nativity Icon Panagia Evraidos Church 19 Century.jpg":"The Nativity — Panagia Evraidou, Greece, 19th c.",
"File:Cathedral (Monreale) - North arch of transept - Journey of the Magi.jpg":"The Journey of the Magi — Monreale, 12th c.",
"File:Flight into Egypt Icon Mary Evraida Church Kastoria.jpg":"The Flight into Egypt — Kastoria, Greece, 19th c.",
"File:Cathedral (Monreale) - South arch of transept - Flight into Egypt.jpg":"The Flight into Egypt — Monreale, 12th c.",
"File:Flight into Egypt (12 Sinai).jpg":"The Flight into Egypt — Sinai, 12th c.",
"File:Menologion of Basil II - Massacre of the Innocents.jpg":"The Massacre of the Innocents — Menologion of Basil II, c. 985",
"File:Detail of the Massacre of the innocents mosaic at Chora (1).jpg":"The Massacre of the Innocents — Chora, Constantinople, 14th c.",
"File:St John the Baptist Late XVII - Early XVIII Cenury St Mary Blonichka Church, Ohris Icon Gallery.jpg":"St John the Forerunner, the Angel of the Desert — Ohrid, c. 1700",
"File:019 Baptism of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":"The Theophany — Athanasios Margaritis, Langadas, 1850",
"File:03 Baptism of Christ Icon from Saint Paraskevi Church in Adam.jpg":"The Theophany — Adam, Greece, before 1900",
"File:0663Ha. Hermitage Museum (Hall 143). Icon of the Epiphany.jpg":"The Theophany — Russian North, 17th c.",
"File:Cathedral (Monreale) - Right wing transept - 2nd Temptation of Christ.jpg":"The Second Temptation — Monreale, 12th c.",
"File:Monreale - healing of paralytic.jpg":"The Healing of the Paralytic — Monreale, 12th c.",
"File:Healing of the Paralytic 04-17.jpg":"The Healing of the Paralytic — Dionisy, Ferapontov, 1502",
"File:Matthew the Evangelist - icon.jpeg":"St Matthew the Evangelist — Palekh, Russia, 19th c.",
"File:Raising of Jairus' daughter 03-19.jpg":"The Daughter of Jairus — Dionisy, Ferapontov, 1502",
"File:Tokalı Kilise Raising of daughter of Jairus - 2004 6964.jpg":"The Daughter of Jairus — Tokalı Kilise, Cappadocia, 10th c.",
"File:Mosaic of the exorcism of the Gerasene demoniac from the Basilica of Sant'Apollinare Nuovo.jpg":"The Gerasene Demoniac — Sant'Apollinare Nuovo, Ravenna, 6th c.",
"File:Synaxis of the Twelve Apostles Dimitar Molerov Rila Monastery 1835.jpg":"The Synaxis of the Twelve Apostles — Dimitar Molerov, Rila, 1835",
"File:The Twelve Apostles, with later gilding, Greek, Late Byzantine, early 1300s, tempera and gold leaf on wood panel - Princeton University Art Museum - DSC06701.jpg":"The Twelve Apostles — Late Byzantine panel, early 1300s",
"File:Prophetes Ionas Dionysiou.jpg":"The Prophet Jonah — Dionysiou, Athos, 1547",
"File:103 Beheading of Saint John the Baptist Icon from Saint Paraskevi Church in Langadas.jpg":"The Head of the Forerunner — Langadas, Greece, 1927",
"File:19 Beheading of Saint John the Baptist Icon in Assumption of Mary Church in Agios Vasileios.jpg":"The Beheading of the Forerunner — Agios Vasileios, Greece, before 1900",
"File:Feeding the multitude, Sant'Apollinare Nuovo, Ravenna.jpg":"The Multiplication of the Loaves — Sant'Apollinare Nuovo, Ravenna, 6th c.",
"File:042 Transfiguration of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":"The Transfiguration — Stavrakis Margaritis, Langadas, 1885",
"File:Icon of the Transfiguration from Saint Catherine's, Sinai.jpg":"The Transfiguration — St Catherine's, Sinai, 12th c.",
"File:Icon of transfiguration (Spaso-Preobrazhensky Monastery, Yaroslavl).jpg":"The Transfiguration — Yaroslavl, c. 1516",
"File:Ravenna — The Good Shepherd mosaic.jpg":"The Good Shepherd — Galla Placidia, Ravenna, c. 425",
"File:005 Entry into Jerusalem Icon from Saint Paraskevi Church in Langadas.jpg":"The Entry into Jerusalem — Langadas, Greece, before 1900",
"File:18 Triumphal entry into Jerusalem Icon from Saint Paraskevi Church in Adam..jpg":"The Entry into Jerusalem — Athanasios of Adam, 1846",
"File:Entry into Jerusalem (Afon icon).jpg":"The Entry into Jerusalem — Athos, 16th c.",
"File:Rossano Gospels - Cleansing of the Temple.jpg":"The Cleansing of the Temple — Rossano Gospels, 6th c.",
"File:Fig tree cursed 04-16.jpg":"The Cursing of the Fig Tree — Dionisy, Ferapontov, 1502",
"File:Ten virgins 05-15.jpg":"The Ten Virgins — Dionisy, Ferapontov, 1502",
"File:John Tokhabi, Last Judgment, around 1100. Icon, tempera. St Catherine monastery on Sinai, Egypt.jpg":"The Last Judgment — John Tokhabi, Sinai, c. 1100",
"File:05 Last Supper Icon from Saint Paraskevi Church in Adam.jpg":"The Mystical Supper — Asterios Anagnostos, Adam, 1898",
"File:Kirillo-Belozersky iconostasis 12 - Last Supper.jpg":"The Mystical Supper — Kirillo-Belozersky iconostasis, 1497",
"File:Gethsemane Dionysiou.jpg":"The Prayer in Gethsemane — Dionysiou, Athos, 1547",
"File:Cathedral (Monreale) - Right wing transept - Agony in the Garden.jpg":"The Agony in the Garden — Monreale, 12th c.",
"File:Judas's kiss (Monreale).jpg":"The Kiss of Judas — Monreale, 12th c.",
"File:Kiss of Judas (Church of Saint Nicolas the Orphan).jpg":"The Kiss of Judas — St Nicholas Orphanos, Thessaloniki, 14th c.",
"File:Christ before Caiaphas, GRACANICA 1 090A7764.jpg":"Christ before Caiaphas — Gračanica, Serbia, 14th c.",
"File:Judas hangs himself. Gelati fresco.JPG":"The End of Judas — Gelati, Georgia, 18th c.",
"File:Pilate judgement (icon).jpg":"Christ before Pilate — Russian icon, 15th c.",
"File:Flagellation of Christ (icon).jpg":"The Scourging — Novgorod tablet icon, 15th c.",
"File:Crucifixion Icon Sinai 12th century.jpg":"The Crucifixion — Sinai, late 12th c.",
"File:024 Crucifixion of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":"The Crucifixion — Langadas, Greece, 1855",
"File:Double-sided icon - Crucifixion and Hodegetria (9-13th c., Byzantine museum).jpg":"The Crucifixion — double-sided icon, Byzantine Museum, Athens",
"File:Lamentation icon Nerezi MK.jpg":"The Lamentation — Nerezi, Macedonia, 1164",
"File:Lamentation by Emmanuel Lambardos (Byzantine museum).jpg":"The Lamentation — Emmanuel Lambardos, Crete, 17th c.",
"File:09 Epitaphios Icon in Assumption of Mary Church in Agios Vasileios.jpg":"The Epitaphios Threnos — Agios Vasileios, Greece, before 1900",
"File:Sealing of Christ's Tomb (Russia, 19th c.).jpg":"The Sealing of the Tomb — Russia, late 19th c.",
"File:Sleeping soldiers by Christ's tomb, Mileševa.jpg":"The Sleeping Guard — Mileševa, Serbia, 13th c.",
};
