module.exports={
'File:Second Coming by G.Klontzas (16th c.).jpg':'The Second Coming — Georgios Klontzas, Crete, late 16th c.',
'File:Christ banish tradesmen from Temple (Monreale).jpg':'The Cleansing of the Temple — Monreale, 12th c.',
'USER:icon-nativity':'The Nativity of Christ',
'File:Victor (iconographer) Tree of Jesse.png':'The Tree of Jesse — Victor of Crete, 1674',
'File:Cathedral (Monreale) - North arch of transept - Adoration by the Magi.jpg':'The Adoration of the Magi — Monreale, 12th c.',
'File:Menologion of Basil II - Flight into Egypt.jpg':'The Flight into Egypt — Menologion of Basil II, c. 1000',
'File:Massacre of the Innocents (Ionian, 17th c., Byzantine museum).jpg':'The Holy Innocents — Ionian school, 17th c.',
'File:Christos Prodomo Dionysiou.jpg':'Christ with St John the Forerunner — Dionysiou, Athos, 1547',
'File:Baptism of Christ, Early XIV Century, St Mary Perivleptos Church, Ohrid Icon Gallery.jpg':'The Theophany — Ohrid, early 14th c.',
"File:Christ's temptation (Monreale).jpg":'The Temptation of Christ — Monreale, 12th c.',
'File:Christos Didaskon Dionysiou.jpg':'Christ the Teacher — Dionysiou, Athos, 1547',
'File:Christos Apostolois Dionysiou.jpg':'Christ with the Apostles — Dionysiou, Athos, 1547',
'File:Iomenos Asthenoun tas apo Poikilon noson.jpg':'Christ Healing the Multitudes — Dionysiou, Athos, 1547',
'File:IkonaZapovediBlazhenGIM.jpg':'The Commandments of the Beatitudes — Russian icon',
'File:105 Christ Enthroned Icon from Saint Paraskevi Church in Langadas.jpg':'Christ Enthroned — Langadas, Greece, 19th c.',
'File:Christ cleans leper man.jpg':'The Cleansing of the Leper — Monreale, 12th c.',
'File:Iomenos Gon Ekatonarchou Dionysiou.jpg':'Christ and the Centurion — Dionysiou, Athos, 1547',
"File:Monreale - Jesus heals Simon's mother in law.jpg":'Healing of Peter’s Mother-in-law — Monreale, 12th c.',
'File:Hrist utišava buru na moru, manastir Gračanica.jpg':'Christ Stilling the Storm — Gračanica, 14th c.',
'File:Christos Iomenos Daimonon Takophon Dionysiou.jpg':'The Gadarene Demoniacs — Dionysiou, Athos, 1547',
'File:Christos Iomenos Paralyton Dionysiou.jpg':'The Healing of the Paralytic — Dionysiou, Athos, 1547',
'File:090 Mathew the Apostle Icon from Saint Paraskevi Church in Langadas.jpg':'St Matthew the Apostle — Langadas, Greece, 19th c.',
'File:Daughter of the head of synagogue is resurrected by Christ.jpg':'The Daughter of Jairus — Monreale, 12th c.',
'File:Christos Iomenos Typhlon.jpg':'The Healing of the Blind — Dionysiou, Athos, 1547',
'File:Iomenos Daimonizomenon Dionysiou.jpg':'Christ Casting Out a Devil — Dionysiou, Athos, 1547',
'File:Iomenos Daimonizomenous Dionysiou.jpg':'The Deliverance of the Possessed — Dionysiou, Athos, 1547',
'File:Synaxis of the Twelve Apostles by Constantinople master (early 14th c., Pushkin museum).jpg':'The Synaxis of the Twelve Apostles — Constantinople, early 14th c.',
'File:The Twelve Apostles, with later gilding, Greek, Late Byzantine, early 1300s, tempera and gold leaf on wood panel - Princeton University Art Museum - DSC06701.jpg':'The Twelve Apostles — Greek, late Byzantine, early 14th c.',
'File:Elkomenos Prodromos Phylaken Dionysiou.jpg':'The Forerunner Led to Prison — Dionysiou, Athos, 1547',
'File:Christos Pantokrator Dionysiou.jpg':'Christ Pantocrator — Dionysiou, Athos, 1547',
'File:Iomenos xeran echon cheira Dionysiou.jpg':'The Man with the Withered Hand — Dionysiou, Athos, 1547',
'File:Prophetes Ionas Ketos Dionysiou.jpg':'The Prophet Jonah — Dionysiou, Athos, 1547',
'File:Theotokos Panachranta Dionysiou.jpg':'The Theotokos Panachranta — Dionysiou, Athos, 1547',
"File:Representation of the Sower's parable.JPEG":'The Parable of the Sower — Orthodox mosaic',
'File:Apotome Agiou Ioannou Prodromou Dionysiou.jpg':'The Beheading of the Forerunner — Dionysiou, Athos, 1547',
'File:Evlogesis Pente Arton Dionysiou.jpg':'The Blessing of the Five Loaves — Dionysiou, Athos, 1547',
'File:Monreale - Peter Saved from the Waves.jpg':'Christ Saving Peter from the Waves — Monreale, 12th c.',
'File:Christos Iomenos Thygatera Xananaias Dionysiou.jpg':'The Canaanite Woman — Dionysiou, Athos, 1547',
'File:Monreale - Multiplication of the Loaves and Fishes.jpg':'The Multiplication of the Loaves — Monreale, 12th c.',
'File:Transfiguration of Christ Icon Sinai 12th century.jpg':'The Transfiguration — Sinai, 12th c.',
'File:The Good Shepherd from the Imperial Palace of Constantinople 5th-6th century AD.jpg':'The Good Shepherd — Great Palace, Constantinople, 5th–6th c.',
'File:Workers in the vineyard, Minuscule 269 (11th century).jpg':'The Labourers in the Vineyard — Byzantine Gospel book, 11th c.',
'File:Christ heals two Jericho blind men.jpg':'The Blind Men of Jericho — Monreale, 12th c.',
'File:Baiophoros Dionysiou.jpg':'The Entry into Jerusalem — Dionysiou, Athos, 1547',
'File:Rossano Gospels - Cleansing of the Temple.jpg':'The Cleansing of the Temple — Rossano Gospels, 6th c.',
'File:074 Cursing the fig tree Icon from Saint Paraskevi Church in Langadas.jpg':'The Cursing of the Fig Tree — Langadas, Greece, 19th c.',
'File:Parable of the Wedding Feast 04-14.jpg':'The Wedding Feast — Dionisius, Ferapontov Monastery, 1502',
'File:Christ, last judgment, narthex, GRACANICA 7 D39A0936.jpg':'Christ in Glory, from the Last Judgment — Gračanica, 14th c.',
'File:RossGospWiseFoolVirginsF4.jpg':'The Wise and Foolish Virgins — Rossano Gospels, 6th c.',
'File:Separation of Sheep and Goats MET cdi24-144-4s1.jpg':'The Separation of the Sheep and the Goats — Ravenna, 6th c.',
'File:Christ before Caiaphas, GRACANICA 1 090A7764.jpg':'Christ before Caiaphas — Gračanica, 14th c.',
'File:Monreale - Anointing at Bethany.jpg':'The Anointing at Bethany — Monreale, 12th c.',
'File:Judas receiving money, icon of Yaroslavl (19 c, priv.coll).jpg':'Judas Receiving the Silver — Yaroslavl school, 19th c.',
'File:Deipnos Mystikos Dionysiou.jpg':'The Mystical Supper — Dionysiou, Athos, 1547',
'File:Alektor Petrou Dionysiou.jpg':'Peter and the Cock — Dionysiou, Athos, 1547',
"File:The Lord's prayer in Gethsemane - Stavronikita monastery, Mt Athos - Theophanes of Crete, 16th c..jpg":'The Prayer in Gethsemane — Theophanes the Cretan, Stavronikita, 16th c.',
'File:Prodosia Dionysiou.jpg':'The Betrayal — Dionysiou, Athos, 1547',
'File:Krinomenos Christou Dionysiou.jpg':'Christ Judged — Dionysiou, Athos, 1547',
'File:Ypestrepseta Triakonta Argyria Ioudas.jpg':'Judas Returns the Thirty Pieces — Dionysiou, Athos, 1547',
'File:Aponepsis Pilatou Dionysiou.jpg':'Pilate Washing His Hands — Dionysiou, Athos, 1547',
'File:Stavrosis Dionysiou.jpg':'The Crucifixion — Dionysiou, Athos, 1547',
'File:Epitaphios Threnos Dionysiou.jpg':'The Lamentation at the Tomb — Dionysiou, Athos, 1547',
'File:Mnemeion Christou Dionysiou.jpg':'The Sealed Tomb — Dionysiou, Athos, 1547',
'File:Ide Topos pou Ekato Dionysiou.jpg':'“Behold the Place Where the Lord Lay” — Dionysiou, Athos, 1547',
};
