// pericope id -> Commons file title (USER: = image supplied by the reader)
module.exports={
  "genealogy": "File:Victor (iconographer) Tree of Jesse.png",
  "annunciation": "USER:icon-nativity",
  "magi": "File:Cathedral (Monreale) - North arch of transept - Adoration by the Magi.jpg",
  "flight2": "File:Menologion of Basil II - Flight into Egypt.jpg",
  "innocents2": "File:Massacre of the Innocents (Ionian, 17th c., Byzantine museum).jpg",
  "nativity": "File:Menologion of Basil II - Flight into Egypt.jpg",
  "forerunner": "File:Christos Prodomo Dionysiou.jpg",
  "theophany": "File:Baptism of Christ, Early XIV Century, St Mary Perivleptos Church, Ohrid Icon Gallery.jpg",
  "temptation": "File:Christ's temptation (Monreale).jpg",
  "galilee": "File:Christos Didaskon Dionysiou.jpg",
  "calling": "File:Christos Apostolois Dionysiou.jpg",
  "multitudes": "File:Iomenos Asthenoun tas apo Poikilon noson.jpg",
  "beatitudes": "File:IkonaZapovediBlazhenGIM.jpg",
  "saltlight5": "File:Christos Didaskon Dionysiou.jpg",
  "law5a": "File:Christos Didaskon Dionysiou.jpg",
  "murder5": "File:Christos Didaskon Dionysiou.jpg",
  "adultery5": "File:Christos Didaskon Dionysiou.jpg",
  "oaths5": "File:Christos Didaskon Dionysiou.jpg",
  "resist5": "File:Christos Didaskon Dionysiou.jpg",
  "enemies5": "File:Christos Didaskon Dionysiou.jpg",
  "alms6": "File:Christos Didaskon Dionysiou.jpg",
  "lordsprayer": "File:105 Christ Enthroned Icon from Saint Paraskevi Church in Langadas.jpg",
  "treasure6": "File:Christos Didaskon Dionysiou.jpg",
  "anxiety6": "File:Christos Didaskon Dionysiou.jpg",
  "judge7": "File:Christos Didaskon Dionysiou.jpg",
  "askseek7": "File:Christos Didaskon Dionysiou.jpg",
  "wisebuilder": "File:Christos Didaskon Dionysiou.jpg",
  "leper8": "File:Christ cleans leper man.jpg",
  "centurion8": "File:Iomenos Gon Ekatonarchou Dionysiou.jpg",
  "petermen8": "File:Monreale - Jesus heals Simon's mother in law.jpg",
  "cost8": null,
  "storm": "File:Hrist utišava buru na moru, manastir Gračanica.jpg",
  "demoniacs8": "File:Christos Iomenos Daimonon Takophon Dionysiou.jpg",
  "paralytic": "File:Christos Iomenos Paralyton Dionysiou.jpg",
  "matthew": "File:090 Mathew the Apostle Icon from Saint Paraskevi Church in Langadas.jpg",
  "fasting9": "File:Christos Didaskon Dionysiou.jpg",
  "jairus": "File:Daughter of the head of synagogue is resurrected by Christ.jpg",
  "blind9": "File:Christos Iomenos Typhlon.jpg",
  "mute9": "File:Iomenos Daimonizomenon Dionysiou.jpg",
  "harvest9": "File:Christos Apostolois Dionysiou.jpg",
  "twelve": "File:Synaxis of the Twelve Apostles by Constantinople master (early 14th c., Pushkin museum).jpg",
  "persecute10": "File:Synaxis of the Twelve Apostles by Constantinople master (early 14th c., Pushkin museum).jpg",
  "fear10": "File:The Twelve Apostles, with later gilding, Greek, Late Byzantine, early 1300s, tempera and gold leaf on wood panel - Princeton University Art Museum - DSC06701.jpg",
  "confess10": "File:The Twelve Apostles, with later gilding, Greek, Late Byzantine, early 1300s, tempera and gold leaf on wood panel - Princeton University Art Museum - DSC06701.jpg",
  "rewards10": "File:Christos Apostolois Dionysiou.jpg",
  "johnq": "File:Elkomenos Prodromos Phylaken Dionysiou.jpg",
  "thisgen11": "File:Christos Prodomo Dionysiou.jpg",
  "woecities11": "File:Christos Didaskon Dionysiou.jpg",
  "hidden11": "File:Christos Pantokrator Dionysiou.jpg",
  "yoke": "File:Christos Pantokrator Dionysiou.jpg",
  "sabbath": "File:Iomenos xeran echon cheira Dionysiou.jpg",
  "beelzebub12": "File:Iomenos Daimonizomenous Dionysiou.jpg",
  "signjonah12": "File:Prophetes Ionas Ketos Dionysiou.jpg",
  "kindred12": "File:Theotokos Panachranta Dionysiou.jpg",
  "sower": "File:Representation of the Sower's parable.JPEG",
  "weeds13": "File:Christos Didaskon Dionysiou.jpg",
  "mustard13": "File:Christos Didaskon Dionysiou.jpg",
  "weedsexp13": "File:Christos Didaskon Dionysiou.jpg",
  "kingdom": "File:Christos Didaskon Dionysiou.jpg",
  "prophet13": "File:Christos Didaskon Dionysiou.jpg",
  "beheading": "File:Apotome Agiou Ioannou Prodromou Dionysiou.jpg",
  "feeding5": "File:Evlogesis Pente Arton Dionysiou.jpg",
  "walking": "File:Monreale - Peter Saved from the Waves.jpg",
  "tradition15": "File:Christos Didaskon Dionysiou.jpg",
  "canaanite": "File:Christos Iomenos Thygatera Xananaias Dionysiou.jpg",
  "feeding4": "File:Monreale - Multiplication of the Loaves and Fishes.jpg",
  "signdem16": "File:Christos Didaskon Dionysiou.jpg",
  "leaven": "File:Christos Apostolois Dionysiou.jpg",
  "confession": "File:Christos Apostolois Dionysiou.jpg",
  "passion16": "File:Christos Apostolois Dionysiou.jpg",
  "transfiguration": "File:Transfiguration of Christ Icon Sinai 12th century.jpg",
  "boy17": "File:Iomenos Daimonizomenon Dionysiou.jpg",
  "passion17": "File:Christos Apostolois Dionysiou.jpg",
  "tax17": "File:Christos Apostolois Dionysiou.jpg",
  "greatest18": "File:Christos Didaskon Dionysiou.jpg",
  "lostsheep": "File:The Good Shepherd from the Imperial Palace of Constantinople 5th-6th century AD.jpg",
  "reconcile18": null,
  "servant": "File:Christos Didaskon Dionysiou.jpg",
  "divorce19": "File:Christos Didaskon Dionysiou.jpg",
  "children": "File:Christos Didaskon Dionysiou.jpg",
  "richman": "File:Christos Didaskon Dionysiou.jpg",
  "vineyard": "File:Workers in the vineyard, Minuscule 269 (11th century).jpg",
  "passion20a": "File:Christos Apostolois Dionysiou.jpg",
  "james20": "File:Christos Apostolois Dionysiou.jpg",
  "blind20": "File:Christ heals two Jericho blind men.jpg",
  "entry": "File:Baiophoros Dionysiou.jpg",
  "temple": "File:Rossano Gospels - Cleansing of the Temple.jpg",
  "figtree21": "File:074 Cursing the fig tree Icon from Saint Paraskevi Church in Langadas.jpg",
  "authority21": "File:Christos Didaskon Dionysiou.jpg",
  "twosons21": "File:Workers in the vineyard, Minuscule 269 (11th century).jpg",
  "tenants21": "File:Workers in the vineyard, Minuscule 269 (11th century).jpg",
  "wedding": "File:Parable of the Wedding Feast 04-14.jpg",
  "caesar22": "File:Christos Didaskon Dionysiou.jpg",
  "resurrect22": "File:Christos Didaskon Dionysiou.jpg",
  "commandment": "File:Christos Didaskon Dionysiou.jpg",
  "hypocrisy23": "File:Christos Didaskon Dionysiou.jpg",
  "woes": "File:Christos Didaskon Dionysiou.jpg",
  "lament23": "File:Baiophoros Dionysiou.jpg",
  "olivet": "File:Christ, last judgment, narthex, GRACANICA 7 D39A0936.jpg",
  "virgins": "File:RossGospWiseFoolVirginsF4.jpg",
  "talents": "File:Christos Didaskon Dionysiou.jpg",
  "judgment": "File:Separation of Sheep and Goats MET cdi24-144-4s1.jpg",
  "plot26": "File:Christ before Caiaphas, GRACANICA 1 090A7764.jpg",
  "anointing26": "File:Monreale - Anointing at Bethany.jpg",
  "judas26": "File:Judas receiving money, icon of Yaroslavl (19 c, priv.coll).jpg",
  "supper": "File:Deipnos Mystikos Dionysiou.jpg",
  "denial26": "File:Alektor Petrou Dionysiou.jpg",
  "gethsemane": "File:The Lord's prayer in Gethsemane - Stavronikita monastery, Mt Athos - Theophanes of Crete, 16th c..jpg",
  "arrest26": "File:Prodosia Dionysiou.jpg",
  "trial": "File:Krinomenos Christou Dionysiou.jpg",
  "judas27": "File:Ypestrepseta Triakonta Argyria Ioudas.jpg",
  "pilate": "File:Aponepsis Pilatou Dionysiou.jpg",
  "crucifixion": "File:Stavrosis Dionysiou.jpg",
  "burial": "File:Epitaphios Threnos Dionysiou.jpg",
  "guard27": "File:Mnemeion Christou Dionysiou.jpg",
  "resurrection": "File:Ide Topos pou Ekato Dionysiou.jpg",
  "guardrep28": "File:Mnemeion Christou Dionysiou.jpg",
  "commission": "File:Christos Apostolois Dionysiou.jpg",
};
