// Pericope -> the Wikimedia Commons file shown for it.
//
// ONE ICON, ONE PASSAGE. No file appears twice: an icon stands for the passage it actually
// depicts, and a passage with no icon of its own gets none (it renders as a plain verse row,
// tier c). `make check` fails if any image is used more than once.
//
// Every placement below was checked against the image itself, not its title — see
// HANDOFF Gotchas. Passages absent from this map are deliberate: Orthodox iconography is
// built on the feast cycle, the miracles and the saints, and has no scene-icon for most of
// the parables and teaching passages.
module.exports={
  "genealogy": "File:Victor (iconographer) Tree of Jesse.png",
  "annunciation": "USER:icon-nativity",
  "magi": "File:Cathedral (Monreale) - North arch of transept - Adoration by the Magi.jpg",
  "flight2": "File:Menologion of Basil II - Flight into Egypt.jpg",
  "innocents2": "File:Massacre of the Innocents (Ionian, 17th c., Byzantine museum).jpg",
  "forerunner": "File:Christos Prodomo Dionysiou.jpg",
  "theophany": "File:Baptism of Christ, Early XIV Century, St Mary Perivleptos Church, Ohrid Icon Gallery.jpg",
  "temptation": "File:Christ's temptation (Monreale).jpg",
  "galilee": "File:Elkomenos Prodromos Phylaken Dionysiou.jpg",
  "multitudes": "File:Iomenos Asthenoun tas apo Poikilon noson.jpg",
  "beatitudes": "File:IkonaZapovediBlazhenGIM.jpg",
  "leper8": "File:Christ cleans leper man.jpg",
  "centurion8": "File:Iomenos Gon Ekatonarchou Dionysiou.jpg",
  "petermen8": "File:Monreale - Jesus heals Simon's mother in law.jpg",
  "storm": "File:Hrist utišava buru na moru, manastir Gračanica.jpg",
  "demoniacs8": "File:Iomenos Daimonizomenous Dionysiou.jpg",
  "paralytic": "File:Christos Iomenos Paralyton Dionysiou.jpg",
  "matthew": "File:090 Mathew the Apostle Icon from Saint Paraskevi Church in Langadas.jpg",
  "jairus": "File:Daughter of the head of synagogue is resurrected by Christ.jpg",
  "blind9": "File:Christos Iomenos Typhlon.jpg",
  "mute9": "File:Christos Iomenos Daimonon Takophon Dionysiou.jpg",
  "twelve": "File:Synaxis of the Twelve Apostles by Constantinople master (early 14th c., Pushkin museum).jpg",
  "yoke": "File:Christos Pantokrator Dionysiou.jpg",
  "sabbath": "File:Iomenos xeran echon cheira Dionysiou.jpg",
  "beelzebub12": "File:Iomenos Daimonizomenon Dionysiou.jpg",
  "signjonah12": "File:Prophetes Ionas Ketos Dionysiou.jpg",
  "sower": "File:Representation of the Sower's parable.JPEG",
  "beheading": "File:Apotome Agiou Ioannou Prodromou Dionysiou.jpg",
  "feeding5": "File:Evlogesis Pente Arton Dionysiou.jpg",
  "walking": "File:Monreale - Peter Saved from the Waves.jpg",
  "canaanite": "File:Christos Iomenos Thygatera Xananaias Dionysiou.jpg",
  "feeding4": "File:Monreale - Multiplication of the Loaves and Fishes.jpg",
  "transfiguration": "File:Transfiguration of Christ Icon Sinai 12th century.jpg",
  "lostsheep": "File:The Good Shepherd from the Imperial Palace of Constantinople 5th-6th century AD.jpg",
  "vineyard": "File:Workers in the vineyard, Minuscule 269 (11th century).jpg",
  "blind20": "File:Christ heals two Jericho blind men.jpg",
  "entry": "File:Baiophoros Dionysiou.jpg",
  "temple": "File:Christ banish tradesmen from Temple (Monreale).jpg",
  "figtree21": "File:074 Cursing the fig tree Icon from Saint Paraskevi Church in Langadas.jpg",
  "wedding": "File:Parable of the Wedding Feast 04-14.jpg",
  "olivet": "File:Second Coming by G.Klontzas (16th c.).jpg",
  "virgins": "File:RossGospWiseFoolVirginsF4.jpg",
  "judgment": "File:Separation of Sheep and Goats MET cdi24-144-4s1.jpg",
  "anointing26": "File:Monreale - Anointing at Bethany.jpg",
  "judas26": "File:Judas receiving money, icon of Yaroslavl (19 c, priv.coll).jpg",
  "supper": "File:Deipnos Mystikos Dionysiou.jpg",
  "denial26": "File:Alektor Petrou Dionysiou.jpg",
  "gethsemane": "File:The Lord's prayer in Gethsemane - Stavronikita monastery, Mt Athos - Theophanes of Crete, 16th c..jpg",
  "arrest26": "File:Prodosia Dionysiou.jpg",
  "trial": "File:Krinomenos Christou Dionysiou.jpg",
  "judas27": "File:Ypestrepseta Triakonta Argyria Ioudas.jpg",
  "pilate": "File:Aponepsis Pilatou Dionysiou.jpg",
  "crucifixion": "File:Stavrosis Dionysiou.jpg",
  "burial": "File:Epitaphios Threnos Dionysiou.jpg",
  "guard27": "File:Mnemeion Christou Dionysiou.jpg",
  "resurrection": "File:Ide Topos pou Ekato Dionysiou.jpg",
  "commission": "File:Christos Apostolois Dionysiou.jpg",
};
