// Prose readings, keyed by Commons file title. Each says where the icon was made, what it
// shows, and what in it answers to Mark's verses — nothing the picture does not show, and
// nothing borrowed from another Gospel without saying whose it is.
module.exports={

// ---- chapter 1 ----

"File:St John the Baptist Late XVII - Early XVIII Cenury St Mary Blonichka Church, Ohris Icon Gallery.jpg":
 "A panel from the church of St Mary Blonichka at Ohrid, painted about 1700. It is the Forerunner as the Church paints him rather than a scene from these verses: he stands full length with great brown wings folded behind him, because Mark opens by quoting Malachi's word for him, Behold, I send my messenger before thy face — and the Greek of that verse, angelos, is the word for both a messenger and an angel. The painter has taken Mark's own quotation literally. Everything else in the panel answers to Mark's description of him: the shaggy hide he wears over his shoulders is the camel's hair, and Mark adds that he had a girdle of a skin about his loins. The scroll he holds gives the preaching in Matthew's words, ΜΕΤΑΝΟΕΙΤΕ ΗΓΓΙΚΕΝ ΓΑΡ Η ΒΑΣΙΛΕΙΑ ΤΩΝ ΟΥΡΑΝΩΝ — Repent ye: for the kingdom of heaven is at hand — where Mark says only that he did preach the baptism of repentance for the remission of sins. In the charger at his waist lies his own severed head: the icon shows the end of the man at the moment of his beginning, which is why it belongs to the Forerunner himself and not to any one passage about him.",

"File:Baptism of Christ, Early XIV Century, St Mary Perivleptos Church, Ohrid Icon Gallery.jpg":
 "An early fourteenth-century panel from St Mary Peribleptos at Ohrid, one of the great Macedonian churches. Christ stands upright in the Jordan with his hand raised in blessing over the water; the Forerunner leans in from the left bank and lays his hand on Christ's head, which is what Mark states in five words — was baptized of John in Jordan. From a segment of heaven at the top a shaft comes straight down to him: Mark says the heavens opened, and the Spirit like a dove descending upon him. Four angels wait on the right bank with their hands covered, ready to receive him from the water — a courtesy the Church paints into every Theophany, not something Mark reports. In the water at Christ's feet two small figures turn away, an old man reclining and a rider on a sea-beast: the Jordan and the sea of Psalm 114, which the Church sings at this feast. At the foot of the left bank an axe lies against the root of a tree; that is the Forerunner's warning in Matthew and Luke, not in Mark, who gives none of his sermon but the promise of one mightier.",

"File:019 Baptism of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":
 "Painted in 1850 by Athanasios Margaritis for the church of St Paraskevi at Langadas, north of Thessaloniki. The composition is the same as the older Macedonian ones but the hand is a village hand and the colour is warmer: Christ stands waist-deep in a blue-green Jordan, the Forerunner reaches across with his right hand on Christ's head and a scroll in his left, and two angels crowd the right bank with their arms wrapped in their cloaks. What this painter has made most of is the opening of the heavens. A wide gold wound is torn in the dark sky and a red-orange shaft comes down out of it to Christ's head — Mark's word is the strongest of the four, that he saw the heavens opened, torn apart. The trees on either bank are painted as flat dark discs on bare stems, the convention of these Greek village panels for a wilderness.",

"File:03 Baptism of Christ Icon from Saint Paraskevi Church in Adam.jpg":
 "A Greek panel from the church of St Paraskevi at Adam, made before 1900 and darkened by candle smoke. It is the only one of the four here that paints the dove itself: a white bird hangs at the centre of a bank of grey cloud with a spray of rays spreading from it to Christ's head, so that Mark's two clauses — the heavens opened, and the Spirit like a dove descending upon him — are both in front of the eye at once. The Forerunner steps down from a rock on the left with his hand on Christ's head; three angels lean in from the right, the nearest holding a folded cloth. Mark alone of the Evangelists puts the whole event in Christ's own sight and hearing — he saw the heavens opened, and the voice that follows is spoken to him, not about him: Thou art my beloved Son. The icon keeps that intimacy — nobody but the Forerunner and the angels is present, and there is no crowd.",

"File:0663Ha. Hermitage Museum (Hall 143). Icon of the Epiphany.jpg":
 "A seventeenth-century panel from the Russian North, now in the Hermitage. The Jordan is painted as a deep black cleft between pale rocks, narrow at the bottom and opening upward, so that the water stands almost vertically around Christ like a grave. Russian painters made this reading of the feast their own: the descent into the river is the descent into death, and the white dove at the point of the long rays from heaven is what Mark says comes down on him as he comes up out of it. The Forerunner bends almost double from the rock on the left, his hand on Christ's head and his other hand raised to his face. Three angels stand on the right in graded reds and greens, the nearest holding a white cloth; their bowed heads and covered hands say what the voice says in Mark's next verse, Thou art my beloved Son, in whom I am well pleased.",

"File:Christ's temptation (Monreale).jpg":
 "A mosaic of the 1180s from the nave of Monreale in Sicily, made by Greek craftsmen for a Norman king. Christ stands on a bare rock holding a closed scroll; the devil, black and winged and gaunt, stretches a hand toward five round stones on the ground between them. The Latin around them is the exchange: SI FILI DI ES DIC VT LAPIDES ISTI PANE FIA[NT] — If thou be the Son of God, command that these stones be made bread — and Christ's reply, [SCRI]PTV[M] E[ST] NON IN SOLO PANE V[IVIT HO]MO, It is written, man shall not live by bread alone. Those words are Matthew's and Luke's. Mark gives the forty days in two verses and no dialogue at all: he was there in the wilderness forty days, tempted of Satan; and was with the wild beasts; and the angels ministered unto him. Neither the beasts nor the ministering angels are in this mosaic. What it does show is the one thing Mark does say — Satan and Christ alone in a stony place, and the tempter refused.",

"File:Elkomenos Prodromos Phylaken Dionysiou.jpg":
 "A fresco of 1547 from the katholikon of Dionysiou on Mount Athos, part of the great cycle of the Forerunner's life there. The inscription across the top names the scene exactly: ΕΛΚΟΜΕΝΟΣ Ο ΠΡΟΔΡΟΜΟΣ ΕΙΣ ΤΗΝ ΦΥΛΑΚΗΝ — the Forerunner dragged into the prison. A soldier in a plumed helmet has him by both bound wrists and hauls him forward; the Forerunner leans back against the pull, barefoot, his feet skidding on the pavement. On the right is the prison, a pale stone tower with a barred window, and two faces are already looking out of it. On the left Herod sits on a carved throne with a guard behind him holding a red spear. Mark says none of this: he reports the imprisonment in a subordinate clause — Now after that John was put in prison, Jesus came into Galilee — and moves straight on to the preaching of the kingdom. This is the icon of the event that clause refers to, which is why it stands here and why the card says it is not a depiction of these verses.",

// ---- chapters 1-2 ----

"File:Monreale - Jesus heals Simon's mother in law.jpg":
 "A mosaic of the 1180s from Monreale in Sicily. The Latin along the top reads IHS LIBERAT SOCRV[M] SIMONIS A MAGNIS FEBRIBVS — Jesus frees Simon's mother-in-law from a great fever. The adjective is Luke's; Mark says only that she lay sick of a fever. Everything else in the mosaic is Mark's sentence turned into a picture, and it is the gesture that matters: Christ has crossed the room with his arm already out toward her, she has raised herself on the bed and is reaching back, and the two hands are a hand's breadth apart across the gold. Mark is the only Evangelist who says he took her by the hand, and lifted her up — Matthew has him touch her hand, Luke has him rebuke the fever from a distance. The four who came in with him from the synagogue stand behind at the left, Simon and Andrew with James and John; a fifth head looks out of the doorway behind the bed. Mark ends the verse with what she did next, and she ministered unto them, which is why the painter has her rising rather than lying still.",

"File:Christ cleans leper man.jpg":
 "Monreale again, from the same twelfth-century cycle. The inscription is the leper's own words: POTES ME MVNDARE — thou canst make me clean. Mark gives them in full, If thou wilt, thou canst make me clean, and they are the only words in this picture. The leper stands at the right on a staff, his legs and arms and face flecked with the dark spots the mosaicist used for the disease, one hand raised toward Christ. Christ comes from the left with his own hand stretched out across the gold. Mark is the one who says what happened in that gap — moved with compassion, put forth his hand, and touched him — and the mosaic stops a moment short of it, at the reach rather than the touch. Behind Christ press the heads of his disciples. The little house at the right edge is where Mark sends him next: go thy way, shew thyself to the priest.",

"File:Monreale - healing of paralytic.jpg":
 "A Monreale mosaic of the 1180s, and the one picture in this reader that could only have been made from Mark. Its own inscription says so: APERVERVNT TECTVM — they uncovered the roof. Along the top of the wall two men lean over a broken parapet, one at each end of a rope, letting a bed down into the room. Neither Matthew nor Luke has men on a roof — Matthew says only that they brought him, and it is Mark who gives the press of people, the four bearers, the roof dug open and the bed lowered through it. Christ sits enthroned at the left with a disciple behind him, his hand out toward the man; the paralytic, already off the bed, kneels on it and stretches both arms back at him. At the right a knot of scribes in green and blue mutter together: Mark has them reasoning in their hearts, Why doth this man thus speak blasphemies? A second bed with a white coverlet stands behind them.",

"File:Healing of the Paralytic 04-17.jpg":
 "A fresco of 1502 by Dionisy in the Nativity cathedral at Ferapontov, in the Russian North, painted on a curved wall above an arch. It reads left to right as a sequence rather than a moment. At the left Christ sits with the apostles behind him and his hand raised; below him four men carry the paralytic in on a low bier, their heads crowded together over him — Mark's detail, borne of four. In the middle of the wall the same man walks away upright with the bed on his shoulder, which is Mark's last verse: he arose, took up the bed, and went forth before them all. At the right stand the people who watched it, in the dark robes Russian painters give the scribes. There is no roof in this fresco; what Dionisy has painted is the going out, not the coming in, and the two pictures beside each other in this gallery give the whole of Mark's account between them.",

"File:090 Mathew the Apostle Icon from Saint Paraskevi Church in Langadas.jpg":
 "A village panel of the nineteenth century from St Paraskevi at Langadas, north of Thessaloniki. It is the Apostle Matthew as the Church paints him: an old man with a long white beard, a codex open on his knee and a reed pen in his right hand, the blue ground bare behind his gold halo. He is here because of a name. Mark says the man at the receipt of custom was Levi the son of Alphaeus, and Matthew's own Gospel says that at the same table and the same words the man was Matthew; the Church has always read the two as one man, and keeps both names for him. So this is not a picture of the call — nothing in it is a custom-house, and no-one is being called — but the icon of the man it happened to, painted at the far end of his life with the Gospel he came to write already in his hands.",

"File:Matthew the Evangelist - icon.jpeg":
 "A Palekh panel of the nineteenth century, from the Russian village that painted icons in a fine, almost miniaturist hand. The inscription in the corner names him: С. ЕVАГГ. МАТѲЕЙ, the holy Evangelist Matthew. He sits at a desk in orange and violet with the quill lifted, an open book under his hand with Slavonic writing on the page, and a bound Gospel with a jewelled cover propped at his side. Behind his shoulder stands an angel, leaning in — the winged man, the symbol the Church assigns to him, painted here not as a creature beside him but as the one who is dictating. Like its neighbour it belongs to the man rather than to Mark's two verses: what the Church remembers about the publican who got up from the table is what he wrote afterwards.",

// ---- chapters 3-5 ----

"File:Iomenos xeran echon cheira Dionysiou.jpg":
 "A fresco of 1547 from the katholikon of Dionysiou on Athos. The inscription names it: Ο Χ(ΡΙΣΤΟ)Σ ΙΩΜΕΝΟΣ ΤΟΝ ΞΗΡΑΝ ΕΧΟΝΤΑ ΤΗΝ ΧΕΙΡΑ — Christ healing the man having the withered hand. The whole scene is an interior, a synagogue given the panelled walls and coffered ceiling of a Greek church, with a strip of starry night above it. Christ sits at the left with the apostles crowded behind him. In the middle of the floor, alone and upright, stands the man in a short red tunic with his arm already coming up — Mark alone reports the order that put him there, and it is an order to be looked at: Stand forth. Three elders sit along the right wall in green, red and purple, one with his hand raised in objection. They are what the passage is really about. Mark says Christ looked round about on them with anger, being grieved for the hardness of their hearts, and no other Evangelist dares write that word of him; then, in the last verse, these same men go out: And the Pharisees went forth, and straightway took counsel with the Herodians against him, how they might destroy him.",

"File:Synaxis of the Twelve Apostles by Constantinople master (early 14th c., Pushkin museum).jpg":
 "A panel painted in Constantinople in the early fourteenth century, now in Moscow. Its title is written across the top in Greek — Η ΣΥΝΑΞΙΣ ΤΩΝ ΑΓΙΩΝ ΔΩΔΕΚΑ ΑΠΟΣΤΟΛΩΝ, the assembly of the holy twelve apostles — with each man's name lettered in gold above his head. They stand in two ranks, four in front with their haloes overlapping and eight behind, holding scrolls and Gospel books. This is a feast, not a moment: the Church keeps the Synaxis of the Twelve on the thirtieth of June and sets this icon over it. Mark's verses are the choosing itself — he goeth up into a mountain, and calleth unto him whom he would — and he gives the roll of names that this icon letters in gold. Two of the surnames in that list are his alone: Simon he surnamed Peter, and the sons of Zebedee he surnamed Boanerges, which is, The sons of thunder.",

"File:Synaxis of the Twelve Apostles Dimitar Molerov Rila Monastery 1835.jpg":
 "Painted in 1835 by Dimitar Molerov at the monastery of Rila in Bulgaria, and photographed close, so that five of the twelve fill the frame. The style is late and half-Western — modelled faces, deep folds — but the arrangement is the old one: a row of standing men, each with his halo and his attribute. One holds a white scroll, one a Gospel bound in gold and jewels, and the last a small silver cross on a long stem — the mark of a martyr, which every one of them but John became. Mark's list at 3:16 is the reason the Church can paint them as individuals at all: it is the first time in this Gospel that the twelve are named one by one, and what they were ordained for is in the same sentence — that they should be with him, and that he might send them forth to preach.",

"File:The Twelve Apostles, with later gilding, Greek, Late Byzantine, early 1300s, tempera and gold leaf on wood panel - Princeton University Art Museum - DSC06701.jpg":
 "A Greek panel of the early fourteenth century, tempera and gold leaf on wood, regilded later. The panel has darkened almost to a single brown, and what survives clearly is the arrangement: three ranks of haloed heads, the punched gold discs still catching light, the bodies beneath them barely legible. That arrangement is the whole statement. Like the Constantinople icon it gathers the twelve into one company rather than telling a story, and the Church's reason for keeping them together is Mark's: they were ordained first of all that they should be with him, and only after that to preach and to cast out devils. The icon paints the first half of it — men standing with each other, doing nothing.",

"File:Representation of the Sower's parable.JPEG":
 "A modern Orthodox mosaic, its title lettered in Romanian across the top: PILDA SEMĂNĂTORULUI, the parable of the sower, numbered 21 in the cycle it belongs to. Christ himself is the sower, haloed, walking out of the middle of the picture with the seed gathered in a fold of his cloak and his right hand flung open. Round him the four grounds of the parable are laid out at once, which is what a mosaic can do and a story cannot: the trodden path at the left with four black birds already down on it; the bare grey rock at the upper right; a thicket of thorns with red flowers along the right-hand edge; and the standing green corn behind him. Mark's telling is the shortest of the three and it begins with a word the others leave out — Hearken — and ends with the yield counted upward: some thirty, and some sixty, and some an hundred.",

"File:Hrist utišava buru na moru, manastir Gračanica.jpg":
 "A fresco of about 1320 from Gračanica in Kosovo, and the most Marcan picture in this reader. Christ is in it twice. At the left he stands upright in the bow with his hand out over the water, and at the right he lies asleep in the stern with his head propped on his hand — the same person, painted at two moments of the same minute, which is how Byzantine wall-painters tell a story inside one frame. The sleeping figure is Mark's detail and nobody else's: he was in the hinder part of the ship, asleep on a pillow. Between the two the boat is full of men working — one hauling on a line in a red tunic, one bracing at the mast, one turned back toward the sleeper with his hands open in the gesture of a question. Mark gives them the sharpest words in any account of this night: Master, carest thou not that we perish? The sea is painted as rank on rank of grey scallops that run off the bottom of the fresco, and the sky behind is nearly black.",

"File:Mosaic of the exorcism of the Gerasene demoniac from the Basilica of Sant'Apollinare Nuovo.jpg":
 "A mosaic of about 520 from Sant'Apollinare Nuovo at Ravenna, one of the oldest pictures in this reader and older than the beard: Christ is painted as a young man in a purple robe with a cruciform halo, as the earliest Christian art always painted him. He stands at the left with one apostle in white beside him and his hand held out. In front of him, small and crouching on the ground in a short pale tunic, is one man — and that is why this mosaic stands beside Mark rather than beside Matthew, who has two men in this country. Mark's is one, and Mark spends eight verses on him that nobody else spends: the chains and fetters plucked asunder, the crying night and day among the tombs, the cutting of himself with stones, and the name — My name is Legion: for we are many. At the right a herd of dark swine runs down into a band of bright blue water. Mark counts them where the others do not: they were about two thousand.",

// ---- chapters 5-6 ----

"File:Daughter of the head of synagogue is resurrected by Christ.jpg":
 "Monreale, the 1180s. The Latin along the top says what it is — Jesus raises the daughter of the ruler of the synagogue, in the house. That last phrase matters: Mark is careful about who was let in. He suffered no man to follow him, save Peter, and James, and John the brother of James, and then put out the mourners who laughed at him, and took the father and the mother and his own three inside with him. The mosaicist has kept the room small and crowded to match. Christ comes in from the left and has her by the hand — and she is already sitting up, in a white gown and headcloth, her legs still under the brown patterned coverlet, with a woman behind steadying her shoulder. Mark says he took the damsel by the hand, and that is what the mosaic is built around. Mark alone records the two Aramaic words Christ used, and then translates them for his readers: Talitha cumi; which is, being interpreted, Damsel, I say unto thee, arise. He alone adds the last, practical sentence too: and commanded that something should be given her to eat.",

"File:Raising of Jairus' daughter 03-19.jpg":
 "Dionisy's fresco of 1502 at Ferapontov, painted on a curved wall above an arch, and damaged: the face inside one of the haloes has flaked away entirely, leaving a bare ring of ochre. The bed stands across the left of the wall with the child on it, already raised on one elbow in her white shift. A haloed figure stands over her with a hand out, and at the right, separated by the standing bystanders, is a second haloed figure in dark red. Russian painters of this school habitually give a scene twice on one wall — the coming and the doing — and that is the likeliest reading here, though the damage makes it a reading rather than a certainty. Mark's own account has the same doubled shape: the message reaches Christ on the road, Thy daughter is dead: why troublest thou the Master any further? and he goes on to the house all the same.",

"File:Tokalı Kilise Raising of daughter of Jairus - 2004 6964.jpg":
 "From the Tokalı Kilise in Cappadocia, painted in the tenth century on the rock wall of a cave church. It is the oldest and the roughest of the three and the strongest. Almost half the picture is the bed: a great swag of deep red cloth, drawn with looping ornament and a row of black chevrons along its edge, hanging down the whole lower half of the wall. The girl lies along the top of it in blue, small against it. Christ stands to the left of centre with his hand out toward her, and the household crowds in behind. Mark's telling is built the same way, out of one held detail after another — the ruler falling at his feet, the delay while the woman in the crowd is healed, the message that comes too late, and then the two words in the room. The painter has given the death its whole weight in that red bed, and the raising a single reaching arm.",

"File:Apotome Agiou Ioannou Prodromou Dionysiou.jpg":
 "Dionysiou on Athos, 1547. The inscription names it the beheading of the Forerunner. The executioner stands over him in scale armour with the sword already swung back above his head; the Forerunner kneels on the rock, his body bent right down, and his haloed head is shown forward of his shoulders, at the instant. At the right a young woman in a red gown with a crown on her head kneels and holds out a golden dish to catch it. Mark tells this story at more length than anything else in his Gospel that Christ is not in, and the picture follows him closely: the daughter's dancing and the oath, the request made in haste — I will that thou give me by and by in a charger the head of John the Baptist — and the king who was exceeding sorry and sent anyway. Behind them stands the prison with its barred window, where Mark has kept John since chapter one.",

"File:103 Beheading of Saint John the Baptist Icon from Saint Paraskevi Church in Langadas.jpg":
 "A Greek panel of 1927 from St Paraskevi at Langadas, very dark now and split by a crack from top to bottom. There is no scene in it at all: only the severed head, face upward in a shallow dish, with its gold halo behind it filling the panel. This is an icon the Church paints on its own, for the feast of the Beheading on the twenty-ninth of August, a day kept as a strict fast. It stands here because of the two words Mark gives Herodias' daughter — in a charger — and because of the sentence after them, which no reader forgets: and the damsel gave it to her mother.",

"File:19 Beheading of Saint John the Baptist Icon in Assumption of Mary Church in Agios Vasileios.jpg":
 "A Greek panel from the Dormition church at Agios Vasileios, painted before 1900 and worn round its edges. It takes the moment after the Dionysiou fresco's: the executioner, in gold armour and a plumed helmet, holds the head by the hair and is lowering it into the gold charger that a crowned woman in gold holds up to him with both hands. The body lies along the bottom of the panel, headless, in green and dark red. Behind them is the prison wall with its grated window. Mark's word for the man with the sword is a Latin one borrowed into Greek — a speculator, a guardsman of the king's own bodyguard — and it is the kind of detail that keeps turning up in this Gospel: the king sent an executioner, and commanded his head to be brought.",

"File:Evlogesis Pente Arton Dionysiou.jpg":
 "Dionysiou, 1547, inscribed Η ΕΥΛΟΓΗΣΙΣ ΤΩΝ ΠΕΝΤΕ ΑΡΤΩΝ — the blessing of the five loaves. Christ stands at the far left with the loaves heaped in a cloth in his hands, and from there the fresco runs downhill to the right through the apostles carrying baskets to the people sitting on the ground. What makes it Mark's is the ground itself. He is the only Evangelist who says what colour it was and how the people were arranged on it: he commanded them to make all sit down by companies upon the green grass, and they sat down in ranks, by hundreds, and by fifties. The painter has taken him at his word and set the crowd in blocks of colour, red beside green, on a slope of grass with small plants drawn on it. At the bottom left stand four wicker baskets packed with broken bread — Mark counts twelve of them taken up afterwards.",

"File:Feeding the multitude, Sant'Apollinare Nuovo, Ravenna.jpg":
 "About 520, from Sant'Apollinare Nuovo at Ravenna, and it leaves the multitude out. The young beardless Christ stands in the centre in purple with both arms stretched wide; two apostles in white at his right hold up round loaves, two at his left hold out the fish. There is no crowd, no grass, no baskets — only the handing over. That is exactly the clause Mark puts at the centre of the miracle: he blessed, and brake the loaves, and gave them to his disciples to set before them. The mosaicist has made the picture out of the giving rather than the eating, and left the five thousand to be understood.",

};
