// Prose readings, keyed by Commons file title. Each says where the icon was made, what it
// shows, and what in it answers to Mark's verses — nothing the picture does not show, and
// nothing borrowed from another Gospel without saying whose it is.
module.exports={

// ---- chapter 1 ----

"File:St John the Baptist Late XVII - Early XVIII Cenury St Mary Blonichka Church, Ohris Icon Gallery.jpg":
 "A panel from the church of St Mary Blonichka at Ohrid, painted about 1700. It is the Forerunner as the Church paints him rather than a scene from these verses: he stands full length with great brown wings folded behind him, because Mark opens by quoting Malachi's word for him, Behold, I send my messenger before thy face — and the Greek of that verse, angelos, is the word for both a messenger and an angel. The painter has taken Mark's own quotation literally. Everything else in the panel answers to Mark's description of him: the shaggy hide he wears over his shoulders is the camel's hair, and Mark adds that he had a girdle of a skin about his loins. The scroll he holds gives the preaching in Matthew's words, ΜΕΤΑΝΟΕΙΤΕ ΗΓΓΙΚΕΝ ΓΑΡ Η ΒΑΣΙΛΕΙΑ ΤΩΝ ΟΥΡΑΝΩΝ — Repent ye: for the kingdom of heaven is at hand — where Mark says only that he did preach the baptism of repentance for the remission of sins. In the charger at his waist lies his own severed head: the icon shows the end of the man at the moment of his beginning, which is why it belongs to the Forerunner himself and not to any one passage about him.",

"File:Baptism of Christ, Early XIV Century, St Mary Perivleptos Church, Ohrid Icon Gallery.jpg":
 "An early fourteenth-century panel from St Mary Peribleptos at Ohrid, one of the great Macedonian churches. Christ stands upright in the Jordan with his hand raised in blessing over the water; the Forerunner leans in from the left bank and lays his hand on Christ's head, which is what Mark states in five words — was baptized of John in Jordan. From a segment of heaven at the top a shaft comes straight down to him: Mark says the heavens opened, and the Spirit like a dove descending upon him. Four angels wait on the right bank with their hands covered, ready to receive him from the water — a courtesy the Church paints into every Theophany, not something Mark reports. In the water at Christ's feet two small figures turn away, an old man reclining and a rider on a sea-beast: the Jordan and the sea of Psalm 114, which the Church sings at this feast. At the foot of the left bank an axe lies against the root of a tree; that is the Forerunner's warning in Matthew and Luke, not in Mark, who gives none of his sermon but the promise of one mightier.",

"File:019 Baptism of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":
 "Painted in 1850 by Athanasios Margaritis for the church of St Paraskevi at Langadas, north of Thessaloniki. The composition is the same as the older Macedonian ones but the hand is a village hand and the colour is warmer: Christ stands waist-deep in a blue-green Jordan, the Forerunner reaches across with his right hand on Christ's head and a scroll in his left, and two angels crowd the right bank with their arms wrapped in their cloaks. What this painter has made most of is the opening of the heavens. A wide gold wound is torn in the dark sky and a red-orange shaft comes down out of it to Christ's head — Mark's word is the strongest of the four, that he saw the heavens opened, torn apart. The trees on either bank are painted as flat dark discs on bare stems, the convention of these Greek village panels for a wilderness.",

"File:03 Baptism of Christ Icon from Saint Paraskevi Church in Adam.jpg":
 "A Greek panel from the church of St Paraskevi at Adam, made before 1900 and darkened by candle smoke. It is the only one of the four here that paints the dove itself: a white bird hangs at the centre of a bank of grey cloud with a spray of rays spreading from it to Christ's head, so that Mark's two clauses — the heavens opened, and the Spirit like a dove descending upon him — are both in front of the eye at once. The Forerunner steps down from a rock on the left with his hand on Christ's head; three angels lean in from the right, the nearest holding a folded cloth. Mark alone of the Evangelists puts the whole event in Christ's own sight and hearing — he saw the heavens opened, and the voice that follows is spoken to him, not about him: Thou art my beloved Son. The icon keeps that intimacy — nobody but the Forerunner and the angels is present, and there is no crowd.",

"File:0663Ha. Hermitage Museum (Hall 143). Icon of the Epiphany.jpg":
 "A seventeenth-century panel from the Russian North, now in the Hermitage. The Jordan is painted as a deep black cleft between pale rocks, narrow at the bottom and opening upward, so that the water stands almost vertically around Christ like a grave. Russian painters made this reading of the feast their own: the descent into the river is the descent into death, and the white dove at the point of the long rays from heaven is what Mark says comes down on him as he comes up out of it. The Forerunner bends almost double from the rock on the left, his hand on Christ's head and his other hand raised to his face. Three angels stand on the right in graded reds and greens, the nearest holding a white cloth; their bowed heads and covered hands say what the voice says in Mark's next verse, Thou art my beloved Son, in whom I am well pleased.",

"File:Christ's temptation (Monreale).jpg":
 "A mosaic of the 1180s from the nave of Monreale in Sicily, made by Greek craftsmen for a Norman king. Christ stands on a bare rock holding a closed scroll; the devil, black and winged and gaunt, stretches a hand toward five round stones on the ground between them. The Latin around them is the exchange: SI FILI DI ES DIC VT LAPIDES ISTI PANE FIA[NT] — If thou be the Son of God, command that these stones be made bread — and Christ's reply, [SCRI]PTV[M] E[ST] NON IN SOLO PANE V[IVIT HO]MO, It is written, man shall not live by bread alone. Those words are Matthew's and Luke's. Mark gives the forty days in two verses and no dialogue at all: he was there in the wilderness forty days, tempted of Satan; and was with the wild beasts; and the angels ministered unto him. Neither the beasts nor the ministering angels are in this mosaic. What it does show is the one thing Mark does say — Satan and Christ alone in a stony place, and the tempter refused.",

"File:Elkomenos Prodromos Phylaken Dionysiou.jpg":
 "A fresco of 1547 from the katholikon of Dionysiou on Mount Athos, part of the great cycle of the Forerunner's life there. The inscription across the top names the scene exactly: ΕΛΚΟΜΕΝΟΣ Ο ΠΡΟΔΡΟΜΟΣ ΕΙΣ ΤΗΝ ΦΥΛΑΚΗΝ — the Forerunner dragged into the prison. A soldier in a plumed helmet has him by both bound wrists and hauls him forward; the Forerunner leans back against the pull, barefoot, his feet skidding on the pavement. On the right is the prison, a pale stone tower with a barred window, and two faces are already looking out of it. On the left Herod sits on a carved throne with a guard behind him holding a red spear. Mark says none of this: he reports the imprisonment in a subordinate clause — Now after that John was put in prison, Jesus came into Galilee — and moves straight on to the preaching of the kingdom. This is the icon of the event that clause refers to, which is why it stands here and why the card says it is not a depiction of these verses.",

// ---- chapters 1-2 ----

"File:Monreale - Jesus heals Simon's mother in law.jpg":
 "A mosaic of the 1180s from Monreale in Sicily. The Latin along the top reads IHS LIBERAT SOCRV[M] SIMONIS A MAGNIS FEBRIBVS — Jesus frees Simon's mother-in-law from a great fever. The adjective is Luke's; Mark says only that she lay sick of a fever. Everything else in the mosaic is Mark's sentence turned into a picture, and it is the gesture that matters: Christ has crossed the room with his arm already out toward her, she has raised herself on the bed and is reaching back, and the two hands are a hand's breadth apart across the gold. Mark is the only Evangelist who says he took her by the hand, and lifted her up — Matthew has him touch her hand, Luke has him rebuke the fever from a distance. The four who came in with him from the synagogue stand behind at the left, Simon and Andrew with James and John; a fifth head looks out of the doorway behind the bed. Mark ends the verse with what she did next, and she ministered unto them, which is why the painter has her rising rather than lying still.",

"File:Christ cleans leper man.jpg":
 "Monreale again, from the same twelfth-century cycle. The inscription is the leper's own words: POTES ME MVNDARE — thou canst make me clean. Mark gives them in full, If thou wilt, thou canst make me clean, and they are the only words in this picture. The leper stands at the right on a staff, his legs and arms and face flecked with the dark spots the mosaicist used for the disease, one hand raised toward Christ. Christ comes from the left with his own hand stretched out across the gold. Mark is the one who says what happened in that gap — moved with compassion, put forth his hand, and touched him — and the mosaic stops a moment short of it, at the reach rather than the touch. Behind Christ press the heads of his disciples. The little house at the right edge is where Mark sends him next: go thy way, shew thyself to the priest.",

"File:Monreale - healing of paralytic.jpg":
 "A Monreale mosaic of the 1180s, and the one picture in this reader that could only have been made from Mark. Its own inscription says so: APERVERVNT TECTVM — they uncovered the roof. Along the top of the wall two men lean over a broken parapet, one at each end of a rope, letting a bed down into the room. Neither Matthew nor Luke has men on a roof — Matthew says only that they brought him, and it is Mark who gives the press of people, the four bearers, the roof dug open and the bed lowered through it. Christ sits enthroned at the left with a disciple behind him, his hand out toward the man; the paralytic, already off the bed, kneels on it and stretches both arms back at him. At the right a knot of scribes in green and blue mutter together: Mark has them reasoning in their hearts, Why doth this man thus speak blasphemies? A second bed with a white coverlet stands behind them.",

"File:Healing of the Paralytic 04-17.jpg":
 "A fresco of 1502 by Dionisy in the Nativity cathedral at Ferapontov, in the Russian North, painted on a curved wall above an arch. It reads left to right as a sequence rather than a moment. At the left Christ sits with the apostles behind him and his hand raised; below him four men carry the paralytic in on a low bier, their heads crowded together over him — Mark's detail, borne of four. In the middle of the wall the same man walks away upright with the bed on his shoulder, which is Mark's last verse: he arose, took up the bed, and went forth before them all. At the right stand the people who watched it, in the dark robes Russian painters give the scribes. There is no roof in this fresco; what Dionisy has painted is the going out, not the coming in, and the two pictures beside each other in this gallery give the whole of Mark's account between them.",

"File:090 Mathew the Apostle Icon from Saint Paraskevi Church in Langadas.jpg":
 "A village panel of the nineteenth century from St Paraskevi at Langadas, north of Thessaloniki. It is the Apostle Matthew as the Church paints him: an old man with a long white beard, a codex open on his knee and a reed pen in his right hand, the blue ground bare behind his gold halo. He is here because of a name. Mark says the man at the receipt of custom was Levi the son of Alphaeus, and Matthew's own Gospel says that at the same table and the same words the man was Matthew; the Church has always read the two as one man, and keeps both names for him. So this is not a picture of the call — nothing in it is a custom-house, and no-one is being called — but the icon of the man it happened to, painted at the far end of his life with the Gospel he came to write already in his hands.",

"File:Matthew the Evangelist - icon.jpeg":
 "A Palekh panel of the nineteenth century, from the Russian village that painted icons in a fine, almost miniaturist hand. The inscription in the corner names him: С. ЕVАГГ. МАТѲЕЙ, the holy Evangelist Matthew. He sits at a desk in orange and violet with the quill lifted, an open book under his hand with Slavonic writing on the page, and a bound Gospel with a jewelled cover propped at his side. Behind his shoulder stands an angel, leaning in — the winged man, the symbol the Church assigns to him, painted here not as a creature beside him but as the one who is dictating. Like its neighbour it belongs to the man rather than to Mark's two verses: what the Church remembers about the publican who got up from the table is what he wrote afterwards.",

};
