// Prose readings, keyed by Commons file title. Each says where the icon was made, what it
// shows, and what in it answers to Mark's verses — nothing the picture does not show, and
// nothing borrowed from another Gospel without saying whose it is.
module.exports={

// ---- chapter 1 ----

"File:St John the Baptist Late XVII - Early XVIII Cenury St Mary Blonichka Church, Ohris Icon Gallery.jpg":
 "A panel from the church of St Mary Blonichka at Ohrid, painted about 1700. It is the Forerunner as the Church paints him rather than a scene from these verses: he stands full length with great brown wings folded behind him, because Mark opens by quoting Malachi's word for him, Behold, I send my messenger before thy face — and the Greek of that verse, angelos, is the word for both a messenger and an angel. The painter has taken Mark's own quotation literally. Everything else in the panel answers to Mark's description of him: the shaggy hide he wears over his shoulders is the camel's hair, and Mark adds that he had a girdle of a skin about his loins. The scroll he holds gives the preaching in Matthew's words, ΜΕΤΑΝΟΕΙΤΕ ΗΓΓΙΚΕΝ ΓΑΡ Η ΒΑΣΙΛΕΙΑ ΤΩΝ ΟΥΡΑΝΩΝ — Repent ye: for the kingdom of heaven is at hand — where Mark says only that he did preach the baptism of repentance for the remission of sins. In the charger at his waist lies his own severed head: the icon shows the end of the man at the moment of his beginning, which is why it belongs to the Forerunner himself and not to any one passage about him.",

"File:Baptism of Christ, Early XIV Century, St Mary Perivleptos Church, Ohrid Icon Gallery.jpg":
 "An early fourteenth-century panel from St Mary Peribleptos at Ohrid, one of the great Macedonian churches. Christ stands upright in the Jordan with his hand raised in blessing over the water; the Forerunner leans in from the left bank and lays his hand on Christ's head, which is what Mark states in five words — was baptized of John in Jordan. From a segment of heaven at the top a shaft comes straight down to him: Mark says the heavens opened, and the Spirit like a dove descending upon him. Four angels wait on the right bank with their hands covered, ready to receive him from the water — a courtesy the Church paints into every Theophany, not something Mark reports. In the water at Christ's feet two small figures turn away, an old man reclining and a rider on a sea-beast: the Jordan and the sea of Psalm 114, which the Church sings at this feast. At the foot of the left bank an axe lies against the root of a tree; that is the Forerunner's warning in Matthew and Luke, not in Mark, who gives none of his sermon but the promise of one mightier.",

"File:019 Baptism of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":
 "Painted in 1850 by Athanasios Margaritis for the church of St Paraskevi at Langadas, north of Thessaloniki. The composition is the same as the older Macedonian ones but the hand is a village hand and the colour is warmer: Christ stands waist-deep in a blue-green Jordan, the Forerunner reaches across with his right hand on Christ's head and a scroll in his left, and two angels crowd the right bank with their arms wrapped in their cloaks. What this painter has made most of is the opening of the heavens. A wide gold wound is torn in the dark sky and a red-orange shaft comes down out of it to Christ's head — Mark's word is the strongest of the four, that he saw the heavens opened, torn apart. The trees on either bank are painted as flat dark discs on bare stems, the convention of these Greek village panels for a wilderness.",

"File:03 Baptism of Christ Icon from Saint Paraskevi Church in Adam.jpg":
 "A Greek panel from the church of St Paraskevi at Adam, made before 1900 and darkened by candle smoke. It is the only one of the four here that paints the dove itself: a white bird hangs at the centre of a bank of grey cloud with a spray of rays spreading from it to Christ's head, so that Mark's two clauses — the heavens opened, and the Spirit like a dove descending upon him — are both in front of the eye at once. The Forerunner steps down from a rock on the left with his hand on Christ's head; three angels lean in from the right, the nearest holding a folded cloth. Mark alone of the Evangelists puts the whole event in Christ's own sight and hearing — he saw the heavens opened, and the voice that follows is spoken to him, not about him: Thou art my beloved Son. The icon keeps that intimacy — nobody but the Forerunner and the angels is present, and there is no crowd.",

"File:0663Ha. Hermitage Museum (Hall 143). Icon of the Epiphany.jpg":
 "A seventeenth-century panel from the Russian North, now in the Hermitage. The Jordan is painted as a deep black cleft between pale rocks, narrow at the bottom and opening upward, so that the water stands almost vertically around Christ like a grave. Russian painters made this reading of the feast their own: the descent into the river is the descent into death, and the white dove at the point of the long rays from heaven is what Mark says comes down on him as he comes up out of it. The Forerunner bends almost double from the rock on the left, his hand on Christ's head and his other hand raised to his face. Three angels stand on the right in graded reds and greens, the nearest holding a white cloth; their bowed heads and covered hands say what the voice says in Mark's next verse, Thou art my beloved Son, in whom I am well pleased.",

"File:Christ's temptation (Monreale).jpg":
 "A mosaic of the 1180s from the nave of Monreale in Sicily, made by Greek craftsmen for a Norman king. Christ stands on a bare rock holding a closed scroll; the devil, black and winged and gaunt, stretches a hand toward five round stones on the ground between them. The Latin around them is the exchange: SI FILI DI ES DIC VT LAPIDES ISTI PANE FIA[NT] — If thou be the Son of God, command that these stones be made bread — and Christ's reply, [SCRI]PTV[M] E[ST] NON IN SOLO PANE V[IVIT HO]MO, It is written, man shall not live by bread alone. Those words are Matthew's and Luke's. Mark gives the forty days in two verses and no dialogue at all: he was there in the wilderness forty days, tempted of Satan; and was with the wild beasts; and the angels ministered unto him. Neither the beasts nor the ministering angels are in this mosaic. What it does show is the one thing Mark does say — Satan and Christ alone in a stony place, and the tempter refused.",

"File:Elkomenos Prodromos Phylaken Dionysiou.jpg":
 "A fresco of 1547 from the katholikon of Dionysiou on Mount Athos, part of the great cycle of the Forerunner's life there. The inscription across the top names the scene exactly: ΕΛΚΟΜΕΝΟΣ Ο ΠΡΟΔΡΟΜΟΣ ΕΙΣ ΤΗΝ ΦΥΛΑΚΗΝ — the Forerunner dragged into the prison. A soldier in a plumed helmet has him by both bound wrists and hauls him forward; the Forerunner leans back against the pull, barefoot, his feet skidding on the pavement. On the right is the prison, a pale stone tower with a barred window, and two faces are already looking out of it. On the left Herod sits on a carved throne with a guard behind him holding a red spear. Mark says none of this: he reports the imprisonment in a subordinate clause — Now after that John was put in prison, Jesus came into Galilee — and moves straight on to the preaching of the kingdom. This is the icon of the event that clause refers to, which is why it stands here and why the card says it is not a depiction of these verses.",

// ---- chapters 1-2 ----

"File:Monreale - Jesus heals Simon's mother in law.jpg":
 "A mosaic of the 1180s from Monreale in Sicily. The Latin along the top reads IHS LIBERAT SOCRV[M] SIMONIS A MAGNIS FEBRIBVS — Jesus frees Simon's mother-in-law from a great fever. The adjective is Luke's; Mark says only that she lay sick of a fever. Everything else in the mosaic is Mark's sentence turned into a picture, and it is the gesture that matters: Christ has crossed the room with his arm already out toward her, she has raised herself on the bed and is reaching back, and the two hands are a hand's breadth apart across the gold. Mark is the only Evangelist who says he took her by the hand, and lifted her up — Matthew has him touch her hand, Luke has him rebuke the fever from a distance. The four who came in with him from the synagogue stand behind at the left, Simon and Andrew with James and John; a fifth head looks out of the doorway behind the bed. Mark ends the verse with what she did next, and she ministered unto them, which is why the painter has her rising rather than lying still.",

"File:Christ cleans leper man.jpg":
 "Monreale again, from the same twelfth-century cycle. The inscription is the leper's own words: POTES ME MVNDARE — thou canst make me clean. Mark gives them in full, If thou wilt, thou canst make me clean, and they are the only words in this picture. The leper stands at the right on a staff, his legs and arms and face flecked with the dark spots the mosaicist used for the disease, one hand raised toward Christ. Christ comes from the left with his own hand stretched out across the gold. Mark is the one who says what happened in that gap — moved with compassion, put forth his hand, and touched him — and the mosaic stops a moment short of it, at the reach rather than the touch. Behind Christ press the heads of his disciples. The little house at the right edge is where Mark sends him next: go thy way, shew thyself to the priest.",

"File:Monreale - healing of paralytic.jpg":
 "A Monreale mosaic of the 1180s, and the one picture in this reader that could only have been made from Mark. Its own inscription says so: APERVERVNT TECTVM — they uncovered the roof. Along the top of the wall two men lean over a broken parapet, one at each end of a rope, letting a bed down into the room. Neither Matthew nor Luke has men on a roof — Matthew says only that they brought him, and it is Mark who gives the press of people, the four bearers, the roof dug open and the bed lowered through it. Christ sits enthroned at the left with a disciple behind him, his hand out toward the man; the paralytic, already off the bed, kneels on it and stretches both arms back at him. At the right a knot of scribes in green and blue mutter together: Mark has them reasoning in their hearts, Why doth this man thus speak blasphemies? A second bed with a white coverlet stands behind them.",

"File:Healing of the Paralytic 04-17.jpg":
 "A fresco of 1502 by Dionisy in the Nativity cathedral at Ferapontov, in the Russian North, painted on a curved wall above an arch. It reads left to right as a sequence rather than a moment. At the left Christ sits with the apostles behind him and his hand raised; below him four men carry the paralytic in on a low bier, their heads crowded together over him — Mark's detail, borne of four. In the middle of the wall the same man walks away upright with the bed on his shoulder, which is Mark's last verse: he arose, took up the bed, and went forth before them all. At the right stand the people who watched it, in the dark robes Russian painters give the scribes. There is no roof in this fresco; what Dionisy has painted is the going out, not the coming in, and the two pictures beside each other in this gallery give the whole of Mark's account between them.",

"File:090 Mathew the Apostle Icon from Saint Paraskevi Church in Langadas.jpg":
 "A village panel of the nineteenth century from St Paraskevi at Langadas, north of Thessaloniki. It is the Apostle Matthew as the Church paints him: an old man with a long white beard, a codex open on his knee and a reed pen in his right hand, the blue ground bare behind his gold halo. He is here because of a name. Mark says the man at the receipt of custom was Levi the son of Alphaeus, and Matthew's own Gospel says that at the same table and the same words the man was Matthew; the Church has always read the two as one man, and keeps both names for him. So this is not a picture of the call — nothing in it is a custom-house, and no-one is being called — but the icon of the man it happened to, painted at the far end of his life with the Gospel he came to write already in his hands.",

"File:Matthew the Evangelist - icon.jpeg":
 "A Palekh panel of the nineteenth century, from the Russian village that painted icons in a fine, almost miniaturist hand. The inscription in the corner names him: С. ЕVАГГ. МАТѲЕЙ, the holy Evangelist Matthew. He sits at a desk in orange and violet with the quill lifted, an open book under his hand with Slavonic writing on the page, and a bound Gospel with a jewelled cover propped at his side. Behind his shoulder stands an angel, leaning in — the winged man, the symbol the Church assigns to him, painted here not as a creature beside him but as the one who is dictating. Like its neighbour it belongs to the man rather than to Mark's two verses: what the Church remembers about the publican who got up from the table is what he wrote afterwards.",

// ---- chapters 3-5 ----

"File:Iomenos xeran echon cheira Dionysiou.jpg":
 "A fresco of 1547 from the katholikon of Dionysiou on Athos. The inscription names it: Ο Χ(ΡΙΣΤΟ)Σ ΙΩΜΕΝΟΣ ΤΟΝ ΞΗΡΑΝ ΕΧΟΝΤΑ ΤΗΝ ΧΕΙΡΑ — Christ healing the man having the withered hand. The whole scene is an interior, a synagogue given the panelled walls and coffered ceiling of a Greek church, with a strip of starry night above it. Christ sits at the left with the apostles crowded behind him. In the middle of the floor, alone and upright, stands the man in a short red tunic with his arm already coming up — Mark alone reports the order that put him there, and it is an order to be looked at: Stand forth. Three elders sit along the right wall in green, red and purple, one with his hand raised in objection. They are what the passage is really about. Mark says Christ looked round about on them with anger, being grieved for the hardness of their hearts, and no other Evangelist dares write that word of him; then, in the last verse, these same men go out: And the Pharisees went forth, and straightway took counsel with the Herodians against him, how they might destroy him.",

"File:Synaxis of the Twelve Apostles by Constantinople master (early 14th c., Pushkin museum).jpg":
 "A panel painted in Constantinople in the early fourteenth century, now in Moscow. Its title is written across the top in Greek — Η ΣΥΝΑΞΙΣ ΤΩΝ ΑΓΙΩΝ ΔΩΔΕΚΑ ΑΠΟΣΤΟΛΩΝ, the assembly of the holy twelve apostles — with each man's name lettered in gold above his head. They stand in two ranks, four in front with their haloes overlapping and eight behind, holding scrolls and Gospel books. This is a feast, not a moment: the Church keeps the Synaxis of the Twelve on the thirtieth of June and sets this icon over it. Mark's verses are the choosing itself — he goeth up into a mountain, and calleth unto him whom he would — and he gives the roll of names that this icon letters in gold. Two of the surnames in that list are his alone: Simon he surnamed Peter, and the sons of Zebedee he surnamed Boanerges, which is, The sons of thunder.",

"File:Synaxis of the Twelve Apostles Dimitar Molerov Rila Monastery 1835.jpg":
 "Painted in 1835 by Dimitar Molerov at the monastery of Rila in Bulgaria, and photographed close, so that five of the twelve fill the frame. The style is late and half-Western — modelled faces, deep folds — but the arrangement is the old one: a row of standing men, each with his halo and his attribute. One holds a white scroll, one a Gospel bound in gold and jewels, and the last a small silver cross on a long stem — the mark of a martyr, which every one of them but John became. Mark's list at 3:16 is the reason the Church can paint them as individuals at all: it is the first time in this Gospel that the twelve are named one by one, and what they were ordained for is in the same sentence — that they should be with him, and that he might send them forth to preach.",

"File:The Twelve Apostles, with later gilding, Greek, Late Byzantine, early 1300s, tempera and gold leaf on wood panel - Princeton University Art Museum - DSC06701.jpg":
 "A Greek panel of the early fourteenth century, tempera and gold leaf on wood, regilded later. The panel has darkened almost to a single brown, and what survives clearly is the arrangement: three ranks of haloed heads, the punched gold discs still catching light, the bodies beneath them barely legible. That arrangement is the whole statement. Like the Constantinople icon it gathers the twelve into one company rather than telling a story, and the Church's reason for keeping them together is Mark's: they were ordained first of all that they should be with him, and only after that to preach and to cast out devils. The icon paints the first half of it — men standing with each other, doing nothing.",

"File:Representation of the Sower's parable.JPEG":
 "A modern Orthodox mosaic, its title lettered in Romanian across the top: PILDA SEMĂNĂTORULUI, the parable of the sower, numbered 21 in the cycle it belongs to. Christ himself is the sower, haloed, walking out of the middle of the picture with the seed gathered in a fold of his cloak and his right hand flung open. Round him the four grounds of the parable are laid out at once, which is what a mosaic can do and a story cannot: the trodden path at the left with four black birds already down on it; the bare grey rock at the upper right; a thicket of thorns with red flowers along the right-hand edge; and the standing green corn behind him. Mark's telling is the shortest of the three and it begins with a word the others leave out — Hearken — and ends with the yield counted upward: some thirty, and some sixty, and some an hundred.",

"File:Hrist utišava buru na moru, manastir Gračanica.jpg":
 "A fresco of about 1320 from Gračanica in Kosovo, and the most Marcan picture in this reader. Christ is in it twice. At the left he stands upright in the bow with his hand out over the water, and at the right he lies asleep in the stern with his head propped on his hand — the same person, painted at two moments of the same minute, which is how Byzantine wall-painters tell a story inside one frame. The sleeping figure is Mark's detail and nobody else's: he was in the hinder part of the ship, asleep on a pillow. Between the two the boat is full of men working — one hauling on a line in a red tunic, one bracing at the mast, one turned back toward the sleeper with his hands open in the gesture of a question. Mark gives them the sharpest words in any account of this night: Master, carest thou not that we perish? The sea is painted as rank on rank of grey scallops that run off the bottom of the fresco, and the sky behind is nearly black.",

"File:Mosaic of the exorcism of the Gerasene demoniac from the Basilica of Sant'Apollinare Nuovo.jpg":
 "A mosaic of about 520 from Sant'Apollinare Nuovo at Ravenna, one of the oldest pictures in this reader and older than the beard: Christ is painted as a young man in a purple robe with a cruciform halo, as the earliest Christian art always painted him. He stands at the left with one apostle in white beside him and his hand held out. In front of him, small and crouching on the ground in a short pale tunic, is one man — and that is why this mosaic stands beside Mark rather than beside Matthew, who has two men in this country. Mark's is one, and Mark spends eight verses on him that nobody else spends: the chains and fetters plucked asunder, the crying night and day among the tombs, the cutting of himself with stones, and the name — My name is Legion: for we are many. At the right a herd of dark swine runs down into a band of bright blue water. Mark counts them where the others do not: they were about two thousand.",

// ---- chapters 5-6 ----

"File:Daughter of the head of synagogue is resurrected by Christ.jpg":
 "Monreale, the 1180s. The Latin along the top says what it is — Jesus raises the daughter of the ruler of the synagogue, in the house. That last phrase matters: Mark is careful about who was let in. He suffered no man to follow him, save Peter, and James, and John the brother of James, and then put out the mourners who laughed at him, and took the father and the mother and his own three inside with him. The mosaicist has kept the room small and crowded to match. Christ comes in from the left and has her by the hand — and she is already sitting up, in a white gown and headcloth, her legs still under the brown patterned coverlet, with a woman behind steadying her shoulder. Mark says he took the damsel by the hand, and that is what the mosaic is built around. Mark alone records the two Aramaic words Christ used, and then translates them for his readers: Talitha cumi; which is, being interpreted, Damsel, I say unto thee, arise. He alone adds the last, practical sentence too: and commanded that something should be given her to eat.",

"File:Raising of Jairus' daughter 03-19.jpg":
 "Dionisy's fresco of 1502 at Ferapontov, painted on a curved wall above an arch, and damaged: the face inside one of the haloes has flaked away entirely, leaving a bare ring of ochre. The bed stands across the left of the wall with the child on it, already raised on one elbow in her white shift. A haloed figure stands over her with a hand out, and at the right, separated by the standing bystanders, is a second haloed figure in dark red. Russian painters of this school habitually give a scene twice on one wall — the coming and the doing — and that is the likeliest reading here, though the damage makes it a reading rather than a certainty. Mark's own account has the same doubled shape: the message reaches Christ on the road, Thy daughter is dead: why troublest thou the Master any further? and he goes on to the house all the same.",

"File:Tokalı Kilise Raising of daughter of Jairus - 2004 6964.jpg":
 "From the Tokalı Kilise in Cappadocia, painted in the tenth century on the rock wall of a cave church. It is the oldest and the roughest of the three and the strongest. Almost half the picture is the bed: a great swag of deep red cloth, drawn with looping ornament and a row of black chevrons along its edge, hanging down the whole lower half of the wall. The girl lies along the top of it in blue, small against it. Christ stands to the left of centre with his hand out toward her, and the household crowds in behind. Mark's telling is built the same way, out of one held detail after another — the ruler falling at his feet, the delay while the woman in the crowd is healed, the message that comes too late, and then the two words in the room. The painter has given the death its whole weight in that red bed, and the raising a single reaching arm.",

"File:Apotome Agiou Ioannou Prodromou Dionysiou.jpg":
 "Dionysiou on Athos, 1547. The inscription names it the beheading of the Forerunner. The executioner stands over him in scale armour with the sword already swung back above his head; the Forerunner kneels on the rock, his body bent right down, and his haloed head is shown forward of his shoulders, at the instant. At the right a young woman in a red gown with a crown on her head kneels and holds out a golden dish to catch it. Mark tells this story at more length than anything else in his Gospel that Christ is not in, and the picture follows him closely: the daughter's dancing and the oath, the request made in haste — I will that thou give me by and by in a charger the head of John the Baptist — and the king who was exceeding sorry and sent anyway. Behind them stands the prison with its barred window, where Mark has kept John since chapter one.",

"File:103 Beheading of Saint John the Baptist Icon from Saint Paraskevi Church in Langadas.jpg":
 "A Greek panel of 1927 from St Paraskevi at Langadas, very dark now and split by a crack from top to bottom. There is no scene in it at all: only the severed head, face upward in a shallow dish, with its gold halo behind it filling the panel. This is an icon the Church paints on its own, for the feast of the Beheading on the twenty-ninth of August, a day kept as a strict fast. It stands here because of the two words Mark gives Herodias' daughter — in a charger — and because of the sentence after them, which no reader forgets: and the damsel gave it to her mother.",

"File:19 Beheading of Saint John the Baptist Icon in Assumption of Mary Church in Agios Vasileios.jpg":
 "A Greek panel from the Dormition church at Agios Vasileios, painted before 1900 and worn round its edges. It takes the moment after the Dionysiou fresco's: the executioner, in gold armour and a plumed helmet, holds the head by the hair and is lowering it into the gold charger that a crowned woman in gold holds up to him with both hands. The body lies along the bottom of the panel, headless, in green and dark red. Behind them is the prison wall with its grated window. Mark's word for the man with the sword is a Latin one borrowed into Greek — a speculator, a guardsman of the king's own bodyguard — and it is the kind of detail that keeps turning up in this Gospel: the king sent an executioner, and commanded his head to be brought.",

"File:Evlogesis Pente Arton Dionysiou.jpg":
 "Dionysiou, 1547, inscribed Η ΕΥΛΟΓΗΣΙΣ ΤΩΝ ΠΕΝΤΕ ΑΡΤΩΝ — the blessing of the five loaves. Christ stands at the far left with the loaves heaped in a cloth in his hands, and from there the fresco runs downhill to the right through the apostles carrying baskets to the people sitting on the ground. What makes it Mark's is the ground itself. He is the only Evangelist who says what colour it was and how the people were arranged on it: he commanded them to make all sit down by companies upon the green grass, and they sat down in ranks, by hundreds, and by fifties. The painter has taken him at his word and set the crowd in blocks of colour, red beside green, on a slope of grass with small plants drawn on it. At the bottom left stand four wicker baskets packed with broken bread — Mark counts twelve of them taken up afterwards.",

"File:Feeding the multitude, Sant'Apollinare Nuovo, Ravenna.jpg":
 "About 520, from Sant'Apollinare Nuovo at Ravenna, and it leaves the multitude out. The young beardless Christ stands in the centre in purple with both arms stretched wide; two apostles in white at his right hold up round loaves, two at his left hold out the fish. There is no crowd, no grass, no baskets — only the handing over. That is exactly the clause Mark puts at the centre of the miracle: he blessed, and brake the loaves, and gave them to his disciples to set before them. The mosaicist has made the picture out of the giving rather than the eating, and left the five thousand to be understood.",

// ---- chapters 7-9 ----

"File:Christos Iomenos Thygatera Xananaias Dionysiou.jpg":
 "A fresco of 1547 from the katholikon of Dionysiou on Athos, from the same cycle as the healing of the withered hand. The title across the top keeps Matthew's word for her rather than Mark's — Ο Χ(ΡΙΣΤΟ)Σ ΙΩΜΕΝΟΣ ΤΗΝ ΘΥΓΑΤΕΡΑ ΤΗΣ ΧΑΝΑΝΑΙΑΣ, Christ healing the daughter of the Canaanite — where Mark calls her something else: a Greek, a Syrophenician by nation, the geography of the Roman province rather than the old enemy nation Matthew's word recalls. Neither the fresco's inscription nor its composition knows the difference; the two Gospels' scenes are painted as one. She stands at the centre in a pale robe and head-cloth with both hands lifted, arguing rather than kneeling. Christ, at the left with three apostles at his shoulder, has already put his hand out toward her. Mark gives the exchange in his own plainer words — Let the children first be filled: for it is not meet to take the children’s bread, and to cast it unto the dogs — and her answer keeps his shape of it too, Yes, Lord: yet the dogs under the table eat of the children’s crumbs. What Christ says back is not what Matthew has him say: there is no O woman, great is thy faith here, only For this saying go thy way; the devil is gone out of thy daughter — it is her word he answers, not her faith he names. At the right, on a great red couch under a tiled roof, the daughter is painted already lying down, though Mark's healing happens out of the woman's sight and at a distance: she found the devil gone out, and her daughter laid upon the bed only once she is home again, and the painter has brought that homecoming into the same frame as the plea.",

"File:Monreale - Multiplication of the Loaves and Fishes.jpg":
 "A mosaic of the 1180s from the nave of Monreale in Sicily, from the same cycle as the mosaic of the earlier feeding two chapters back — and, its own Latin inscription makes plain, actually the same event: IHS DE QVINQVE PANIBVS ET DVOBVS PISCIBVS QVINQVE MILIA HOMINVM SATIAVIT ET DE FRAGMENTIS DVODECIM COPHINI IMPLETI SVNT, Jesus fed five thousand men with five loaves and two fishes, and of the fragments twelve baskets were filled. Every number in that sentence is the first feeding's, not this one's: these verses give seven loaves, a few small fishes, about four thousand men, and seven baskets of fragments left over. What the mosaic shows, apart from its own caption, still answers loosely to Mark's giving rather than his numbers. At the left Christ stands with Peter, a small white bundle of bread already passing between their hands — he took the seven loaves, and gave thanks, and brake, and gave to his disciples to set before them, though what is pictured is round loaves rather than the meagre seven the text names. The middle of the mosaic is disciples carrying the food out in procession; the multitude is banked on a green hillside at the right, row above row of faces, with a man bending over baskets at the bottom edge to gather what is left. Mark's own version of the disciples' question, asked a second time despite what they had already seen done once — From whence can a man satisfy these men with bread here in the wilderness? — is the one thing this borrowed mosaic cannot show: that this is the miracle repeated, not the miracle itself.",

"File:Transfiguration of Christ Icon Sinai 12th century.jpg":
 "The pericope opens with a saying before it becomes a scene — there be some of them that stand here, which shall not taste of death, till they have seen the kingdom of God come with power — and the Church has always read what follows as that promise kept: after six days, the mountain, the dazzling raiment. This icon's own record describes the object it was photographed from as a wide festal beam, forty-one and a half by a hundred and fifty-nine centimetres, meant to carry several feasts along a templon screen; what is shown here is a detail, the Transfiguration alone, worn down to bare gold in patches across the whole width of it. Christ stands on the peak at the centre with one hand raised and a scroll in the other. Elias is at the left, old and grey-bearded in a dark mantle with his hands hidden in it; Moses is at the right, younger and dark-haired, holding a pale tablet and reaching his free hand out toward Christ — the Law carried up the mountain in the lawgiver's own hands. Below, on the damaged lower field, three apostles are thrown down in three attitudes — one kneeling with a hand raised, one bowed low at the centre, one turned aside — which is the wreck of Peter's offer, Master, it is good for us to be here: and let us make three tabernacles; one for thee, and one for Moses, and one for Elias. Mark alone gives the reason behind it: for he wist not what to say; for they were sore afraid.",

"File:042 Transfiguration of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":
 "A village panel signed and dated along the bottom in white paint — 1885 · χείρ Σταύρου Μαργαρίτη εκ Κολακιάς, by the hand of Stavros Margaritis of Kolakia — from the same church at Langadas that has an earlier Baptism in this reader from a related hand, Athanasios Margaritis, thirty-five years before. Christ stands at the top inside a pale oval mandorla on bare gold, his right hand raised in blessing. Moses kneels on a cloud at the left, dark-haired, with a pale open tablet on his knee, looking down at it; Elias kneels on a cloud at the right, white-bearded, one hand drawn to his breast. Below them the mountain is a plain red-brown slope and the three disciples are scattered down it in three separate attitudes — one kneeling with both arms thrown up, one fallen face-upward at the centre, one recoiling at the right with his name still legible beside his halo, ΙΑΚ, James. Mark's own word for what has happened to Christ is that he was transfigured, and what he specifies about it is not the face but the clothes: his raiment became shining, exceeding white as snow; so as no fuller on earth can white them — a launderer's trade turned into the measure of a light no launderer's trade could reach. And there appeared unto them Elias with Moses is Mark's own order, naming the prophet before the lawgiver, where Matthew names Moses first.",

"File:Icon of the Transfiguration from Saint Catherine's, Sinai.jpg":
 "A second twelfth-century panel from St Catherine's on Sinai, and the plainest of the four in what it gives Christ: no mandorla, and at full size hardly even a halo — three or four thin red strokes behind his head and then bare ground, where the other three icons in this batch all give him a disc of light. What the icon has instead is the clothing: he stands barefoot on green rock in a white chiton and mantle, one hand at his breast, and his raiment became shining, exceeding white as snow; so as no fuller on earth can white them is carried by the paint rather than by anything drawn around it. Elias stands at the left, old and white-bearded in a dark mantle, one hand drawn to his chest; Moses at the right, young and dark-haired in a patterned robe, his hand simply held out toward Christ — no tablet in it here, unlike the icon beside it in this gallery. Below, a narrow wedge of gold light runs down between two green rocky humps from Christ's feet to the ground, and the three disciples lie broken across it: Peter at the left, old and bearded, kneeling with one hand raised as if still speaking; John at the centre collapsed entirely, face buried in his own robe, nothing of him visible but the curve of his back; James at the right, seated rather than fallen, one hand resting on a drawn-up knee, looking down and away. It is Mark who explains why Peter spoke at all — for he wist not what to say; for they were sore afraid — and this icon's John, given no gesture whatever, is the clearest picture in the reader of what that fear looked like.",

"File:Icon of transfiguration (Spaso-Preobrazhensky Monastery, Yaroslavl).jpg":
 "A Russian panel of about 1516 from the Saviour-Transfiguration monastery at Yaroslavl, the house named for this very feast, and the most elaborate composition in the batch: what the Greek icons keep to one register, this one spreads across three. At the centre Christ stands inside a dark blue-green mandorla shaped almost like an eight-pointed star, long gold rays breaking out of it and small gold stars scattered through the dark; Elias leans in from a crag at the left with a hand raised, and Moses leans in from the crag at the right, an object wrapped in cloth held in both hands against his chest — the Law carried rather than opened. Below them the fall is the most violent of the four: Peter kneels at the left with both hands thrown up to shield his face from the light, still turned toward it and, on Mark's telling, still talking; the other two are painted in the middle of falling rather than fallen, one pitched forward almost head-first down the slope with a hand over his face, the other crouched low and turning away — a suddenly of its own, matched to Mark's last verse here, and suddenly, when they had looked round about, they saw no man any more, save Jesus only with themselves. In the two small registers painted to either side of the mountain is what the Greek panels in this reader leave out entirely: at the left Christ leads the three up the slope before any of this happens, and at the right — a scene that belongs to the verses just after this passage, not to these eight — he brings them down again, charging them to tell no man what they had seen.",

// ---- chapter 11 ----

"File:Baiophoros Dionysiou.jpg":
 "A fresco of 1547 from the katholikon of Dionysiou on Mount Athos, from the same Holy Week cycle as the withered hand and the Canaanite woman's daughter shown elsewhere in this reader. Red letters on the gold ground above name the feast rather than the verses, ΒΑΙΟΦΟΡΟΣ, the Palm-bearing. Christ sits sideways on a pale colt at the centre, his right hand raised in blessing and his left resting on his knee, the monogram IC XC over his halo; the disciples crowd in behind him, one white-haired at his near shoulder. There is only the one animal under him — Mark sends the two disciples for a colt, in the singular, and he sat upon him, where Matthew's account brings an ass and her colt both and seats him on each in turn. At the centre of the panel a boy has climbed a bare tree and leans out to cut a branch, passing it down to a companion waiting below; Mark does not say what tree it was cut from, only that others cut down branches off the trees — it is St John's Gospel that names the palm, and the Church has kept his word for the feast's own name though the scene here is reading Mark's clause. At the foot of the tree a group of children in red and green kneel in the road, one already thrown flat to spread his own cloak under the colt's feet, among those Mark says spread their garments in the way. Jerusalem's walls and red roofs rise at the right, its people already filing out through the gate to meet him.",

"File:005 Entry into Jerusalem Icon from Saint Paraskevi Church in Langadas.jpg":
 "A Greek village panel from St Paraskevi at Langadas, its title lettered in red at the upper left, Η ΒΑΙΟΦΟΡΟC. The scene begins after Mark's own opening verses are already over: two disciples have gone into the village and come back, having found the colt tied by the door without in a place where two ways met, and it is only the finished procession the icon paints, not the finding of it. Christ rides the white colt across the middle of the panel, looking back over his shoulder at the disciples massed behind him rather than forward at the city; a dark palm rises at the centre with a small figure climbing to cut its branches, and Jerusalem's red roofs wait at the upper right with its people coming out at the gate. Garments are laid in the road under the colt's hooves. Mark gives the animal one qualification no icon can paint — whereon never man sat — the colt itself as untried as the city he is about to enter.",

"File:18 Triumphal entry into Jerusalem Icon from Saint Paraskevi Church in Adam..jpg":
 "A Greek panel of 1846 from the village of Adam, the date still legible in the corner. It is the plainest of the four: no rock, no wilderness, no tree at all — Jerusalem fills the whole upper half of the board, a walled town of tiled roofs and one gold dome, and the procession runs along the bottom beneath it. Christ does not look back at his own disciples here, as he does in the icon beside this one; his head is turned forward and his blessing hand toward the people coming out of the gate to meet him, three disciples following at the left under gold haloes. A child kneels in the road to spread a dark cloth in front of the colt's hooves, another garment laid down beside it. This is the one icon here that puts the whole city, gate and dome and walls, in front of Christ's own eyes rather than merely beside him — which is where Mark's own last verse of the passage sends him too: And Jesus entered into Jerusalem, and into the temple: and when he had looked round about upon all things, and now the eventide was come, he went out unto Bethany with the twelve. Nothing happens yet. The city this panel paints so large is only looked at today; what the icon shows as an arrival, Mark writes as a single quiet circuit of an empty room, before the door is shut on the day.",

"File:Entry into Jerusalem (Afon icon).jpg":
 "A sixteenth-century Athonite panel, its inscription written straight onto the gold at the top, and the most crowded of the four: the disciples bank in a close mass at the far left, a dark tree stands at the centre with a boy in red climbing to cut its branches, and the whole right half of the board is given to Jerusalem — white walls, a great dome, and a crowd at the gate painted as thirty or forty heads one behind another. Christ rides the white colt at the left in a dark blue mantle, blessing with his right hand and holding a rolled scroll in his left, the two disciples who fetched the colt for him no longer distinguishable in the crowd behind. It was those two Mark sends ahead at the start of the passage, with instructions built for a single objection: and if any man say unto you, Why do ye this? say ye that the Lord hath need of him; and straightway he will send him hither. Nothing in the icon can paint that sentence being spoken, only its result obeyed — but it is why the villagers loosing the colt let it go without a struggle, and the whole procession here follows from it. At the bottom, children kneel to lay their clothes in the road, and the cry the icon cannot make audible is Mark's own, with a clause the other three Gospels do not carry: Blessed be the kingdom of our father David, that cometh in the name of the Lord.",

"File:074 Cursing the fig tree Icon from Saint Paraskevi Church in Langadas.jpg":
 "A nineteenth-century Greek panel from St Paraskevi at Langadas, its gold ground rubbed through to the board in places. Christ stands right of centre in a rose himation over blue, his right arm stretched toward the tree, an open scroll in his left hand whose writing is no longer legible; the apostles are packed in a wedge of overlapping haloes behind him, and the walls and towers and cypresses of Jerusalem stand at the upper left, the city he had ridden into the day before. The tree fills the right quarter of the panel in thick, healthy green — full leaf, nothing withered in it anywhere — and that is exactly the state Mark's own verse puts it in at the moment Christ reaches it: seeing a fig tree afar off having leaves, he came, if haply he might find any thing thereon: and when he came to it, he found nothing but leaves. Mark alone gives the reason it disappoints him, and it excuses the tree of nothing: for the time of figs was not yet. A tree in full leaf out of season was, by the custom of the country, a tree that should still have carried the small early fruit its leaves promise; this one has none. The icon has painted the leaves and left out both the missing fruit and the curse Christ is about to speak over it — No man eat fruit of thee hereafter for ever — which belongs to the next passage, not to this picture: Mark holds the withering itself back a full day, for the disciples to find in the morning.",

"File:Fig tree cursed 04-16.jpg":
 "A fresco of 1502 by Dionisy at Ferapontov, and the photograph takes in a continuous register of two scenes with no frame between them. At the left, Christ stands with the apostles crowded behind him, his arm out toward a tree that rises thin and pale against the blue — bare branching twigs and not one leaf anywhere on it. Where the Langadas panel beside this one in the gallery paints the tree exactly as Mark's verse finds it, in leaf and fruitless, Dionisy has painted the tree already at the end of a story Mark has not yet told at this point in his own text: on the morrow, when they were come from Bethany, he was hungry, and only then, a full day and another passage later, do the disciples see it dried up from the roots. The fresco compresses Mark's two mornings into one image, the curse and its result shown together as icons often do with a single scene. At the right-hand third of the same wall a table is spread with a white cloth, a company of men seated round it and an old man in a white head-cloth at its head; on the floor beneath them a figure in dark red lies stretched full length at their feet. Mark's own chapters here run on the same daily rhythm the two scenes together suggest — day by day in the temple and out again to Bethany at evening — without this fresco naming which of those days its second scene belongs to.",

"File:Christ banish tradesmen from Temple (Monreale).jpg":
 "A twelfth-century mosaic from Monreale in Sicily, worked by Byzantine craftsmen for a Norman king, from the same cycle as the mosaic of the second, unnamed feeding elsewhere in this gallery. Christ brings his hand down on the money-changers' table at the centre, the coins still heaped on it and pouring off its edge; three sellers recoil at the right under a hanging cage of doves. Two things in the mosaic belong to another Gospel: a short rod raised behind Christ's head is St John's scourge of small cords, which Mark never mentions, and the oxen driven out at the bottom edge are John's animals too — Mark names only the sellers of doves and the money-changers' tables among what was overthrown. What the mosaic cannot show at all is the sentence that follows in Mark and in no other Gospel: and would not suffer that any man should carry any vessel through the temple — not a single dramatic act but a standing order, a whole afternoon of people turned back from using the temple court as a footpath, which no single frozen moment can picture. Mark's own wording of the prophecy Christ speaks next is also his alone in full: My house shall be called of all nations the house of prayer — Matthew and Luke both give the same quotation with of all nations left out.",

"File:Rossano Gospels - Cleansing of the Temple.jpg":
 "A page from the Rossano Gospels, a Greek Gospel book of the sixth century written in silver on parchment dyed purple, one of the oldest illustrated Gospel manuscripts that survives. Across the top of the page runs the scene itself, headed in gold ΠΕΡΙ ΤΩΝ ΕΚΒΛΗΘΕΝΤΩΝ ΕΚ ΤΟΥ ΙΕΡΟΥ, concerning those cast out of the temple: Christ in a gold himation at the left with two figures behind him, a money-changer bent over his table, a man carrying a cage of doves, and two oxen hauled out at the right edge — the doves are Mark's own detail, the oxen St John's, folded here into one picture as the Monreale mosaic elsewhere in this gallery folds them too. Below the scene stand four prophets, cut off at the waist and each holding nothing, a column of his own words written out in Greek beneath him: ΔΑΔ, David, twice, both crowned; ΩΣΗΕ, Hosea; and ΗΣΑΙΑΣ, Isaiah. Isaiah is the prophet Mark himself is quoting when Christ calls the temple the house of prayer — but Jeremiah, whose den of thieves supplies the second half of the same sentence, is not among the four; the manuscript is making its own case for the temple's true king out of David and Hosea as much as out of the one prophet the Gospel names, prophecy and event set on one opening with the joining left to the reader. Mark's own last verse in the passage is the one no picture here can carry: the scribes and chief priests heard it, and sought how they might destroy him: for they feared him, because all the people was astonished at his doctrine — the plot against him decided, in this Gospel, on the very afternoon of the day after he rode in.",

// ---- chapter 13 ----

"File:Second Coming by G.Klontzas (16th c.).jpg":
 "A Cretan icon of the Second Coming — the Deutera Parousia — painted by Georgios Klontzas at the end of the sixteenth century; the same board also stands for the parallel discourse in Matthew's reader, because it paints no one evangelist's wording but the Church's own icon of the Last Judgment. Christ sits in a red mandorla at the centre with two winged angels close beside him and the whole is set on a wheeled, many-eyed vehicle out of Ezekiel's vision — the Church's answer to a scene no Gospel writer could paint directly. In each upper corner a pair of bodiless cherub heads rolls up a dark band across the gold: the sky itself being taken up like a scroll, the icon's own picture for the verse that has no picture, and the stars of heaven shall fall, and the powers that are in heaven shall be shaken. Below the throne two ranks of apostles and saints sit enthroned to left and right, and under them, filling the whole lower two-thirds of the board, the river of fire, the ranks of the saved, and the earth and the sea opening to give up their dead. Mark's own last clause of the discourse reaches both halves of this single board at once — he shall send his angels, and shall gather together his elect from the four winds, from the uttermost part of the earth to the uttermost part of heaven — earth below, heaven above, in one merism Matthew's parallel does not use; his own version keeps the two halves of the sky, from one end of heaven to the other. Nothing here paints the false Christs and false prophets Mark's opening verses warn against, or the trumpet Matthew's account gives the angels; the icon begins where Mark's twenty-sixth verse does, with the Son of man already come in the clouds with great power and glory.",

// ---- chapter 14 ----

"File:Monreale - Anointing at Bethany.jpg":
 "A twelfth-century mosaic from Monreale in Sicily, worked by Byzantine craftsmen for a Norman king; the same mosaic serves Matthew's reader for his own account of the same supper. Christ reclines at the left on a cushioned couch, haloed, his hand low and open toward the floor; a woman is stretched full length at his feet, the only figure in the whole mosaic not upright, her hands at his bare foot. Mark states plainly that she brake the box, and poured it on his head — an alabaster box of ointment of spikenard very precious — the pouring, and the breaking of the vessel itself, are Mark's own details, but the mosaicist has followed John's Gospel in setting her at Christ's feet rather than at his head, and no wiping of the feet with her hair is shown here as John describes it. A small white two-handled vessel stands on the floor below the couch. At the right a crowd of disciples presses in with their hands raised in argument; Mark alone leaves them unnamed — some that had indignation within themselves, and they murmured against her — where Matthew's account of this same supper calls them his disciples outright. One dish sits at the centre of the spread cloth. Mark's own last word of the passage, that wheresoever this gospel shall be preached throughout the whole world, this also that she hath done shall be spoken of for a memorial of her, is a promise the picture keeps simply by still being looked at, fresco and reader both, this many centuries on.",

"File:Judas receiving money, icon of Yaroslavl (19 c, priv.coll).jpg":
 "A nineteenth-century icon of the Yaroslavl school, its Church Slavonic title across the top naming Judas selling Christ for thirty pieces of silver — the same panel Matthew's reader shows for his own, fuller account of the bargain. Judas stands unhaloed at the left, his bare hand laid on the edge of a white cloth on which small coins lie spread and being counted; the high priest sits at the centre in the hood of his office with both hands on the money, a scribe and a knot of elders pressing in from the right under a canopy that marks the scene as indoors. What the icon paints as a settled price is fuller than Mark's own text allows: Mark says only that Judas went unto the chief priests, to betray him unto them, and when they heard it, they were glad, and promised to give him money — no number is named, and the asking is not Judas's own as it is in Matthew's account, where he himself opens with what will ye give me. The thirty pieces the coins on the cloth stand for, and the counting out the icon paints in the open, belong to the fuller story the Church has always read behind Mark's sparer one, not to anything these two verses state outright.",

"File:Deipnos Mystikos Dionysiou.jpg":
 "The Mystical Supper from the katholikon of Dionysiou on Mount Athos, painted in 1547, with Ο ΔΕΙΠΝΟΣ Ο ΜΥΣΤΙΚΟΣ lettered across the night sky above the table. Christ sits at the middle of the far side with his right hand lifted before his breast, and the cloth in front of him is laid for a meal already under way: round loaves scattered over it, goblets and jugs, knives, two candlesticks, and in the middle a footed bowl with a single fish lying in it. Mark's four verses are what was said and done over such a table — as they did eat, Jesus took bread, and blessed, and brake it, and gave to them, and said, Take, eat: this is my body — and the painter gives the blessing to the lifted hand and leaves the loaves on the cloth, not in his fingers. Two figures come from outside these verses. The young disciple resting his head against the Lord is John's detail, from his own Gospel; Mark never gives it. And the man in green under a red cloak, flung forward across the cloth with his arm stretched toward the bowl, is the sign Mark had already given two verses before this passage opens: It is one of the twelve, that dippeth with me in the dish. Mark's words have no hand in them, where Matthew's version of the saying does, and Mark names no disciple at this table and has no one leave it; of the cup he says only that they all drank of it. The fish is the painter's as well: the chapter says that they made ready the passover, and names no fish.",

"File:05 Last Supper Icon from Saint Paraskevi Church in Adam.jpg":
 "A village panel from Saint Paraskevi at Adam in Greece, the work of Asterios Anagnostos in 1898, now split from top to bottom down its left third, the crack running straight through the beloved disciple's halo. For Mark's four verses it gives the blessing and the cup. Christ sits at the head of the table in a red tunic under a dark mantle with his right hand raised, palm outward and two fingers up: Mark has him bless over the bread and give thanks over the cup, and the painter gives both to the one raised hand. Two small cups stand on the cloth, one on either side of the great basin in the middle, with a dark flask beside the nearer; neither is in his hand, and Mark's sentence finishes what the picture leaves standing — and they all drank of it, told as a thing done, where Matthew's account gives it as a command, Drink ye all of it. Every head at the table carries a halo. The rest of the board is the meal Mark had begun a few verses earlier: the beardless disciple in green bowed on the board at the Lord's side is John's detail, not Mark's, and a green sleeve reaches in from the right until the hand is over the rim of the basin. That reach is verse 20, It is one of the twelve, that dippeth with me in the dish, and the painter sets no other mark on the man it belongs to — he is haloed like the rest. An oil lamp hangs on its chain over Christ's head between the two halves of the title, ὁ δεῖπνος ὁ μυστικός; Mark had already said that in the evening he cometh with the twelve.",

"File:Kirillo-Belozersky iconostasis 12 - Last Supper.jpg":
 "From the festival row of the iconostasis at the Kirillo-Belozersky monastery in the Russian north, painted in 1497. The painter puts Christ not at the middle of the table but at its upper left corner, haloed, in a red tunic under a blue mantle, with the disciple John's Gospel calls beloved bowed against his breast; and he tips the tabletop up like a page so that everything on it lies in plain view. It holds very little. Small triangular pieces are set about the pale cloth, and an apostle on the far side at the right already has one in his fingers — the only thing on the table in anyone's hand, and the nearest the icon comes to Mark's brake it, and gave to them. A single footed cup stands at the left; a small lidded vessel stands in the middle; and at the right a second cup survives only as an outline, drawn and never painted, or its paint long gone. The most pointed gesture belongs to an apostle in green who leans over from the far side and lowers his hand into the footed cup. That is the sign of verse 20, one of the twelve, that dippeth with me in the dish, but the vessel he reaches into here is a cup, not a dish — the cup of which Mark, three verses later, says they all drank of it. Mark's word over that cup stops at which is shed for many, without the for the remission of sins that Matthew's version adds, and his last verse is the one of the four that looks past the table altogether: I will drink no more of the fruit of the vine, until that day that I drink it new in the kingdom of God.",

"File:The Lord's prayer in Gethsemane - Stavronikita monastery, Mt Athos - Theophanes of Crete, 16th c..jpg":
 "A fresco by Theophanes the Cretan in the katholikon of Stavronikita on Mount Athos, sixteenth century, badly worn along its upper edge, where the dark ground has flaked away and only a few letters of the title survive. Christ is painted four times on the rock: at the upper left bowed so low that his face is hidden against the stone; upright at the top; kneeling at the right with his face lifted; and lower down, standing, with his hand held out toward the sleepers. The first figure is Mark's verb exactly — he went forward a little, and fell on the ground — where Matthew's account has him fall on his face; and the lifted face at the right is the prayer that Mark alone gives with its Aramaic first word, Abba, Father, all things are possible unto thee; take away this cup from me: nevertheless not what I will, but what thou wilt. The whole lower half of the wall is the disciples, a dozen of them, sitting with their heads down or lying across one another, one stretched full length along the foot of the wall and one wrapped head and all in a red cloak. Mark keeps them in two groups — the others told Sit ye here, while I shall pray, and Peter and James and John taken further on — and the painter has let them all fall asleep in one heap. Nearest the standing Christ's hand a disciple in yellow sits upright, though the plaster is too worn to show whether his eyes are open; Mark has the Lord speak to one of them by name, Simon, sleepest thou? couldest not thou watch one hour? and on the second return find them asleep again, (for their eyes were heavy,) neither wist they what to answer him.",

"File:Gethsemane Dionysiou.jpg":
 "The Prayer of Christ from the katholikon of Dionysiou on Athos, 1547, painted round the head of an arched opening in the wall, so that the scene runs along a rocky ridge at the top and down the right side of a great black arch; Η ΠΡΟΣΕΥΧΗ ΤΟΥ ΧΥ is lettered across the night sky. Three times along the ridge Christ kneels, each figure marked ΙΣ ΧΣ, and each is given a different posture: the first with both hands spread open, the second upright with his hand raised to his cheek in grief, the third bent forward with a hand stretched down toward the rock. The middle figure is Mark's own account of the first moment in the garden — he began to be sore amazed, and to be very heavy, and told the three, My soul is exceeding sorrowful unto death — and Mark is the only Evangelist who says amazed. The three kneeling figures are one more prayer than Mark narrates: he tells the first, then And again he went away, and prayed, and spake the same words, and leaves the third to be understood from he cometh the third time. Between the two words of the title a tiny winged figure with a gold halo flies down out of the dark; Mark has no angel in the garden, and the painter has borrowed Luke's. At the right Christ stands with a closed white scroll in his left hand and his right hand raised over the sleepers, and the one disciple sitting up, grey-haired and short-bearded in yellow as Peter is painted, looks up at him with both hands open and says nothing. Mark alone gives both halves of that: the rebuke by name, Simon, sleepest thou? and at the next return, neither wist they what to answer him. Round him the others sleep every way a man can — heads on hands, one with his mouth fallen open, one wrapped head and all in a red mantle, an old man stretched on the ground in green.",

"File:Cathedral (Monreale) - Right wing transept - Agony in the Garden.jpg":
 "A mosaic from the right transept of Monreale cathedral in Sicily, twelfth century, set by Byzantine craftsmen. Christ is shown twice. At the top he kneels on the crest of a pale hill with both hands raised, and an angel flies in level out of the gold from the left, reaching toward him: Luke's angel, the one Luke alone reports. Mark has none. Below the kneeling figure the hill is filled with the disciples asleep, wrapped in their mantles and slumped against one another in a heap. At the right the Lord stands a second time, a closed scroll in his left hand, holding out his right toward the one disciple who is sitting up — white-haired and short-bearded, in an ochre mantle over blue, his hand at his breast, turned toward him, the likeness the Church gives Peter. It is the moment Mark tells more exactly than anyone: he cometh, and findeth them sleeping, and saith unto Peter, Simon, sleepest thou? couldest not thou watch one hour? Across the gold at the upper right the letters that can still be read, …LATE ET ORATE… TIS IN TEM…, are the Latin of the next sentence, which Mark gives as Watch ye and pray, lest ye enter into temptation, and goes on, The spirit truly is ready, but the flesh is weak. A second band of lettering runs along the upper left, too worn in this photograph to be read.",

"File:Prodosia Dionysiou.jpg":
 "The Betrayal — Η ΠΡΟΔΟΣΙΑ — from the katholikon of Dionysiou on Athos, 1547, under a black night sky pricked with stars. Judas has come in from the left in a red mantle over green, both arms round the Lord and his face against his; Christ stands in the midst and does not move. Mark gives the kiss two words and gives Christ none: as soon as he was come, he goeth straightway to him, and saith, Master, master; and kissed him. Matthew's Friend, wherefore art thou come? is not in Mark, nor Luke's question about the kiss; the Lord's first words in Mark are to the crowd — Are ye come out, as against a thief, with swords and with staves to take me? — and the painter has given the crowd exactly those: swords, clubs and an axe raised over the heads, a torch flaring at the left and a gabled lantern held up on a pole. The torch is in the hand of an old man in a red hood at the far left, and a second hooded elder stands at the right edge in green; Mark sends the multitude from the chief priests and the scribes and the elders, and the painter has put the elders in among the swords. A young man in a red tunic reaches in from the right and takes hold of the Lord's garment: they laid their hands on him, and took him. At the lower right a grey-haired man in ochre kneels on a youth in a short red tunic and holds a blade to his head. Mark names neither: one of them that stood by drew a sword, and smote a servant of the high priest, and cut off his ear — it is John's Gospel that says Simon Peter and Malchus — and in Mark the blow gets no answer from the Lord at all. High in the upper left corner, outside the torchlight, two young men stand on the rocks looking toward the arrest, unhaloed and unnamed. Mark closes the scene with they all forsook him, and fled, and then with a detail no other Gospel has, a certain young man, having a linen cloth cast about his naked body — he left the linen cloth, and fled from them naked. The fresco shows no such flight; its two watchers are clothed and standing still.",

"File:Judas's kiss (Monreale).jpg":
 "A twelfth-century mosaic from Monreale in Sicily, with TRADITIO at the left end of its band and DOM… at the right, where the photograph's edge cuts it off: the handing over of the Lord. Spears, axes and a lantern on a crooked pole fill the gold above a crowd packed to the top of the panel, and at the centre of it the Lord stands facing straight out while Judas comes in from the right in a pale mantle, his arm about him and his face at his cheek. Mark gives the arrangement that embrace was carrying out: Whomsoever I shall kiss, that same is he; take him, and lead him away safely — safely is Mark's word, where Matthew's account has hold him fast. The face at the centre is not turned to the kiss, and in Mark the Lord says nothing to Judas at all. A beardless man on the left has already reached his arm across the Lord's breast, so that the seizing has begun before the kiss is over — and they laid their hands on him, and took him, which Mark puts in the very next verse. At the lower left a grey-haired man kneels on a young man thrown to the ground and has him by the head. Mark calls the striker only one of them that stood by and the victim a servant of the high priest; he does not say the striker was a disciple, and he names neither man. At the far left edge a young man in a plain mantle stands apart from the press. Nothing marks him as the young man of Mark's last two verses, who fled from them naked; he is clothed and still, and no one in the mosaic is running.",

"File:Kiss of Judas (Church of Saint Nicolas the Orphan).jpg":
 "A fourteenth-century fresco from the church of St Nicholas Orphanos in Thessaloniki. The photograph gives the heart of it — the kiss and the crowd — and cuts it at the right through a figure in orange that cannot be made out. Judas leans in from the left in a pale mantle, one hand gripping the dark mantle at the Lord's breast and his face against his; Christ stands upright at the right of the pair under a deep orange-red halo with his face turned a little from the kiss, and low against his mantle a white scroll shows in a hand half hidden under Judas's arm. A second arm, in red with a patterned cuff, reaches across from the right and takes him by the shoulder. That is Mark's order with nothing between: Master, master; and kissed him, and then, And they laid their hands on him, and took him. Over every head a line of spear-heads, axes and curved blades stands against the night, and a lantern is carried in above them with ΙΣ ΧΣ written beneath it. At the far left a man in a red mantle holds a long sword up and strikes nothing. Mark's account of the blow begins one of them that stood by drew a sword, and the fresco goes no further than that: no servant is down and no ear is cut. What it gives instead is the thing Christ speaks of when Mark first lets him speak: Are ye come out, as against a thief, with swords and with staves to take me? I was daily with you in the temple teaching, and ye took me not: but the scriptures must be fulfilled.",

};
