// A readable name for every icon this reader shows, keyed by Commons file title. Most are the
// name the other readers give the same file — they name the place and the date, not the Gospel —
// and the rest are Mark's own where his account names the scene differently.
module.exports={
"File:Christos Prodomo Dionysiou.jpg":"Christ with St John the Forerunner — Dionysiou, Athos, 1547",
"File:St John the Baptist Late XVII - Early XVIII Cenury St Mary Blonichka Church, Ohris Icon Gallery.jpg":"St John the Forerunner, the Angel of the Desert — Ohrid, c. 1700",
"File:Baptism of Christ, Early XIV Century, St Mary Perivleptos Church, Ohrid Icon Gallery.jpg":"The Theophany — Ohrid, early 14th c.",
"File:019 Baptism of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":"The Theophany — Athanasios Margaritis, Langadas, 1850",
"File:03 Baptism of Christ Icon from Saint Paraskevi Church in Adam.jpg":"The Theophany — Adam, Greece, before 1900",
"File:0663Ha. Hermitage Museum (Hall 143). Icon of the Epiphany.jpg":"The Theophany — Russian North, 17th c.",
"File:Christ's temptation (Monreale).jpg":"The Temptation of Christ — Monreale, 12th c.",
"File:Elkomenos Prodromos Phylaken Dionysiou.jpg":"The Forerunner Led to Prison — Dionysiou, Athos, 1547",
"File:Monreale - Jesus heals Simon's mother in law.jpg":"Healing of Peter’s Mother-in-law — Monreale, 12th c.",
"File:Christ cleans leper man.jpg":"The Cleansing of the Leper — Monreale, 12th c.",
"File:Monreale - healing of paralytic.jpg":"The Healing of the Paralytic — Monreale, 12th c.",
"File:Healing of the Paralytic 04-17.jpg":"The Healing of the Paralytic — Dionisy, Ferapontov, 1502",
"File:090 Mathew the Apostle Icon from Saint Paraskevi Church in Langadas.jpg":"St Matthew the Apostle, called Levi — Langadas, Greece, 19th c.",
"File:Matthew the Evangelist - icon.jpeg":"St Matthew the Evangelist, called Levi — Palekh, Russia, 19th c.",
"File:Iomenos xeran echon cheira Dionysiou.jpg":"The Man with the Withered Hand — Dionysiou, Athos, 1547",
"File:Synaxis of the Twelve Apostles by Constantinople master (early 14th c., Pushkin museum).jpg":"The Synaxis of the Twelve Apostles — Constantinople, early 14th c.",
"File:Synaxis of the Twelve Apostles Dimitar Molerov Rila Monastery 1835.jpg":"The Synaxis of the Twelve Apostles — Dimitar Molerov, Rila, 1835",
"File:The Twelve Apostles, with later gilding, Greek, Late Byzantine, early 1300s, tempera and gold leaf on wood panel - Princeton University Art Museum - DSC06701.jpg":"The Twelve Apostles — Late Byzantine panel, early 1300s",
"File:Representation of the Sower's parable.JPEG":"The Parable of the Sower — Orthodox mosaic",
"File:Hrist utišava buru na moru, manastir Gračanica.jpg":"Christ Stilling the Storm — Gračanica, 14th c.",
"File:Mosaic of the exorcism of the Gerasene demoniac from the Basilica of Sant'Apollinare Nuovo.jpg":"The Gerasene Demoniac — Sant’Apollinare Nuovo, Ravenna, 6th c.",
"File:Monreale - Healing of the Woman with an Issue of Blood.jpg":"The Woman with the Issue of Blood — Monreale, 12th c.",
"File:Daughter of the head of synagogue is resurrected by Christ.jpg":"The Daughter of Jairus — Monreale, 12th c.",
"File:Raising of Jairus' daughter 03-19.jpg":"The Daughter of Jairus — Dionisy, Ferapontov, 1502",
"File:Tokalı Kilise Raising of daughter of Jairus - 2004 6964.jpg":"The Daughter of Jairus — Tokalı Kilise, Cappadocia, 10th c.",
"File:Apotome Agiou Ioannou Prodromou Dionysiou.jpg":"The Beheading of the Forerunner — Dionysiou, Athos, 1547",
"File:103 Beheading of Saint John the Baptist Icon from Saint Paraskevi Church in Langadas.jpg":"The Head of the Forerunner — Langadas, Greece, 1927",
"File:19 Beheading of Saint John the Baptist Icon in Assumption of Mary Church in Agios Vasileios.jpg":"The Beheading of the Forerunner — Agios Vasileios, Greece, before 1900",
"File:Evlogesis Pente Arton Dionysiou.jpg":"The Blessing of the Five Loaves — Dionysiou, Athos, 1547",
"File:Feeding the multitude, Sant'Apollinare Nuovo, Ravenna.jpg":"The Multiplication of the Loaves — Sant'Apollinare Nuovo, Ravenna, 6th c.",
"File:Christos Iomenos Thygatera Xananaias Dionysiou.jpg":"The Canaanite Woman — Dionysiou, Athos, 1547",
"File:Monreale - Multiplication of the Loaves and Fishes.jpg":"The Multiplication of the Loaves — Monreale, 12th c.",
"File:Transfiguration of Christ Icon Sinai 12th century.jpg":"The Transfiguration — Sinai, 12th c.",
"File:042 Transfiguration of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":"The Transfiguration — Stavrakis Margaritis, Langadas, 1885",
"File:Icon of the Transfiguration from Saint Catherine's, Sinai.jpg":"The Transfiguration — St Catherine's, Sinai, 12th c.",
"File:Icon of transfiguration (Spaso-Preobrazhensky Monastery, Yaroslavl).jpg":"The Transfiguration — Yaroslavl, c. 1516",
"File:Baiophoros Dionysiou.jpg":"The Entry into Jerusalem — Dionysiou, Athos, 1547",
"File:005 Entry into Jerusalem Icon from Saint Paraskevi Church in Langadas.jpg":"The Entry into Jerusalem — Langadas, Greece, before 1900",
"File:18 Triumphal entry into Jerusalem Icon from Saint Paraskevi Church in Adam..jpg":"The Entry into Jerusalem — Athanasios of Adam, 1846",
"File:Entry into Jerusalem (Afon icon).jpg":"The Entry into Jerusalem — Athos, 16th c.",
"File:074 Cursing the fig tree Icon from Saint Paraskevi Church in Langadas.jpg":"The Cursing of the Fig Tree — Langadas, Greece, 19th c.",
"File:Fig tree cursed 04-16.jpg":"The Cursing of the Fig Tree — Dionisy, Ferapontov, 1502",
"File:Christ banish tradesmen from Temple (Monreale).jpg":"The Cleansing of the Temple — Monreale, 12th c.",
"File:Rossano Gospels - Cleansing of the Temple.jpg":"The Cleansing of the Temple — Rossano Gospels, 6th c.",
"File:Second Coming by G.Klontzas (16th c.).jpg":"The Second Coming — Georgios Klontzas, Crete, late 16th c.",
"File:Monreale - Anointing at Bethany.jpg":"The Anointing at Bethany — Monreale, 12th c.",
"File:Judas receiving money, icon of Yaroslavl (19 c, priv.coll).jpg":"Judas Receiving the Silver — Yaroslavl school, 19th c.",
"File:Deipnos Mystikos Dionysiou.jpg":"The Mystical Supper — Dionysiou, Athos, 1547",
"File:05 Last Supper Icon from Saint Paraskevi Church in Adam.jpg":"The Mystical Supper — Asterios Anagnostos, Adam, 1898",
"File:Kirillo-Belozersky iconostasis 12 - Last Supper.jpg":"The Mystical Supper — Kirillo-Belozersky iconostasis, 1497",
"File:The Lord's prayer in Gethsemane - Stavronikita monastery, Mt Athos - Theophanes of Crete, 16th c..jpg":"The Prayer in Gethsemane — Theophanes the Cretan, Stavronikita, 16th c.",
"File:Gethsemane Dionysiou.jpg":"The Prayer in Gethsemane — Dionysiou, Athos, 1547",
"File:Cathedral (Monreale) - Right wing transept - Agony in the Garden.jpg":"The Agony in the Garden — Monreale, 12th c.",
"File:Prodosia Dionysiou.jpg":"The Betrayal — Dionysiou, Athos, 1547",
"File:Judas's kiss (Monreale).jpg":"The Kiss of Judas — Monreale, 12th c.",
"File:Kiss of Judas (Church of Saint Nicolas the Orphan).jpg":"The Kiss of Judas — St Nicholas Orphanos, Thessaloniki, 14th c.",
"File:Krinomenos Christou Dionysiou.jpg":"Christ Judged — Dionysiou, Athos, 1547",
"File:Christ before Caiaphas, GRACANICA 1 090A7764.jpg":"Christ before Caiaphas — Gračanica, Serbia, 14th c.",
"File:Alektor Petrou Dionysiou.jpg":"Peter and the Cock — Dionysiou, Athos, 1547",
"File:Ravenna, sant'apollinare nuovo, int., storie cristologiche, epoca di teodorico 07.1 rinnegamento di pietro.jpg":"The Denial of Peter — Sant’Apollinare Nuovo, Ravenna, 6th c.",
"File:Pilate judgement (icon).jpg":"Christ before Pilate — Russian icon, 15th c.",
"File:Cathedral (Monreale) - Right wing transept - Before Pilate.jpg":"Christ Led before Pilate — Monreale, 12th c.",
"File:Mastigosis Dionysiou.jpg":"The Scourging of Christ — Dionysiou, Athos, 1547",
"File:Flagellation of Christ (icon).jpg":"The Scourging — Novgorod tablet icon, 15th c.",
"File:Empaigmos Dionysiou.jpg":"The Mocking of Christ — Dionysiou, Athos, 1547",
"File:Stavrosis Dionysiou.jpg":"The Crucifixion — Dionysiou, Athos, 1547",
"File:Crucifixion Icon Sinai 12th century.jpg":"The Crucifixion — Sinai, late 12th c.",
"File:024 Crucifixion of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":"The Crucifixion — Langadas, Greece, 1855",
"File:Double-sided icon - Crucifixion and Hodegetria (9-13th c., Byzantine museum).jpg":"The Crucifixion — double-sided icon, Byzantine Museum, Athens",
"File:Great Lavra Monastery Katholikon Church Crucifixion, Theophanes the Cretan 1535.jpg":"The Crucifixion — Theophanes the Cretan, Great Lavra, Athos, 1535",
"File:Cathedral (Monreale) - Left wing transept - West wall - Crucifixion.jpg":"The Crucifixion — Monreale, 12th c.",
"File:Etesatou Ioseph Somatou Christou.jpg":"Joseph Asks Pilate for the Body — Dionysiou, Athos, 1547",
"File:Apokalthelosis Dionysiou.jpg":"The Taking Down from the Cross — Dionysiou, Athos, 1547",
"File:Epitaphios Threnos Dionysiou.jpg":"The Lamentation at the Tomb — Dionysiou, Athos, 1547",
"File:Cathedral (Monreale) - Left wing transept - North wall - Entombment.jpg":"The Laying in the Tomb — Monreale, 12th c.",
"File:Ide Topos pou Ekato Dionysiou.jpg":"“Behold the Place Where They Laid Him” — Dionysiou, Athos, 1547",
"File:Emphania Soteros Dionysiou.jpg":"Christ Appears to Mary Magdalene — Dionysiou, Athos, 1547",
"File:Noli me tangere (16th c., Cretan).jpg":"Touch Me Not — Cretan icon, 16th c.",
"File:Touch Me Not (Noli me tangere), Lambardos Emmanuel, Municipal Gallery of Corfu, 04.jpg":"Touch Me Not — Emmanuel Lambardos, Corfu",
"File:Christos Apostolois Dionysiou.jpg":"Christ with the Apostles — Dionysiou, Athos, 1547",
"File:016 Ascension of Jesus Icon from Saint Paraskevi Church in Langadas.jpg":"The Ascension — Langadas, Greece, before 1900",
"File:Cathedral (Monreale) - Left wing transept - Ascension.jpg":"The Ascension — Monreale, 12th c.",
};
