// Write src/books/luke/anchors.json. Luke is the longest Gospel (1,151 verses) and the
// Catena divides it into 245 blocks — far finer than Mark's 105, because the Magnificat and
// the Benedictus are commented on verse by verse. So unlike Mark's, these divisions are not
// the Catena's blocks one for one: they are the traditional pericopes, set to begin where a
// Catena block begins so that the Fathers' comments still sit inside exactly one passage,
// which is what fathers.js selects on.
//
//   node src/tools/luke_anchors.js src/books/luke/anchors.json
//
// It refuses to write on a gap, an overlap, a duplicate id, or a chapter whose passages do
// not add up to the KJV's verse count, so coverage is proven rather than assumed.
const fs=require('fs');
const kjv=require('../books/luke/kjv.json');

const P=[
[1,[[1,4,'prologue','The Prologue to Theophilus'],
    [5,25,'zacharias','The Annunciation to Zacharias'],
    [26,38,'annunciation','The Annunciation to the Theotokos'],
    [39,45,'visitation','The Visitation'],
    [46,56,'magnificat','The Magnificat'],
    [57,66,'forerunnerbirth','The Nativity of the Forerunner'],
    [67,80,'benedictus','The Prophecy of Zacharias']]],
[2,[[1,7,'nativity','The Nativity of Christ'],
    [8,20,'shepherds','The Shepherds and the Angels'],
    [21,21,'circumcision','The Circumcision'],
    [22,38,'meeting','The Meeting in the Temple'],
    [39,41,'nazareth','The Return to Nazareth'],
    [42,52,'twelveyears','Christ at Twelve Years in the Temple']]],
[3,[[1,6,'forerunnerpreach','The Preaching of the Forerunner'],
    [7,14,'fruits','Bring Forth Fruits of Repentance'],
    [15,20,'mightier','He Shall Baptize with the Holy Ghost'],
    [21,22,'baptism','The Baptism of Christ'],
    [23,38,'genealogy','The Genealogy of Christ']]],
[4,[[1,13,'temptation','The Temptation in the Wilderness'],
    [14,21,'synagogue','The Spirit of the Lord Is Upon Me'],
    [22,30,'noprophet','No Prophet Is Accepted in His Own Country'],
    [31,37,'capernaum','The Unclean Spirit at Capernaum'],
    [38,41,'petersmother','Simon’s Wife’s Mother'],
    [42,44,'preaching','Preaching in the Synagogues of Galilee']]],
[5,[[1,11,'draught','The Draught of Fishes'],
    [12,16,'leper','The Cleansing of the Leper'],
    [17,26,'paralytic','The Paralytic Let Down Through the Tiles'],
    [27,32,'levi','The Calling of Levi'],
    [33,39,'fasting','The Question of Fasting']]],
[6,[[1,5,'sabbath','Lord of the Sabbath'],
    [6,11,'witheredhand','The Withered Hand'],
    [12,19,'twelve','The Choosing of the Twelve'],
    [20,26,'beatitudes','The Beatitudes and the Woes'],
    [27,36,'loveenemies','Love Your Enemies'],
    [37,42,'judgenot','Judge Not'],
    [43,49,'houserock','The Tree and Its Fruit, and the House on the Rock']]],
[7,[[1,10,'centurion','The Centurion’s Servant'],
    [11,17,'nain','The Widow’s Son at Nain'],
    [18,23,'johnsends','John Sends from Prison'],
    [24,35,'witnesstojohn','Christ’s Witness to the Forerunner'],
    [36,50,'sinfulwoman','The Sinful Woman Anoints His Feet']]],
[8,[[1,3,'women','The Women Who Ministered to Him'],
    [4,15,'sower','The Parable of the Sower'],
    [16,18,'candle','The Candle and the Measure'],
    [19,21,'brethren','Who Is My Mother?'],
    [22,25,'storm','The Stilling of the Storm'],
    [26,39,'gadarene','The Gadarene Demoniac'],
    [40,48,'issueofblood','The Woman with the Issue of Blood'],
    [49,56,'jairus','The Daughter of Jairus']]],
[9,[[1,6,'sending','The Sending of the Twelve'],
    [7,9,'herod','Herod Hears of Jesus'],
    [10,17,'fivethousand','The Five Thousand Fed'],
    [18,22,'confession','The Confession of Peter'],
    [23,27,'takecross','Whosoever Will Come After Me'],
    [28,36,'transfiguration','The Transfiguration'],
    [37,43,'dumbspirit','The Boy with the Unclean Spirit'],
    [44,50,'greatest','The Passion Foretold, and Who Should Be Greatest'],
    [51,56,'samaritanvillage','The Village That Would Not Receive Him'],
    [57,62,'followme','Follow Me']]],
[10,[[1,12,'seventy','The Sending of the Seventy'],
     [13,16,'chorazin','Woe unto Thee, Chorazin'],
     [17,20,'returnseventy','The Return of the Seventy'],
     [21,24,'thankfather','I Thank Thee, O Father'],
     [25,37,'samaritan','The Good Samaritan'],
     [38,42,'marthamary','Martha and Mary']]],
[11,[[1,4,'lordsprayer','The Lord’s Prayer'],
     [5,13,'friendmidnight','The Friend at Midnight'],
     [14,26,'beelzebub','The Dumb Spirit Cast Out'],
     [27,32,'blessedwomb','Blessed Is the Womb, and the Sign of Jonas'],
     [33,36,'lightbody','The Light of the Body'],
     [37,44,'woepharisees','Woe unto You, Pharisees'],
     [45,54,'woelawyers','Woe unto You, Lawyers']]],
[12,[[1,12,'leaven','Beware the Leaven of the Pharisees'],
     [13,21,'richfool','The Rich Fool'],
     [22,34,'takenothought','Take No Thought for Your Life'],
     [35,40,'loinsgirded','Let Your Loins Be Girded'],
     [41,53,'steward','The Faithful and Wise Steward'],
     [54,59,'discern','Discerning the Time']]],
[13,[[1,5,'repent','Except Ye Repent'],
     [6,9,'figtree','The Barren Fig Tree'],
     [10,17,'bowedwoman','The Woman Bowed Together'],
     [18,21,'mustard','The Mustard Seed and the Leaven'],
     [22,30,'straitgate','The Strait Gate'],
     [31,35,'jerusalem','O Jerusalem, Jerusalem']]],
[14,[[1,6,'dropsy','The Man with the Dropsy'],
     [7,14,'chiefrooms','The Chief Rooms, and the Poor Bidden'],
     [15,24,'greatsupper','The Great Supper'],
     [25,27,'bearcross','Whosoever Doth Not Bear His Cross'],
     [28,33,'countcost','Counting the Cost'],
     [34,35,'salt','Salt That Has Lost His Savour']]],
[15,[[1,7,'lostsheep','The Lost Sheep'],
     [8,10,'lostcoin','The Lost Piece of Silver'],
     [11,32,'prodigal','The Prodigal Son']]],
[16,[[1,7,'unjuststeward','The Unjust Steward'],
     [8,13,'mammon','Ye Cannot Serve God and Mammon'],
     [14,18,'derided','The Pharisees Derided Him'],
     [19,31,'lazarus','The Rich Man and Lazarus']]],
[17,[[1,4,'offences','Offences and Forgiveness'],
     [5,10,'faithservants','Increase Our Faith, and the Unprofitable Servants'],
     [11,19,'tenlepers','The Ten Lepers'],
     [20,21,'kingdomwithin','The Kingdom of God Is Within You'],
     [22,25,'daysofson','The Days of the Son of Man'],
     [26,37,'daysofnoe','As It Was in the Days of Noe']]],
[18,[[1,8,'unjustjudge','The Unjust Judge'],
     [9,14,'publican','The Pharisee and the Publican'],
     [15,17,'children','Suffer the Little Children'],
     [18,23,'richruler','The Rich Ruler'],
     [24,30,'needleseye','The Eye of a Needle'],
     [31,34,'foretold','The Third Foretelling of the Passion'],
     [35,43,'blindjericho','The Blind Man at Jericho']]],
[19,[[1,10,'zacchaeus','Zacchaeus'],
     [11,27,'pounds','The Parable of the Pounds'],
     [28,36,'entry','The Entry into Jerusalem'],
     [37,40,'olivet','The Descent of the Mount of Olives'],
     [41,44,'wept','He Wept Over the City'],
     [45,48,'temple','The Cleansing of the Temple']]],
[20,[[1,8,'bywhat','By What Authority?'],
     [9,18,'husbandmen','The Wicked Husbandmen'],
     [19,26,'tribute','Render unto Caesar'],
     [27,40,'risen','The Question of the Resurrection'],
     [41,44,'davidson','The Son of David'],
     [45,47,'scribes','Beware of the Scribes']]],
[21,[[1,4,'mites','The Widow’s Two Mites'],
     [5,11,'stones','Not One Stone Upon Another'],
     [12,19,'persecution','They Shall Lay Their Hands on You'],
     [20,24,'armies','Jerusalem Compassed with Armies'],
     [25,33,'coming','The Son of Man Coming in a Cloud'],
     [34,38,'watch','Watch Ye Therefore']]],
[22,[[1,6,'plot','The Plot and the Bargain'],
     [7,13,'upperroom','The Preparing of the Passover'],
     [14,20,'supper','The Mystical Supper'],
     [21,23,'betrayer','The Hand of the Betrayer'],
     [24,30,'whogreatest','Which Should Be the Greatest'],
     [31,34,'satandesired','Satan Hath Desired to Have You'],
     [35,38,'swords','The Two Swords'],
     [39,46,'gethsemane','The Agony in the Garden'],
     [47,53,'arrest','The Betrayal and the Arrest'],
     [54,62,'denial','The Denial of Peter'],
     [63,71,'council','Mocked, and Before the Council']]],
[23,[[1,5,'pilate','Before Pilate'],
     [6,12,'herodtrial','Before Herod'],
     [13,25,'barabbas','Barabbas Released'],
     [26,32,'simoncyrene','Simon of Cyrene and the Daughters of Jerusalem'],
     [33,43,'crucifixion','The Crucifixion, and the Thief'],
     [44,49,'death','The Darkness and the Death of Christ'],
     [50,56,'burial','The Burial']]],
[24,[[1,12,'myrrhbearers','The Myrrhbearing Women at the Tomb'],
     [13,24,'emmausroad','The Road to Emmaus'],
     [25,35,'breaking','Known in the Breaking of Bread'],
     [36,43,'peace','Peace Be unto You'],
     [44,49,'understanding','The Opening of Their Understanding'],
     [50,53,'ascension','The Ascension']]],
];

const counts={}; kjv.chapters.forEach(c=>counts[+c.chapter]=c.verses.length);
const out={}; const ids=new Set(); let n=0;
for(const [ch,rows] of P){
  out[String(ch)]=rows.map(([vS,vE,id,name])=>{
    if(ids.has(id)) throw new Error('duplicate id '+id);
    ids.add(id); n++;
    return {id,vS,vE,name};
  });
  // Contiguous and complete: every verse of the chapter sits in exactly one passage.
  let expect=1;
  for(const r of rows){ if(r[0]!==expect) throw new Error(`ch${ch}: gap or overlap at ${r[0]}, expected ${expect}`); expect=r[1]+1; }
  if(expect-1!==counts[ch]) throw new Error(`ch${ch}: covers ${expect-1} verses, KJV has ${counts[ch]}`);
}
if(Object.keys(out).length!==kjv.chapters.length) throw new Error('chapters: '+Object.keys(out).length+' vs KJV '+kjv.chapters.length);
fs.writeFileSync(process.argv[2],JSON.stringify(out,null,1)+'\n');
console.log('wrote',n,'passages over',Object.keys(out).length,'chapters — every verse covered once');
